name: LOAD_SRVC_ODS_LOAN_WH
config-version: 2

vars:
  SRVDSR_LOADDTTM: ''''
  TRUNC_FLAG: 'N'
  SRVALT2_LOADDTTM: ''''
  SS_SRC_SRVDSR_TBL: 'SRVDSR'
  APT_STRING_PADCHAR: '0x20'
  ETL_BATCH_ID: ''''
  BDFL_CREATDTS: ''''
  LSBORR00_LOADDTTM: ''''
  BDFL_UPDATDTS: ''''
  SRVMBSP_LOADDTTM: ''''
  PS_ODS_SRVCWH_SQL: '(As pre-defined)'
  PS_ODS_SRVCWH_Filepath: '(As pre-defined)'
  SRVMLD_LOADDTTM: ''''
  DISPATCH_FLAG: 'Y'
  SRVMBSP2_LOADDTTM: ''''
  SRVESCE_LOADDTTM: ''''
