name: DCR_1010W_DLRCRDT_DLRBANK_UI
config-version: 2

vars:
  WDBUSER: 'PROJDEF'
  MFRDBNAME: 'PROJDEF'
  MFRDBUSER: 'PROJDEF'
  WETL01FW: 'PROJDEF'
  jpDate: ''''
  WDBPWD: 'HDI@IJV8O9JN064IL:JD1K95'
  APT_DISABLE_COMBINATION: 'False'
  WDBNAME: 'PROJDEF'
  MFRDBPWD: 'HDI@IJV8O9JN064IL:JD1K95'
