/* Transformation Name ==>BANK_NULL_REJ ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='BANK_NULL_REJ',
		schema='',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='overwrite')
}}

With O_SRC_DEALERBANKOut as (
	/* SubQuery from Source ==>O_SRC_DEALERBANK */
Select 
 * 
 from 
(SELECT FCCDHIS.I_BUS as I_BANK, FCCDHIS.I_CUST as I_BUS, LTRIM(RTRIM(FCCDHIS.I_BANK_ABA)) as I_BANK_ABA, FCCDHIS.C_FINC_SRCE_PRMRY, LTRIM(RTRIM(FCCDHIS.X_ADDR_LINE_1_BANK)) as X_ADDR_LINE_1_BANK, FCCDHIS.N_PERSN_CNTCT as N_PERSN_CNTCT, FCCDHIS.I_AREA as I_AREA, FCCDHIS.I_PH as I_PH, FCCDHIS.C_FRNCHZ_SET, FCCDHIS.T_STMP_UPD, DATE(FCCDHIS.T_STMP_UPD) as D_SRCE_UPD FROM N_DB_APP_EDW_DEV.SCM.F_FCCDHIS as FCCDHIS JOIN (SELECT MAX(FCCDHIS.T_STMP_UPD) as T_STMP_UPD_MAX, DATE(FCCDHIS.T_STMP_UPD) as D_UPD, FCCDHIS.I_CUST, LTRIM(RTRIM(FCCDHIS.C_FRNCHZ_SET)) as C_FRNCHZ_SET FROM N_DB_APP_EDW_DEV.SCM.F_FCCDHIS as FCCDHIS GROUP BY DATE(FCCDHIS.T_STMP_UPD), FCCDHIS.I_CUST, LTRIM(RTRIM(FCCDHIS.C_FRNCHZ_SET))) LATEST_HIST WHERE DATE(FCCDHIS.T_STMP_UPD) >= 'DSHASHJPDATEDSHASH' AND FCCDHIS.T_STMP_UPD= LATEST_HIST.T_STMP_UPD_MAX AND FCCDHIS.I_CUST= LATEST_HIST.I_CUST AND FCCDHIS.C_FRNCHZ_SET= LATEST_HIST.C_FRNCHZ_SET ORDER BY FCCDHIS.I_CUST, DATE ( FCCDHIS.T_STMP_UPD ), FCCDHIS.T_STMP_UPD DESC WITH UR)
 ),

SRC_SQL_BANK_FCCINSTOut as (
	/* SubQuery from Source ==>SRC_SQL_BANK_FCCINST */
Select 
 * 
 from 
(SELECT distinct FCCINST.I_BUS, LTRIM(RTRIM(FCCINST.I_FININ_ABA)) as I_BANK_ABA, LTRIM(RTRIM(PBUSADD.X_LINE_1)) as X_LINE_1 FROM N_DB_APP_EDW_DEV.SCM.F_FCCINST as FCCINST LEFT OUTER JOIN P.PBUSADD as PBUSADD ON FCCINST.I_BUS= PBUSADD.I_BUS WHERE FCCINST.I_FININ_ABA NOT LIKE '00000%' WITH UR)
 ),

XFR_SRC_DLRBANKOut as (
	
Select 
StgNewCust as StgOldCust,
I_BUS as StgNewCust,
StgNewDate as StgOldDate,
I_BUS || D_SRCE_UPD as StgNewDate,
StgNewDlrDiv as StgOldDlrDiv,
TRIM ( C_FRNCHZ_SET ) as StgNewDlrDiv,
StgPass as StgOldPass,
( CASE WHEN StgNewDate = StgOldDate THEN ( ( CASE WHEN StgOldPass = 1 THEN StgOldPass = 1 ELSE if TRIM ( StgNewDlrDiv ) = '' 0 ELSE 1 ) ELSE 0 END ) ) END ) Else 1 as StgPass,
( CASE WHEN StgNewCust = StgOldCust THEN StgNewCust = StgOldCust ELSE StgRank + 1 ELSE StgRank ) END ) Else 1 as StgRank,
I_BANK as I_BANK,
I_BUS as I_BUS,
I_BANK_ABA as I_BANK_ABA,
C_FINC_SRCE_PRMRY as C_FINC_SRCE_PRMRY,
X_ADDR_LINE_1_BANK as X_ADDR_LINE_1_BANK,
TRIM ( N_PERSN_CNTCT ) as N_PERSN_CNTCT,
TRIM ( I_AREA ) as I_AREA,
TRIM ( I_PH ) as I_PH,
TRIM ( C_FRNCHZ_SET ) as C_FRNCHZ_SET,
T_STMP_UPD as T_STMP_UPD,
D_SRCE_UPD as D_SRCE_UPD,
StgRank as Rank
From O_SRC_DEALERBANKOut as O_SRC_DEALERBANKOut),

XFR_SRC_DLRBANK_Filter1Out as (
	Select 
	I_BANK,
	 I_BUS,
	 I_BANK_ABA,
	 C_FINC_SRCE_PRMRY,
	 X_ADDR_LINE_1_BANK,
	 trim ( N_PERSN_CNTCT ),
	 trim ( I_AREA ),
	 trim ( I_PH ),
	 trim ( C_FRNCHZ_SET ),
	 T_STMP_UPD,
	 D_SRCE_UPD,
	 StgRank 
From XFR_SRC_DLRBANKOut as XFR_SRC_DLRBANKOut Where StgPass = 1),

LKP_BANK_DATAOut as (
	Select 
	XFR_SRC_DLRBANK.I_BANK as I_BANK_1,
	 XFR_SRC_DLRBANK.I_BUS as I_BUS_1,
	 XFR_SRC_DLRBANK.I_BANK_ABA as I_BANK_ABA_1,
	 XFR_SRC_DLRBANK.X_ADDR_LINE_1_BANK as X_ADDR_LINE_1_BANK_1,
	 XFR_SRC_DLRBANK.C_FINC_SRCE_PRMRY as C_FINC_SRCE_PRMRY_1,
	 XFR_SRC_DLRBANK.N_PERSN_CNTCT as N_PERSN_CNTCT_1,
	 XFR_SRC_DLRBANK.I_AREA as I_AREA_1,
	 XFR_SRC_DLRBANK.I_PH as I_PH_1,
	 XFR_SRC_DLRBANK.C_FRNCHZ_SET as C_FRNCHZ_SET_1,
	 XFR_SRC_DLRBANK.T_STMP_UPD as T_STMP_UPD_1,
	 XFR_SRC_DLRBANK.D_SRCE_UPD as D_SRCE_UPD_1,
	 XFR_SRC_DLRBANK.Rank as Rank_1,
	 SRC_SQL_BANK_FCCINSTOut.I_BUS_1 as I_BANK_1,
	 SRC_SQL_BANK_FCCINSTOut.I_BUS_2 as I_BANK_2_1,
	 XFR_SRC_DLRBANK_Filter1.I_BUS AS I_BUS_2,
	 XFR_SRC_DLRBANK_Filter1.C_FRNCHZ_SET AS C_FRNCHZ_SET_2,
	 XFR_SRC_DLRBANK_Filter1.C_FINC_SRCE_PRMRY AS C_FINC_SRCE_PRMRY_2,
	 XFR_SRC_DLRBANK_Filter1.Rank AS Rank_2,
	 XFR_SRC_DLRBANK_Filter1.I_PH AS I_PH_2,
	 SRC_SQL_BANK_FCCINST.X_LINE_1 AS X_LINE_1,
	 XFR_SRC_DLRBANK_Filter1.I_AREA AS I_AREA_2,
	 SRC_SQL_BANK_FCCINST.I_BUS_1 AS I_BUS_1,
	 SRC_SQL_BANK_FCCINST.I_BANK_ABA AS I_BANK_ABA_2,
	 SRC_SQL_BANK_FCCINST.I_BUS_2 AS I_BUS_2,
	 XFR_SRC_DLRBANK_Filter1.X_ADDR_LINE_1_BANK AS X_ADDR_LINE_1_BANK_2,
	 XFR_SRC_DLRBANK_Filter1.T_STMP_UPD AS T_STMP_UPD_2,
	 XFR_SRC_DLRBANK.I_BANK AS I_BANK_2_2,
	 XFR_SRC_DLRBANK_Filter1.I_BANK_ABA AS I_BANK_ABA_3,
	 XFR_SRC_DLRBANK_Filter1.N_PERSN_CNTCT AS N_PERSN_CNTCT_2,
	 XFR_SRC_DLRBANK_Filter1.D_SRCE_UPD AS D_SRCE_UPD_2,
	 XFR_SRC_DLRBANK_Filter1.I_BANK AS I_BANK_2 
FROM
	XFR_SRC_DLRBANK_Filter1Out as XFR_SRC_DLRBANK_Filter1Out 
 LEFT JOIN SRC_SQL_BANK_FCCINSTOut
ON
	I_BANK_ABA = I_BANK_ABA
	AND X_ADDR_LINE_1_BANK = X_LINE_1
 
),

DSstgVar_XFR_CHK_BANK_NULLOut as (
	
Select 
CASE WHEN TRIM ( C_FINC_SRCE_PRMRY ) = 'FINCO' THEN TRIM ( C_FINC_SRCE_PRMRY ) = 'FINCO' ELSE COALESCE ( I_BANK_1 ) ) ) Else I_BANK END as StgBank,
I_BANK as I_BANK,
I_BUS as I_BUS,
I_BANK_ABA as I_BANK_ABA,
X_ADDR_LINE_1_BANK as X_ADDR_LINE_1_BANK,
C_FINC_SRCE_PRMRY as C_FINC_SRCE_PRMRY,
N_PERSN_CNTCT as N_PERSN_CNTCT,
I_AREA as I_AREA,
I_PH as I_PH,
C_FRNCHZ_SET as C_FRNCHZ_SET,
T_STMP_UPD as T_STMP_UPD,
D_SRCE_UPD as D_SRCE_UPD,
Rank as Rank,
I_BUS_1 as I_BANK_1,
I_BUS_2 as I_BANK_2
From LKP_BANK_DATAOut as LKP_BANK_DATAOut),

Lnk_Bank_null_rejOut as (
	
Select 
StgBank as I_BANK,
I_BUS as I_BUS,
I_BANK_ABA as I_BANK_ABA,
C_FINC_SRCE_PRMRY as C_FINC_SRCE_PRMRY,
N_PERSN_CNTCT as N_PERSN_CNTCT,
I_AREA as I_AREA,
I_PH as I_PH,
C_FRNCHZ_SET as C_FRNCHZ_SET,
T_STMP_UPD as T_STMP_UPD,
D_SRCE_UPD as D_SRCE_UPD,
COALESCE ( I_BANK_1 ) as I_BANK_1,
COALESCE ( I_BANK_2 ) as I_BANK_2 
From DSstgVar_XFR_CHK_BANK_NULLOut as DSstgVar_XFR_CHK_BANK_NULLOut Where StgBank  !=  0)


Select 
	I_BANK as I_BANK,
	I_BUS as I_BUS,
	I_BANK_ABA as I_BANK_ABA,
	C_FINC_SRCE_PRMRY as C_FINC_SRCE_PRMRY,
	N_PERSN_CNTCT as N_PERSN_CNTCT,
	I_AREA as I_AREA,
	I_PH as I_PH,
	C_FRNCHZ_SET as C_FRNCHZ_SET,
	T_STMP_UPD as T_STMP_UPD,
	D_SRCE_UPD as D_SRCE_UPD,
	I_BANK_1 as I_BANK_1,
	I_BANK_2 as I_BANK_2 
From Lnk_Bank_null_rejOut as Lnk_Bank_null_rejOut