/* Transformation Name ==>TEMP_CIS_NAME ,Transformation Type ==>Target */

{{
    config(
        materialized='incremental',
        alias='TEMP_CIS_NAME',
        schema='',
        pre_hook="",
        post_hook="",
        incremental_strategy='append'
    )
}}

WITH SQLOut AS (
    /* SubQuery from Source ==>SQL */
    /* transType: "Source" */
    SELECT
        CUSTOMER_NUMBER,
        CUSTOMER_NAME
    FROM (
        SELECT DISTINCT
            CAR1.CUSTOMER_NUMBER,
            CUST.CUSTOMER_NAME
        FROM
            BRIOVIEW.CUSTOMER_ACCOUNT_RELATIONSHIP AS CAR1,
            BRIOVIEW.CUSTOMER_ACCOUNT_RELATIONSHIP AS CAR2,
            BRIOVIEW.CUSTOMER AS CUST,
            BRIOVIEW.LOAN AS LOAN,
            BRIOVIEW.DATE_LAST_BUS_DAY AS LBD
        WHERE
            CAR1.ACCOUNT_NUMBER = CAR2.ACCOUNT_NUMBER
            AND CAR2.CUSTOMER_NUMBER = CUST.CUSTOMER_NUMBER
            AND CAR1.SOURCE_SYSTEM_PROCESS_DATE = CAR2.SOURCE_SYSTEM_PROCESS_DATE
            AND CAR1.ACCOUNT_NUMBER = LOAN.ACCOUNT_NUMBER
            AND CAR1.SOURCE_SYSTEM_PROCESS_DATE = LOAN.SOURCE_SYSTEM_PROCESS_DATE
            AND CAR1.SOURCE_SYSTEM = CAR2.SOURCE_SYSTEM
            AND CAR1.SOURCE_SYSTEM = LOAN.SOURCE_SYSTEM
            AND CAR1.PRODUCT_TYPE_CODE IN ('AFSLN', 'LN', 'OLOAN')
            AND CAR2.PRODUCT_TYPE_CODE IN ('AFSLN', 'LN', 'OLOAN')
            AND CAR1.RELATIONSHIP_TYPE_CODE IN ('000', '022', '023', '059', '062', '064')
            AND CAR2.RELATIONSHIP_TYPE_CODE IN ('000', '022', '023', '059', '062', '064')
            AND CAR1.SOURCE_SYSTEM_PROCESS_DATE = LBD.BUSINESS_DAY_DATE
            AND CAR1.CUSTOMER_NUMBER <> CAR2.CUSTOMER_NUMBER
            AND (CAR1.HISTORY_INDICATOR IN (' ', 'B') OR CAR1.HISTORY_INDICATOR IS NULL)
            AND (CAR2.HISTORY_INDICATOR IN (' ', 'B') OR CAR2.HISTORY_INDICATOR IS NULL)

        UNION

        SELECT DISTINCT
            CAR3.CUSTOMER_NUMBER,
            CUST1.CUSTOMER_NAME
        FROM
            BRIOVIEW.CUSTOMER_ACCOUNT_RELATIONSHIP AS CAR3,
            BRIOVIEW.CUSTOMER_ACCOUNT_RELATIONSHIP AS CAR4,
            BRIOVIEW.CUSTOMER AS CUST1,
            BRIOVIEW.COMMITMENT AS CMMT,
            BRIOVIEW.DATE_LAST_BUS_DAY AS LBD
        WHERE
            CAR3.ACCOUNT_NUMBER = CAR4.ACCOUNT_NUMBER
            AND CAR4.CUSTOMER_NUMBER = CUST1.CUSTOMER_NUMBER
            AND CAR3.SOURCE_SYSTEM_PROCESS_DATE = CAR4.SOURCE_SYSTEM_PROCESS_DATE
            AND CAR3.ACCOUNT_NUMBER = CMMT.ACCOUNT_NUMBER
            AND CAR3.SOURCE_SYSTEM_PROCESS_DATE = CMMT.SOURCE_SYSTEM_PROCESS_DATE
            AND CAR3.SOURCE_SYSTEM = CAR4.SOURCE_SYSTEM
            AND CAR3.SOURCE_SYSTEM = CMMT.SOURCE_SYSTEM
            AND CAR3.PRODUCT_TYPE_CODE IN ('AFSLN', 'LN', 'OLOAN')
            AND CAR4.PRODUCT_TYPE_CODE IN ('AFSLN', 'LN', 'OLOAN')
            AND CAR3.RELATIONSHIP_TYPE_CODE IN ('000', '022', '023', '059', '062', '064')
            AND CAR4.RELATIONSHIP_TYPE_CODE IN ('000', '022', '023', '059', '062', '064')
            AND CAR3.SOURCE_SYSTEM_PROCESS_DATE = LBD.BUSINESS_DAY_DATE
            AND CAR3.CUSTOMER_NUMBER <> CAR4.CUSTOMER_NUMBER
            AND (CAR3.HISTORY_INDICATOR IN (' ', 'B') OR CAR3.HISTORY_INDICATOR IS NULL)
            AND (CAR4.HISTORY_INDICATOR IN (' ', 'B') OR CAR4.HISTORY_INDICATOR IS NULL)
        ORDER BY
            CAR3.CUSTOMER_NUMBER,
            CUST1.CUSTOMER_NAME
    ) AS sub
),

DSR_QueryOut AS (
    /* transType: "Expression" */
    SELECT
        SQLOut.CUSTOMER_NUMBER AS CIS_NUMBER,
        SQLOut.CUSTOMER_NAME AS CUSTOMER_NAME
    FROM SQLOut AS SQLOut
),

QueryOut AS (
    /* transType: "Expression" */
    SELECT
        CUSTOMER_NUMBER AS CIS_NUMBER,
        CUSTOMER_NAME AS CUSTOMER_NAME
    FROM DSR_QueryOut AS DSR_QueryOut
)

SELECT
    CIS_NUMBER AS CIS_NUMBER,
    CUSTOMER_NAME AS CUSTOMER_NAME
FROM QueryOut AS QueryOut