{{
  config(
    materialized='incremental',
    alias='TREASURY_CREDIT',
    schema='',
    pre_hook="",
    post_hook="",
    incremental_strategy='merge',
    unique_key=[],
    merge_update_columns=['ACCOUNT_NUMBER','NOTE_NUMBER','CIS_NUMBER']
  )
}}
With ECM_TRACK_VWOut as (
	/* transType: "Source" */
Select ACCOUNT, 
		NOTE, 
		SYSTEM_KEY, 
		CUST_NAME, 
		ORIG, 
		MOD_DATA
 from 
{{ source ('DS_CCLOS','ECM_TRACK_VW') }}
 ),

TREASURY_CREDITOut as (
	/* transType: "Source" */
Select ACCOUNT_NUMBER, 
		NOTE_NUMBER, 
		COMMITMENT_NUMBER, 
		CUSTOMER_NAME, 
		CIS_NUMBER, 
		TAXID_NUMBER, 
		RELATED_NAME, 
		RELATED_ACCOUNT, 
		STATUS, 
		EMPLOYEE_FLAG, 
		FT_BARCODE, 
		ACCOUNT_BRANCH_CBC_NUMBER
 from 
{{ source ('DS_ACCT_CLIENT','TREASURY_CREDIT') }}
 ),

JNR_MERGE_QueryOut as (
	/* transType: "Joiner" */
Select 
	ECM_TRACK_VWOut.ACCOUNT as ACCOUNT,
	 ECM_TRACK_VWOut.NOTE as NOTE,
	 ECM_TRACK_VWOut.SYSTEM_KEY as SYSTEM_KEY,
	 ECM_TRACK_VWOut.CUST_NAME as CUST_NAME,
	 ECM_TRACK_VWOut.ORIG as ORIG,
	 ECM_TRACK_VWOut.MOD_DATA as MOD_DATA,
	 ECM_TRACK_VWOut.ACCOUNT_NUMBER as ACCOUNT_NUMBER,
	 NOTE_NUMBER as NOTE_NUMBER,
	 COMMITMENT_NUMBER as COMMITMENT_NUMBER,
	 CUSTOMER_NAME as CUSTOMER_NAME,
	 CIS_NUMBER as CIS_NUMBER,
	 TAXID_NUMBER as TAXID_NUMBER,
	 RELATED_NAME as RELATED_NAME,
	 RELATED_ACCOUNT as RELATED_ACCOUNT,
	 STATUS as STATUS,
	 EMPLOYEE_FLAG as EMPLOYEE_FLAG,
	 ECM_TRACK_VWOut.FT_BARCODE as FT_BARCODE,
	 ACCOUNT_BRANCH_CBC_NUMBER as ACCOUNT_BRANCH_CBC_NUMBER 
From
TREASURY_CREDITOut as TREASURY_CREDITOut inner JOIN TREASURY_CREDITOut as TREASURY_CREDITOut 
ON
TREASURY_CREDITOut.ACCOUNT_NUMBER = ECM_TRACK_VWOut.ACCOUNT And TREASURY_CREDITOut.CIS_NUMBER = ECM_TRACK_VWOut.SYSTEM_KEY 
),

DSR_QueryOut as (
	/* transType: "Expression" */
Select 
	JNR_MERGE_QueryOut.ACCOUNT as ACCOUNT_NUMBER,
	 JNR_MERGE_QueryOut.NOTE_NUMBER as NOTE_NUMBER,
	 JNR_MERGE_QueryOut.COMMITMENT_NUMBER as COMMITMENT_NUMBER,
	 JNR_MERGE_QueryOut.CUSTOMER_NAME as CUSTOMER_NAME,
	 JNR_MERGE_QueryOut.CIS_NUMBER as CIS_NUMBER,
	 JNR_MERGE_QueryOut.TAXID_NUMBER as TAXID_NUMBER,
	 JNR_MERGE_QueryOut.RELATED_NAME as RELATED_NAME,
	 JNR_MERGE_QueryOut.RELATED_ACCOUNT as RELATED_ACCOUNT,
	 JNR_MERGE_QueryOut.STATUS as STATUS,
	 JNR_MERGE_QueryOut.EMPLOYEE_FLAG as EMPLOYEE_FLAG,
	 JNR_MERGE_QueryOut.MOD_DATA as FT_BARCODE,
	 JNR_MERGE_QueryOut.ACCOUNT_BRANCH_CBC_NUMBER as ACCOUNT_BRANCH_CBC_NUMBER
From JNR_MERGE_QueryOut as JNR_MERGE_QueryOut),

QueryOut as (
	/* transType: "Expression" */
Select 
	RTRIM ( ACCOUNT ) as ACCOUNT_NUMBER,
	 NOTE_NUMBER as NOTE_NUMBER,
	 COMMITMENT_NUMBER as COMMITMENT_NUMBER,
	 CUSTOMER_NAME as CUSTOMER_NAME,
	 CIS_NUMBER as CIS_NUMBER,
	 TAXID_NUMBER as TAXID_NUMBER,
	 RELATED_NAME as RELATED_NAME,
	 RELATED_ACCOUNT as RELATED_ACCOUNT,
	 STATUS as STATUS,
	 rtrim ( EMPLOYEE_FLAG,
	 ' ' ) as EMPLOYEE_FLAG,
	 long_to_varchar ( MOD_DATA,
	 20,
	 1 ) as FT_BARCODE,
	 ACCOUNT_BRANCH_CBC_NUMBER as ACCOUNT_BRANCH_CBC_NUMBER
From DSR_QueryOut as DSR_QueryOut),

Table_Comparison_LKPOut as (
	/* transType: "Lookup Procedure" */
Select 
	QueryOut.ACCOUNT_NUMBER as ACCOUNT_NUMBER_1,
	 QueryOut.NOTE_NUMBER as NOTE_NUMBER_1,
	 QueryOut.COMMITMENT_NUMBER as COMMITMENT_NUMBER_1,
	 QueryOut.CUSTOMER_NAME as CUSTOMER_NAME_1,
	 QueryOut.CIS_NUMBER as CIS_NUMBER_1,
	 QueryOut.TAXID_NUMBER as TAXID_NUMBER_1,
	 QueryOut.RELATED_NAME as RELATED_NAME_1,
	 QueryOut.RELATED_ACCOUNT as RELATED_ACCOUNT_1,
	 QueryOut.STATUS as STATUS_1,
	 QueryOut.EMPLOYEE_FLAG as EMPLOYEE_FLAG_1,
	 QueryOut.FT_BARCODE as FT_BARCODE_1,
	 QueryOut.ACCOUNT_BRANCH_CBC_NUMBER as ACCOUNT_BRANCH_CBC_NUMBER_1,
	 Query.ACCOUNT_NUMBER AS ACCOUNT_NUMBER_2,
	 Query.NOTE_NUMBER AS NOTE_NUMBER_2,
	 Query.COMMITMENT_NUMBER AS COMMITMENT_NUMBER_2,
	 Query.CUSTOMER_NAME AS CUSTOMER_NAME_2,
	 Query.CIS_NUMBER AS CIS_NUMBER_2,
	 Query.TAXID_NUMBER AS TAXID_NUMBER_2,
	 Query.RELATED_NAME AS RELATED_NAME_2,
	 Query.RELATED_ACCOUNT AS RELATED_ACCOUNT_2,
	 Query.STATUS AS STATUS_2,
	 Query.EMPLOYEE_FLAG AS EMPLOYEE_FLAG_2,
	 Query.FT_BARCODE AS FT_BARCODE_2,
	 Query.ACCOUNT_BRANCH_CBC_NUMBER AS ACCOUNT_BRANCH_CBC_NUMBER_2 
FROM
	QueryOut as QueryOut 
 LEFT JOIN DBO.TREASURY_CREDITOut
ON
	ACCOUNT_NUMBER=ACCOUNT_NUMBER
	AND NOTE_NUMBER=NOTE_NUMBER
	AND CIS_NUMBER=CIS_NUMBER
 
),

Table_Comparison_EXPOut as (
	/* transType: "Expression" */
Select 
	ACCOUNT_NUMBER as ACCOUNT_NUMBER,
	 NOTE_NUMBER as NOTE_NUMBER,
	 COMMITMENT_NUMBER as COMMITMENT_NUMBER,
	 CUSTOMER_NAME as CUSTOMER_NAME,
	 CIS_NUMBER as CIS_NUMBER,
	 TAXID_NUMBER as TAXID_NUMBER,
	 RELATED_NAME as RELATED_NAME,
	 RELATED_ACCOUNT as RELATED_ACCOUNT,
	 STATUS as STATUS,
	 EMPLOYEE_FLAG as EMPLOYEE_FLAG,
	 FT_BARCODE as FT_BARCODE,
	 ACCOUNT_BRANCH_CBC_NUMBER as ACCOUNT_BRANCH_CBC_NUMBER,
	 MD5 ( ACCOUNT_NUMBER CONCAT NOTE_NUMBER CONCAT CIS_NUMBER CONCAT FT_BARCODE ) as src_hashcode,
	 MD5 ( ACCOUNT_NUMBER CONCAT NOTE_NUMBER CONCAT CIS_NUMBER CONCAT FT_BARCODE ) as tgt_hashcode,
	 ( CASE WHEN ACCOUNT_NUMBER IS NULL AND NOTE_NUMBER IS NULL AND CIS_NUMBER IS NULL THEN 1 ELSE ( CASE WHEN src_hashcode != tgt_hashcode THEN 3 ELSE 0 END ) END ) as change_code
From Table_Comparison_LKPOut as Table_Comparison_LKPOut),

Map_OperationOut as (
	/* transType: "Router" */
Select 
	Table_Comparison_EXPOut.ACCOUNT_NUMBER as ACCOUNT_NUMBER,
	 Table_Comparison_EXPOut.NOTE_NUMBER as NOTE_NUMBER,
	 Table_Comparison_EXPOut.COMMITMENT_NUMBER as COMMITMENT_NUMBER,
	 Table_Comparison_EXPOut.CUSTOMER_NAME as CUSTOMER_NAME,
	 Table_Comparison_EXPOut.CIS_NUMBER as CIS_NUMBER,
	 Table_Comparison_EXPOut.TAXID_NUMBER as TAXID_NUMBER,
	 Table_Comparison_EXPOut.RELATED_NAME as RELATED_NAME,
	 Table_Comparison_EXPOut.RELATED_ACCOUNT as RELATED_ACCOUNT,
	 Table_Comparison_EXPOut.STATUS as STATUS,
	 Table_Comparison_EXPOut.EMPLOYEE_FLAG as EMPLOYEE_FLAG,
	 Table_Comparison_EXPOut.FT_BARCODE as FT_BARCODE,
	 Table_Comparison_EXPOut.ACCOUNT_BRANCH_CBC_NUMBER as ACCOUNT_BRANCH_CBC_NUMBER,
	 Table_Comparison_EXPOut.src_hashcode as src_hashcode,
	 Table_Comparison_EXPOut.tgt_hashcode as tgt_hashcode,
	 Table_Comparison_EXPOut.change_code as change_code
 FROM Table_Comparison_EXPOut as Table_Comparison_EXPOut Where change_code = 3 )

Select 
	ACCOUNT_NUMBER as ACCOUNT_NUMBER,
	NOTE_NUMBER as NOTE_NUMBER,
	COMMITMENT_NUMBER as COMMITMENT_NUMBER,
	CUSTOMER_NAME as CUSTOMER_NAME,
	CIS_NUMBER as CIS_NUMBER,
	TAXID_NUMBER as TAXID_NUMBER,
	RELATED_NAME as RELATED_NAME,
	RELATED_ACCOUNT as RELATED_ACCOUNT,
	STATUS as STATUS,
	EMPLOYEE_FLAG as EMPLOYEE_FLAG,
	FT_BARCODE as FT_BARCODE,
	ACCOUNT_BRANCH_CBC_NUMBER as ACCOUNT_BRANCH_CBC_NUMBER 
From Map_OperationOut as Map_OperationOut