/* Transformation Name ==>TREASURY_CREDIT_2 ,Transformation Type ==>Target */

{{
    config(
        materialized = 'incremental',
        alias = 'TREASURY_CREDIT',
        schema = '',
        pre_hook = "",
        post_hook = "",
        incremental_strategy = 'append'
    )
}}

WITH ECM_TRACK_VWOut AS (
    /* transType: "Source" */
    SELECT
        ACCOUNT,
        NOTE,
        SYSTEM_KEY,
        CUST_NAME,
        ORIG,
        MOD_DATA
    FROM {{ source('DS_CCLOS', 'ECM_TRACK_VW') }}
),

TREASURY_CREDITOut AS (
    /* transType: "Source" */
    SELECT
        ACCOUNT_NUMBER,
        NOTE_NUMBER,
        COMMITMENT_NUMBER,
        CUSTOMER_NAME,
        CIS_NUMBER,
        TAXID_NUMBER,
        RELATED_NAME,
        RELATED_ACCOUNT,
        STATUS,
        EMPLOYEE_FLAG,
        FT_BARCODE,
        ACCOUNT_BRANCH_CBC_NUMBER
    FROM {{ source('DS_ACCT_CLIENT', 'TREASURY_CREDIT') }}
),

JNR_MERGE_QueryOut AS (
    /* transType: "Joiner" */
    SELECT
        ECM_TRACK_VWOut.ACCOUNT AS ACCOUNT,
        ECM_TRACK_VWOut.NOTE AS NOTE,
        ECM_TRACK_VWOut.SYSTEM_KEY AS SYSTEM_KEY,
        ECM_TRACK_VWOut.CUST_NAME AS CUST_NAME,
        ECM_TRACK_VWOut.ORIG AS ORIG,
        ECM_TRACK_VWOut.MOD_DATA AS MOD_DATA,
        TREASURY_CREDITOut.ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
        TREASURY_CREDITOut.NOTE_NUMBER AS NOTE_NUMBER,
        TREASURY_CREDITOut.COMMITMENT_NUMBER AS COMMITMENT_NUMBER,
        TREASURY_CREDITOut.CUSTOMER_NAME AS CUSTOMER_NAME,
        TREASURY_CREDITOut.CIS_NUMBER AS CIS_NUMBER,
        TREASURY_CREDITOut.TAXID_NUMBER AS TAXID_NUMBER,
        TREASURY_CREDITOut.RELATED_NAME AS RELATED_NAME,
        TREASURY_CREDITOut.RELATED_ACCOUNT AS RELATED_ACCOUNT,
        TREASURY_CREDITOut.STATUS AS STATUS,
        TREASURY_CREDITOut.EMPLOYEE_FLAG AS EMPLOYEE_FLAG,
        ECM_TRACK_VWOut.FT_BARCODE AS FT_BARCODE,
        TREASURY_CREDITOut.ACCOUNT_BRANCH_CBC_NUMBER AS ACCOUNT_BRANCH_CBC_NUMBER
    FROM TREASURY_CREDITOut AS TREASURY_CREDITOut
    INNER JOIN ECM_TRACK_VWOut AS ECM_TRACK_VWOut
        ON TREASURY_CREDITOut.ACCOUNT_NUMBER = ECM_TRACK_VWOut.ACCOUNT
        AND TREASURY_CREDITOut.CIS_NUMBER = ECM_TRACK_VWOut.SYSTEM_KEY
),

DSR_QueryOut AS (
    /* transType: "Expression" */
    SELECT
        JNR_MERGE_QueryOut.ACCOUNT AS ACCOUNT_NUMBER,
        JNR_MERGE_QueryOut.NOTE_NUMBER,
        JNR_MERGE_QueryOut.COMMITMENT_NUMBER,
        JNR_MERGE_QueryOut.CUSTOMER_NAME,
        JNR_MERGE_QueryOut.CIS_NUMBER,
        JNR_MERGE_QueryOut.TAXID_NUMBER,
        JNR_MERGE_QueryOut.RELATED_NAME,
        JNR_MERGE_QueryOut.RELATED_ACCOUNT,
        JNR_MERGE_QueryOut.STATUS,
        JNR_MERGE_QueryOut.EMPLOYEE_FLAG,
        JNR_MERGE_QueryOut.FT_BARCODE,
        JNR_MERGE_QueryOut.ACCOUNT_BRANCH_CBC_NUMBER
    FROM JNR_MERGE_QueryOut AS JNR_MERGE_QueryOut
),

QueryOut AS (
    /* transType: "Expression" */
    SELECT
        RTRIM(ACCOUNT) AS ACCOUNT_NUMBER,
        NOTE_NUMBER,
        COMMITMENT_NUMBER,
        CUSTOMER_NAME,
        CIS_NUMBER,
        TAXID_NUMBER,
        RELATED_NAME,
        RELATED_ACCOUNT,
        STATUS,
        RTRIM(EMPLOYEE_FLAG, ' ') AS EMPLOYEE_FLAG,
        TO_VARCHAR(MOD_DATA) AS FT_BARCODE,
        ACCOUNT_BRANCH_CBC_NUMBER
    FROM DSR_QueryOut AS DSR_QueryOut
),

Table_Comparison_LKPOut AS (
    /* transType: "Lookup Procedure" */
    SELECT
        QueryOut.ACCOUNT_NUMBER AS ACCOUNT_NUMBER_1,
        QueryOut.NOTE_NUMBER AS NOTE_NUMBER_1,
        QueryOut.COMMITMENT_NUMBER AS COMMITMENT_NUMBER_1,
        QueryOut.CUSTOMER_NAME AS CUSTOMER_NAME_1,
        QueryOut.CIS_NUMBER AS CIS_NUMBER_1,
        QueryOut.TAXID_NUMBER AS TAXID_NUMBER_1,
        QueryOut.RELATED_NAME AS RELATED_NAME_1,
        QueryOut.RELATED_ACCOUNT AS RELATED_ACCOUNT_1,
        QueryOut.STATUS AS STATUS_1,
        QueryOut.EMPLOYEE_FLAG AS EMPLOYEE_FLAG_1,
        QueryOut.FT_BARCODE AS FT_BARCODE_1,
        QueryOut.ACCOUNT_BRANCH_CBC_NUMBER AS ACCOUNT_BRANCH_CBC_NUMBER_1,
        TGT.ACCOUNT_NUMBER AS ACCOUNT_NUMBER_2,
        TGT.NOTE_NUMBER AS NOTE_NUMBER_2,
        TGT.COMMITMENT_NUMBER AS COMMITMENT_NUMBER_2,
        TGT.CUSTOMER_NAME AS CUSTOMER_NAME_2,
        TGT.CIS_NUMBER AS CIS_NUMBER_2,
        TGT.TAXID_NUMBER AS TAXID_NUMBER_2,
        TGT.RELATED_NAME AS RELATED_NAME_2,
        TGT.RELATED_ACCOUNT AS RELATED_ACCOUNT_2,
        TGT.STATUS AS STATUS_2,
        TGT.EMPLOYEE_FLAG AS EMPLOYEE_FLAG_2,
        TGT.FT_BARCODE AS FT_BARCODE_2,
        TGT.ACCOUNT_BRANCH_CBC_NUMBER AS ACCOUNT_BRANCH_CBC_NUMBER_2
    FROM QueryOut AS QueryOut
    LEFT JOIN DBO.TREASURY_CREDITOut AS TGT
        ON QueryOut.ACCOUNT_NUMBER = TGT.ACCOUNT_NUMBER
        AND QueryOut.NOTE_NUMBER = TGT.NOTE_NUMBER
        AND QueryOut.CIS_NUMBER = TGT.CIS_NUMBER
),

Table_Comparison_EXPOut AS (
    /* transType: "Expression" */
    SELECT
        ACCOUNT_NUMBER_1 AS ACCOUNT_NUMBER,
        NOTE_NUMBER_1 AS NOTE_NUMBER,
        COMMITMENT_NUMBER_1 AS COMMITMENT_NUMBER,
        CUSTOMER_NAME_1 AS CUSTOMER_NAME,
        CIS_NUMBER_1 AS CIS_NUMBER,
        TAXID_NUMBER_1 AS TAXID_NUMBER,
        RELATED_NAME_1 AS RELATED_NAME,
        RELATED_ACCOUNT_1 AS RELATED_ACCOUNT,
        STATUS_1 AS STATUS,
        EMPLOYEE_FLAG_1 AS EMPLOYEE_FLAG,
        FT_BARCODE_1 AS FT_BARCODE,
        ACCOUNT_BRANCH_CBC_NUMBER_1 AS ACCOUNT_BRANCH_CBC_NUMBER,
        MD5(ACCOUNT_NUMBER_1 || NOTE_NUMBER_1 || CIS_NUMBER_1 || FT_BARCODE_1) AS src_hashcode,
        MD5(ACCOUNT_NUMBER_2 || NOTE_NUMBER_2 || CIS_NUMBER_2 || FT_BARCODE_2) AS tgt_hashcode,
        CASE
            WHEN ACCOUNT_NUMBER_1 IS NULL
                 AND NOTE_NUMBER_1 IS NULL
                 AND CIS_NUMBER_1 IS NULL THEN 1
            WHEN src_hashcode != tgt_hashcode THEN 3
            ELSE 0
        END AS change_code
    FROM Table_Comparison_LKPOut AS Table_Comparison_LKPOut
),

Map_OperationOut AS (
    /* transType: "Router" */
    SELECT
        ACCOUNT_NUMBER,
        NOTE_NUMBER,
        COMMITMENT_NUMBER,
        CUSTOMER_NAME,
        CIS_NUMBER,
        TAXID_NUMBER,
        RELATED_NAME,
        RELATED_ACCOUNT,
        STATUS,
        EMPLOYEE_FLAG,
        FT_BARCODE,
        ACCOUNT_BRANCH_CBC_NUMBER,
        src_hashcode,
        tgt_hashcode,
        change_code
    FROM Table_Comparison_EXPOut AS Table_Comparison_EXPOut
    WHERE change_code = 1
)

SELECT
    ACCOUNT_NUMBER,
    NOTE_NUMBER,
    COMMITMENT_NUMBER,
    CUSTOMER_NAME,
    CIS_NUMBER,
    TAXID_NUMBER,
    RELATED_NAME,
    RELATED_ACCOUNT,
    STATUS,
    EMPLOYEE_FLAG,
    FT_BARCODE,
    ACCOUNT_BRANCH_CBC_NUMBER
FROM Map_OperationOut AS Map_OperationOut