/* Transformation Name ==>SC_BOE_INTEROPERABILITY_FACT ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='BOE_INTEROPERABILITY',
		schema='EMIR_SHARED',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_SC_RR_TRIPARTY_COLL_AND_EXP_FACTOut as (
	/* SubQuery from Source ==>SQ_SQ_SC_RR_TRIPARTY_COLL_AND_EXP_FACT */
Select 
BUSINESS_DATE,
EXCHANGE,
INTEROP_ID,
INTEROP_DESC,
EXPOSURE_AMT,
CURRENCY_MNEMONIC,
Coll_Type,
FinInstrmId,
issr,
Trpty_MktVal_AMT,
Trpty_MktVal_CCY,
MktVal_AMT,
PstHrcutVal_AMT,
PstHrcutVal_CCY,
CollRqrmnt
 from 
(SELECT
 distinct
    DATE_TRUNC('DAY',a.BUSINESS_DATE) as BUSINESS_DATE,
    d.STRING_VALUE3 as EXCHANGE,
    d.STRING_VALUE5 as INTEROP_ID,
    d.STRING_VALUE4 as INTEROP_DESC,
    a.EXPOSURE_AMT as EXPOSURE_AMT,
    c.CURRENCY_MNEMONIC as CURRENCY_MNEMONIC,
    null as Coll_Type,
    null as FinInstrmId,
    null as issr,
    null as Trpty_MktVal_AMT,
    null as Trpty_MktVal_CCY,
    null as MktVal_AMT,
    null as PstHrcutVal_AMT,
    null as PstHrcutVal_CCY,
    'MGIN' as CollRqrmnt
 FROM
 (SELECT
    BUSINESS_DATE,
    COLLATERAL_REC_SHORT_CODE,
    EXPOSURE_AMT,
    BASKET_NUMBER,
    EXPOSURE_REF,
    EXPOSURE_CURR_ID
 FROM
{{ source('reg_rep', 'RR_TRIPARTY_COLL_AND_EXP_FACT') }}
 WHERE  
  BUSINESS_DATE= TO_DATE('{{ var("BUSINESS_DATE") }}','YYYYMMDD') AND 
  COLLATERAL_GIVER_SHORT_CODE= 'LCHGIVER') a
 INNER JOIN 
 (SELECT
    INSTRUMENT_GROUP,
    ISIN,
    SECURITY_VALUE,
    EXPOSURE_REF
 FROM
{{ source('reg_rep', 'RR_TRIPARTY_COLL_AND_EXP_FACT') }}
 WHERE  
  BUSINESS_DATE= TO_DATE('{{ var("BUSINESS_DATE") }}','YYYYMMDD') AND 
  COLLATERAL_GIVER_SHORT_CODE IS NULL) b
 ON
  A.EXPOSURE_REF= B.EXPOSURE_REF
 INNER JOIN 
  dw_mart.currency_dim as c
 ON
  C.ID= A.EXPOSURE_CURR_ID
 INNER JOIN 
  application_variables as d
 ON
  A.COLLATERAL_REC_SHORT_CODE= D.STRING_VALUE2 AND 
  D.VARIABLE_NAME= 'BOE_INTEROP_MNEMONIC' AND 
   'Y'  != 
 (SELECT
    STRING_VALUE
 FROM
    APPLICATION_VARIABLES
 WHERE 
  VARIABLE_NAME= 'BOE_INTEROP_STRATEGIC_FLAG')
 UNION 
 SELECT
 distinct
    DATE_TRUNC('DAY',a.BUSINESS_DATE) as BUSINESS_DATE,
    d.STRING_VALUE3 as EXCHANGE,
    d.STRING_VALUE5 as INTEROP_ID,
    d.STRING_VALUE4 as INTEROP_DESC,
    null as EXPOSURE_AMT,
    null as CURRENCY_MNEMONIC,
    b.INSTRUMENT_GROUP as Coll_Type,
    TO_VARCHAR(b.ISIN) as FinInstrmId,
    '00000000000000000000' as issr,
    MAX(a.EXPOSURE_AMT) as Trpty_MktVal_AMT,
    c.CURRENCY_MNEMONIC as Trpty_MktVal_CCY,
    SUM((1 || b.Margin_Percent) * b.SECURITY_VALUE) as MktVal_AMT,
    SUM(b.SECURITY_VALUE) as PstHrcutVal_AMT,
    c.CURRENCY_MNEMONIC as PstHrcutVal_CCY,
    'MGIN' as CollRqrmnt
 FROM
 (SELECT
    BUSINESS_DATE,
    COLLATERAL_REC_SHORT_CODE,
    EXPOSURE_AMT,
    BASKET_NUMBER,
    EXPOSURE_REF,
    EXPOSURE_CURR_ID
 FROM
{{ source('reg_rep', 'RR_TRIPARTY_COLL_AND_EXP_FACT') }}
 WHERE  
  BUSINESS_DATE= TO_DATE('{{ var("BUSINESS_DATE") }}','YYYYMMDD') AND 
  COLLATERAL_GIVER_SHORT_CODE= 'LCHGIVER') a
 INNER JOIN 
 (SELECT
    INSTRUMENT_GROUP,
    ISIN,
    SECURITY_VALUE,
    EXPOSURE_REF,
    MARGIN_PERCENT
 FROM
{{ source('reg_rep', 'RR_TRIPARTY_COLL_AND_EXP_FACT') }}
 WHERE  
  BUSINESS_DATE= TO_DATE('{{ var("BUSINESS_DATE") }}','YYYYMMDD') AND 
  COLLATERAL_GIVER_SHORT_CODE IS NULL) b
 ON
  A.EXPOSURE_REF= B.EXPOSURE_REF
 INNER JOIN 
  dw_mart.currency_dim as c
 ON
  C.ID= A.EXPOSURE_CURR_ID
 INNER JOIN 
  application_variables as d
 ON
  A.COLLATERAL_REC_SHORT_CODE= D.STRING_VALUE2 AND 
  D.VARIABLE_NAME= 'BOE_INTEROP_MNEMONIC' AND 
   'Y'  != 
 (SELECT
    STRING_VALUE
 FROM
    APPLICATION_VARIABLES
 WHERE 
  VARIABLE_NAME= 'BOE_INTEROP_STRATEGIC_FLAG')
 GROUP BY
    DATE_TRUNC('DAY',a.BUSINESS_DATE),
    d.STRING_VALUE3,
    d.STRING_VALUE5,
    d.STRING_VALUE4,
    b.INSTRUMENT_GROUP,
    TO_VARCHAR(b.ISIN),
    c.CURRENCY_MNEMONIC
 UNION 
 SELECT
 distinct
    DATE_TRUNC('DAY',a.BUSINESS_DATE),
    STRING_VALUE3 as EXCHANGE,
    STRING_VALUE5 as INTEROP_ID,
    STRING_VALUE4 as INTEROP_DESC,
    TRANSACTION_AMT as EXPOSURE_AMT,
    TRANSACTION_CCY as CURRENCY_MNEMONIC,
    null as Coll_Type,
    null as FinInstrmId,
    null as issr,
    null as Trpty_MktVal_AMT,
    null as Trpty_MktVal_CCY,
    null as MktVal_AMT,
    null as PstHrcutVal_AMT,
    null as PstHrcutVal_CCY,
    'MGIN' as CollRqrmnt
 FROM
{{ source('reg_rep', 'RR_BNK_TRIPTYALC_INVST_FACT') }} as a
 INNER JOIN 
  application_variables as d
 ON
  A.MNEMONIC= D.STRING_VALUE
 WHERE  
  D.VARIABLE_NAME= 'BOE_INTEROP_MNEMONIC' AND 
  BUSINESS_DATE= TO_DATE('{{ var("BUSINESS_DATE") }}','YYYYMMDD') AND 
   'Y' =
 (SELECT
    STRING_VALUE
 FROM
    APPLICATION_VARIABLES
 WHERE 
  VARIABLE_NAME= 'BOE_INTEROP_STRATEGIC_FLAG')
 UNION 
 SELECT
 distinct
    DATE_TRUNC('DAY',a.BUSINESS_DATE),
    STRING_VALUE3 as EXCHANGE,
    STRING_VALUE5 as INTEROP_ID,
    STRING_VALUE4 as INTEROP_DESC,
    null as EXPOSURE_AMT,
    null as CURRENCY_MNEMONIC,
    COLLATERAL_GROUP as Coll_Type,
    TO_VARCHAR(a.ISIN) as FinInstrmId,
    '00000000000000000000' as issr,
    TRANSACTION_AMT as Trpty_MktVal_AMT,
    TRANSACTION_CCY as Trpty_MktVal_CCY,
    PRE_HC_MV_TX_CCY_AMT as MktVal_AMT,
    POST_HC_MV_TX_CCY_AMT as PstHrcutVal_AMT,
    TRANSACTION_CCY as PstHrcutVal_CCY,
    'MGIN' as CollRqrmnt
 FROM
{{ source('reg_rep', 'RR_BNK_TRIPTYALC_INVST_FACT') }} as a
 INNER JOIN 
  application_variables as d
 ON
  A.MNEMONIC= D.STRING_VALUE
 WHERE  
  D.VARIABLE_NAME= 'BOE_INTEROP_MNEMONIC' AND 
  BUSINESS_DATE= TO_DATE('{{ var("BUSINESS_DATE") }}','YYYYMMDD') AND 
   'Y' =
 (SELECT
    STRING_VALUE
 FROM
    APPLICATION_VARIABLES
 WHERE 
  VARIABLE_NAME= 'BOE_INTEROP_STRATEGIC_FLAG'))
 ),

SQ_SC_RR_POSITIONS_FACTOut as (
	/* SubQuery from Source ==>SQ_SQ_SC_RR_POSITIONS_FACT */
Select 
NOTIONAL_AMT,
INTEROP_ID,
INTEROP_DESC,
CURRENCY_MNEMONIC
 from 
(SELECT
    SUM(DECODE(NVL(INSTRUMENTS_DIM.SECURITY_TYPE,'NONTERM'),'TERM',ABS(MTM_NOTIONAL),0)) as NOTIONAL_AMT,
    application_variables.STRING_VALUE5 as INTEROP_ID,
    application_variables.STRING_VALUE4 as INTEROP_DESC,
    CURRENCY_DIM.CURRENCY_MNEMONIC
 FROM
{{ source('reg_rep', 'RR_POSITIONS_FACT') }}
 INNER JOIN 
  INSTRUMENTS_DIM as INSTRUMENTS_DIM
 ON
  RR_POSITIONS_FACT.INSTRUMENT_ID= INSTRUMENTS_DIM.ID
 INNER JOIN 
  CURRENCY_DIM as CURRENCY_DIM
 ON
  RR_POSITIONS_FACT.MARGIN_CURRENCY_ID= CURRENCY_DIM.ID
 INNER JOIN 
  application_variables as application_variables
 ON
  COUNTERPARTIES_DIM.CLEARING_MEMBER_MNEMONIC= APPLICATION_VARIABLES.STRING_VALUE5
 WHERE  
  MEMBER_COUNTERPARTY_ID= COUNTERPARTIES_DIM.ID AND 
   BUSINESS_DATE_ID =
 (SELECT
 distinct
    ID
 FROM
{{ source('dw_mart', 'CALENDAR_DIM') }}
 WHERE  
  CAL_DATE= TO_DATE('{{ var("BUSINESS_DATE") }}','YYYYMMDD') AND 
  TYPE= 'LTD_STD') AND 
   exchange_id IN
 (SELECT
    id
 FROM
{{ source('dw_mart', 'exchange_dim') }}
 WHERE 
  EXCHANGE_MNEMONIC= 'ECL')
 GROUP BY
    application_variables.STRING_VALUE5,
    application_variables.STRING_VALUE4,
    CURRENCY_DIM.CURRENCY_MNEMONIC)
 ),

SQ_SC_RR_TRADE_AND_TRANSACTION_FACTOut as (
	/* SubQuery from Source ==>SQ_SQ_SC_RR_TRADE_AND_TRANSACTION_FACT */
Select 
BUSINESS_DATE_TIME,
TrdsClrd,
INTEROP_ID,
INTEROP_DESC
 from 
(SELECT
    a.BUSINESS_DATE_TIME,
    ROUND(COUNT(a.ID)/2) as TrdsClrd,
    d.STRING_VALUE5 as INTEROP_ID,
    d.STRING_VALUE4 as INTEROP_DESC
 FROM
{{ source('reg_rep', 'RR_TRADE_AND_TRANSACTION_FACT') }} as a
 INNER JOIN 
  COUNTERPARTIES_DIM as b
 ON
  A.MEMBER_COUNTERPARTY_ID= B.ID
 INNER JOIN 
  application_variables as d
 ON
  B.CLEARING_MEMBER_MNEMONIC= D.STRING_VALUE5
 WHERE  
  D.VARIABLE_NAME= 'BOE_INTEROP_MNEMONIC' AND 
   a.exchange_id IN
 (SELECT
    id
 FROM
{{ source('dw_mart', 'exchange_dim') }}
 WHERE 
  EXCHANGE_MNEMONIC= 'ECL') AND 
  TRADE_ACTION_TYPE= 'NEW' AND 
   BUSINESS_DATE_ID =
 (SELECT
 distinct
    ID
 FROM
{{ source('dw_mart', 'CALENDAR_DIM') }}
 WHERE  
  CAL_DATE= TO_DATE('{{ var("BUSINESS_DATE") }}','YYYYMMDD') AND 
  TYPE= 'LTD_STD')
 GROUP BY
    a.BUSINESS_DATE_TIME,
    d.STRING_VALUE5,
    d.STRING_VALUE4)
 ),

SQ_SC_RR_POSITIONS_FACT_master as (
  Select
  	SQ_SC_RR_POSITIONS_FACTOut.NOTIONAL_AMT as NOTIONAL_AMT,
	 SQ_SC_RR_POSITIONS_FACTOut.INTEROP_ID as INTEROP_ID1,
	 SQ_SC_RR_POSITIONS_FACTOut.INTEROP_DESC as INTEROP_DESC1,
	 SQ_SC_RR_POSITIONS_FACTOut.CURRENCY_MNEMONIC as CURRENCY_MNEMONIC
  From SQ_SC_RR_POSITIONS_FACTOut as SQ_SC_RR_POSITIONS_FACTOut
),
JNR_gross_CLRIDOut as (
Select 
	SQ_SC_RR_TRADE_AND_TRANSACTION_FACTOut.BUSINESS_DATE_TIME as BUSINESS_DATE_TIME,
	 SQ_SC_RR_TRADE_AND_TRANSACTION_FACTOut.TrdsClrd as TrdsClrd,
	 SQ_SC_RR_TRADE_AND_TRANSACTION_FACTOut.INTEROP_ID as INTEROP_ID,
	 SQ_SC_RR_TRADE_AND_TRANSACTION_FACTOut.INTEROP_DESC as INTEROP_DESC,
	 SQ_SC_RR_POSITIONS_FACT_master.NOTIONAL_AMT as NOTIONAL_AMT,
	 SQ_SC_RR_POSITIONS_FACT_master.INTEROP_ID1 as INTEROP_ID1,
	 SQ_SC_RR_POSITIONS_FACT_master.INTEROP_DESC1 as INTEROP_DESC1,
	 SQ_SC_RR_POSITIONS_FACT_master.CURRENCY_MNEMONIC as CURRENCY_MNEMONIC,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
SQ_SC_RR_POSITIONS_FACT_master as SQ_SC_RR_POSITIONS_FACT_master inner JOIN SQ_SC_RR_TRADE_AND_TRANSACTION_FACTOut as SQ_SC_RR_TRADE_AND_TRANSACTION_FACTOut 
ON
SQ_SC_RR_TRADE_AND_TRANSACTION_FACTOut.INTEROP_ID = SQ_SC_RR_POSITIONS_FACT_master.INTEROP_ID1 
),

exp_TTL_SECURITYOut as (
	
Select 
	BUSINESS_DATE as BUSINESS_DATE,
	 NULL as Trdsclrd,
	 EXCHANGE as EXCHANGE,
	 INTEROP_ID as INTEROP_ID,
	 INTEROP_DESC as INTEROP_DESC,
	 EXPOSURE_AMT as EXPOSURE_AMT,
	 CURRENCY_MNEMONIC as CURRENCY_MNEMONIC,
	 Coll_Type as Coll_Type,
	 FinInstrmId as FinInstrmId,
	 issr as issr,
	 Trpty_MktVal_AMT as Trpty_MktVal_AMT,
	 Trpty_MktVal_CCY as Trpty_MktVal_CCY,
	 MktVal_AMT as MktVal_AMT,
	 NULL as NOTIONAL_AMT,
	 PstHrcutVal_AMT as PstHrcutVal_AMT,
	 PstHrcutVal_CCY as PstHrcutVal_CCY,
	 CollRqrmnt as CollRqrmnt,
	 NULL as GROSS_NOTIONAL_CURRENCY
From SQ_SC_RR_TRIPARTY_COLL_AND_EXP_FACTOut as SQ_SC_RR_TRIPARTY_COLL_AND_EXP_FACTOut),

DSR_exp_TTL_SECURITY1Out as (
	
Select 
	JNR_gross_CLRIDOut.BUSINESS_DATE_TIME as BUSINESS_DATE,
	 JNR_gross_CLRIDOut.TrdsClrd as Trdsclrd,
	 JNR_gross_CLRIDOut.INTEROP_ID as INTEROP_ID,
	 JNR_gross_CLRIDOut.INTEROP_DESC as INTEROP_DESC,
	 JNR_gross_CLRIDOut.NOTIONAL_AMT as NOTIONAL_AMT,
	 JNR_gross_CLRIDOut.CURRENCY_MNEMONIC as CURRENCY_MNEMONIC2
From JNR_gross_CLRIDOut as JNR_gross_CLRIDOut),

exp_TTL_SECURITY1Out as (
	
Select 
	BUSINESS_DATE as BUSINESS_DATE,
	 Trdsclrd as Trdsclrd,
	 'ECL' as EXCHANGE,
	 INTEROP_ID as INTEROP_ID,
	 INTEROP_DESC as INTEROP_DESC,
	 NULL as EXPOSURE_AMT,
	 NULL as CURRENCY_MNEMONIC,
	 NULL as Coll_Type,
	 NULL as FinInstrmId,
	 '00000000000000000000' as issr,
	 NULL as Trpty_MktVal_AMT,
	 NULL as Trpty_MktVal_CCY,
	 NULL as MktVal_AMT,
	 NOTIONAL_AMT as NOTIONAL_AMT,
	 NULL as PstHrcutVal_AMT,
	 CURRENCY_MNEMONIC2 as CURRENCY_MNEMONIC2,
	 NULL as CURRENCY_MNEMONIC1,
	 NULL as PstHrcutVal_CCY,
	 'Margin' as ColRqmnt
From DSR_exp_TTL_SECURITY1Out as DSR_exp_TTL_SECURITY1Out),

Union_ALL_DATEOut as (
	 
 Select 
	BUSINESS_DATE as BUSINESS_DATE,
	 Trdsclrd as Trdsclrd,
	 EXCHANGE as EXCHANGE,
	 INTEROP_ID as INTEROP_ID,
	 INTEROP_DESC as INTEROP_DESC,
	 EXPOSURE_AMT as EXPOSURE_AMT,
	 CURRENCY_MNEMONIC as CURRENCY_MNEMONIC,
	 Coll_Type as Coll_Type,
	 FinInstrmId as FinInstrmId,
	 issr as issr,
	 Trpty_MktVal_AMT as Trpty_MktVal_AMT,
	 Trpty_MktVal_CCY as Trpty_MktVal_CCY,
	 MktVal_AMT as MktVal_AMT,
	 NOTIONAL_AMT as NOTIONAL_AMT,
	 PstHrcutVal_AMT as PstHrcutVal_AMT,
	 PstHrcutVal_CCY as PstHrcutVal_CCY,
	 CollRqrmnt as CollRqrmnt,
	 GROSS_NOTIONAL_CURRENCY as GROSS_NOTIONAL_CURRENCY
From (
(Select 
	exp_TTL_SECURITYOut.BUSINESS_DATE as BUSINESS_DATE1,
	 exp_TTL_SECURITYOut.Trdsclrd as Trdsclrd1,
	 exp_TTL_SECURITYOut.EXCHANGE as EXCHANGE1,
	 exp_TTL_SECURITYOut.INTEROP_ID as INTEROP_ID1,
	 exp_TTL_SECURITYOut.INTEROP_DESC as INTEROP_DESC1,
	 exp_TTL_SECURITYOut.EXPOSURE_AMT as EXPOSURE_AMT1,
	 exp_TTL_SECURITYOut.CURRENCY_MNEMONIC as CURRENCY_MNEMONIC1,
	 exp_TTL_SECURITYOut.Coll_Type as Coll_Type1,
	 exp_TTL_SECURITYOut.FinInstrmId as FinInstrmId1,
	 exp_TTL_SECURITYOut.issr as issr1,
	 exp_TTL_SECURITYOut.Trpty_MktVal_AMT as Trpty_MktVal_AMT1,
	 exp_TTL_SECURITYOut.Trpty_MktVal_CCY as Trpty_MktVal_CCY1,
	 exp_TTL_SECURITYOut.MktVal_AMT as MktVal_AMT1,
	 exp_TTL_SECURITYOut.NOTIONAL_AMT as NOTIONAL_AMT1,
	 exp_TTL_SECURITYOut.PstHrcutVal_AMT as PstHrcutVal_AMT1,
	 exp_TTL_SECURITYOut.PstHrcutVal_CCY as PstHrcutVal_CCY1,
	 exp_TTL_SECURITYOut.CollRqrmnt as CollRqrmnt1,
	 exp_TTL_SECURITYOut.GROSS_NOTIONAL_CURRENCY as GROSS_NOTIONAL_CURRENCY2 
From exp_TTL_SECURITYOut as exp_TTL_SECURITYOut )
 Union All 
 (Select 
	exp_TTL_SECURITY1Out.BUSINESS_DATE as BUSINESS_DATE2,
	 exp_TTL_SECURITY1Out.Trdsclrd as Trdsclrd2,
	 exp_TTL_SECURITY1Out.EXCHANGE as EXCHANGE2,
	 exp_TTL_SECURITY1Out.INTEROP_ID as INTEROP_ID2,
	 exp_TTL_SECURITY1Out.INTEROP_DESC as INTEROP_DESC2,
	 exp_TTL_SECURITY1Out.EXPOSURE_AMT as EXPOSURE_AMT2,
	 exp_TTL_SECURITY1Out.CURRENCY_MNEMONIC as CURRENCY_MNEMONIC2,
	 exp_TTL_SECURITY1Out.Coll_Type as Coll_Type2,
	 exp_TTL_SECURITY1Out.FinInstrmId as FinInstrmId2,
	 exp_TTL_SECURITY1Out.issr as issr2,
	 exp_TTL_SECURITY1Out.Trpty_MktVal_AMT as Trpty_MktVal_AMT2,
	 exp_TTL_SECURITY1Out.Trpty_MktVal_CCY as Trpty_MktVal_CCY2,
	 exp_TTL_SECURITY1Out.MktVal_AMT as MktVal_AMT2,
	 exp_TTL_SECURITY1Out.NOTIONAL_AMT as NOTIONAL_AMT2,
	 exp_TTL_SECURITY1Out.PstHrcutVal_AMT as PstHrcutVal_AMT2,
	 exp_TTL_SECURITY1Out.CURRENCY_MNEMONIC1 as PstHrcutVal_CCY2,
	 exp_TTL_SECURITY1Out.PstHrcutVal_CCY as CollRqrmnt2,
	 exp_TTL_SECURITY1Out.CURRENCY_MNEMONIC2 as GROSS_NOTIONAL_CURRENCY3 
From exp_TTL_SECURITY1Out as exp_TTL_SECURITY1Out )
)),

SC_SEQ_INTEROP1Out as (
	Select 
	Union_ALL_DATEOut.INTEROP_ID as INTEROP_ID,
	 Union_ALL_DATEOut.CURRENCY_MNEMONIC as CURRENCY_MNEMONIC,
	 Union_ALL_DATEOut.EXCHANGE as EXCHANGE,
	 Union_ALL_DATEOut.GROSS_NOTIONAL_CURRENCY as GROSS_NOTIONAL_CURRENCY,
	 Union_ALL_DATEOut.Trdsclrd as Trdsclrd,
	 Union_ALL_DATEOut.FinInstrmId as FinInstrmId,
	 Union_ALL_DATEOut.Trpty_MktVal_CCY as Trpty_MktVal_CCY,
	 Union_ALL_DATEOut.PstHrcutVal_AMT as PstHrcutVal_AMT,
	 Union_ALL_DATEOut.MktVal_AMT as MktVal_AMT,
	 Union_ALL_DATEOut.issr as issr,
	 Union_ALL_DATEOut.Coll_Type as Coll_Type,
	 Union_ALL_DATEOut.NOTIONAL_AMT as NOTIONAL_AMT,
	 Union_ALL_DATEOut.PstHrcutVal_CCY as PstHrcutVal_CCY,
	 Union_ALL_DATEOut.Trpty_MktVal_AMT as Trpty_MktVal_AMT,
	 Union_ALL_DATEOut.EXPOSURE_AMT as EXPOSURE_AMT,
	 Union_ALL_DATEOut.INTEROP_DESC as INTEROP_DESC,
	 Union_ALL_DATEOut.CollRqrmnt as CollRqrmnt 
FROM Union_ALL_DATEOut as Union_ALL_DATEOut),

Target_Table_Name_SK_Max_Value AS (
  SELECT
    MAX(GENERATED_SEQ) AS max_generated_seq
  FROM {{ this }}
),

 DSR_EXP_FINAL1Out as (
	
Select 
	SC_SEQ_INTEROP1Out.(SELECT max_generated_seq FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER() AS GENERATED_SEQ,
	 SC_SEQ_INTEROP1Out.Trdsclrd as Trdsclrd,
	 SC_SEQ_INTEROP1Out.EXCHANGE as EXCHANGE,
	 SC_SEQ_INTEROP1Out.INTEROP_ID as INTEROP_ID,
	 SC_SEQ_INTEROP1Out.INTEROP_DESC as INTEROP_DESC,
	 SC_SEQ_INTEROP1Out.EXPOSURE_AMT as EXPOSURE_AMT,
	 SC_SEQ_INTEROP1Out.CURRENCY_MNEMONIC as CURRENCY_MNEMONIC,
	 SC_SEQ_INTEROP1Out.Coll_Type as Coll_Type,
	 SC_SEQ_INTEROP1Out.FinInstrmId as FinInstrmId,
	 SC_SEQ_INTEROP1Out.issr as issr,
	 SC_SEQ_INTEROP1Out.Trpty_MktVal_AMT as Trpty_MktVal_AMT,
	 SC_SEQ_INTEROP1Out.Trpty_MktVal_CCY as Trpty_MktVal_CCY,
	 SC_SEQ_INTEROP1Out.MktVal_AMT as MktVal_AMT,
	 SC_SEQ_INTEROP1Out.NOTIONAL_AMT as NOTIONAL_AMT,
	 SC_SEQ_INTEROP1Out.PstHrcutVal_AMT as PstHrcutVal_AMT,
	 SC_SEQ_INTEROP1Out.PstHrcutVal_CCY as PstHrcutVal_CCY,
	 SC_SEQ_INTEROP1Out.CollRqrmnt as CollRqrmnt,
	 SC_SEQ_INTEROP1Out.GROSS_NOTIONAL_CURRENCY as GROSS_NOTIONAL_CURRENCY
From SC_SEQ_INTEROP1Out as SC_SEQ_INTEROP1Out),

EXP_FINAL1Out as (
	
Select 
	GENERATED_SEQ as GENERATED_SEQ,
	 LPAD ( GENERATED_SEQ,
	 9,
	 '0' ) as v_SEQ_LPAD_TO_9,
	 DATEDIFF ( SECOND,
	 TO_TIMESTAMP ( '01/01/1970 00:00:00',
	 'DD-MM-YYYY HH24:MI:SS' ),
	 dsCurrentTimestamp ( ) ) as v_EPOC_TIME,
	 v_EPOC_TIME || v_SEQ_LPAD_TO_9 as v_CONCATE_ID,
	 v_CONCATE_ID as ID,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 dsf_1.ID as BATCH_DETAILS_ID,
	 DATE_TRUNC ( 'DAY',
	 TO_DATE ( LTRIM ( RTRIM ( '{{ var("BATCH_BUSINESS_DATE") }}' ) ),
	 'YYYYMMDD' ) ) as v_BATCH_BUSINESS_DATE,
	 v_BATCH_BUSINESS_DATE as BATCH_BUSINESS_DATE,
	 dsf_2.ID as BUSINESS_DATE_ID,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT,
	 TO_DATE ( '{{ var("BUSINESS_DATE") }}',
	 'YYYYMMDD' ) as BUSINESS_DATE,
	 Trdsclrd as Trdsclrd,
	 EXCHANGE as EXCHANGE,
	 INTEROP_ID as INTEROP_ID,
	 INTEROP_DESC as INTEROP_DESC,
	 EXPOSURE_AMT as EXPOSURE_AMT,
	 CURRENCY_MNEMONIC as CURRENCY_MNEMONIC,
	 Coll_Type as Coll_Type,
	 FinInstrmId as FinInstrmId,
	 issr as issr,
	 Trpty_MktVal_AMT as Trpty_MktVal_AMT,
	 Trpty_MktVal_CCY as Trpty_MktVal_CCY,
	 MktVal_AMT as MktVal_AMT,
	 NOTIONAL_AMT as NOTIONAL_AMT,
	 PstHrcutVal_AMT as PstHrcutVal_AMT,
	 PstHrcutVal_CCY as PstHrcutVal_CCY,
	 CollRqrmnt as CollRqrmnt,
	 NULL as SUBMIT_FLAG,
	 GROSS_NOTIONAL_CURRENCY as GROSS_NOTIONAL_CURRENCY,
	 0 as ERROR_INDICATOR
From DSR_EXP_FINAL1Out as DSR_EXP_FINAL1Out
LEFT JOIN (
SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME FROM (  SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    BATCH_DETAILS.ID as ID,    BATCH_DETAILS.BATCH_ID as BATCH_ID,    BATCH_DETAILS.TARGET_TABLE_NAME as TARGET_TABLE_NAME,    BATCH_DETAILS.FILE_NAME as FILE_NAME,    BATCH_DETAILS.STATUS as STATUS FROM (SELECT    id,    TARGET_TABLE_NAME,    BATCH_ID,    STATUS,    ACTIVE_FLAG,    BATCH_DETAILS_START_TIME,    FILE_NAME,    RANK() OVER(partition by batch_id,TARGET_TABLE_NAME,FILE_NAME order by BATCH_DETAILS_START_TIME DESC) as RANK FROM    BATCH_DETAILS) BATCH_DETAILS WHERE    RANK= 1 AND   STATUS= 'I' AND   ACTIVE_FLAG= 1 )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}' AND dsf_1.FILE_NAME = '{{ var("SOURCE_NAME") }}'
LEFT JOIN (
SELECT ID, CAL_DATE, TYPE FROM (  SELECT ID, CAL_DATE, TYPE,  ROW_NUMBER() OVER (PARTITION BY CAL_DATE, TYPE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CAL_DATE, TYPE,  ROW_NUMBER() OVER (PARTITION BY CAL_DATE, TYPE ORDER BY CAL_DATE, TYPE NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CALENDAR_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.CAL_DATE = 'LTD_STD' AND dsf_2.TYPE = v_BATCH_BUSINESS_DATE
),

DSR_SC_BOE_INTEROPERABILITY_FACTOut as (
	
Select 
	EXP_FINAL1Out.ID as ID,
	 EXP_FINAL1Out.BATCH_ID as BATCH_ID,
	 EXP_FINAL1Out.BUSINESS_DATE as BUSINESS_DATE,
	 EXP_FINAL1Out.BUSINESS_DATE_ID as BUSINESS_DATE_ID,
	 EXP_FINAL1Out.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_FINAL1Out.EXCHANGE as EXCHANGE,
	 EXP_FINAL1Out.INTEROP_ID as INTEROP_ID,
	 EXP_FINAL1Out.INTEROP_DESC as INTEROP_DESC,
	 EXP_FINAL1Out.EXPOSURE_AMT as TtlInitlMrgn_AMT,
	 EXP_FINAL1Out.CURRENCY_MNEMONIC as TtlInitlMrgn_CCY,
	 EXP_FINAL1Out.Trdsclrd as TrdsClrd,
	 EXP_FINAL1Out.NOTIONAL_AMT as GrssNtnlAmt_AMT,
	 EXP_FINAL1Out.GROSS_NOTIONAL_CURRENCY as GrssNtnlAmt_CCY,
	 EXP_FINAL1Out.PstHrcutVal_AMT as PstHrcutVal_AMT,
	 EXP_FINAL1Out.PstHrcutVal_CCY as PstHrcutVal_CCY,
	 EXP_FINAL1Out.Trpty_MktVal_AMT as Trpty_MktVal_AMT,
	 EXP_FINAL1Out.Trpty_MktVal_CCY as Trpty_MktVal_CCY,
	 EXP_FINAL1Out.Coll_Type as Coll_Type,
	 EXP_FINAL1Out.FinInstrmId as FinInstrmId,
	 EXP_FINAL1Out.issr as issr,
	 EXP_FINAL1Out.MktVal_AMT as MktVal_AMT,
	 EXP_FINAL1Out.Trpty_MktVal_CCY as MktVal_CCY,
	 EXP_FINAL1Out.CollRqrmnt as CollRqrmnt,
	 EXP_FINAL1Out.SUBMIT_FLAG as SUBMIT_FLAG,
	 EXP_FINAL1Out.ERROR_INDICATOR as ERROR_INDICATOR
From EXP_FINAL1Out as EXP_FINAL1Out)

Select 
	ID as ID,
	BATCH_ID as BATCH_ID,
	BUSINESS_DATE as BUSINESS_DATE,
	BUSINESS_DATE_ID as BUSINESS_DATE_ID,
	BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	EXCHANGE as EXCHANGE,
	INTEROP_ID as INTEROP_ID,
	INTEROP_DESC as INTEROP_DESC,
	TtlInitlMrgn_AMT as TtlInitlMrgn_AMT,
	TtlInitlMrgn_CCY as TtlInitlMrgn_CCY,
	TrdsClrd as TrdsClrd,
	GrssNtnlAmt_AMT as GrssNtnlAmt_AMT,
	GrssNtnlAmt_CCY as GrssNtnlAmt_CCY,
	PstHrcutVal_AMT as PstHrcutVal_AMT,
	PstHrcutVal_CCY as PstHrcutVal_CCY,
	Trpty_MktVal_AMT as Trpty_MktVal_AMT,
	Trpty_MktVal_CCY as Trpty_MktVal_CCY,
	Coll_Type as Coll_Type,
	FinInstrmId as FinInstrmId,
	issr as issr,
	MktVal_AMT as MktVal_AMT,
	MktVal_CCY as MktVal_CCY,
	CollRqrmnt as CollRqrmnt,
	SUBMIT_FLAG as SUBMIT_FLAG,
	ERROR_INDICATOR as ERROR_INDICATOR 
From DSR_SC_BOE_INTEROPERABILITY_FACTOut as DSR_SC_BOE_INTEROPERABILITY_FACTOut