/* Transformation Name ==>SC_LD_SA_CONTRACT ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='LD_SA_CONTRACT',
		schema='LDSA_SHARED',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_SC_LCHSA_ETD_Contract_YYYYmmdd_YYYYmmddHH24missOut as (
	Select REPORT_DATE, 
		CONTRACT_ID, 
		CLEARING_ORG, 
		PRODUCT_FAMILY_CODE, 
		BASE_PRODUCT, 
		UNDERLYING_TYPE, 
		MIC, 
		CLEARING_CURRENCY, 
		PRICE_MULTIPLIER, 
		MATURITY_DATE, 
		DELIVERY_TYPE, 
		UNDERLYING_INTERNAL_CODE, 
		UNDERLYING_ISIN_CODE, 
		OPTION_TYPE, 
		OPTION_EXERCISE_STYLE, 
		STRIKE_PRICE, 
		REFERENCE_PRICE, 
		ISIN_CODE, 
		EXTERNAL_CONTRACT_CODE, 
		EXCHANGE_RATE, 
		UNDERLYING_SUB_TYPE, 
		ASSET_CLASS, 
		CRYPTO_ASSET, 
		UNDERLYING_NAME, 
		UNDERLYING_IND_TYPE, 
		SETTLEMENT_CCY, 
		FINAL_CONTRACTUAL_STLMT_DT, 
		CurrentlyProcessedFileName
 from 
{{ source ('FlatFile_catalog_1','LCHSA_ETD_Contract_YYYYmmdd_YYYYmmddHH24miss') }} 
 ),

EXP_TRIMOut as (
	
Select 
	REPORT_DATE as REPORT_DATE,
	 ( CASE WHEN REPORT_DATE IS NOT NULL THEN TO_DATE ( LTRIM ( RTRIM ( REPORT_DATE ) ),
	 'DD/MM/YYYY' ) ELSE ABORT ( 'REPORT_DATE IS NULL from Source which is a mandatory field,
	hence aborting the session' ) END ) as O_REPORT_DATE,
	 RTRIM ( LTRIM ( CONTRACT_ID ) ) as O_CONTRACT_ID,
	 RTRIM ( LTRIM ( CLEARING_ORG ) ) as O_CLEARING_ORG,
	 RTRIM ( LTRIM ( PRODUCT_FAMILY_CODE ) ) as O_PRODUCT_FAMILY_CODE,
	 RTRIM ( LTRIM ( BASE_PRODUCT ) ) as O_BASE_PRODUCT,
	 RTRIM ( LTRIM ( UNDERLYING_TYPE ) ) as O_UNDERLYING_TYPE,
	 RTRIM ( LTRIM ( MIC ) ) as O_MIC,
	 RTRIM ( LTRIM ( CLEARING_CURRENCY ) ) as O_CLEARING_CURRENCY,
	 RTRIM ( LTRIM ( PRICE_MULTIPLIER ) ) as O_PRICE_MULTIPLIER,
	 MATURITY_DATE as MATURITY_DATE,
	 ( CASE WHEN MATURITY_DATE IS NOT NULL THEN LTRIM ( RTRIM ( MATURITY_DATE ) ) ELSE NULL END ) as TRIM_MATURITY_DATE,
	 ( CASE WHEN TRIM_MATURITY_DATE IS NOT NULL THEN ( CASE WHEN TO_DATE ( TRIM_MATURITY_DATE,
	 'YYYY/MM/DD' ) THEN TO_DATE ( TRIM_MATURITY_DATE,
	 'YYYY/MM/DD' ) ELSE ( CASE WHEN TO_DATE ( TRIM_MATURITY_DATE,
	 'DD/MM/YYYY' ) THEN TO_DATE ( TRIM_MATURITY_DATE,
	 'DD/MM/YYYY' ) ELSE ( CASE WHEN TO_DATE ( TRIM_MATURITY_DATE,
	 'YYYY-MM-DD' ) THEN TO_DATE ( TRIM_MATURITY_DATE,
	 'YYYY-MM-DD' ) ELSE null END ) END ) END ) ELSE NULL END ) as V_MATURITY_DATE,
	 ( CASE WHEN V_MATURITY_DATE IS NOT NULL THEN TO_DATE ( TO_VARCHAR ( V_MATURITY_DATE,
	 'DD/MM/YYYY' ),
	 'DD/MM/YYYY' ) ELSE NULL END ) as O_MATURITY_DATE,
	 RTRIM ( LTRIM ( DELIVERY_TYPE ) ) as O_DELIVERY_TYPE,
	 RTRIM ( LTRIM ( UNDERLYING_INTERNAL_CODE ) ) as O_UNDERLYING_INTERNAL_CODE,
	 RTRIM ( LTRIM ( UNDERLYING_ISIN_CODE ) ) as O_UNDERLYING_ISIN_CODE,
	 RTRIM ( LTRIM ( OPTION_TYPE ) ) as O_OPTION_TYPE,
	 RTRIM ( LTRIM ( OPTION_EXERCISE_STYLE ) ) as O_OPTION_EXERCISE_STYLE,
	 RTRIM ( LTRIM ( STRIKE_PRICE ) ) as O_STRIKE_PRICE,
	 RTRIM ( LTRIM ( REFERENCE_PRICE ) ) as O_REFERENCE_PRICE,
	 RTRIM ( LTRIM ( ISIN_CODE ) ) as O_ISIN_CODE,
	 RTRIM ( LTRIM ( EXTERNAL_CONTRACT_CODE ) ) as O_EXTERNAL_CONTRACT_CODE,
	 LTRIM ( RTRIM ( EXCHANGE_RATE ) ) as O_EXCHANGE_RATE,
	 LTRIM ( RTRIM ( UNDERLYING_SUB_TYPE ) ) as O_UNDERLYING_SUB_TYPE,
	 RTRIM ( LTRIM ( ASSET_CLASS ) ) as O_ASSET_CLASS,
	 RTRIM ( LTRIM ( CRYPTO_ASSET ) ) as O_CRYPTO_ASSET,
	 RTRIM ( LTRIM ( UNDERLYING_NAME ) ) as O_UNDERLYING_NAME,
	 RTRIM ( LTRIM ( UNDERLYING_IND_TYPE ) ) as O_UNDERLYING_IND_TYPE,
	 RTRIM ( LTRIM ( SETTLEMENT_CCY ) ) as O_SETTLEMENT_CCY,
	 FINAL_CONTRACTUAL_STLMT_DT as FINAL_CONTRACTUAL_STLMT_DT,
	 TO_DATE ( LTRIM ( RTRIM ( FINAL_CONTRACTUAL_STLMT_DT ) ),
	 'DD/MM/YYYY' ) as O_FINAL_CONTRACTUAL_STLMT_DT,
	 CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 'LCH.SA' as ENTITY_NAME,
	 '1' as ENABLE_IND
From SQ_SC_LCHSA_ETD_Contract_YYYYmmdd_YYYYmmddHH24missOut as SQ_SC_LCHSA_ETD_Contract_YYYYmmdd_YYYYmmddHH24missOut),

DSR_EXP_PASS_THROUGHOut as (
	
Select 
	EXP_TRIMOut.O_REPORT_DATE as REPORT_DATE,
	 EXP_TRIMOut.ENTITY_NAME as ENTITY_NAME,
	 EXP_TRIMOut.O_CONTRACT_ID as CONTRACT_ID,
	 EXP_TRIMOut.O_CLEARING_ORG as CLEARING_ORG,
	 EXP_TRIMOut.O_PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	 EXP_TRIMOut.O_BASE_PRODUCT as BASE_PRODUCT,
	 EXP_TRIMOut.O_UNDERLYING_TYPE as UNDERLYING_TYPE,
	 EXP_TRIMOut.O_MIC as MIC,
	 EXP_TRIMOut.O_CLEARING_CURRENCY as CLEARING_CURRENCY,
	 EXP_TRIMOut.O_PRICE_MULTIPLIER as PRICE_MULTIPLIER,
	 EXP_TRIMOut.O_MATURITY_DATE as MATURITY_DATE,
	 EXP_TRIMOut.O_DELIVERY_TYPE as DELIVERY_TYPE,
	 EXP_TRIMOut.O_UNDERLYING_INTERNAL_CODE as UNDERLYING_INTERNAL_CODE,
	 EXP_TRIMOut.O_UNDERLYING_ISIN_CODE as UNDERLYING_ISIN_CODE,
	 EXP_TRIMOut.O_OPTION_TYPE as OPTION_TYPE,
	 EXP_TRIMOut.O_OPTION_EXERCISE_STYLE as OPTION_EXERCISE_STYLE,
	 EXP_TRIMOut.O_STRIKE_PRICE as STRIKE_PRICE,
	 EXP_TRIMOut.O_REFERENCE_PRICE as REFERENCE_PRICE,
	 EXP_TRIMOut.O_ISIN_CODE as ISIN_CODE,
	 EXP_TRIMOut.O_EXTERNAL_CONTRACT_CODE as EXTERNAL_CONTRACT_CODE,
	 EXP_TRIMOut.O_EXCHANGE_RATE as EXCHANGE_RATE,
	 EXP_TRIMOut.O_UNDERLYING_SUB_TYPE as UNDERLYING_SUB_TYPE,
	 EXP_TRIMOut.O_ASSET_CLASS as ASSET_CLASS,
	 EXP_TRIMOut.O_CRYPTO_ASSET as CRYPTO_ASSET,
	 EXP_TRIMOut.O_UNDERLYING_NAME as UNDERLYING_NAME,
	 EXP_TRIMOut.O_UNDERLYING_IND_TYPE as UNDERLYING_IND_TYPE,
	 EXP_TRIMOut.O_SETTLEMENT_CCY as SETTLEMENT_CCY,
	 EXP_TRIMOut.ENABLE_IND as ENABLE_IND,
	 EXP_TRIMOut.CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 EXP_TRIMOut.O_FINAL_CONTRACTUAL_STLMT_DT as FINAL_CONTRACTUAL_STLMT_DT
From EXP_TRIMOut as EXP_TRIMOut),

Target_Table_Name_SK_Max_Value AS (
  SELECT
    MAX(GENERATED_SEQ) AS max_generated_seq
  FROM {{ this }}
),

 DSR_SC_EXP_EPOC_GENERATOROut as (
	
Select 
	SC_SEQ_LD_SA_CONTRACTOut.(SELECT max_generated_seq FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER() AS GENERATED_SEQ
From SC_SEQ_LD_SA_CONTRACTOut as SC_SEQ_LD_SA_CONTRACTOut),

EXP_PASS_THROUGHOut as (
	
Select 
	'{{ var("BATCH_ID") }}' as BATCH_ID,
	 :LKP.SC_LKP_BATCH_DETAILS ( '{{ var("BATCH_ID") }}',
	 '{{ var("TARGET_NAME") }}',
	 '{{ var("SOURCE_NAME_OVERRIDE") }}' ) as BATCH_DETAILS_ID,
	 REPORT_DATE as REPORT_DATE,
	 TO_DATE ( '{{ var("BUSINESS_DATE") }}',
	 'DDMMYYYY' ) as O_BUSINESS_DATE,
	 TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ) as BATCH_START_DATE,
	 ENTITY_NAME as ENTITY_NAME,
	 :LKP.SC_LKP_ENTITY_DIM ( ENTITY_NAME,
	 REPORT_DATE ) as ENTITY_ID,
	 CONTRACT_ID as CONTRACT_ID,
	 CLEARING_ORG as CLEARING_ORG,
	 PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	 BASE_PRODUCT as BASE_PRODUCT,
	 UNDERLYING_TYPE as UNDERLYING_TYPE,
	 MIC as MIC,
	 CLEARING_CURRENCY as CLEARING_CURRENCY,
	 PRICE_MULTIPLIER as PRICE_MULTIPLIER,
	 MATURITY_DATE as MATURITY_DATE,
	 DELIVERY_TYPE as DELIVERY_TYPE,
	 UNDERLYING_INTERNAL_CODE as UNDERLYING_INTERNAL_CODE,
	 UNDERLYING_ISIN_CODE as UNDERLYING_ISIN_CODE,
	 OPTION_TYPE as OPTION_TYPE,
	 OPTION_EXERCISE_STYLE as OPTION_EXERCISE_STYLE,
	 STRIKE_PRICE as STRIKE_PRICE,
	 REFERENCE_PRICE as REFERENCE_PRICE,
	 ISIN_CODE as ISIN_CODE,
	 EXTERNAL_CONTRACT_CODE as EXTERNAL_CONTRACT_CODE,
	 EXCHANGE_RATE as EXCHANGE_RATE,
	 UNDERLYING_SUB_TYPE as UNDERLYING_SUB_TYPE,
	 ASSET_CLASS as ASSET_CLASS,
	 CRYPTO_ASSET as CRYPTO_ASSET,
	 UNDERLYING_NAME as UNDERLYING_NAME,
	 UNDERLYING_IND_TYPE as UNDERLYING_IND_TYPE,
	 SETTLEMENT_CCY as SETTLEMENT_CCY,
	 ENABLE_IND as ENABLE_IND,
	 '{{ var("FILE_NAME") }}' as FILE_NAME,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT,
	 CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 FINAL_CONTRACTUAL_STLMT_DT as FINAL_CONTRACTUAL_STLMT_DT
From DSR_EXP_PASS_THROUGHOut as DSR_EXP_PASS_THROUGHOut
LEFT JOIN (
SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME FROM (  SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    BATCH_DETAILS.ID as ID,    BATCH_DETAILS.BATCH_ID as BATCH_ID,    BATCH_DETAILS.TARGET_TABLE_NAME as TARGET_TABLE_NAME,    BATCH_DETAILS.FILE_NAME as FILE_NAME,    BATCH_DETAILS.STATUS as STATUS FROM (SELECT    id,    TARGET_TABLE_NAME,    BATCH_ID,    STATUS,    ACTIVE_FLAG,    BATCH_DETAILS_START_TIME,    FILE_NAME,    RANK() OVER(partition by batch_id,TARGET_TABLE_NAME,FILE_NAME order by BATCH_DETAILS_START_TIME DESC) as RANK FROM    BATCH_DETAILS) BATCH_DETAILS WHERE    RANK= 1 AND   STATUS= 'I' AND   ACTIVE_FLAG= 1 )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}' AND dsf_1.FILE_NAME = '{{ var("SOURCE_NAME_OVERRIDE") }}'
LEFT JOIN (
SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    ENTITY_DIM.DIMENSION_KEY as DIMENSION_KEY,    ENTITY_DIM.NAME as NAME,    ENTITY_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(ENTITY_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    ENTITY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.NAME = ENTITY_NAME AND dsf_2.EFFECTIVE_DATE <= REPORT_DATE AND dsf_2.EXPIRATION_DATE >= REPORT_DATE
),

SC_EXP_EPOC_GENERATOROut as (
	
Select 
	LPAD ( GENERATED_SEQ,
	 9,
	 '0' ) as v_SEQ_LPAD_TO_9,
	 DATEDIFF ( SECOND,
	 TO_TIMESTAMP ( '01/01/1970 00:00:00',
	 'DD-MM-YYYY HH24:MI:SS' ),
	 dsCurrentTimestamp ( ) ) as v_EPOC_TIME,
	 v_EPOC_TIME || v_SEQ_LPAD_TO_9 as v_CONCATE_ID,
	 v_CONCATE_ID as ID
From DSR_SC_EXP_EPOC_GENERATOROut as DSR_SC_EXP_EPOC_GENERATOROut),

DSR_EXP_ERROR_LOGICOut as (
	
Select 
	EXP_PASS_THROUGHOut.REPORT_DATE as BUSINESS_DATE,
	 EXP_PASS_THROUGHOut.BATCH_ID as BATCH_ID,
	 EXP_PASS_THROUGHOut.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_PASS_THROUGHOut.BATCH_START_DATE as BATCH_START_DATE,
	 EXP_PASS_THROUGHOut.ENTITY_ID as ENTITY_ID,
	 EXP_PASS_THROUGHOut.CONTRACT_ID as CONTRACT_ID,
	 EXP_PASS_THROUGHOut.CLEARING_ORG as CLEARING_ORG,
	 EXP_PASS_THROUGHOut.PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	 EXP_PASS_THROUGHOut.BASE_PRODUCT as BASE_PRODUCT,
	 EXP_PASS_THROUGHOut.CLEARING_CURRENCY as CLEARING_CURRENCY,
	 EXP_PASS_THROUGHOut.FILE_NAME as FILE_NAME
From EXP_PASS_THROUGHOut as EXP_PASS_THROUGHOut),

EXP_ERROR_LOGICOut as (
	
Select 
	BUSINESS_DATE as BUSINESS_DATE,
	 BATCH_ID as BATCH_ID,
	 BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 BATCH_START_DATE as BATCH_START_DATE,
	 '{{ var("PMWorkflowName", "") }}' as WORKFLOW_NAME,
	 '{{ var("PMMappingName", "") }}' as MAPPING_NAME,
	 '{{ var("TARGET_NAME") }}' as TARGET_NAME,
	 'Y' as NUM_FLAG_Y,
	 ENTITY_ID as ENTITY_ID,
	 ( CASE WHEN v_COUNT_PREV IS NULL OR v_COUNT_PREV = 0 THEN 1 ELSE v_COUNT_PREV + 1 END ) as v_COUNT,
	 v_COUNT as v_COUNT_PREV,
	 CONTRACT_ID as CONTRACT_ID,
	 CLEARING_ORG as CLEARING_ORG,
	 PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	 BASE_PRODUCT as BASE_PRODUCT,
	 CLEARING_CURRENCY as CLEARING_CURRENCY,
	 FILE_NAME as FILE_NAME,
	 'E300_BLANK_FIELD_OR_LKUP_FAIL' as VALIDATION_NAME,
	 'STRING' as DATA_TYPE_STRING,
	 'DATE' as DATA_TYPE_DATE,
	 'NUMBER' as DATA_TYPE_NUMBER,
	 'ENTITY_ID' as ATTRIBUTE_NAME_1,
	 'CONTRACT_ID' as ATTRIBUTE_NAME_2,
	 'CLEARING_ORG' as ATTRIBUTE_NAME_3,
	 'PRODUCT_FAMILY_CODE' as ATTRIBUTE_NAME_4,
	 'BASE_PRODUCT' as ATTRIBUTE_NAME_5,
	 'CLEARING_CURRENCY' as ATTRIBUTE_NAME_6
From DSR_EXP_ERROR_LOGICOut as DSR_EXP_ERROR_LOGICOut),

DSR_EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut as (
	
Select 
	EXP_ERROR_LOGICOut.VALIDATION_NAME as in_VALIDATION_NAME,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_2 as in_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.DATA_TYPE_STRING as in_DATA_TYPE,
	 EXP_ERROR_LOGICOut.CONTRACT_ID as in_ATTRIBUTE_TO_BE_VALIDATED_STR
From EXP_ERROR_LOGICOut as EXP_ERROR_LOGICOut),

DSR_EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORGOut as (
	
Select 
	EXP_ERROR_LOGICOut.VALIDATION_NAME as in_VALIDATION_NAME,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_3 as in_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.DATA_TYPE_STRING as in_DATA_TYPE,
	 EXP_ERROR_LOGICOut.CLEARING_ORG as in_ATTRIBUTE_TO_BE_VALIDATED_STR
From EXP_ERROR_LOGICOut as EXP_ERROR_LOGICOut),

DSR_EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCYOut as (
	
Select 
	EXP_ERROR_LOGICOut.VALIDATION_NAME as in_VALIDATION_NAME,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_6 as in_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.DATA_TYPE_STRING as in_DATA_TYPE,
	 EXP_ERROR_LOGICOut.CLEARING_CURRENCY as in_ATTRIBUTE_TO_BE_VALIDATED_STR
From EXP_ERROR_LOGICOut as EXP_ERROR_LOGICOut),

DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut as (
	
Select 
	EXP_ERROR_LOGICOut.VALIDATION_NAME as in_VALIDATION_NAME,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_1 as in_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.DATA_TYPE_NUMBER as in_DATA_TYPE,
	 EXP_ERROR_LOGICOut.NUM_FLAG_Y as in_DIMENSION_KEY_FLAG,
	 EXP_ERROR_LOGICOut.ENTITY_ID as in_ATTRIBUTE_TO_BE_VALIDATED_NUM
From EXP_ERROR_LOGICOut as EXP_ERROR_LOGICOut),

DSR_EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCTOut as (
	
Select 
	EXP_ERROR_LOGICOut.VALIDATION_NAME as in_VALIDATION_NAME,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_5 as in_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.DATA_TYPE_STRING as in_DATA_TYPE,
	 EXP_ERROR_LOGICOut.BASE_PRODUCT as in_ATTRIBUTE_TO_BE_VALIDATED_STR
From EXP_ERROR_LOGICOut as EXP_ERROR_LOGICOut),

DSR_EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODEOut as (
	
Select 
	EXP_ERROR_LOGICOut.VALIDATION_NAME as in_VALIDATION_NAME,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_4 as in_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.DATA_TYPE_STRING as in_DATA_TYPE,
	 EXP_ERROR_LOGICOut.PRODUCT_FAMILY_CODE as in_ATTRIBUTE_TO_BE_VALIDATED_STR
From EXP_ERROR_LOGICOut as EXP_ERROR_LOGICOut),

EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut as (
	
Select 
	'{{ var("TARGET_NAME") }}' as TARGET_TABLE_NAME,
	 dsf_1.ACTIVE_Y_N_STR_VL as v_VALIDATION_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ACTIVE END ) as v_VALIDATION_ACTIVE_NVL,
	 dsf_2.ACTIVE_Y_N as v_VALIDATION_ON_TABLE_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ON_TABLE_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ON_TABLE_ACTIVE END ) as v_VALIDATION_ON_TABLE_ACTIVE_NVL,
	 ( CASE WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_DATE,
	 ( CASE WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_STR,
	 ( CASE WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL OR ( ( CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END ) = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2 ) THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_NUM,
	 ( CASE WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P' END ) as v_VALIDATION_PASS_FAIL,
	 v_VALIDATION_PASS_FAIL as o_VALIDATION_PASS_FAIL,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE ELSE NULL END ) as v_ERROR_MESSAGE_DATE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR ELSE NULL END ) as v_ERROR_MESSAGE_STR,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM ELSE NULL END ) as v_ERROR_MESSAGE_NUM,
	 v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM as o_COMBINED_ERROR_MESSAGE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as o_ERROR_SEVERITY
From DSR_EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut as DSR_EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut
LEFT JOIN (
SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
LEFT JOIN (
SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORGOut as (
	
Select 
	'{{ var("TARGET_NAME") }}' as TARGET_TABLE_NAME,
	 dsf_1.ACTIVE_Y_N_STR_VL as v_VALIDATION_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ACTIVE END ) as v_VALIDATION_ACTIVE_NVL,
	 dsf_2.ACTIVE_Y_N as v_VALIDATION_ON_TABLE_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ON_TABLE_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ON_TABLE_ACTIVE END ) as v_VALIDATION_ON_TABLE_ACTIVE_NVL,
	 ( CASE WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_DATE,
	 ( CASE WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_STR,
	 ( CASE WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL OR ( ( CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END ) = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2 ) THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_NUM,
	 ( CASE WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P' END ) as v_VALIDATION_PASS_FAIL,
	 v_VALIDATION_PASS_FAIL as o_VALIDATION_PASS_FAIL,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE ELSE NULL END ) as v_ERROR_MESSAGE_DATE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR ELSE NULL END ) as v_ERROR_MESSAGE_STR,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM ELSE NULL END ) as v_ERROR_MESSAGE_NUM,
	 v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM as o_COMBINED_ERROR_MESSAGE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as o_ERROR_SEVERITY
From DSR_EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORGOut as DSR_EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORGOut
LEFT JOIN (
SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
LEFT JOIN (
SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCYOut as (
	
Select 
	'{{ var("TARGET_NAME") }}' as TARGET_TABLE_NAME,
	 dsf_1.ACTIVE_Y_N_STR_VL as v_VALIDATION_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ACTIVE END ) as v_VALIDATION_ACTIVE_NVL,
	 dsf_2.ACTIVE_Y_N as v_VALIDATION_ON_TABLE_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ON_TABLE_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ON_TABLE_ACTIVE END ) as v_VALIDATION_ON_TABLE_ACTIVE_NVL,
	 ( CASE WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_DATE,
	 ( CASE WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_STR,
	 ( CASE WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL OR ( ( CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END ) = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2 ) THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_NUM,
	 ( CASE WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P' END ) as v_VALIDATION_PASS_FAIL,
	 v_VALIDATION_PASS_FAIL as o_VALIDATION_PASS_FAIL,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE ELSE NULL END ) as v_ERROR_MESSAGE_DATE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR ELSE NULL END ) as v_ERROR_MESSAGE_STR,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM ELSE NULL END ) as v_ERROR_MESSAGE_NUM,
	 v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM as o_COMBINED_ERROR_MESSAGE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as o_ERROR_SEVERITY
From DSR_EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCYOut as DSR_EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCYOut
LEFT JOIN (
SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
LEFT JOIN (
SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut as (
	
Select 
	'{{ var("TARGET_NAME") }}' as TARGET_TABLE_NAME,
	 dsf_1.ACTIVE_Y_N_STR_VL as v_VALIDATION_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ACTIVE END ) as v_VALIDATION_ACTIVE_NVL,
	 dsf_2.ACTIVE_Y_N as v_VALIDATION_ON_TABLE_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ON_TABLE_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ON_TABLE_ACTIVE END ) as v_VALIDATION_ON_TABLE_ACTIVE_NVL,
	 ( CASE WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_DATE,
	 ( CASE WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_STR,
	 ( CASE WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL OR ( ( CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END ) = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2 ) THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_NUM,
	 ( CASE WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P' END ) as v_VALIDATION_PASS_FAIL,
	 v_VALIDATION_PASS_FAIL as o_VALIDATION_PASS_FAIL,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE ELSE NULL END ) as v_ERROR_MESSAGE_DATE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR ELSE NULL END ) as v_ERROR_MESSAGE_STR,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM ELSE NULL END ) as v_ERROR_MESSAGE_NUM,
	 v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM as o_COMBINED_ERROR_MESSAGE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as o_ERROR_SEVERITY
From DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut as DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut
LEFT JOIN (
SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
LEFT JOIN (
SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCTOut as (
	
Select 
	'{{ var("TARGET_NAME") }}' as TARGET_TABLE_NAME,
	 dsf_1.ACTIVE_Y_N_STR_VL as v_VALIDATION_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ACTIVE END ) as v_VALIDATION_ACTIVE_NVL,
	 dsf_2.ACTIVE_Y_N as v_VALIDATION_ON_TABLE_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ON_TABLE_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ON_TABLE_ACTIVE END ) as v_VALIDATION_ON_TABLE_ACTIVE_NVL,
	 ( CASE WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_DATE,
	 ( CASE WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_STR,
	 ( CASE WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL OR ( ( CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END ) = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2 ) THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_NUM,
	 ( CASE WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P' END ) as v_VALIDATION_PASS_FAIL,
	 v_VALIDATION_PASS_FAIL as o_VALIDATION_PASS_FAIL,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE ELSE NULL END ) as v_ERROR_MESSAGE_DATE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR ELSE NULL END ) as v_ERROR_MESSAGE_STR,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM ELSE NULL END ) as v_ERROR_MESSAGE_NUM,
	 v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM as o_COMBINED_ERROR_MESSAGE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as o_ERROR_SEVERITY
From DSR_EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCTOut as DSR_EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCTOut
LEFT JOIN (
SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
LEFT JOIN (
SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODEOut as (
	
Select 
	'{{ var("TARGET_NAME") }}' as TARGET_TABLE_NAME,
	 dsf_1.ACTIVE_Y_N_STR_VL as v_VALIDATION_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ACTIVE END ) as v_VALIDATION_ACTIVE_NVL,
	 dsf_2.ACTIVE_Y_N as v_VALIDATION_ON_TABLE_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ON_TABLE_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ON_TABLE_ACTIVE END ) as v_VALIDATION_ON_TABLE_ACTIVE_NVL,
	 ( CASE WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_DATE,
	 ( CASE WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_STR,
	 ( CASE WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL OR ( ( CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END ) = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2 ) THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_NUM,
	 ( CASE WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P' END ) as v_VALIDATION_PASS_FAIL,
	 v_VALIDATION_PASS_FAIL as o_VALIDATION_PASS_FAIL,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE ELSE NULL END ) as v_ERROR_MESSAGE_DATE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR ELSE NULL END ) as v_ERROR_MESSAGE_STR,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM ELSE NULL END ) as v_ERROR_MESSAGE_NUM,
	 v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM as o_COMBINED_ERROR_MESSAGE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as o_ERROR_SEVERITY
From DSR_EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODEOut as DSR_EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODEOut
LEFT JOIN (
SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
LEFT JOIN (
SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master as (
  Select
  	EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_VALIDATION_PASS_FAIL as ENTITY_ID_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_COMBINED_ERROR_MESSAGE as ENTITY_ID_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_ERROR_SEVERITY as ENTITY_ID_ERROR_SEVERITY
  From EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut as EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut
),

EXP_ERROR_LOGIC_details as (
  Select
  	EXP_ERROR_LOGICOut.BUSINESS_DATE as BUSINESS_DATE,
	 EXP_ERROR_LOGICOut.BATCH_ID as BATCH_ID,
	 EXP_ERROR_LOGICOut.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_ERROR_LOGICOut.BATCH_START_DATE as BATCH_START_DATE,
	 EXP_ERROR_LOGICOut.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_ERROR_LOGICOut.MAPPING_NAME as MAPPING_NAME,
	 EXP_ERROR_LOGICOut.TARGET_NAME as TARGET_NAME,
	 EXP_ERROR_LOGICOut.VALIDATION_NAME as VALIDATION_NAME,
	 EXP_ERROR_LOGICOut.CONTRACT_ID as CONTRACT_ID,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_1 as ENTITY_ID_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.ENTITY_ID as ENTITY_ID,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_2 as CONTRACT_ID_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_3 as CLEARING_ORG_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.CLEARING_ORG as CLEARING_ORG,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_4 as PRODUCT_FAMILY_CODE_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_5 as BASE_PRODUCT_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.BASE_PRODUCT as BASE_PRODUCT,
	 EXP_ERROR_LOGICOut.ATTRIBUTE_NAME_6 as CLEARING_CURRENCY_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGICOut.CLEARING_CURRENCY as CLEARING_CURRENCY
  From EXP_ERROR_LOGICOut as EXP_ERROR_LOGICOut
),

EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODE_details as (
  Select
  	EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODEOut.o_VALIDATION_PASS_FAIL as PRODUCT_FAMILY_CODE_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODEOut.o_COMBINED_ERROR_MESSAGE as PRODUCT_FAMILY_CODE_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODEOut.o_ERROR_SEVERITY as PRODUCT_FAMILY_CODE_ERROR_SEVERITY
  From EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODEOut as EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODEOut
),

EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCT_details as (
  Select
  	EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCTOut.o_VALIDATION_PASS_FAIL as BASE_PRODUCT_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCTOut.o_COMBINED_ERROR_MESSAGE as BASE_PRODUCT_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCTOut.o_ERROR_SEVERITY as BASE_PRODUCT_ERROR_SEVERITY
  From EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCTOut as EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCTOut
),

EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details as (
  Select
  	EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut.o_VALIDATION_PASS_FAIL as CONTRACT_ID_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut.o_COMBINED_ERROR_MESSAGE as CONTRACT_ID_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut.o_ERROR_SEVERITY as CONTRACT_ID_ERROR_SEVERITY
  From EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut as EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut
),

EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORG_details as (
  Select
  	EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORGOut.o_VALIDATION_PASS_FAIL as CLEARING_ORG_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORGOut.o_COMBINED_ERROR_MESSAGE as CLEARING_ORG_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORGOut.o_ERROR_SEVERITY as CLEARING_ORG_ERROR_SEVERITY
  From EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORGOut as EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORGOut
),

EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCY_details as (
  Select
  	EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCYOut.o_VALIDATION_PASS_FAIL as CLEARING_CURRENCY_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCYOut.o_COMBINED_ERROR_MESSAGE as CLEARING_CURRENCY_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCYOut.o_ERROR_SEVERITY as CLEARING_CURRENCY_ERROR_SEVERITY
  From EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCYOut as EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCYOut
),
dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out as (
Select 
	EXP_ERROR_LOGIC_details.BUSINESS_DATE as BUSINESS_DATE,
	 EXP_ERROR_LOGIC_details.BATCH_ID as BATCH_ID,
	 EXP_ERROR_LOGIC_details.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_ERROR_LOGIC_details.BATCH_START_DATE as BATCH_START_DATE,
	 EXP_ERROR_LOGIC_details.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_ERROR_LOGIC_details.MAPPING_NAME as MAPPING_NAME,
	 EXP_ERROR_LOGIC_details.TARGET_NAME as TARGET_NAME,
	 EXP_ERROR_LOGIC_details.VALIDATION_NAME as VALIDATION_NAME,
	 EXP_ERROR_LOGIC_details.CONTRACT_ID as CONTRACT_ID,
	 EXP_ERROR_LOGIC_details.ENTITY_ID_ATTRIBUTE_NAME as ENTITY_ID_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGIC_details.ENTITY_ID as ENTITY_ID,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.ENTITY_ID_VALIDATION_PASS_FAIL as ENTITY_ID_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.ENTITY_ID_ERROR_MESSAGE as ENTITY_ID_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.ENTITY_ID_ERROR_SEVERITY as ENTITY_ID_ERROR_SEVERITY,
	 EXP_ERROR_LOGIC_details.CONTRACT_ID_ATTRIBUTE_NAME as CONTRACT_ID_ATTRIBUTE_NAME,
	 EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.CONTRACT_ID_VALIDATION_PASS_FAIL as CONTRACT_ID_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.CONTRACT_ID_ERROR_MESSAGE as CONTRACT_ID_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.CONTRACT_ID_ERROR_SEVERITY as CONTRACT_ID_ERROR_SEVERITY,
	 EXP_ERROR_LOGIC_details.CLEARING_ORG_ATTRIBUTE_NAME as CLEARING_ORG_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGIC_details.CLEARING_ORG as CLEARING_ORG,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORG_details.CLEARING_ORG_VALIDATION_PASS_FAIL as CLEARING_ORG_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORG_details.CLEARING_ORG_ERROR_MESSAGE as CLEARING_ORG_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORG_details.CLEARING_ORG_ERROR_SEVERITY as CLEARING_ORG_ERROR_SEVERITY,
	 EXP_ERROR_LOGIC_details.PRODUCT_FAMILY_CODE_ATTRIBUTE_NAME as PRODUCT_FAMILY_CODE_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGIC_details.PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	 EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODE_details.PRODUCT_FAMILY_CODE_VALIDATION_PASS_FAIL as PRODUCT_FAMILY_CODE_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODE_details.PRODUCT_FAMILY_CODE_ERROR_MESSAGE as PRODUCT_FAMILY_CODE_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODE_details.PRODUCT_FAMILY_CODE_ERROR_SEVERITY as PRODUCT_FAMILY_CODE_ERROR_SEVERITY,
	 EXP_ERROR_LOGIC_details.BASE_PRODUCT_ATTRIBUTE_NAME as BASE_PRODUCT_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGIC_details.BASE_PRODUCT as BASE_PRODUCT,
	 EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCT_details.BASE_PRODUCT_VALIDATION_PASS_FAIL as BASE_PRODUCT_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCT_details.BASE_PRODUCT_ERROR_MESSAGE as BASE_PRODUCT_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCT_details.BASE_PRODUCT_ERROR_SEVERITY as BASE_PRODUCT_ERROR_SEVERITY,
	 EXP_ERROR_LOGIC_details.CLEARING_CURRENCY_ATTRIBUTE_NAME as CLEARING_CURRENCY_ATTRIBUTE_NAME,
	 EXP_ERROR_LOGIC_details.CLEARING_CURRENCY as CLEARING_CURRENCY,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCY_details.CLEARING_CURRENCY_VALIDATION_PASS_FAIL as CLEARING_CURRENCY_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCY_details.CLEARING_CURRENCY_ERROR_MESSAGE as CLEARING_CURRENCY_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCY_details.CLEARING_CURRENCY_ERROR_SEVERITY as CLEARING_CURRENCY_ERROR_SEVERITY,
	 SC_EXP_EPOC_GENERATOROut.ID as ID,
	 EXP_PASS_THROUGHOut.CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 EXP_PASS_THROUGHOut.FINAL_CONTRACTUAL_STLMT_DT as FINAL_CONTRACTUAL_STLMT_DT,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master as EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master INNER JOIN EXP_ERROR_LOGIC_details as EXP_ERROR_LOGIC_details 
ON
EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.jkey = EXP_ERROR_LOGIC_details.jkey
 INNER JOIN EXP_PASS_THROUGHOut as EXP_PASS_THROUGHOut 
ON
EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.jkey = EXP_PASS_THROUGHOut.jkey
 INNER JOIN SC_EXP_EPOC_GENERATOROut as SC_EXP_EPOC_GENERATOROut 
ON
EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.jkey = SC_EXP_EPOC_GENERATOROut.jkey
 INNER JOIN EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODE_details as EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODE_details 
ON
EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.jkey = EXP_LDSA_VALIDATION_CHECKER_PRODUCT_FAMILY_CODE_details.jkey
 INNER JOIN EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCT_details as EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCT_details 
ON
EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.jkey = EXP_LDSA_VALIDATION_CHECKER_BASE_PRODUCT_details.jkey
 INNER JOIN EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details as EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details 
ON
EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.jkey = EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.jkey
 INNER JOIN EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORG_details as EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORG_details 
ON
EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.jkey = EXP_LDSA_VALIDATION_CHECKER_CLEARING_ORG_details.jkey
 INNER JOIN EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCY_details as EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCY_details 
ON
EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.jkey = EXP_LDSA_VALIDATION_CHECKER_CLEARING_CURRENCY_details.jkey
 
),

EXP_CONSOLIDATE_VALIDATIONSOut as (
	
Select 
	BUSINESS_DATE as BUSINESS_DATE,
	 BATCH_ID as BATCH_ID,
	 BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 BATCH_START_DATE as BATCH_START_DATE,
	 WORKFLOW_NAME as WORKFLOW_NAME,
	 MAPPING_NAME as MAPPING_NAME,
	 TARGET_NAME as TARGET_NAME,
	 VALIDATION_NAME as VALIDATION_NAME,
	 '{{ var("FILE_NAME") }}' as FILE_NAME,
	 CONTRACT_ID as CONTRACT_ID,
	 'FILE NAME:' || FILE_NAME || '/' || 'BUSINESS_DATE:' || BUSINESS_DATE || '/' || 'CONTRACT_ID:' || CONTRACT_ID || '/' as v_ERROR_MESSAGE,
	 ENTITY_ID_ATTRIBUTE_NAME as ENTITY_ID_ATTRIBUTE_NAME,
	 ENTITY_ID as ENTITY_ID,
	 ENTITY_ID_VALIDATION_PASS_FAIL as ENTITY_ID_VALIDATION_PASS_FAIL,
	 ENTITY_ID_ERROR_MESSAGE as ENTITY_ID_ERROR_MESSAGE,
	 ENTITY_ID_ERROR_SEVERITY as ENTITY_ID_ERROR_SEVERITY,
	 v_ERROR_MESSAGE || ENTITY_ID_ERROR_MESSAGE as O_ENTITY_ID_ERROR_MESSAGE,
	 CONTRACT_ID_ATTRIBUTE_NAME as CONTRACT_ID_ATTRIBUTE_NAME,
	 CONTRACT_ID_VALIDATION_PASS_FAIL as CONTRACT_ID_VALIDATION_PASS_FAIL,
	 CONTRACT_ID_ERROR_MESSAGE as CONTRACT_ID_ERROR_MESSAGE,
	 CONTRACT_ID_ERROR_SEVERITY as CONTRACT_ID_ERROR_SEVERITY,
	 v_ERROR_MESSAGE || CONTRACT_ID_ERROR_MESSAGE as O_CONTRACT_ID_ERROR_MESSAGE,
	 CLEARING_ORG_ATTRIBUTE_NAME as CLEARING_ORG_ATTRIBUTE_NAME,
	 CLEARING_ORG as CLEARING_ORG,
	 CLEARING_ORG_VALIDATION_PASS_FAIL as CLEARING_ORG_VALIDATION_PASS_FAIL,
	 CLEARING_ORG_ERROR_MESSAGE as CLEARING_ORG_ERROR_MESSAGE,
	 CLEARING_ORG_ERROR_SEVERITY as CLEARING_ORG_ERROR_SEVERITY,
	 v_ERROR_MESSAGE || CLEARING_ORG_ERROR_MESSAGE as O_CLEARING_ORG_ERROR_MESSAGE,
	 PRODUCT_FAMILY_CODE_ATTRIBUTE_NAME as PRODUCT_FAMILY_CODE_ATTRIBUTE_NAME,
	 PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	 PRODUCT_FAMILY_CODE_VALIDATION_PASS_FAIL as PRODUCT_FAMILY_CODE_VALIDATION_PASS_FAIL,
	 PRODUCT_FAMILY_CODE_ERROR_MESSAGE as PRODUCT_FAMILY_CODE_ERROR_MESSAGE,
	 PRODUCT_FAMILY_CODE_ERROR_SEVERITY as PRODUCT_FAMILY_CODE_ERROR_SEVERITY,
	 v_ERROR_MESSAGE || PRODUCT_FAMILY_CODE_ERROR_MESSAGE as O_PRODUCT_FAMILY_CODE_ERROR_MESSAGE,
	 BASE_PRODUCT_ATTRIBUTE_NAME as BASE_PRODUCT_ATTRIBUTE_NAME,
	 BASE_PRODUCT as BASE_PRODUCT,
	 BASE_PRODUCT_VALIDATION_PASS_FAIL as BASE_PRODUCT_VALIDATION_PASS_FAIL,
	 BASE_PRODUCT_ERROR_MESSAGE as BASE_PRODUCT_ERROR_MESSAGE,
	 BASE_PRODUCT_ERROR_SEVERITY as BASE_PRODUCT_ERROR_SEVERITY,
	 v_ERROR_MESSAGE || BASE_PRODUCT_ERROR_MESSAGE as O_BASE_PRODUCT_ERROR_MESSAGE,
	 CLEARING_CURRENCY_ATTRIBUTE_NAME as CLEARING_CURRENCY_ATTRIBUTE_NAME,
	 CLEARING_CURRENCY as CLEARING_CURRENCY,
	 CLEARING_CURRENCY_VALIDATION_PASS_FAIL as CLEARING_CURRENCY_VALIDATION_PASS_FAIL,
	 CLEARING_CURRENCY_ERROR_MESSAGE as CLEARING_CURRENCY_ERROR_MESSAGE,
	 CLEARING_CURRENCY_ERROR_SEVERITY as CLEARING_CURRENCY_ERROR_SEVERITY,
	 v_ERROR_MESSAGE || CLEARING_CURRENCY_ERROR_MESSAGE as O_CLEARING_CURRENCY_ERROR_MESSAGE,
	 ( CASE WHEN ENTITY_ID_VALIDATION_PASS_FAIL = 'F' OR CONTRACT_ID_VALIDATION_PASS_FAIL = 'F' OR CLEARING_ORG_VALIDATION_PASS_FAIL = 'F' OR PRODUCT_FAMILY_CODE_VALIDATION_PASS_FAIL = 'F' OR BASE_PRODUCT_VALIDATION_PASS_FAIL = 'F' OR CLEARING_CURRENCY_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as O_MD_ERROR_IND,
	 ID as ID,
	 CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 ( CASE WHEN REGEXP_INSTR ( CurrentlyProcessedFileName,
	 'DCL' ) > 0 THEN 'DCLSA' ELSE 'MATIF_MONEP' END ) as DATA_SET_NAME,
	 FINAL_CONTRACTUAL_STLMT_DT as FINAL_CONTRACTUAL_STLMT_DT
From dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out as dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out),

EXP_PASS_THROUGH_master as (
  Select
  	EXP_PASS_THROUGHOut.BATCH_ID as BATCH_ID,
	 EXP_PASS_THROUGHOut.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_PASS_THROUGHOut.REPORT_DATE as BUSINESS_DATE,
	 EXP_PASS_THROUGHOut.BATCH_START_DATE as BATCH_START_DATE,
	 EXP_PASS_THROUGHOut.ENTITY_ID as ENTITY_ID,
	 EXP_PASS_THROUGHOut.CONTRACT_ID as CONTRACT_ID,
	 EXP_PASS_THROUGHOut.CLEARING_ORG as CLEARING_ORG,
	 EXP_PASS_THROUGHOut.PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	 EXP_PASS_THROUGHOut.BASE_PRODUCT as BASE_PRODUCT,
	 EXP_PASS_THROUGHOut.UNDERLYING_TYPE as UNDERLYING_TYPE,
	 EXP_PASS_THROUGHOut.MIC as MIC,
	 EXP_PASS_THROUGHOut.CLEARING_CURRENCY as CLEARING_CURRENCY,
	 EXP_PASS_THROUGHOut.PRICE_MULTIPLIER as PRICE_MULTIPLIER,
	 EXP_PASS_THROUGHOut.MATURITY_DATE as MATURITY_DATE,
	 EXP_PASS_THROUGHOut.DELIVERY_TYPE as DELIVERY_TYPE,
	 EXP_PASS_THROUGHOut.UNDERLYING_INTERNAL_CODE as UNDERLYING_INTERNAL_CODE,
	 EXP_PASS_THROUGHOut.UNDERLYING_ISIN_CODE as UNDERLYING_ISIN_CODE,
	 EXP_PASS_THROUGHOut.OPTION_TYPE as OPTION_TYPE,
	 EXP_PASS_THROUGHOut.OPTION_EXERCISE_STYLE as OPTION_EXERCISE_STYLE,
	 EXP_PASS_THROUGHOut.STRIKE_PRICE as STRIKE_PRICE,
	 EXP_PASS_THROUGHOut.REFERENCE_PRICE as REFERENCE_PRICE,
	 EXP_PASS_THROUGHOut.ISIN_CODE as ISIN_CODE,
	 EXP_PASS_THROUGHOut.EXTERNAL_CONTRACT_CODE as EXTERNAL_CONTRACT_CODE,
	 EXP_PASS_THROUGHOut.EXCHANGE_RATE as EXCHANGE_RATE,
	 EXP_PASS_THROUGHOut.UNDERLYING_SUB_TYPE as UNDERLYING_SUB_TYPE,
	 EXP_PASS_THROUGHOut.ASSET_CLASS as ASSET_CLASS,
	 EXP_PASS_THROUGHOut.CRYPTO_ASSET as CRYPTO_ASSET,
	 EXP_PASS_THROUGHOut.UNDERLYING_NAME as UNDERLYING_NAME,
	 EXP_PASS_THROUGHOut.UNDERLYING_IND_TYPE as UNDERLYING_IND_TYPE,
	 EXP_PASS_THROUGHOut.SETTLEMENT_CCY as SETTLEMENT_CCY
  From EXP_PASS_THROUGHOut as EXP_PASS_THROUGHOut
),

EXP_CONSOLIDATE_VALIDATIONS_details as (
  Select
  	EXP_CONSOLIDATE_VALIDATIONSOut.ID as ID,
	 EXP_CONSOLIDATE_VALIDATIONSOut.O_MD_ERROR_IND as MD_ERROR_IND,
	 EXP_CONSOLIDATE_VALIDATIONSOut.DATA_SET_NAME as DATA_SET_NAME,
	 EXP_CONSOLIDATE_VALIDATIONSOut.FINAL_CONTRACTUAL_STLMT_DT as FINAL_CONTRACTUAL_SETTLEMENT_DATE
  From EXP_CONSOLIDATE_VALIDATIONSOut as EXP_CONSOLIDATE_VALIDATIONSOut
),
dsJoiner_SC_LD_SA_CONTRACT0Out as (
Select 
	EXP_CONSOLIDATE_VALIDATIONS_details.ID as ID,
	 EXP_PASS_THROUGH_master.BATCH_ID as BATCH_ID,
	 EXP_PASS_THROUGH_master.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_PASS_THROUGH_master.BUSINESS_DATE as BUSINESS_DATE,
	 EXP_PASS_THROUGH_master.BATCH_START_DATE as BATCH_START_DATE,
	 EXP_PASS_THROUGH_master.ENTITY_ID as ENTITY_ID,
	 EXP_PASS_THROUGH_master.CONTRACT_ID as CONTRACT_ID,
	 EXP_PASS_THROUGH_master.CLEARING_ORG as CLEARING_ORG,
	 EXP_PASS_THROUGH_master.PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	 EXP_PASS_THROUGH_master.BASE_PRODUCT as BASE_PRODUCT,
	 EXP_PASS_THROUGH_master.UNDERLYING_TYPE as UNDERLYING_TYPE,
	 EXP_PASS_THROUGH_master.MIC as MIC,
	 EXP_PASS_THROUGH_master.CLEARING_CURRENCY as CLEARING_CURRENCY,
	 EXP_PASS_THROUGH_master.PRICE_MULTIPLIER as PRICE_MULTIPLIER,
	 EXP_PASS_THROUGH_master.MATURITY_DATE as MATURITY_DATE,
	 EXP_PASS_THROUGH_master.DELIVERY_TYPE as DELIVERY_TYPE,
	 EXP_PASS_THROUGH_master.UNDERLYING_INTERNAL_CODE as UNDERLYING_INTERNAL_CODE,
	 EXP_PASS_THROUGH_master.UNDERLYING_ISIN_CODE as UNDERLYING_ISIN_CODE,
	 EXP_PASS_THROUGH_master.OPTION_TYPE as OPTION_TYPE,
	 EXP_PASS_THROUGH_master.OPTION_EXERCISE_STYLE as OPTION_EXERCISE_STYLE,
	 EXP_PASS_THROUGH_master.STRIKE_PRICE as STRIKE_PRICE,
	 EXP_PASS_THROUGH_master.REFERENCE_PRICE as REFERENCE_PRICE,
	 EXP_PASS_THROUGH_master.ISIN_CODE as ISIN_CODE,
	 EXP_PASS_THROUGH_master.EXTERNAL_CONTRACT_CODE as EXTERNAL_CONTRACT_CODE,
	 EXP_PASS_THROUGH_master.EXCHANGE_RATE as EXCHANGE_RATE,
	 EXP_PASS_THROUGH_master.UNDERLYING_SUB_TYPE as UNDERLYING_SUB_TYPE,
	 EXP_CONSOLIDATE_VALIDATIONS_details.MD_ERROR_IND as MD_ERROR_IND,
	 EXP_CONSOLIDATE_VALIDATIONS_details.DATA_SET_NAME as DATA_SET_NAME,
	 EXP_PASS_THROUGH_master.ASSET_CLASS as ASSET_CLASS,
	 EXP_PASS_THROUGH_master.CRYPTO_ASSET as CRYPTO_ASSET,
	 EXP_PASS_THROUGH_master.UNDERLYING_NAME as UNDERLYING_NAME,
	 EXP_PASS_THROUGH_master.UNDERLYING_IND_TYPE as UNDERLYING_IND_TYPE,
	 EXP_PASS_THROUGH_master.SETTLEMENT_CCY as SETTLEMENT_CCY,
	 EXP_CONSOLIDATE_VALIDATIONS_details.FINAL_CONTRACTUAL_SETTLEMENT_DATE as FINAL_CONTRACTUAL_SETTLEMENT_DATE,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
EXP_PASS_THROUGH_master as EXP_PASS_THROUGH_master inner JOIN EXP_CONSOLIDATE_VALIDATIONS_details as EXP_CONSOLIDATE_VALIDATIONS_details 
ON
EXP_CONSOLIDATE_VALIDATIONS_details.jkey = EXP_PASS_THROUGH_master.jkey 
)

Select 
	ID as ID,
	BATCH_ID as BATCH_ID,
	BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	BUSINESS_DATE as BUSINESS_DATE,
	BATCH_START_DATE as BATCH_START_DATE,
	ENTITY_ID as ENTITY_ID,
	CONTRACT_ID as CONTRACT_ID,
	CLEARING_ORG as CLEARING_ORG,
	PRODUCT_FAMILY_CODE as PRODUCT_FAMILY_CODE,
	BASE_PRODUCT as BASE_PRODUCT,
	UNDERLYING_TYPE as UNDERLYING_TYPE,
	MIC as MIC,
	CLEARING_CURRENCY as CLEARING_CURRENCY,
	PRICE_MULTIPLIER as PRICE_MULTIPLIER,
	MATURITY_DATE as MATURITY_DATE,
	DELIVERY_TYPE as DELIVERY_TYPE,
	UNDERLYING_INTERNAL_CODE as UNDERLYING_INTERNAL_CODE,
	UNDERLYING_ISIN_CODE as UNDERLYING_ISIN_CODE,
	OPTION_TYPE as OPTION_TYPE,
	OPTION_EXERCISE_STYLE as OPTION_EXERCISE_STYLE,
	STRIKE_PRICE as STRIKE_PRICE,
	REFERENCE_PRICE as REFERENCE_PRICE,
	ISIN_CODE as ISIN_CODE,
	EXTERNAL_CONTRACT_CODE as EXTERNAL_CONTRACT_CODE,
	EXCHANGE_RATE as EXCHANGE_RATE,
	UNDERLYING_SUB_TYPE as UNDERLYING_SUB_TYPE,
	MD_ERROR_IND as MD_ERROR_IND,
	DATA_SET_NAME as DATA_SET_NAME,
	ASSET_CLASS as ASSET_CLASS,
	CRYPTO_ASSET as CRYPTO_ASSET,
	UNDERLYING_NAME as UNDERLYING_NAME,
	UNDERLYING_IND_TYPE as UNDERLYING_IND_TYPE,
	SETTLEMENT_CCY as SETTLEMENT_CCY,
	FINAL_CONTRACTUAL_SETTLEMENT_DATE as FINAL_CONTRACTUAL_SETTLEMENT_DATE 
From dsJoiner_SC_LD_SA_CONTRACT0Out as dsJoiner_SC_LD_SA_CONTRACT0Out