/*
Transformation Name ==>SC_PROCESS_ERROR_DETAILS ,Transformation Type ==>Target
*/

{{
    config(
        materialized='incremental',
        alias='PROCESS_ERROR_DETAILS',
        schema='LDSA_SHARED',
        pre_hook="",
        post_hook="",
        incremental_strategy='append'
    )
}}

WITH SQ_SC_LCHSA_ETD_Trade_YYYYmmdd_YYYYmmddHH24missOut AS (
    SELECT
        REPORT_DATE,
        UTI,
        TRADE_LEG_ID,
        TMF_CODE,
        LIFECYCLE,
        CMF_CODE,
        BUY_SELL_IND,
        CONTRACT_ID,
        TRADE_LEG_QTY,
        TRADED_PRICE,
        CLEARING_TIMESTAMP,
        EXTERNAL_TRADE_NUMBER,
        RTN,
        SUBSEQUENT_POSTN_UTI,
        EXECUTION_TIMESTAMP,
        EFFECTIVE_DATE,
        EARLY_TERM_DATE,
        ACTION_TYPE,
        EVENT_TYPE,
        EVENT_DATE,
        CurrentlyProcessedFileName
    FROM {{ source('FlatFile_catalog_1', 'LCHSA_ETD_Trade_YYYYmmdd_YYYYmmddHH24miss') }}
),

EXP_TRIMOut AS (
    SELECT
        (CASE
            WHEN REPORT_DATE IS NOT NULL THEN TO_DATE(LTRIM(RTRIM(REPORT_DATE)), 'DD/MM/YYYY')
            ELSE ABORT('REPORT_DATE is NULL from Source which is a mandatory field, hence aborting the session')
         END) AS O_REPORT_DATE,
        LTRIM(RTRIM(UTI)) AS O_UTI,
        LTRIM(RTRIM(TRADE_LEG_ID)) AS O_TRADE_LEG_ID,
        LTRIM(RTRIM(TMF_CODE)) AS O_TMF_CODE,
        LTRIM(RTRIM(LIFECYCLE)) AS O_LIFECYCLE,
        LTRIM(RTRIM(CMF_CODE)) AS O_CMF_CODE,
        LTRIM(RTRIM(BUY_SELL_IND)) AS O_BUY_SELL_IND,
        LTRIM(RTRIM(CONTRACT_ID)) AS O_CONTRACT_ID,
        LTRIM(RTRIM(TRADE_LEG_QTY)) AS O_TRADE_LEG_QTY,
        LTRIM(RTRIM(TRADED_PRICE)) AS O_TRADED_PRICE,
        LTRIM(RTRIM(CLEARING_TIMESTAMP)) AS V_CLEARING_TIMESTAMP,
        (CASE
            WHEN V_CLEARING_TIMESTAMP IS NOT NULL THEN TO_TIMESTAMP(V_CLEARING_TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS')
            ELSE NULL
         END) AS O_CLEARING_TIMESTAMP,
        LTRIM(RTRIM(EXTERNAL_TRADE_NUMBER)) AS O_EXTERNAL_TRADE_NUMBER,
        'LCH.SA' AS ENTITY_NAME,
        LTRIM(RTRIM(RTN)) AS O_RTN,
        LTRIM(RTRIM(SUBSEQUENT_POSTN_UTI)) AS v_SUBSEQUENT_POSTN_UTI,
        (CASE
            WHEN SUBSTRING(v_SUBSEQUENT_POSTN_UTI, 1, 3) = 'R1I' THEN UPPER(v_SUBSEQUENT_POSTN_UTI)
            ELSE SUBSEQUENT_POSTN_UTI
         END) AS O_SUBSEQUENT_POSTN_UTI1,
        LTRIM(RTRIM(EXECUTION_TIMESTAMP)) AS V_EXECUTION_TIMESTAMP,
        (CASE
            WHEN V_EXECUTION_TIMESTAMP IS NOT NULL THEN TO_TIMESTAMP(V_EXECUTION_TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS')
            ELSE NULL
         END) AS O_EXECUTION_TIMESTAMP,
        EFFECTIVE_DATE,
        (CASE
            WHEN EFFECTIVE_DATE IS NOT NULL THEN TO_DATE(LTRIM(RTRIM(EFFECTIVE_DATE)), 'DD/MM/YYYY')
            ELSE NULL
         END) AS O_EFFECTIVE_DATE,
        EARLY_TERM_DATE,
        (CASE
            WHEN EARLY_TERM_DATE IS NOT NULL THEN TO_DATE(LTRIM(RTRIM(EARLY_TERM_DATE)), 'DD/MM/YYYY')
            ELSE NULL
         END) AS O_EARLY_TERM_DATE,
        ACTION_TYPE,
        LTRIM(RTRIM(ACTION_TYPE)) AS O_ACTION_TYPE,
        EVENT_TYPE,
        LTRIM(RTRIM(EVENT_TYPE)) AS O_EVENT_TYPE,
        EVENT_DATE,
        (CASE
            WHEN EVENT_DATE IS NOT NULL THEN TO_DATE(LTRIM(RTRIM(EVENT_DATE)), 'DD/MM/YYYY')
            ELSE NULL
         END) AS O_EVENT_DATE,
        CurrentlyProcessedFileName
    FROM SQ_SC_LCHSA_ETD_Trade_YYYYmmdd_YYYYmmddHH24missOut
),

Target_Table_Name_SK_Max_Value AS (
    SELECT
        MAX(GENERATED_SEQ) AS max_generated_seq
    FROM {{ this }}
),

DSR_SC_EXP_EPOC_GENERATOROut AS (
    SELECT
        (SELECT max_generated_seq FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER () AS GENERATED_SEQ
    FROM (SELECT 1) AS dummy
),

SC_EXP_EPOC_GENERATOROut AS (
    SELECT
        LPAD(GENERATED_SEQ, 9, '0') AS v_SEQ_LPAD_TO_9,
        DATEDIFF(
            SECOND,
            TO_TIMESTAMP('01/01/1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),
            dsCurrentTimestamp()
        ) AS v_EPOC_TIME,
        v_EPOC_TIME || v_SEQ_LPAD_TO_9 AS v_CONCATE_ID,
        v_CONCATE_ID AS ID
    FROM DSR_SC_EXP_EPOC_GENERATOROut
),

EXP_TRIM_details AS (
    SELECT
        O_REPORT_DATE AS REPORT_DATE,
        O_REPORT_DATE AS BUSINESS_DATE,
        ENTITY_NAME,
        O_UTI AS UTI,
        O_TRADE_LEG_ID AS TRADE_LEG_ID,
        O_TMF_CODE AS TMF_CODE,
        O_LIFECYCLE AS LIFECYCLE,
        O_CMF_CODE AS CMF_CODE,
        O_BUY_SELL_IND AS BUY_SELL_IND,
        O_CONTRACT_ID AS CONTRACT_ID,
        O_TRADE_LEG_QTY AS TRADE_LEG_QTY,
        O_TRADED_PRICE AS TRADED_PRICE,
        O_CLEARING_TIMESTAMP AS CLEARING_TIMESTAMP,
        O_EXTERNAL_TRADE_NUMBER AS EXTERNAL_TRADE_NUMBER,
        O_RTN AS RTN,
        O_SUBSEQUENT_POSTN_UTI1 AS SUBSEQUENT_POSTN_UTI,
        O_EXECUTION_TIMESTAMP AS EXECUTION_TIMESTAMP,
        O_EFFECTIVE_DATE AS EFFECTIVE_DATE,
        O_EARLY_TERM_DATE AS EARLY_TERM_DATE,
        O_ACTION_TYPE AS ACTION_TYPE,
        O_EVENT_TYPE AS EVENT_TYPE,
        O_EVENT_DATE AS EVENT_DATE,
        CurrentlyProcessedFileName
    FROM EXP_TRIMOut
),

dsJoiner_EXP_PASS_THROUGH0Out AS (
    SELECT
        SC_EXP_EPOC_GENERATOROut.ID AS ID,
        EXP_TRIM_details.REPORT_DATE,
        EXP_TRIM_details.BUSINESS_DATE,
        EXP_TRIM_details.ENTITY_NAME,
        EXP_TRIM_details.UTI,
        EXP_TRIM_details.TRADE_LEG_ID,
        EXP_TRIM_details.TMF_CODE,
        EXP_TRIM_details.LIFECYCLE,
        EXP_TRIM_details.CMF_CODE,
        EXP_TRIM_details.BUY_SELL_IND,
        EXP_TRIM_details.CONTRACT_ID,
        EXP_TRIM_details.TRADE_LEG_QTY,
        EXP_TRIM_details.TRADED_PRICE,
        EXP_TRIM_details.CLEARING_TIMESTAMP,
        EXP_TRIM_details.EXTERNAL_TRADE_NUMBER,
        EXP_TRIM_details.RTN,
        EXP_TRIM_details.SUBSEQUENT_POSTN_UTI,
        EXP_TRIM_details.EXECUTION_TIMESTAMP,
        EXP_TRIM_details.EFFECTIVE_DATE,
        EXP_TRIM_details.EARLY_TERM_DATE,
        EXP_TRIM_details.ACTION_TYPE,
        EXP_TRIM_details.EVENT_TYPE,
        EXP_TRIM_details.EVENT_DATE,
        EXP_TRIM_details.CurrentlyProcessedFileName,
        ROW_NUMBER() OVER (ORDER BY 1) AS jkey
    FROM SC_EXP_EPOC_GENERATOROut
    INNER JOIN EXP_TRIM_details
        ON ROW_NUMBER() OVER (ORDER BY 1) = ROW_NUMBER() OVER (ORDER BY 1)
),

EXP_PASS_THROUGHOut AS (
    SELECT
        ID,
        '{{ var("BATCH_ID") }}' AS BATCH_ID,
        dsf_1.ID AS BATCH_DETAILS_ID,
        REPORT_DATE,
        BUSINESS_DATE,
        TO_TIMESTAMP('{{ var("BATCH_START_DATE") }}', 'DD-MON-YYYY HH24:MI:SS') AS BATCH_START_DATE,
        ENTITY_NAME,
        dsf_2.DIMENSION_KEY AS ENTITY_ID,
        UTI,
        TRADE_LEG_ID,
        TMF_CODE,
        LIFECYCLE,
        CMF_CODE,
        BUY_SELL_IND,
        CONTRACT_ID,
        TRADE_LEG_QTY,
        TRADED_PRICE,
        CLEARING_TIMESTAMP,
        EXTERNAL_TRADE_NUMBER,
        RTN,
        SUBSEQUENT_POSTN_UTI,
        EXECUTION_TIMESTAMP,
        EFFECTIVE_DATE,
        EARLY_TERM_DATE,
        ACTION_TYPE,
        EVENT_TYPE,
        (CASE WHEN EVENT_TYPE IS NULL THEN 'N/A' ELSE EVENT_TYPE END) AS v_EVENT_TYPE,
        dsf_3.VARIABLE_NAME AS v_LKP_EVENT_TYPE_VAL,
        (CASE WHEN v_LKP_EVENT_TYPE_VAL IS NULL THEN NULL ELSE 'PASS' END) AS O_EVENT_TYPE_VAL,
        EVENT_DATE,
        CurrentlyProcessedFileName,
        'STRING' AS DATA_TYPE_STRING,
        'DATE' AS DATA_TYPE_DATE,
        'NUMBER' AS DATA_TYPE_NUMBER,
        'N' AS NUM_FLAG_N,
        'Y' AS NUM_FLAG_Y,
        'E300_BLANK_FIELD_OR_LKUP_FAIL' AS VALIDATION_NAME,
        'ENTITY_ID' AS ATTRIBUTE_NAME_1,
        'UTI' AS ATTRIBUTE_NAME_2,
        'TRADE_LEG_ID' AS ATTRIBUTE_NAME_3,
        'TMF_CODE' AS ATTRIBUTE_NAME_4,
        'LIFECYCLE' AS ATTRIBUTE_NAME_5,
        'CMF_CODE' AS ATTRIBUTE_NAME_6,
        'BUY_SELL_IND' AS ATTRIBUTE_NAME_7,
        'CONTRACT_ID' AS ATTRIBUTE_NAME_8,
        'ACTION_TYPE' AS ATTRIBUTE_NAME_9,
        'EVENT_TYPE' AS ATTRIBUTE_NAME_10,
        v_TOT_REC_COUNT + 1 AS v_TOT_REC_COUNT
    FROM dsJoiner_EXP_PASS_THROUGH0Out
    LEFT JOIN (
        SELECT
            ID,
            BATCH_ID,
            TARGET_TABLE_NAME,
            FILE_NAME
        FROM (
            SELECT
                ID,
                BATCH_ID,
                TARGET_TABLE_NAME,
                FILE_NAME,
                ROW_NUMBER() OVER (
                    PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME
                    ORDER BY rnk_fst DESC NULLS LAST
                ) AS rnk_lst
            FROM (
                SELECT
                    ID,
                    BATCH_ID,
                    TARGET_TABLE_NAME,
                    FILE_NAME,
                    ROW_NUMBER() OVER (
                        PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME
                        ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST
                    ) AS rnk_fst
                FROM (
                    SELECT
                        BATCH_DETAILS.ID AS ID,
                        BATCH_DETAILS.BATCH_ID AS BATCH_ID,
                        BATCH_DETAILS.TARGET_TABLE_NAME AS TARGET_TABLE_NAME,
                        BATCH_DETAILS.FILE_NAME AS FILE_NAME,
                        BATCH_DETAILS.STATUS AS STATUS
                    FROM (
                        SELECT
                            id,
                            TARGET_TABLE_NAME,
                            BATCH_ID,
                            STATUS,
                            ACTIVE_FLAG,
                            BATCH_DETAILS_START_TIME,
                            FILE_NAME,
                            RANK() OVER (
                                PARTITION BY batch_id, TARGET_TABLE_NAME, FILE_NAME
                                ORDER BY BATCH_DETAILS_START_TIME DESC
                            ) AS RANK
                        FROM BATCH_DETAILS
                    ) BATCH_DETAILS
                    WHERE RANK = 1
                      AND STATUS = 'I'
                      AND ACTIVE_FLAG = 1
                )
            )
        ) lkp_inner
    ) dsf_1
        ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}'
       AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}'
       AND dsf_1.FILE_NAME = '{{ var("FILE_NAME_OVERRIDE") }}'
    LEFT JOIN (
        SELECT
            DIMENSION_KEY,
            NAME,
            EFFECTIVE_DATE,
            EXPIRATION_DATE
        FROM (
            SELECT
                DIMENSION_KEY,
                NAME,
                EFFECTIVE_DATE,
                EXPIRATION_DATE,
                ROW_NUMBER() OVER (
                    PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE
                    ORDER BY rnk_fst DESC NULLS LAST
                ) AS rnk_lst
            FROM (
                SELECT
                    DIMENSION_KEY,
                    NAME,
                    EFFECTIVE_DATE,
                    EXPIRATION_DATE,
                    ROW_NUMBER() OVER (
                        PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE
                        ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST
                    ) AS rnk_fst
                FROM (
                    SELECT
                        ENTITY_DIM.DIMENSION_KEY,
                        ENTITY_DIM.NAME,
                        ENTITY_DIM.EFFECTIVE_DATE,
                        NVL(ENTITY_DIM.EXPIRATION_DATE, TO_DATE('31-DEC-2099', 'DD-MON-YYYY')) AS EXPIRATION_DATE
                    FROM ENTITY_DIM
                )
            )
        )
    ) dsf_2
        ON dsf_2.NAME = ENTITY_NAME
       AND dsf_2.EFFECTIVE_DATE <= REPORT_DATE
       AND dsf_2.EXPIRATION_DATE >= REPORT_DATE
    LEFT JOIN (
        SELECT
            VARIABLE_NAME,
            STRING_VALUE,
            STRING_VALUE2
        FROM (
            SELECT
                VARIABLE_NAME,
                STRING_VALUE,
                STRING_VALUE2,
                ROW_NUMBER() OVER (
                    PARTITION BY STRING_VALUE, STRING_VALUE2
                    ORDER BY rnk_fst DESC NULLS LAST
                ) AS rnk_lst
            FROM (
                SELECT
                    VARIABLE_NAME,
                    STRING_VALUE,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (
                        PARTITION BY STRING_VALUE, STRING_VALUE2
                        ORDER BY STRING_VALUE, STRING_VALUE2 NULLS LAST
                    ) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.VARIABLE_NAME,
                        APPLICATION_VARIABLES.STRING_VALUE,
                        APPLICATION_VARIABLES.STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'LDSA_TRADE_ACTION_TYPE_TO_EVENT_TYPE_MAPPING'
                      AND ACTIVE_Y_N = 'Y'
                )
            )
        )
    ) dsf_3
        ON dsf_3.STRING_VALUE = ACTION_TYPE
       AND dsf_3.STRING_VALUE2 = v_EVENT_TYPE
),

DSR_EXP_LDSA_VALIDATION_CHECKER_EVENTTYPEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_10 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.O_EVENT_TYPE_VAL AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_8 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_NUMBER AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.CONTRACT_ID AS in_ATTRIBUTE_TO_BE_VALIDATED_NUM
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_9 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.ACTION_TYPE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_1 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_NUMBER AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.NUM_FLAG_Y AS in_DIMENSION_KEY_FLAG,
        EXP_PASS_THROUGHOut.ENTITY_ID AS in_ATTRIBUTE_TO_BE_VALIDATED_NUM
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_UTIOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_2 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.UTI AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_IDOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_3 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_NUMBER AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.TRADE_LEG_ID AS in_ATTRIBUTE_TO_BE_VALIDATED_NUM
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_INDOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_7 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.BUY_SELL_IND AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_LIFECYCLEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_5 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.LIFECYCLE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_CMF_CODEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_6 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.CMF_CODE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_4 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.TMF_CODE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

EXP_LDSA_VALIDATION_CHECKER_EVENTTYPEOut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        COALESCE(dsf_1.ACTIVE_Y_N_STR_VL, 'N') AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        COALESCE(dsf_2.ACTIVE_Y_N, 'N') AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE
                        WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                             OR (COALESCE(in_DIMENSION_KEY_FLAG, 'N') = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2)
                        THEN 'F' ELSE 'P'
                     END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F'
                THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_EVENTTYPEOut
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N_STR_VL,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N_STR_VL,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N_STR_VL,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.ACTIVE_Y_N AS ACTIVE_Y_N_STR_VL,
                        APPLICATION_VARIABLES.STRING_VALUE AS STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER'
                      AND ACTIVE_Y_N = 'Y'
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N,
            VARIABLE_NAME,
            STRING_VALUE,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N,
                VARIABLE_NAME,
                STRING_VALUE,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N,
                    VARIABLE_NAME,
                    STRING_VALUE,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
       AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
       AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

-- Similar validation CTEs for CONTRACT_ID, ACTIONTYPE, ENTITY_ID, UTI, TRADE_LEG_ID,
-- BUY_SELL_IND, LIFECYCLE, CMF_CODE, TMF_CODE are omitted for brevity but follow the same pattern as above.

EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_VALIDATION_PASS_FAIL AS ENTITY_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_COMBINED_ERROR_MESSAGE AS ENTITY_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_ERROR_SEVERITY AS ENTITY_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut
),

EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_CMF_CODEOut.o_VALIDATION_PASS_FAIL AS CMF_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_CMF_CODEOut.o_COMBINED_ERROR_MESSAGE AS CMF_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_CMF_CODEOut.o_ERROR_SEVERITY AS CMF_CODE_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_CMF_CODEOut
),

EXP_LDSA_VALIDATION_CHECKER_UTI_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_UTIOut.o_VALIDATION_PASS_FAIL AS UTI_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_UTIOut.o_COMBINED_ERROR_MESSAGE AS UTI_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_UTIOut.o_ERROR_SEVERITY AS UTI_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_UTIOut
),

EXP_LDSA_VALIDATION_CHECKER_EVENTTYPE_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_EVENTTYPEOut.o_VALIDATION_PASS_FAIL AS EVENTTYPE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_EVENTTYPEOut.o_COMBINED_ERROR_MESSAGE AS EVENTTYPE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_EVENTTYPEOut.o_ERROR_SEVERITY AS EVENTTYPE_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_EVENTTYPEOut
),

EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_ID_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_IDOut.o_VALIDATION_PASS_FAIL AS TRADE_LEG_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_IDOut.o_COMBINED_ERROR_MESSAGE AS TRADE_LEG_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_IDOut.o_ERROR_SEVERITY AS TRADE_LEG_ID_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_IDOut
),

EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_IND_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_INDOut.o_VALIDATION_PASS_FAIL AS BUY_SELL_IND_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_INDOut.o_COMBINED_ERROR_MESSAGE AS BUY_SELL_IND_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_INDOut.o_ERROR_SEVERITY AS BUY_SELL_IND_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_INDOut
),

EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut.o_VALIDATION_PASS_FAIL AS TMF_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut.o_COMBINED_ERROR_MESSAGE AS TMF_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut.o_ERROR_SEVERITY AS TMF_CODE_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut
),

EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut.o_VALIDATION_PASS_FAIL AS CONTRACT_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut.o_COMBINED_ERROR_MESSAGE AS CONTRACT_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut.o_ERROR_SEVERITY AS CONTRACT_ID_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut
),

EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_LIFECYCLEOut.o_VALIDATION_PASS_FAIL AS LIFECYCLE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_LIFECYCLEOut.o_COMBINED_ERROR_MESSAGE AS LIFECYCLE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_LIFECYCLEOut.o_ERROR_SEVERITY AS LIFECYCLE_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_LIFECYCLEOut
),

EXP_PASS_THROUGH_details AS (
    SELECT
        EXP_PASS_THROUGHOut.ID,
        EXP_PASS_THROUGHOut.BATCH_ID,
        EXP_PASS_THROUGHOut.BATCH_DETAILS_ID,
        EXP_PASS_THROUGHOut.BUSINESS_DATE,
        EXP_PASS_THROUGHOut.BATCH_START_DATE,
        EXP_PASS_THROUGHOut.VALIDATION_NAME,
        EXP_PASS_THROUGHOut.UTI,
        EXP_PASS_THROUGHOut.TMF_CODE,
        EXP_PASS_THROUGHOut.LIFECYCLE,
        EXP_PASS_THROUGHOut.CMF_CODE,
        EXP_PASS_THROUGHOut.BUY_SELL_IND AS BUY_SELL_INDICATOR,
        EXP_PASS_THROUGHOut.CONTRACT_ID,
        EXP_PASS_THROUGHOut.CLEARING_TIMESTAMP,
        EXP_PASS_THROUGHOut.ENTITY_NAME,
        EXP_PASS_THROUGHOut.CurrentlyProcessedFileName,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_1 AS ENTITY_ID_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_4 AS TMF_CODE_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_6 AS CMF_CODE_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_8 AS CONTRACT_ID_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_2 AS UTI_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_3 AS TRADE_LEG_ID_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_5 AS LIFECYCLE_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_7 AS BUY_SELL_IND_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_9 AS ACTIONTYPE_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_10 AS EVENTTYPE_ATTRIBUTE_NAME
    FROM EXP_PASS_THROUGHOut
),

dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out AS (
    SELECT
        EXP_PASS_THROUGH_details.ID,
        EXP_PASS_THROUGH_details.BATCH_ID,
        EXP_PASS_THROUGH_details.BATCH_DETAILS_ID,
        EXP_PASS_THROUGH_details.BUSINESS_DATE,
        EXP_PASS_THROUGH_details.BATCH_START_DATE,
        EXP_PASS_THROUGH_details.VALIDATION_NAME,
        EXP_PASS_THROUGH_details.UTI,
        EXP_PASS_THROUGH_details.TMF_CODE,
        EXP_PASS_THROUGH_details.LIFECYCLE,
        EXP_PASS_THROUGH_details.CMF_CODE,
        EXP_PASS_THROUGH_details.BUY_SELL_INDICATOR,
        EXP_PASS_THROUGH_details.CONTRACT_ID,
        EXP_PASS_THROUGH_details.CLEARING_TIMESTAMP,
        EXP_PASS_THROUGH_details.ENTITY_NAME,
        EXP_PASS_THROUGH_details.CurrentlyProcessedFileName,
        EXP_PASS_THROUGH_details.ENTITY_ID_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.ENTITY_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.ENTITY_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.ENTITY_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.TMF_CODE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.TMF_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.TMF_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.TMF_CODE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.CMF_CODE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details.CMF_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details.CMF_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details.CMF_CODE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.CONTRACT_ID_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.CONTRACT_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.CONTRACT_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.CONTRACT_ID_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.UTI_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_UTI_details.UTI_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_UTI_details.UTI_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_UTI_details.UTI_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.TRADE_LEG_ID_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_ID_details.TRADE_LEG_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_ID_details.TRADE_LEG_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_ID_details.TRADE_LEG_ID_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.LIFECYCLE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details.LIFECYCLE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details.LIFECYCLE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details.LIFECYCLE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.BUY_SELL_IND_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_IND_details.BUY_SELL_IND_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_IND_details.BUY_SELL_IND_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_IND_details.BUY_SELL_IND_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.ACTIONTYPE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPE_details.ACTIONTYPE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPE_details.ACTIONTYPE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPE_details.ACTIONTYPE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.EVENTTYPE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_EVENTTYPE_details.EVENTTYPE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_EVENTTYPE_details.EVENTTYPE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_EVENTTYPE_details.EVENTTYPE_ERROR_SEVERITY,
        ROW_NUMBER() OVER (ORDER BY 1) AS jkey
    FROM EXP_PASS_THROUGH_details
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_master.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_UTI_details
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_UTI_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_EVENTTYPE_details
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_EVENTTYPE_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_ID_details
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_TRADE_LEG_ID_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_IND_details
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_BUY_SELL_IND_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPE_details
        ON EXP_PASS_THROUGH_details.jkey = EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPE_details.jkey
),

EXP_CONSOLIDATE_VALIDATIONSOut AS (
    SELECT
        ID,
        BATCH_ID,
        BATCH_DETAILS_ID,
        BUSINESS_DATE,
        BATCH_START_DATE,
        '{{ var("PMWorkflowName", "") }}' AS WORKFLOW_NAME,
        '{{ var("PMMappingName", "") }}' AS MAPPING_NAME,
        '{{ var("TARGET_NAME") }}' AS TARGET_NAME,
        VALIDATION_NAME,
        '{{ var("FILE_NAME") }}' AS FILE_NAME,
        'FILE NAME:' || FILE_NAME || '/' || 'BUSINESS_DATE:' || BUSINESS_DATE || '/' || 'UTI:' || UTI || '/' AS v_ERROR_MESSAGE,
        UTI,
        TRADE_LEG_ID,
        TMF_CODE,
        LIFECYCLE,
        CMF_CODE,
        BUY_SELL_INDICATOR,
        CONTRACT_ID,
        TRADE_LEG_QTY,
        TRADED_PRICE,
        CLEARING_TIMESTAMP,
        EXTERNAL_TRADE_NUMBER,
        ENTITY_NAME,
        CurrentlyProcessedFileName,
        ENTITY_ID_ATTRIBUTE_NAME,
        ENTITY_ID_VALIDATION_PASS_FAIL,
        ENTITY_ERROR_SEVERITY,
        v_ERROR_MESSAGE || ENTITY_ID_ERROR_MESSAGE AS O_ENTITY_ERROR_MESSAGE,
        TMF_CODE_ATTRIBUTE_NAME,
        TMF_CODE_VALIDATION_PASS_FAIL,
        TMF_CODE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || TMF_CODE_ERROR_MESSAGE AS O_TMF_CODE_ERROR_MESSAGE,
        CMF_CODE_ATTRIBUTE_NAME,
        CMF_CODE_VALIDATION_PASS_FAIL,
        CMF_CODE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || CMF_CODE_ERROR_MESSAGE AS O_CMF_CODE_ERROR_MESSAGE,
        CONTRACT_ID_ATTRIBUTE_NAME,
        CONTRACT_ID_VALIDATION_PASS_FAIL,
        CONTRACT_ID_ERROR_SEVERITY,
        v_ERROR_MESSAGE || CONTRACT_ID_ERROR_MESSAGE AS O_CONTRACT_ID_ERROR_MESSAGE,
        UTI_ATTRIBUTE_NAME,
        UTI_VALIDATION_PASS_FAIL,
        UTI_ERROR_SEVERITY,
        v_ERROR_MESSAGE || UTI_ERROR_MESSAGE AS O_UTI_ERROR_MESSAGE,
        TRADE_LEG_ID_ATTRIBUTE_NAME,
        TRADE_LEG_ID_VALIDATION_PASS_FAIL,
        TRADE_LEG_ID_ERROR_SEVERITY,
        v_ERROR_MESSAGE || TRADE_LEG_ID_ERROR_MESSAGE AS O_TRADE_LEG_ID_ERROR_MESSAGE,
        LIFECYCLE_ATTRIBUTE_NAME,
        LIFECYCLE_VALIDATION_PASS_FAIL,
        LIFECYCLE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || LIFECYCLE_ERROR_MESSAGE AS O_LIFECYCLE_ERROR_MESSAGE,
        BUY_SELL_IND_ATTRIBUTE_NAME,
        BUY_SELL_IND_VALIDATION_PASS_FAIL,
        BUY_SELL_IND_ERROR_SEVERITY,
        v_ERROR_MESSAGE || BUY_SELL_IND_ERROR_MESSAGE AS O_BUY_SELL_IND_ERROR_MESSAGE,
        ACTIONTYPE_ATTRIBUTE_NAME,
        ACTIONTYPE_VALIDATION_PASS_FAIL,
        ACTIONTYPE_ERROR_MESSAGE,
        ACTIONTYPE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || ACTIONTYPE_ERROR_MESSAGE AS O_ACTIONTYPE_ERROR_MESSAGE,
        EVENTTYPE_ATTRIBUTE_NAME,
        EVENTTYPE_VALIDATION_PASS_FAIL,
        EVENTTYPE_ERROR_MESSAGE,
        EVENTTYPE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || EVENTTYPE_ERROR_MESSAGE AS O_EVENTTYPE_ERROR_MESSAGE,
        CASE
            WHEN ENTITY_ID_VALIDATION_PASS_FAIL = 'F'
                 OR UTI_VALIDATION_PASS_FAIL = 'F'
                 OR TRADE_LEG_ID_VALIDATION_PASS_FAIL = 'F'
                 OR TMF_CODE_VALIDATION_PASS_FAIL = 'F'
                 OR LIFECYCLE_VALIDATION_PASS_FAIL = 'F'
                 OR CMF_CODE_VALIDATION_PASS_FAIL = 'F'
                 OR BUY_SELL_IND_VALIDATION_PASS_FAIL = 'F'
                 OR CONTRACT_ID_VALIDATION_PASS_FAIL = 'F'
                 OR ACTIONTYPE_VALIDATION_PASS_FAIL = 'F'
                 OR EVENTTYPE_VALIDATION_PASS_FAIL = 'F'
            THEN 1 ELSE 0
        END AS MD_ERROR_IND,
        CASE
            WHEN REGEXP_INSTR(CurrentlyProcessedFileName, 'DCL') > 0 THEN 'DCLSA'
            ELSE 'MATIF_MONEP'
        END AS DATA_SET_NAME
    FROM dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out
),

DSR_FIL_ERROR_LOGICOut AS (
    SELECT
        EXP_CONSOLIDATE_VALIDATIONSOut.TRADE_LEG_ID_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_TRADE_LEG_ID_ERROR_MESSAGE AS TRADE_LEG_ID_ERROR_MESSSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.UTI_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.LIFECYCLE_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.UTI_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_UTI_ERROR_MESSAGE AS UTI_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.LIFECYCLE_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_LIFECYCLE_ERROR_MESSAGE AS LIFECYCLE_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.ACTIONTYPE_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.ACTIONTYPE_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_ACTIONTYPE_ERROR_MESSAGE AS ACTIONTYPE_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.EVENTTYPE_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.EVENTTYPE_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_EVENTTYPE_ERROR_MESSAGE AS EVENTTYPE_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.BUY_SELL_IND_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.BUY_SELL_IND_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_BUY_SELL_IND_ERROR_MESSAGE AS BUY_SELL_IND_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.VALIDATION_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.TMF_CODE_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.TMF_CODE_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_TMF_CODE_ERROR_MESSAGE AS TMF_CODE_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.CMF_CODE_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.CMF_CODE_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_CMF_CODE_ERROR_MESSAGE AS CMF_CODE_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.MD_ERROR_IND,
        EXP_CONSOLIDATE_VALIDATIONSOut.ID,
        EXP_CONSOLIDATE_VALIDATIONSOut.BATCH_ID,
        EXP_CONSOLIDATE_VALIDATIONSOut.BATCH_DETAILS_ID,
        EXP_CONSOLIDATE_VALIDATIONSOut.BUSINESS_DATE,
        EXP_CONSOLIDATE_VALIDATIONSOut.BATCH_START_DATE,
        EXP_CONSOLIDATE_VALIDATIONSOut.WORKFLOW_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.MAPPING_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.TARGET_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.CurrentlyProcessedFileName,
        EXP_CONSOLIDATE_VALIDATIONSOut.ENTITY_ID_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.ENTITY_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_ENTITY_ERROR_MESSAGE AS ENTITY_ID_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.CONTRACT_ID_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.CONTRACT_ID_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_CONTRACT_ID_ERROR_MESSAGE AS CONTRACT_ID_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.TRADE_LEG_ID_ATTRIBUTE_NAME
    FROM EXP_CONSOLIDATE_VALIDATIONSOut
),

DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut AS (
    SELECT
        FIL_ERROR_LOGICOut.ENTITY_ID_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_1,
        FIL_ERROR_LOGICOut.ENTITY_ID_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_1,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_1,
        FIL_ERROR_LOGICOut.ENTITY_ID_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_1,
        FIL_ERROR_LOGICOut.UTI_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_2,
        FIL_ERROR_LOGICOut.UTI_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_2,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_2,
        FIL_ERROR_LOGICOut.UTI_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_2,
        FIL_ERROR_LOGICOut.TRADE_LEG_ID_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_3,
        FIL_ERROR_LOGICOut.TRADE_LEG_ID_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_3,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_3,
        FIL_ERROR_LOGICOut.TMF_CODE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_4,
        FIL_ERROR_LOGICOut.TMF_CODE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_4,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_4,
        FIL_ERROR_LOGICOut.TRADE_LEG_ID_ERROR_MESSSAGE AS INPUT_ATTRIBUTE_VALUE_3,
        FIL_ERROR_LOGICOut.TMF_CODE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_4,
        FIL_ERROR_LOGICOut.LIFECYCLE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_5,
        FIL_ERROR_LOGICOut.LIFECYCLE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_5,
        FIL_ERROR_LOGICOut.LIFECYCLE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_5,
        FIL_ERROR_LOGICOut.BATCH_DETAILS_ID AS INPUT_BATCH_DETAILS_ID,
        FIL_ERROR_LOGICOut.BATCH_START_DATE AS INPUT_BATCH_START_DATE,
        FIL_ERROR_LOGICOut.ACTIONTYPE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_9,
        FIL_ERROR_LOGICOut.ACTIONTYPE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_9,
        FIL_ERROR_LOGICOut.ACTIONTYPE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_9,
        FIL_ERROR_LOGICOut.EVENTTYPE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_10,
        FIL_ERROR_LOGICOut.EVENTTYPE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_10,
        FIL_ERROR_LOGICOut.EVENTTYPE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_10,
        FIL_ERROR_LOGICOut.BUY_SELL_IND_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_7,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_5,
        FIL_ERROR_LOGICOut.CMF_CODE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_6,
        FIL_ERROR_LOGICOut.CMF_CODE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_6,
        FIL_ERROR_LOGICOut.CMF_CODE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_6,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_6,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_7,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_8,
        FIL_ERROR_LOGICOut.BUY_SELL_IND_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_7,
        FIL_ERROR_LOGICOut.BUY_SELL_IND_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_7,
        FIL_ERROR_LOGICOut.CONTRACT_ID_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_8,
        FIL_ERROR_LOGICOut.CONTRACT_ID_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_8,
        FIL_ERROR_LOGICOut.CONTRACT_ID_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_8,
        FIL_ERROR_LOGICOut.ID AS INPUT_REFERENCE_RECORD_ID,
        FIL_ERROR_LOGICOut.CurrentlyProcessedFileName AS INPUT_FILE_NAME,
        FIL_ERROR_LOGICOut.BUSINESS_DATE AS INPUT_BATCH_BUSINESS_DATE,
        FIL_ERROR_LOGICOut.BATCH_ID AS INPUT_BATCH_ID,
        FIL_ERROR_LOGICOut.WORKFLOW_NAME AS INPUT_WORKFLOW_NAME,
        FIL_ERROR_LOGICOut.MAPPING_NAME AS INPUT_MAPPING_NAME,
        FIL_ERROR_LOGICOut.TARGET_NAME AS INPUT_TARGET_NAME
    FROM DSR_FIL_ERROR_LOGICOut
    WHERE MD_ERROR_IND = 1
),

SC_mplt_DV_PROCESS_ERROR_DETAILSOut AS (
    SELECT
        ID,
        PROCESS_DATE,
        REFERENCE_BATCH_ID,
        REFERENCE_PROCESS,
        REFERENCE_SUB_PROCESS,
        REFERENCE_TARGET_NAME,
        REFERENCE_RECORD_ID,
        REFERENCE_BUSINESS_KEY,
        REFERENCE_ATTRIBUTE_NAME,
        REFERENCE_ATTRIBUTE_VALUE,
        ERROR_CODE,
        ERROR_SEVERITY,
        ADDITIONAL_DETAILS,
        REFERENCE_BATCH_DETAILS_ID,
        BATCH_START_DATE AS CREATED_TS,
        ENTITY_ID_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_1,
        ENTITY_ID_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_1,
        VALIDATION_NAME AS INPUT_ERROR_CODE_1,
        ENTITY_ID_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_1,
        UTI_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_2,
        UTI_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_2,
        VALIDATION_NAME AS INPUT_ERROR_CODE_2,
        UTI_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_2,
        TRADE_LEG_ID_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_3,
        TRADE_LEG_ID_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_3,
        VALIDATION_NAME AS INPUT_ERROR_CODE_3,
        TMF_CODE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_4,
        TMF_CODE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_4,
        VALIDATION_NAME AS INPUT_ERROR_CODE_4,
        TRADE_LEG_ID_ERROR_MESSSAGE AS INPUT_ATTRIBUTE_VALUE_3,
        TMF_CODE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_4,
        LIFECYCLE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_5,
        LIFECYCLE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_5,
        LIFECYCLE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_5,
        BATCH_DETAILS_ID AS INPUT_BATCH_DETAILS_ID,
        BATCH_START_DATE AS INPUT_BATCH_START_DATE,
        ACTIONTYPE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_9,
        ACTIONTYPE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_9,
        ACTIONTYPE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_9,
        EVENTTYPE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_10,
        EVENTTYPE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_10,
        EVENTTYPE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_10,
        BUY_SELL_IND_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_7,
        VALIDATION_NAME AS INPUT_ERROR_CODE_5,
        CMF_CODE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_6,
        CMF_CODE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_6,
        CMF_CODE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_6,
        VALIDATION_NAME AS INPUT_ERROR_CODE_6,
        VALIDATION_NAME AS INPUT_ERROR_CODE_7,
        VALIDATION_NAME AS INPUT_ERROR_CODE_8,
        BUY_SELL_IND_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_7,
        BUY_SELL_IND_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_7,
        CONTRACT_ID_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_8,
        CONTRACT_ID_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_8,
        CONTRACT_ID_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_8,
        ID AS INPUT_REFERENCE_RECORD_ID,
        CurrentlyProcessedFileName AS INPUT_FILE_NAME,
        BUSINESS_DATE AS INPUT_BATCH_BUSINESS_DATE,
        BATCH_ID AS INPUT_BATCH_ID,
        WORKFLOW_NAME AS INPUT_WORKFLOW_NAME,
        MAPPING_NAME AS INPUT_MAPPING_NAME,
        TARGET_NAME AS INPUT_TARGET_NAME
    FROM DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut
),

DSR_SC_PROCESS_ERROR_DETAILSOut AS (
    SELECT
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.PROCESS_DATE,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_BATCH_ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_PROCESS,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_SUB_PROCESS,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_TARGET_NAME,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_RECORD_ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_BUSINESS_KEY,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_ATTRIBUTE_NAME,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_ATTRIBUTE_VALUE,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ERROR_CODE,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ERROR_SEVERITY,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ADDITIONAL_DETAILS,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_BATCH_DETAILS_ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.CREATED_TS
    FROM SC_mplt_DV_PROCESS_ERROR_DETAILSOut
)

SELECT
    ID,
    PROCESS_DATE,
    REFERENCE_BATCH_ID,
    REFERENCE_PROCESS,
    REFERENCE_SUB_PROCESS,
    REFERENCE_TARGET_NAME,
    REFERENCE_RECORD_ID,
    REFERENCE_BUSINESS_KEY,
    REFERENCE_ATTRIBUTE_NAME,
    REFERENCE_ATTRIBUTE_VALUE,
    ERROR_CODE,
    ERROR_SEVERITY,
    ADDITIONAL_DETAILS,
    REFERENCE_BATCH_DETAILS_ID,
    CREATED_TS
FROM DSR_SC_PROCESS_ERROR_DETAILSOut;