{{
    config(
        materialized='incremental',
        alias='PROCESS_ERROR_DETAILS',
        schema='LDSA_SHARED',
        pre_hook="",
        post_hook="",
        incremental_strategy='append'
    )
}}

WITH SQ_LCHSA_ETD_REFIT_InstrumentDelta_YYYYMMDD_YYYYMMDDHH24missOut AS (
    SELECT
        REPORT_DATE,
        ISIN_CODE,
        DELTA,
        CurrentlyProcessedFileName
    FROM {{ source('FlatFile_catalog_1','LCHSA_ETD_REFIT_InstrumentDelta_YYYYMMDD_YYYYMMDDHH24miss') }}
),

EXP_TRIMOut AS (
    SELECT
        REPORT_DATE AS REPORT_DATE,
        ISIN_CODE AS ISIN_CODE,
        DELTA AS DELTA,
        CASE
            WHEN REPORT_DATE IS NOT NULL THEN TO_DATE(LTRIM(RTRIM(REPORT_DATE)), 'DD/MM/YYYY')
            ELSE RAISE_ERROR('REPORT_DATE is NULL from Source which is a mandatory field, hence aborting the session')
        END AS O_REPORT_DATE,
        LTRIM(RTRIM(ISIN_CODE)) AS O_ISIN_CODE,
        LTRIM(RTRIM(TO_DECIMAL(DELTA))) AS O_DELTA,
        'LCH.SA' AS ENTITY_NAME,
        CASE
            WHEN REGEXP_INSTR(CurrentlyProcessedFileName, 'DCL') > 0 THEN 'DCLSA'
            ELSE 'MATIF_MONEP'
        END AS DATA_SET_NAME,
        CurrentlyProcessedFileName
    FROM SQ_LCHSA_ETD_REFIT_InstrumentDelta_YYYYMMDD_YYYYMMDDHH24missOut
),

Target_Table_Name_SK_Max_Value AS (
    SELECT
        MAX(GENERATED_SEQ) AS max_generated_seq
    FROM {{ this }}
),

DSR_EXPTRANSOut AS (
    SELECT
        (SELECT max_generated_seq FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER () AS GENERATED_SEQ
    FROM {{ source('schema_name','SC_SEQ_LD_SA_INSTRUMENT_DELTA') }} AS SC_SEQ_LD_SA_INSTRUMENT_DELTAOut
),

EXPTRANSOut AS (
    SELECT
        LPAD(GENERATED_SEQ, 9, '0') AS v_SEQ_LPAD_TO_9,
        DATEDIFF(
            SECOND,
            TO_TIMESTAMP('01/01/1970 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),
            CURRENT_TIMESTAMP()
        ) AS v_EPOC_TIME,
        v_EPOC_TIME || v_SEQ_LPAD_TO_9 AS v_CONCATE_ID,
        v_CONCATE_ID AS ID
    FROM DSR_EXPTRANSOut
),

EXP_TRIM_details AS (
    SELECT
        EXP_TRIMOut.O_REPORT_DATE AS BUSINESS_DATE,
        EXP_TRIMOut.O_ISIN_CODE AS ISIN_CODE,
        EXP_TRIMOut.O_DELTA AS DELTA,
        EXP_TRIMOut.ENTITY_NAME AS ENTITY_NAME,
        EXP_TRIMOut.DATA_SET_NAME AS DATA_SET_NAME,
        EXP_TRIMOut.CurrentlyProcessedFileName AS CurrentlyProcessedFileName
    FROM EXP_TRIMOut
),

dsJoiner_EXP_PASS_THROUGH0Out AS (
    SELECT
        EXPTRANSOut.ID AS ID,
        EXP_TRIM_details.BUSINESS_DATE AS BUSINESS_DATE,
        EXP_TRIM_details.ISIN_CODE AS ISIN_CODE,
        EXP_TRIM_details.DELTA AS DELTA,
        EXP_TRIM_details.ENTITY_NAME AS ENTITY_NAME,
        EXP_TRIM_details.DATA_SET_NAME AS DATA_SET_NAME,
        EXP_TRIM_details.CurrentlyProcessedFileName AS CurrentlyProcessedFileName,
        ROW_NUMBER() OVER (ORDER BY 1) AS jkey
    FROM EXPTRANSOut
    INNER JOIN EXP_TRIM_details
        ON 1 = 1
),

EXP_PASS_THROUGHOut AS (
    SELECT
        ID AS ID,
        '{{ var("BATCH_ID") }}' AS BATCH_ID,
        dsf_1.ID AS BATCH_DETAILS_ID,
        TO_TIMESTAMP('{{ var("BATCH_START_DATE") }}', 'DD-MON-YYYY HH24:MI:SS') AS BATCH_START_DATE,
        BUSINESS_DATE,
        ISIN_CODE,
        DELTA,
        ENTITY_NAME,
        dsf_2.DIMENSION_KEY AS ENTITY_ID,
        DATA_SET_NAME,
        '{{ var("PMWorkflowName", "") }}' AS WORKFLOW_NAME,
        '{{ var("PMMappingName", "") }}' AS MAPPING_NAME,
        '{{ var("TARGET_NAME") }}' AS TARGET_NAME,
        'E300_BLANK_FIELD_OR_LKUP_FAIL' AS VALIDATION_NAME,
        'NUMBER' AS DATA_TYPE_NUM,
        'STRING' AS DATA_TYPE_STRING,
        'DATE' AS DATA_TYPE_DATE,
        'Y' AS NUM_VAL_Y,
        'ENTITY_ID' AS ATTRIBUTE_NAME_ENTITY_ID,
        'ISIN_CODE' AS ATTRIBUTE_NAME_ISIN_CODE,
        'DELTA' AS ATTRIBUTE_NAME_DELTA,
        CurrentlyProcessedFileName,
        v_TOT_REC_COUNT + 1 AS v_TOT_REC_COUNT
    FROM dsJoiner_EXP_PASS_THROUGH0Out
    LEFT JOIN (
        SELECT
            ID,
            BATCH_ID,
            TARGET_TABLE_NAME,
            FILE_NAME
        FROM (
            SELECT
                ID,
                BATCH_ID,
                TARGET_TABLE_NAME,
                FILE_NAME,
                ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ID,
                    BATCH_ID,
                    TARGET_TABLE_NAME,
                    FILE_NAME,
                    ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst,
                    ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_DETAILS_START_TIME DESC) AS RANK,
                    STATUS,
                    ACTIVE_FLAG,
                    BATCH_DETAILS_START_TIME
                FROM BATCH_DETAILS
                WHERE RANK = 1
                  AND STATUS = 'I'
                  AND ACTIVE_FLAG = 1
            )
        ) lkp_inner
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}'
       AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}'
       AND dsf_1.FILE_NAME = '{{ var("FILE_NAME_OVERRIDE") }}'
    LEFT JOIN (
        SELECT
            DIMENSION_KEY,
            NAME,
            EFFECTIVE_DATE,
            EXPIRATION_DATE
        FROM (
            SELECT
                DIMENSION_KEY,
                NAME,
                EFFECTIVE_DATE,
                EXPIRATION_DATE,
                ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    DIMENSION_KEY,
                    NAME,
                    EFFECTIVE_DATE,
                    EXPIRATION_DATE,
                    ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        ENTITY_DIM.DIMENSION_KEY,
                        ENTITY_DIM.NAME,
                        ENTITY_DIM.EFFECTIVE_DATE,
                        COALESCE(ENTITY_DIM.EXPIRATION_DATE, TO_DATE('31-DEC-2099','DD-MON-YYYY')) AS EXPIRATION_DATE
                    FROM ENTITY_DIM
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.NAME = ENTITY_NAME
       AND dsf_2.EFFECTIVE_DATE <= BUSINESS_DATE
       AND dsf_2.EXPIRATION_DATE >= BUSINESS_DATE
),

DSR_EXP_LDSA_VALIDATION_CHECKER_DELTAOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_DELTA AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_NUM AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.DELTA AS in_ATTRIBUTE_TO_BE_VALIDATED_NUM
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_ENTITY_ID AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_NUM AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.ENTITY_ID AS in_ATTRIBUTE_TO_BE_VALIDATED_NUM
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_ISIN_CODE AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.ISIN_CODE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

EXP_LDSA_VALIDATION_CHECKER_DELTAOut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        CASE WHEN dsf_1.ACTIVE_Y_N_STR_VL IS NULL THEN 'N' ELSE dsf_1.ACTIVE_Y_N_STR_VL END AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        CASE WHEN dsf_2.ACTIVE_Y_N IS NULL THEN 'N' ELSE dsf_2.ACTIVE_Y_N END AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE
                        WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                             OR (CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END) = 'Y'
                                AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2
                        THEN 'F' ELSE 'P'
                     END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_DELTAOut AS DSR_EXP_LDSA_VALIDATION_CHECKER_DELTAOut
    LEFT JOIN (
        SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                       ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
                WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER' AND ACTIVE_Y_N = 'Y'
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                   ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                       ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
       AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
       AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        CASE WHEN dsf_1.ACTIVE_Y_N_STR_VL IS NULL THEN 'N' ELSE dsf_1.ACTIVE_Y_N_STR_VL END AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        CASE WHEN dsf_2.ACTIVE_Y_N IS NULL THEN 'N' ELSE dsf_2.ACTIVE_Y_N END AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE
                        WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                             OR (CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END) = 'Y'
                                AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2
                        THEN 'F' ELSE 'P'
                     END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut AS DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut
    LEFT JOIN (
        SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                       ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
                WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER' AND ACTIVE_Y_N = 'Y'
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                   ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                       ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
       AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
       AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        CASE WHEN dsf_1.ACTIVE_Y_N_STR_VL IS NULL THEN 'N' ELSE dsf_1.ACTIVE_Y_N_STR_VL END AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        CASE WHEN dsf_2.ACTIVE_Y_N IS NULL THEN 'N' ELSE dsf_2.ACTIVE_Y_N END AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE
                        WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                             OR (CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END) = 'Y'
                                AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2
                        THEN 'F' ELSE 'P'
                     END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut AS DSR_EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut
    LEFT JOIN (
        SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                       ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
                WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER' AND ACTIVE_Y_N = 'Y'
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                   ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                       ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
       AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
       AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_DELTA_master AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_DELTAOut.o_VALIDATION_PASS_FAIL AS DELTA_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_DELTAOut.o_COMBINED_ERROR_MESSAGE AS DELTA_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_DELTAOut.o_ERROR_SEVERITY AS DELTA_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_DELTAOut
),

EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_VALIDATION_PASS_FAIL AS ENTITY_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_COMBINED_ERROR_MESSAGE AS ENTITY_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_ERROR_SEVERITY AS ENTITY_ID_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut
),

EXP_PASS_THROUGH_details AS (
    SELECT
        EXP_PASS_THROUGHOut.ID,
        EXP_PASS_THROUGHOut.BATCH_ID,
        EXP_PASS_THROUGHOut.BATCH_DETAILS_ID,
        EXP_PASS_THROUGHOut.BATCH_START_DATE,
        EXP_PASS_THROUGHOut.BUSINESS_DATE,
        EXP_PASS_THROUGHOut.WORKFLOW_NAME,
        EXP_PASS_THROUGHOut.MAPPING_NAME,
        EXP_PASS_THROUGHOut.TARGET_NAME,
        EXP_PASS_THROUGHOut.VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_ENTITY_ID AS ENTITY_ID_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_ISIN_CODE AS ISIN_CODE_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_DELTA AS DELTA_ATTRIBUTE_NAME
    FROM EXP_PASS_THROUGHOut
),

EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut.o_VALIDATION_PASS_FAIL AS ISIN_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut.o_COMBINED_ERROR_MESSAGE AS ISIN_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut.o_ERROR_SEVERITY AS ISIN_CODE_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut
),

dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out AS (
    SELECT
        EXP_PASS_THROUGH_details.ID,
        EXP_PASS_THROUGH_details.BATCH_ID,
        EXP_PASS_THROUGH_details.BATCH_DETAILS_ID,
        EXP_PASS_THROUGH_details.BATCH_START_DATE,
        EXP_PASS_THROUGH_details.BUSINESS_DATE,
        EXP_PASS_THROUGH_details.WORKFLOW_NAME,
        EXP_PASS_THROUGH_details.MAPPING_NAME,
        EXP_PASS_THROUGH_details.TARGET_NAME,
        EXP_PASS_THROUGH_details.VALIDATION_NAME,
        EXP_PASS_THROUGH_details.ENTITY_ID_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.ISIN_CODE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details.ISIN_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details.ISIN_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details.ISIN_CODE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.DELTA_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_DELTA_master.DELTA_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_DELTA_master.DELTA_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_DELTA_master.DELTA_ERROR_SEVERITY,
        ROW_NUMBER() OVER (ORDER BY 1) AS jkey
    FROM EXP_LDSA_VALIDATION_CHECKER_DELTA_master
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details ON 1 = 1
    INNER JOIN EXP_PASS_THROUGH_details ON 1 = 1
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details ON 1 = 1
),

EXP_CONSOLIDATE_VALIDATIONSOut AS (
    SELECT
        ID,
        BATCH_ID,
        BATCH_DETAILS_ID,
        BATCH_START_DATE,
        BUSINESS_DATE,
        WORKFLOW_NAME,
        MAPPING_NAME,
        TARGET_NAME,
        VALIDATION_NAME,
        '{{ var("FILE_NAME") }}' AS FILE_NAME,
        'FILE NAME:' || FILE_NAME || '/' || 'BUSINESS_DATE:' || BUSINESS_DATE || '/' AS v_ERROR_MESSAGE,
        ENTITY_ID_ATTRIBUTE_NAME,
        ENTITY_ID_VALIDATION_PASS_FAIL,
        ENTITY_ID_ERROR_MESSAGE,
        ENTITY_ID_ERROR_SEVERITY,
        v_ERROR_MESSAGE || ENTITY_ID_ERROR_MESSAGE AS O_ENTITY_ID_ERROR_MESSAGE,
        ISIN_CODE_ATTRIBUTE_NAME,
        ISIN_CODE_VALIDATION_PASS_FAIL,
        ISIN_CODE_ERROR_MESSAGE,
        ISIN_CODE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || ISIN_CODE_ERROR_MESSAGE AS O_ISIN_CODE_ERROR_MESSAGE,
        DELTA_ATTRIBUTE_NAME,
        DELTA_VALIDATION_PASS_FAIL,
        DELTA_ERROR_MESSAGE,
        DELTA_ERROR_SEVERITY,
        v_ERROR_MESSAGE || DELTA_ERROR_MESSAGE AS O_DELTA_ERROR_MESSAGE,
        CASE
            WHEN ENTITY_ID_VALIDATION_PASS_FAIL = 'F'
                 OR ISIN_CODE_VALIDATION_PASS_FAIL = 'F'
                 OR DELTA_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0
        END AS MD_ERROR_IND
    FROM dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out
),

DSR_FILTRANSOut AS (
    SELECT
        EXP_CONSOLIDATE_VALIDATIONSOut.O_ENTITY_ID_ERROR_MESSAGE AS ENTITY_ID_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.ISIN_CODE_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.ISIN_CODE_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_ISIN_CODE_ERROR_MESSAGE AS ISIN_CODE_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.DELTA_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.DELTA_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_DELTA_ERROR_MESSAGE AS DELTA_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.MD_ERROR_IND,
        EXP_CONSOLIDATE_VALIDATIONSOut.ID,
        EXP_CONSOLIDATE_VALIDATIONSOut.BATCH_ID,
        EXP_CONSOLIDATE_VALIDATIONSOut.BATCH_DETAILS_ID,
        EXP_CONSOLIDATE_VALIDATIONSOut.BATCH_START_DATE,
        EXP_CONSOLIDATE_VALIDATIONSOut.BUSINESS_DATE,
        EXP_CONSOLIDATE_VALIDATIONSOut.WORKFLOW_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.MAPPING_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.TARGET_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.VALIDATION_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.ENTITY_ID_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.ENTITY_ID_ERROR_SEVERITY
    FROM EXP_CONSOLIDATE_VALIDATIONSOut
),

DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut AS (
    SELECT
        FILTRANSOut.MAPPING_NAME AS INPUT_MAPPING_NAME,
        FILTRANSOut.TARGET_NAME AS INPUT_TARGET_NAME,
        FILTRANSOut.ENTITY_ID_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_1,
        FILTRANSOut.VALIDATION_NAME AS INPUT_ERROR_CODE_1,
        FILTRANSOut.ENTITY_ID_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_1,
        FILTRANSOut.ENTITY_ID_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_1,
        FILTRANSOut.VALIDATION_NAME AS INPUT_ERROR_CODE_2,
        FILTRANSOut.VALIDATION_NAME AS INPUT_ERROR_CODE_3,
        FILTRANSOut.ISIN_CODE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_2,
        FILTRANSOut.ISIN_CODE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_2,
        FILTRANSOut.ISIN_CODE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_2,
        FILTRANSOut.DELTA_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_3,
        FILTRANSOut.DELTA_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_3,
        FILTRANSOut.DELTA_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_3,
        FILTRANSOut.BATCH_DETAILS_ID AS INPUT_BATCH_DETAILS_ID,
        FILTRANSOut.BATCH_START_DATE AS INPUT_BATCH_START_DATE,
        FILTRANSOut.ID AS INPUT_REFERENCE_RECORD_ID,
        FILTRANSOut.BUSINESS_DATE AS INPUT_BATCH_BUSINESS_DATE,
        FILTRANSOut.BATCH_ID AS INPUT_BATCH_ID,
        FILTRANSOut.WORKFLOW_NAME AS INPUT_WORKFLOW_NAME
    FROM DSR_FILTRANSOut AS DSR_FILTRANSOut
    WHERE MD_ERROR_IND = 1
),

SC_mplt_DV_PROCESS_ERROR_DETAILSOut AS (
    SELECT
        REFERENCE_ATTRIBUTE_NAME,
        REFERENCE_ATTRIBUTE_VALUE,
        ERROR_CODE,
        ERROR_SEVERITY,
        ADDITIONAL_DETAILS,
        REFERENCE_BATCH_DETAILS_ID,
        BATCH_START_DATE AS CREATED_TS,
        ID,
        PROCESS_DATE,
        REFERENCE_BATCH_ID,
        REFERENCE_PROCESS,
        REFERENCE_SUB_PROCESS,
        REFERENCE_TARGET_NAME,
        REFERENCE_RECORD_ID,
        REFERENCE_BUSINESS_KEY,
        INPUT_MAPPING_NAME,
        INPUT_TARGET_NAME,
        INPUT_ATTRIBUTE_NAME_1,
        INPUT_ERROR_CODE_1,
        INPUT_ERROR_SEVERITY_1,
        INPUT_ATTRIBUTE_VALUE_1,
        INPUT_ERROR_CODE_2,
        INPUT_ERROR_CODE_3,
        INPUT_ATTRIBUTE_NAME_2,
        INPUT_ERROR_SEVERITY_2,
        INPUT_ATTRIBUTE_VALUE_2,
        INPUT_ATTRIBUTE_NAME_3,
        INPUT_ERROR_SEVERITY_3,
        INPUT_ATTRIBUTE_VALUE_3,
        INPUT_BATCH_DETAILS_ID,
        INPUT_BATCH_START_DATE,
        INPUT_REFERENCE_RECORD_ID,
        INPUT_BATCH_BUSINESS_DATE,
        INPUT_BATCH_ID,
        INPUT_WORKFLOW_NAME
    FROM DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut
),

DSR_SC_PROCESS_ERROR_DETAILSOut AS (
    SELECT
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.PROCESS_DATE,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_BATCH_ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_PROCESS,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_SUB_PROCESS,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_TARGET_NAME,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_RECORD_ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_BUSINESS_KEY,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_ATTRIBUTE_NAME,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_ATTRIBUTE_VALUE,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ERROR_CODE,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ERROR_SEVERITY,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ADDITIONAL_DETAILS,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_BATCH_DETAILS_ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.CREATED_TS
    FROM SC_mplt_DV_PROCESS_ERROR_DETAILSOut
)

SELECT
    ID,
    PROCESS_DATE,
    REFERENCE_BATCH_ID,
    REFERENCE_PROCESS,
    REFERENCE_SUB_PROCESS,
    REFERENCE_TARGET_NAME,
    REFERENCE_RECORD_ID,
    REFERENCE_BUSINESS_KEY,
    REFERENCE_ATTRIBUTE_NAME,
    REFERENCE_ATTRIBUTE_VALUE,
    ERROR_CODE,
    ERROR_SEVERITY,
    ADDITIONAL_DETAILS,
    REFERENCE_BATCH_DETAILS_ID,
    CREATED_TS
FROM DSR_SC_PROCESS_ERROR_DETAILSOut