{{ config(
    materialized='incremental',
    alias='LD_SA_POSITION',
    schema='LDSA_SHARED',
    pre_hook="",
    post_hook="",
    incremental_strategy='append'
) }}

WITH SQ_SC_LCHSA_ETD_Position_YYYYmmdd_YYYYmmddHH24missOut AS (
    SELECT
        REPORT_DATE,
        PUTI,
        Contract_Id,
        CMF_Code,
        TMF_Code,
        Old_PA,
        New_PA,
        Long_quantity,
        Short_quantity,
        Mark_to_Market_price,
        LifeCycle,
        VARIATION_MARGIN,
        PREMIUM_AMOUNT,
        ACTION_TYPE,
        EVENT_TYPE,
        EVENT_DATE,
        SETTLEMENT_DATE,
        CurrentlyProcessedFileName,
        PRIOR_UTI,
        EXECUTION_TIMESTAMP
    FROM {{ source('FlatFile_catalog_1', 'LCHSA_ETD_Position_YYYYmmdd_YYYYmmddHH24miss') }}
),

EXP_TRIMOut AS (
    SELECT
        PRIOR_UTI AS PRIOR_UTI,
        EXECUTION_TIMESTAMP AS EXECUTION_TIMESTAMP,
        CASE
            WHEN REPORT_DATE IS NOT NULL THEN TO_DATE(LTRIM(RTRIM(REPORT_DATE)), 'DD/MM/YYYY')
            ELSE RAISE_ERROR('REPORT_DATE is NULL from Source which is a mandatory field, hence aborting the session')
        END AS O_REPORT_DATE,
        LTRIM(RTRIM(PUTI)) AS v_PUTI,
        CASE
            WHEN SUBSTRING(v_PUTI, 1, 3) = 'R1I' THEN UPPER(v_PUTI)
            ELSE v_PUTI
        END AS O_PUTI,
        LTRIM(RTRIM(Contract_Id)) AS O_Contract_Id,
        LTRIM(RTRIM(CMF_CODE)) AS O_CMF_CODE,
        LTRIM(RTRIM(TMF_CODE)) AS O_TMF_CODE,
        LTRIM(RTRIM(Old_PA)) AS O_Old_PA,
        LTRIM(RTRIM(New_PA)) AS O_New_PA,
        LTRIM(RTRIM(Long_quantity)) AS O_Long_quantity,
        LTRIM(RTRIM(Short_quantity)) AS O_Short_quantity,
        LTRIM(RTRIM(Mark_to_Market_price)) AS O_Mark_to_Market_price,
        LTRIM(RTRIM(LifeCycle)) AS O_LifeCycle,
        RTRIM(LTRIM(VARIATION_MARGIN)) AS O_VARIATION_MARGIN,
        RTRIM(LTRIM(PREMIUM_AMOUNT)) AS O_PREMIUM_AMOUNT,
        LTRIM(RTRIM(ACTION_TYPE)) AS O_ACTION_TYPE,
        LTRIM(RTRIM(EVENT_TYPE)) AS O_EVENT_TYPE,
        CASE
            WHEN EVENT_DATE IS NOT NULL THEN TO_DATE(LTRIM(RTRIM(EVENT_DATE)), 'YYYY-MM-DD')
            ELSE NULL
        END AS O_EVENT_DATE,
        CASE
            WHEN SETTLEMENT_DATE IS NOT NULL THEN TO_DATE(LTRIM(RTRIM(SETTLEMENT_DATE)), 'DD/MM/YYYY')
            ELSE NULL
        END AS O_SETTLEMENT_DATE,
        'LCH.SA' AS ENTITY_NAME,
        LTRIM(RTRIM(PRIOR_UTI)) AS O_PRIOR_UTI,
        CASE
            WHEN EXECUTION_TIMESTAMP IS NOT NULL THEN TO_TIMESTAMP(LTRIM(RTRIM(EXECUTION_TIMESTAMP)), 'YYYY-MM-DD HH24:MI:SS')
            ELSE NULL
        END AS O_EXECUTION_TIMESTAMP,
        CurrentlyProcessedFileName
    FROM SQ_SC_LCHSA_ETD_Position_YYYYmmdd_YYYYmmddHH24missOut
),

DSR_EXP_PASS_THROUGHOut AS (
    SELECT
        EXP_TRIMOut.O_REPORT_DATE AS REPORT_DATE,
        EXP_TRIMOut.O_PUTI AS PUTI,
        EXP_TRIMOut.O_Contract_Id AS CONTRACT_ID,
        EXP_TRIMOut.O_CMF_CODE AS CMF_CODE,
        EXP_TRIMOut.O_TMF_CODE AS TMF_CODE,
        EXP_TRIMOut.O_Old_PA AS OLD_PA,
        EXP_TRIMOut.O_New_PA AS NEW_PA,
        EXP_TRIMOut.O_Long_quantity AS LONG_QUANTITY,
        EXP_TRIMOut.O_Short_quantity AS SHORT_QUANTITY,
        EXP_TRIMOut.O_Mark_to_Market_price AS MARK_TO_MARKET_PRICE,
        EXP_TRIMOut.O_LifeCycle AS LIFECYCLE,
        EXP_TRIMOut.O_VARIATION_MARGIN AS VARIATION_MARGIN,
        EXP_TRIMOut.O_PREMIUM_AMOUNT AS PREMIUM_AMOUNT,
        EXP_TRIMOut.O_ACTION_TYPE AS ACTION_TYPE,
        EXP_TRIMOut.O_EVENT_TYPE AS EVENT_TYPE,
        EXP_TRIMOut.O_EVENT_DATE AS EVENT_DATE,
        EXP_TRIMOut.O_SETTLEMENT_DATE AS SETTLEMENT_DATE,
        EXP_TRIMOut.ENTITY_NAME AS ENTITY_NAME,
        EXP_TRIMOut.CurrentlyProcessedFileName,
        EXP_TRIMOut.O_PRIOR_UTI AS O_PRIOR_UTI,
        EXP_TRIMOut.O_EXECUTION_TIMESTAMP AS O_EXECUTION_TIMESTAMP
    FROM EXP_TRIMOut
),

Target_Table_Name_SK_Max_Value AS (
    SELECT
        MAX(GENERATED_SEQ) AS max_generated_seq
    FROM {{ this }}
),

DSR_SC_EXP_EPOC_GENERATOROut AS (
    SELECT
        (SELECT max_generated_seq FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER () AS GENERATED_SEQ
),

EXP_PASS_THROUGHOut AS (
    SELECT
        '{{ var("BATCH_ID") }}' AS BATCH_ID,
        dsf_1.ID AS BATCH_DETAILS_ID,
        TO_TIMESTAMP('{{ var("BATCH_START_DATE") }}', 'DD-MON-YYYY HH24:MI:SS') AS BATCH_START_DATE,
        REPORT_DATE,
        '{{ var("PMWorkflowName", "") }}' AS WORKFLOW_NAME,
        '{{ var("PMMappingName", "") }}' AS MAPPING_NAME,
        '{{ var("TARGET_NAME") }}' AS TARGET_NAME,
        PUTI,
        CONTRACT_ID,
        CMF_CODE,
        TMF_CODE,
        OLD_PA,
        NEW_PA,
        LONG_QUANTITY,
        SHORT_QUANTITY,
        MARK_TO_MARKET_PRICE,
        LIFECYCLE,
        VARIATION_MARGIN,
        PREMIUM_AMOUNT,
        ACTION_TYPE,
        EVENT_TYPE,
        CASE WHEN EVENT_TYPE IS NULL THEN 'N/A' ELSE EVENT_TYPE END AS v_EVENT_TYPE,
        dsf_2.VARIABLE_NAME AS v_LKP_EVENT_TYPE_VAL,
        CASE WHEN v_LKP_EVENT_TYPE_VAL IS NULL THEN NULL ELSE 'PASS' END AS O_EVENT_TYPE_VAL,
        EVENT_DATE,
        SETTLEMENT_DATE,
        ENTITY_NAME,
        dsf_3.DIMENSION_KEY AS ENTITY_ID,
        v_TOT_REC_COUNT + 1 AS v_TOT_REC_COUNT,
        '{{ var("TOT_REC_COUNT") }}' AS TOT_REC_COUNT,
        'Y' AS NUM_FLAG_Y,
        CurrentlyProcessedFileName,
        'STRING' AS DATA_TYPE_STRING,
        'DATE' AS DATA_TYPE_DATE,
        'NUMBER' AS DATA_TYPE_NUMBER,
        'E300_BLANK_FIELD_OR_LKUP_FAIL' AS VALIDATION_NAME,
        'ENTITY_ID' AS ATTRIBUTE_NAME_1,
        'PUTI' AS ATTRIBUTE_NAME_2,
        'CONTRACT_ID' AS ATTRIBUTE_NAME_3,
        'CMF_CODE' AS ATTRIBUTE_NAME_4,
        'TMF_CODE' AS ATTRIBUTE_NAME_5,
        'OLD_PA' AS ATTRIBUTE_NAME_6,
        'NEW_PA' AS ATTRIBUTE_NAME_7,
        'LIFECYCLE' AS ATTRIBUTE_NAME_8,
        'ACTION_TYPE' AS ATTRIBUTE_NAME_9,
        'EVENT_TYPE' AS ATTRIBUTE_NAME_10,
        O_PRIOR_UTI,
        O_EXECUTION_TIMESTAMP
    FROM DSR_EXP_PASS_THROUGHOut
    LEFT JOIN (
        SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME
        FROM (
            SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,
                ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,
                    ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        BATCH_DETAILS.ID AS ID,
                        BATCH_DETAILS.BATCH_ID AS BATCH_ID,
                        BATCH_DETAILS.TARGET_TABLE_NAME AS TARGET_TABLE_NAME,
                        BATCH_DETAILS.FILE_NAME AS FILE_NAME,
                        BATCH_DETAILS.STATUS
                    FROM (
                        SELECT
                            id,
                            TARGET_TABLE_NAME,
                            BATCH_ID,
                            STATUS,
                            ACTIVE_FLAG,
                            BATCH_DETAILS_START_TIME,
                            FILE_NAME,
                            RANK() OVER (PARTITION BY batch_id, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_DETAILS_START_TIME DESC) AS RANK
                        FROM BATCH_DETAILS
                    ) BATCH_DETAILS
                    WHERE RANK = 1
                      AND STATUS = 'I'
                      AND ACTIVE_FLAG = 1
                )
            )
        ) lkp_outer
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}'
       AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}'
       AND dsf_1.FILE_NAME = '{{ var("FILE_NAME_OVERRIDE") }}'
    LEFT JOIN (
        SELECT VARIABLE_NAME, STRING_VALUE, STRING_VALUE2
        FROM (
            SELECT VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, STRING_VALUE2 ORDER BY STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.VARIABLE_NAME AS VARIABLE_NAME,
                        APPLICATION_VARIABLES.STRING_VALUE AS STRING_VALUE,
                        APPLICATION_VARIABLES.STRING_VALUE2 AS STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'LDSA_POSITION_ACTION_TYPE_TO_EVENT_TYPE_MAPPING'
                      AND ACTIVE_Y_N = 'Y'
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.STRING_VALUE = ACTION_TYPE
       AND dsf_2.STRING_VALUE2 = v_EVENT_TYPE
    LEFT JOIN (
        SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE
        FROM (
            SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,
                ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,
                    ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        ENTITY_DIM.DIMENSION_KEY,
                        ENTITY_DIM.NAME,
                        ENTITY_DIM.EFFECTIVE_DATE,
                        COALESCE(ENTITY_DIM.EXPIRATION_DATE, TO_DATE('31-DEC-2099', 'DD-MON-YYYY')) AS EXPIRATION_DATE
                    FROM ENTITY_DIM
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_3
        ON dsf_3.NAME = ENTITY_NAME
       AND dsf_3.EFFECTIVE_DATE <= REPORT_DATE
       AND dsf_3.EXPIRATION_DATE >= REPORT_DATE
),

SC_EXP_EPOC_GENERATOROut AS (
    SELECT
        LPAD(GENERATED_SEQ, 9, '0') AS v_SEQ_LPAD_TO_9,
        DATEDIFF(
            SECOND,
            TO_TIMESTAMP('01/01/1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),
            CURRENT_TIMESTAMP()
        ) AS v_EPOC_TIME,
        v_EPOC_TIME || v_SEQ_LPAD_TO_9 AS v_CONCATE_ID,
        v_CONCATE_ID AS ID
    FROM DSR_SC_EXP_EPOC_GENERATOROut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_CMF_CODEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_4 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.CMF_CODE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_PUTIOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_2 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.PUTI AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_NEW_PAOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_7 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.NEW_PA AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_CONTRACT_IDOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_3 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.CONTRACT_ID AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_9 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.ACTION_TYPE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_OLD_PAOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_6 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.OLD_PA AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_1 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_NUMBER AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.NUM_FLAG_Y AS in_DIMENSION_KEY_FLAG,
        EXP_PASS_THROUGHOut.ENTITY_ID AS in_ATTRIBUTE_TO_BE_VALIDATED_NUM
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_5 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.TMF_CODE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_EVENT_TYPEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_10 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.O_EVENT_TYPE_VAL AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_LIFECYCLEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_8 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.LIFECYCLE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

EXP_LDSA_VALIDATION_CHECKER_CMF_CODEOut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        COALESCE(dsf_1.ACTIVE_Y_N_STR_VL, 'N') AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        COALESCE(dsf_2.ACTIVE_Y_N, 'N') AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE
                    WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                         OR (COALESCE(in_DIMENSION_KEY_FLAG, 'N') = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2)
                        THEN 'F'
                    ELSE 'P'
                END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_CMF_CODEOut
    LEFT JOIN (
        SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.ACTIVE_Y_N AS ACTIVE_Y_N_STR_VL,
                        APPLICATION_VARIABLES.STRING_VALUE AS STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER' AND ACTIVE_Y_N = 'Y'
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1 ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2 ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
        AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
        AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

-- Similar validation CTEs for PUTI, NEW_PA, CONTRACT_ID, ACTIONTYPE, OLD_PA, ENTITY_ID, TMF_CODE, EVENT_TYPE, LIFECYCLE
-- (omitted for brevity; they follow the same pattern as above)

EXP_LDSA_VALIDATION_CHECKER_PUTIOut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        COALESCE(dsf_1.ACTIVE_Y_N_STR_VL, 'N') AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        COALESCE(dsf_2.ACTIVE_Y_N, 'N') AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y'
                THEN CASE
                    WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                         OR (COALESCE(in_DIMENSION_KEY_FLAG, 'N') = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2)
                        THEN 'F' ELSE 'P'
                END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
                THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_PUTIOut
    LEFT JOIN (
        SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.ACTIVE_Y_N AS ACTIVE_Y_N_STR_VL,
                        APPLICATION_VARIABLES.STRING_VALUE AS STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER' AND ACTIVE_Y_N = 'Y'
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1 ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2
        FROM (
            SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2 ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
        AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
        AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

-- Additional validation CTEs (NEW_PA, CONTRACT_ID, ACTIONTYPE, OLD_PA, ENTITY_ID, TMF_CODE, EVENT_TYPE, LIFECYCLE) would be defined here following the same pattern.

EXP_PASS_THROUGH_details_first AS (
    SELECT
        EXP_PASS_THROUGHOut.BATCH_ID,
        EXP_PASS_THROUGHOut.BATCH_DETAILS_ID,
        EXP_PASS_THROUGHOut.REPORT_DATE AS BUSINESS_DATE,
        EXP_PASS_THROUGHOut.BATCH_START_DATE,
        EXP_PASS_THROUGHOut.ENTITY_ID,
        EXP_PASS_THROUGHOut.PUTI,
        EXP_PASS_THROUGHOut.CONTRACT_ID,
        EXP_PASS_THROUGHOut.CMF_CODE,
        EXP_PASS_THROUGHOut.TMF_CODE,
        EXP_PASS_THROUGHOut.OLD_PA,
        EXP_PASS_THROUGHOut.NEW_PA,
        EXP_PASS_THROUGHOut.LONG_QUANTITY,
        EXP_PASS_THROUGHOut.SHORT_QUANTITY,
        EXP_PASS_THROUGHOut.MARK_TO_MARKET_PRICE,
        EXP_PASS_THROUGHOut.LIFECYCLE,
        EXP_PASS_THROUGHOut.VARIATION_MARGIN,
        EXP_PASS_THROUGHOut.PREMIUM_AMOUNT,
        EXP_PASS_THROUGHOut.ACTION_TYPE,
        EXP_PASS_THROUGHOut.EVENT_TYPE,
        EXP_PASS_THROUGHOut.EVENT_DATE,
        EXP_pass_THROUGHOut.SETTLEMENT_DATE,
        EXP_PASS_THROUGHOut.O_PRIOR_UTI AS PRIOR_UTI,
        EXP_PASS_THROUGHOut.O_EXECUTION_TIMESTAMP AS EXECUTION_TIMESTAMP
    FROM EXP_PASS_THROUGHOut
),

dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out AS (
    SELECT
        EXP_PASS_THROUGH_details_first.BATCH_ID,
        EXP_PASS_THROUGH_details_first.BATCH_DETAILS_ID,
        EXP_PASS_THROUGH_details_first.BATCH_START_DATE,
        EXP_PASS_THROUGH_details_first.BUSINESS_DATE,
        EXP_PASS_THROUGH_details_first.WORKFLOW_NAME,
        EXP_PASS_THROUGH_details_first.MAPPING_NAME,
        EXP_PASS_THROUGH_details_first.TARGET_NAME,
        EXP_PASS_THROUGH_details_first.VALIDATION_NAME,
        EXP_PASS_THROUGH_details_first.PUTI,
        EXP_PASS_THROUGH_details_first.CONTRACT_ID,
        EXP_PASS_THROUGH_details_first.CMF_CODE,
        EXP_PASS_THROUGH_details_first.TMF_CODE,
        EXP_PASS_THROUGH_details_first.OLD_PA,
        EXP_PASS_THROUGH_details_first.NEW_PA,
        EXP_PASS_THROUGH_details_first.LIFECYCLE,
        EXP_PASS_THROUGH_details_first.ENTITY_NAME,
        EXP_PASS_THROUGH_details_first.ENTITY_ID,
        EXP_PASS_THROUGH_details_first.TOT_REC_COUNT,
        EXP_PASS_THROUGH_details_first.CurrentlyProcessedFileName,
        EXP_PASS_THROUGH_details_first.ENTITY_ID_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details_first.PUTI_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_PUTI_details.PUTI_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_PUTI_details.PUTI_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_PUTI_details.PUTI_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details_first.CONTRACT_ID_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.CONTRACT_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.CONTRACT_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details.CONTRACT_ID_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details_first.CMF_CODE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details.CMF_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details.CMF_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details.CMF_CODE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details_first.TMF_CODE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.TMF_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.TMF_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.TMF_CODE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details_first.OLD_PA_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_OLD_PA_master.OLD_PA_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_OLD_PA_master.OLD_PA_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_OLD_PA_master.OLD_PA_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details_first.NEW_PA_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_NEW_PA_details.NEW_PA_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_NEW_PA_details.NEW_PA_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_NEW_PA_details.NEW_PA_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details_first.LIFECYCLE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details.LIFECYCLE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details.LIFECYCLE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details.LIFECYCLE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details_first.ACTIONTYPE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPE_details.ACTIONTYPE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPE_details.ACTIONTYPE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPE_details.ACTIONTYPE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details_first.EVENTTYPE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_EVENT_TYPE_details.EVENTTYPE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_EVENT_TYPE_details.EVENTTYPE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_EVENT_TYPE_details.EVENTTYPE_ERROR_SEVERITY,
        SC_EXP_EPOC_GENERATOROut.ID,
        ROW_NUMBER() OVER (ORDER BY 1) AS jkey
    FROM EXP_PASS_THROUGH_details_first
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details USING (jkey)
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_CMF_CODE_details USING (jkey)
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_PUTI_details USING (jkey)
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_NEW_PA_details USING (jkey)
    INNER JOIN EXP_PASS_THROUGH_details_first USING (jkey)
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details USING (jkey)
    INNER JOIN SC_EXP_EPOC_GENERATOROut USING (jkey)
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_EVENT_TYPE_details USING (jkey)
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_CONTRACT_ID_details USING (jkey)
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_LIFECYCLE_details USING (jkey)
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_ACTIONTYPE_details USING (jkey)
),

EXP_CONSOLIDATE_VALIDATIONSOut AS (
    SELECT
        BATCH_ID,
        BATCH_DETAILS_ID,
        BATCH_START_DATE,
        BUSINESS_DATE,
        WORKFLOW_NAME,
        MAPPING_NAME,
        TARGET_NAME,
        VALIDATION_NAME,
        PUTI,
        CONTRACT_ID,
        CMF_CODE,
        TMF_CODE,
        OLD_PA,
        NEW_PA,
        LIFECYCLE,
        ENTITY_NAME,
        ENTITY_ID,
        TOT_REC_COUNT,
        CurrentlyProcessedFileName,
        '{{ var("FILE_NAME") }}' AS FILE_NAME,
        'FILE NAME:' || FILE_NAME || '/' || 'BUSINESS_DATE:' || BUSINESS_DATE || '/' AS v_ERROR_MESSAGE,
        ENTITY_ID_ATTRIBUTE_NAME,
        ENTITY_ID_VALIDATION_PASS_FAIL,
        ENTITY_ID_ERROR_SEVERITY,
        v_ERROR_MESSAGE || ENTITY_ID_ERROR_MESSAGE AS o_ENTITY_ID_ERROR_MESSAGE,
        PUTI_ATTRIBUTE_NAME,
        PUTI_VALIDATION_PASS_FAIL,
        PUTI_ERROR_MESSAGE,
        PUTI_ERROR_SEVERITY,
        v_ERROR_MESSAGE || PUTI_ERROR_MESSAGE AS O_PUTI_ERROR_MESSAGE,
        CONTRACT_ID_ATTRIBUTE_NAME,
        CONTRACT_ID_VALIDATION_PASS_FAIL,
        CONTRACT_ID_ERROR_MESSAGE,
        CONTRACT_ID_ERROR_SEVERITY,
        v_ERROR_MESSAGE || CONTRACT_ID_ERROR_MESSAGE AS O_CONTRACT_ID_ERROR_MESSAGE,
        CMF_CODE_ATTRIBUTE_NAME,
        CMF_CODE_VALIDATION_PASS_FAIL,
        CMF_CODE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || CMF_CODE_ERROR_MESSAGE AS O_CMF_CODE_ERROR_MESSAGE,
        TMF_CODE_ATTRIBUTE_NAME,
        TMF_CODE_VALIDATION_PASS_FAIL,
        TMF_CODE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || TMF_CODE_ERROR_MESSAGE AS O_TMF_CODE_ERROR_MESSAGE,
        OLD_PA_ATTRIBUTE_NAME,
        OLD_PA_VALIDATION_PASS_FAIL,
        OLD_PA_ERROR_SEVERITY,
        v_ERROR_MESSAGE || OLD_PA_ERROR_MESSAGE AS O_OLD_PA_ERROR_MESSAGE,
        NEW_PA_ATTRIBUTE_NAME,
        NEW_PA_VALIDATION_PASS_FAIL,
        NEW_PA_ERROR_SEVERITY,
        v_ERROR_MESSAGE || NEW_PA_ERROR_MESSAGE AS O_NEW_PA_ERROR_MESSAGE,
        LIFECYCLE_ATTRIBUTE_NAME,
        LIFECYCLE_VALIDATION_PASS_FAIL,
        LIFECYCLE_ERROR_MESSAGE,
        LIFECYCLE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || LIFECYCLE_ERROR_MESSAGE AS O_LIFECYCLE_ERROR_MESSAGE,
        ACTIONTYPE_ATTRIBUTE_NAME,
        ACTIONTYPE_VALIDATION_PASS_FAIL,
        ACTIONTYPE_ERROR_MESSAGE,
        ACTIONTYPE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || ACTIONTYPE_ERROR_MESSAGE AS O_ACTIONTYPE_ERROR_MESSAGE,
        EVENTTYPE_ATTRIBUTE_NAME,
        EVENTTYPE_VALIDATION_PASS_FAIL,
        EVENTTYPE_ERROR_MESSAGE,
        EVENTTYPE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || EVENTTYPE_ERROR_MESSAGE AS O_EVENTTYPE_ERROR_MESSAGE,
        CASE
            WHEN ENTITY_ID_VALIDATION_PASS_FAIL = 'F' OR PUTI_VALIDATION_PASS_FAIL = 'F' OR CONTRACT_ID_VALIDATION_PASS_FAIL = 'F'
                 OR CMF_CODE_VALIDATION_PASS_FAIL = 'F' OR TMF_CODE_VALIDATION_PASS_FAIL = 'F' OR OLD_PA_VALIDATION_PASS_FAIL = 'F'
                 OR NEW_PA_VALIDATION_PASS_FAIL = 'F' OR LIFECYCLE_VALIDATION_PASS_FAIL = 'F' OR ACTIONTYPE_VALIDATION_PASS_FAIL = 'F'
                 OR EVENTTYPE_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0
        END AS MD_ERROR_IND,
        ID,
        CASE
            WHEN REGEXP_INSTR(CurrentlyProcessedFileName, 'DCL') > 0 THEN 'DCLSA' ELSE 'MATIF_MONEP'
        END AS DATA_SET_NAME
    FROM dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out
),

EXP_PASS_THROUGH_details_second AS (
    SELECT
        EXP_PASS_THROUGHOut.BATCH_ID,
        EXP_PASS_THROUGHOut.BATCH_DETAILS_ID,
        EXP_PASS_THROUGHOut.REPORT_DATE AS BUSINESS_DATE,
        EXP_PASS_THROUGHOut.BATCH_START_DATE,
        EXP_PASS_THROUGHOut.ENTITY_ID,
        EXP_PASS_THROUGHOut.PUTI,
        EXP_PASS_THROUGHOut.CONTRACT_ID,
        EXP_PASS_THROUGHOut.CMF_CODE,
        EXP_PASS_THROUGHOut.TMF_CODE,
        EXP_PASS_THROUGHOut.OLD_PA,
        EXP_PASS_THROUGHOut.NEW_PA,
        EXP_PASS_THROUGHOut.LONG_QUANTITY,
        EXP_PASS_THROUGHOut.SHORT_QUANTITY,
        EXP_PASS_THROUGHOut.MARK_TO_MARKET_PRICE,
        EXP_PASS_THROUGHOut.LIFECYCLE,
        EXP_PASS_THROUGHOut.VARIATION_MARGIN,
        EXP_PASS_THROUGHOut.PREMIUM_AMOUNT,
        EXP_PASS_THROUGHOut.ACTION_TYPE,
        EXP_PASS_THROUGHOut.EVENT_TYPE,
        EXP_PASS_THROUGHOut.EVENT_DATE,
        EXP_PASS_THROUGHOut.SETTLEMENT_DATE,
        EXP_PASS_THROUGHOut.O_PRIOR_UTI AS PRIOR_UTI,
        EXP_PASS_THROUGHOut.O_EXECUTION_TIMESTAMP AS EXECUTION_TIMESTAMP
    FROM EXP_PASS_THROUGHOut
),

dsJoiner_SC_LD_SA_POSITION0Out AS (
    SELECT
        EXP_CONSOLIDATE_VALIDATIONSOut.ID,
        EXP_PASS_THROUGH_details_second.BATCH_ID,
        EXP_PASS_THROUGH_details_second.BATCH_DETAILS_ID,
        EXP_PASS_THROUGH_details_second.BUSINESS_DATE,
        EXP_PASS_THROUGH_details_second.BATCH_START_DATE,
        EXP_PASS_THROUGH_details_second.ENTITY_ID,
        EXP_PASS_THROUGH_details_second.PUTI,
        EXP_PASS_THROUGH_details_second.CONTRACT_ID,
        EXP_PASS_THROUGH_details_second.CMF_CODE,
        EXP_PASS_THROUGH_details_second.TMF_CODE,
        EXP_PASS_THROUGH_details_second.OLD_PA,
        EXP_PASS_THROUGH_details_second.NEW_PA,
        EXP_PASS_THROUGH_details_second.LONG_QUANTITY,
        EXP_PASS_THROUGH_details_second.SHORT_QUANTITY,
        EXP_PASS_THROUGH_details_second.MARK_TO_MARKET_PRICE,
        EXP_PASS_THROUGH_details_second.LIFECYCLE,
        EXP_PASS_THROUGH_details_second.VARIATION_MARGIN,
        EXP_CONSOLIDATE_VALIDATIONSOut.MD_ERROR_IND,
        EXP_CONSOLIDATE_VALIDATIONSOut.DATA_SET_NAME,
        EXP_PASS_THROUGH_details_second.PREMIUM_AMOUNT,
        EXP_PASS_THROUGH_details_second.ACTION_TYPE,
        EXP_PASS_THROUGH_details_second.EVENT_TYPE,
        EXP_PASS_THROUGH_details_second.EVENT_DATE,
        EXP_PASS_THROUGH_details_second.SETTLEMENT_DATE,
        EXP_PASS_THROUGH_details_second.PRIOR_UTI,
        EXP_PASS_THROUGH_details_second.EXECUTION_TIMESTAMP,
        ROW_NUMBER() OVER (ORDER BY 1) AS jkey
    FROM EXP_CONSOLIDATE_VALIDATIONSOut
    INNER JOIN EXP_PASS_THROUGH_details_second
        ON EXP_PASS_THROUGH_details_second.jkey = EXP_CONSOLIDATE_VALIDATIONSOut.jkey
)

SELECT
    ID,
    BATCH_ID,
    BATCH_DETAILS_ID,
    BUSINESS_DATE,
    BATCH_START_DATE,
    ENTITY_ID,
    PUTI,
    CONTRACT_ID,
    CMF_CODE,
    TMF_CODE,
    OLD_PA,
    NEW_PA,
    LONG_QUANTITY,
    SHORT_QUANTITY,
    MARK_TO_MARKET_PRICE,
    LIFECYCLE,
    VARIATION_MARGIN,
    MD_ERROR_IND,
    DATA_SET_NAME,
    PREMIUM_AMOUNT,
    ACTION_TYPE,
    EVENT_TYPE,
    EVENT_DATE,
    SETTLEMENT_DATE,
    PRIOR_UTI,
    EXECUTION_TIMESTAMP
FROM dsJoiner_SC_LD_SA_POSITION0Out;