/* Transformation Name ==>SC_LD_SA_INSTRUMENT_DELTA ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='LD_SA_INSTRUMENT_DELTA',
		schema='LDSA_SHARED',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_LCHSA_ETD_REFIT_InstrumentDelta_YYYYMMDD_YYYYMMDDHH24missOut as (
	/* transType: "Source" */
Select REPORT_DATE, 
		ISIN_CODE, 
		DELTA, 
		CurrentlyProcessedFileName
 from 
{{ source ('FlatFile_catalog_1','LCHSA_ETD_REFIT_InstrumentDelta_YYYYMMDD_YYYYMMDDHH24miss') }} 
 ),

EXP_TRIMOut as (
	/* transType: "Expression" */
Select 
	REPORT_DATE as REPORT_DATE,
	 ISIN_CODE as ISIN_CODE,
	 DELTA as DELTA,
	 ( CASE WHEN REPORT_DATE IS NOT NULL THEN TO_DATE ( LTRIM ( RTRIM ( REPORT_DATE ) ),
	 'DD/MM/YYYY' ) ELSE ABORT ( 'REPORT_DATE is NULL from Source which is a mandatory field,
	hence aborting the session' ) END ) as O_REPORT_DATE,
	 LTRIM ( RTRIM ( ISIN_CODE ) ) as O_ISIN_CODE,
	 LTRIM ( RTRIM ( TO_DECIMAL ( DELTA ) ) ) as O_DELTA,
	 'LCH.SA' as ENTITY_NAME,
	 ( CASE WHEN REGEXP_INSTR ( CurrentlyProcessedFileName,
	 'DCL' ) > 0 THEN 'DCLSA' ELSE 'MATIF_MONEP' END ) as DATA_SET_NAME,
	 CurrentlyProcessedFileName as CurrentlyProcessedFileName
From SQ_LCHSA_ETD_REFIT_InstrumentDelta_YYYYMMDD_YYYYMMDDHH24missOut as SQ_LCHSA_ETD_REFIT_InstrumentDelta_YYYYMMDD_YYYYMMDDHH24missOut),

Target_Table_Name_SK_Max_Value AS (
  SELECT
    MAX(GENERATED_SEQ) AS max_generated_seq
  FROM {{ this }}
),

 DSR_EXPTRANSOut as (
	/* transType: "Expression" */
Select 
	SC_SEQ_LD_SA_INSTRUMENT_DELTAOut.(SELECT max_generated_seq FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER() AS GENERATED_SEQ
From SC_SEQ_LD_SA_INSTRUMENT_DELTAOut as SC_SEQ_LD_SA_INSTRUMENT_DELTAOut),

EXPTRANSOut as (
	/* transType: "Expression" */
Select 
	LPAD ( GENERATED_SEQ,
	 9,
	 '0' ) as v_SEQ_LPAD_TO_9,
	 DATEDIFF ( SECOND,
	 TO_TIMESTAMP ( '01/01/1970 00:00:00',
	 'DD-MM-YYYY HH24:MI:SS' ),
	 CURRENT_TIMESTAMP ) as v_EPOC_TIME,
	 v_EPOC_TIME || v_SEQ_LPAD_TO_9 as v_CONCATE_ID,
	 v_CONCATE_ID as ID
From DSR_EXPTRANSOut as DSR_EXPTRANSOut),

EXP_TRIM_details as (
  Select
  	EXP_TRIMOut.O_REPORT_DATE as BUSINESS_DATE,
	 EXP_TRIMOut.O_ISIN_CODE as ISIN_CODE,
	 EXP_TRIMOut.O_DELTA as DELTA,
	 EXP_TRIMOut.ENTITY_NAME as ENTITY_NAME,
	 EXP_TRIMOut.DATA_SET_NAME as DATA_SET_NAME,
	 EXP_TRIMOut.CurrentlyProcessedFileName as CurrentlyProcessedFileName
  From EXP_TRIMOut as EXP_TRIMOut
),
dsJoiner_EXP_PASS_THROUGH0Out as (
	/* transType: "Joiner" */
Select 
	EXPTRANSOut.ID as ID,
	 EXP_TRIM_details.BUSINESS_DATE as BUSINESS_DATE,
	 EXP_TRIM_details.ISIN_CODE as ISIN_CODE,
	 EXP_TRIM_details.DELTA as DELTA,
	 EXP_TRIM_details.ENTITY_NAME as ENTITY_NAME,
	 EXP_TRIM_details.DATA_SET_NAME as DATA_SET_NAME,
	 EXP_TRIM_details.CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
EXPTRANSOut as EXPTRANSOut inner JOIN EXP_TRIM_details as EXP_TRIM_details 
ON
EXP_TRIM_details.jkey = EXPTRANSOut.jkey 
),

EXP_PASS_THROUGHOut as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 dsf_1.ID as BATCH_DETAILS_ID,
	 TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ) as BATCH_START_DATE,
	 BUSINESS_DATE as BUSINESS_DATE,
	 ISIN_CODE as ISIN_CODE,
	 DELTA as DELTA,
	 ENTITY_NAME as ENTITY_NAME,
	 dsf_2.DIMENSION_KEY as ENTITY_ID,
	 DATA_SET_NAME as DATA_SET_NAME,
	 '{{ var("PMWorkflowName") }}' as WORKFLOW_NAME,
	 '{{ var("PMMappingName") }}' as MAPPING_NAME,
	 '{{ var("TARGET_NAME") }}' as TARGET_NAME,
	 'E300_BLANK_FIELD_OR_LKUP_FAIL' as VALIDATION_NAME,
	 'NUMBER' as DATA_TYPE_NUM,
	 'STRING' as DATA_TYPE_STRING,
	 'DATE' as DATA_TYPE_DATE,
	 'Y' as NUM_VAL_Y,
	 'ENTITY_ID' as ATTRIBUTE_NAME_ENTITY_ID,
	 'ISIN_CODE' as ATTRIBUTE_NAME_ISIN_CODE,
	 'DELTA' as ATTRIBUTE_NAME_DELTA,
	 CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT
From dsJoiner_EXP_PASS_THROUGH0Out as dsJoiner_EXP_PASS_THROUGH0Out
LEFT JOIN (
SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME FROM (  SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    BATCH_DETAILS.ID as ID,    BATCH_DETAILS.BATCH_ID as BATCH_ID,    BATCH_DETAILS.TARGET_TABLE_NAME as TARGET_TABLE_NAME,    BATCH_DETAILS.FILE_NAME as FILE_NAME,    BATCH_DETAILS.STATUS as STATUS FROM (SELECT    id,    TARGET_TABLE_NAME,    BATCH_ID,    STATUS,    ACTIVE_FLAG,    BATCH_DETAILS_START_TIME,    FILE_NAME,    RANK() OVER(partition by batch_id,TARGET_TABLE_NAME,FILE_NAME order by BATCH_DETAILS_START_TIME DESC) as RANK FROM    BATCH_DETAILS) BATCH_DETAILS WHERE    RANK= 1 AND   STATUS= 'I' AND   ACTIVE_FLAG= 1 )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}' AND dsf_1.FILE_NAME = '{{ var("FILE_NAME_OVERRIDE") }}'
LEFT JOIN (
SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    ENTITY_DIM.DIMENSION_KEY as DIMENSION_KEY,    ENTITY_DIM.NAME as NAME,    ENTITY_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(ENTITY_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    ENTITY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.NAME = ENTITY_NAME AND dsf_2.EFFECTIVE_DATE <= BUSINESS_DATE AND dsf_2.EXPIRATION_DATE >= BUSINESS_DATE
),

EXP_PASS_THROUGHOut1 as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 dsf_1.ID as BATCH_DETAILS_ID,
	 TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ) as BATCH_START_DATE,
	 BUSINESS_DATE as BUSINESS_DATE,
	 ISIN_CODE as ISIN_CODE,
	 DELTA as DELTA,
	 ENTITY_NAME as ENTITY_NAME,
	 dsf_2.DIMENSION_KEY as ENTITY_ID,
	 DATA_SET_NAME as DATA_SET_NAME,
	 '{{ var("PMWorkflowName") }}' as WORKFLOW_NAME,
	 '{{ var("PMMappingName") }}' as MAPPING_NAME,
	 '{{ var("TARGET_NAME") }}' as TARGET_NAME,
	 'E300_BLANK_FIELD_OR_LKUP_FAIL' as VALIDATION_NAME,
	 'NUMBER' as DATA_TYPE_NUM,
	 'STRING' as DATA_TYPE_STRING,
	 'DATE' as DATA_TYPE_DATE,
	 'Y' as NUM_VAL_Y,
	 'ENTITY_ID' as ATTRIBUTE_NAME_ENTITY_ID,
	 'ISIN_CODE' as ATTRIBUTE_NAME_ISIN_CODE,
	 'DELTA' as ATTRIBUTE_NAME_DELTA,
	 CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT
From dsJoiner_EXP_PASS_THROUGH0Out as dsJoiner_EXP_PASS_THROUGH0Out
LEFT JOIN (
SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME FROM (  SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    BATCH_DETAILS.ID as ID,    BATCH_DETAILS.BATCH_ID as BATCH_ID,    BATCH_DETAILS.TARGET_TABLE_NAME as TARGET_TABLE_NAME,    BATCH_DETAILS.FILE_NAME as FILE_NAME,    BATCH_DETAILS.STATUS as STATUS FROM (SELECT    id,    TARGET_TABLE_NAME,    BATCH_ID,    STATUS,    ACTIVE_FLAG,    BATCH_DETAILS_START_TIME,    FILE_NAME,    RANK() OVER(partition by batch_id,TARGET_TABLE_NAME,FILE_NAME order by BATCH_DETAILS_START_TIME DESC) as RANK FROM    BATCH_DETAILS) BATCH_DETAILS WHERE    RANK= 1 AND   STATUS= 'I' AND   ACTIVE_FLAG= 1 )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}' AND dsf_1.FILE_NAME = '{{ var("FILE_NAME_OVERRIDE") }}'
LEFT JOIN (
SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    ENTITY_DIM.DIMENSION_KEY as DIMENSION_KEY,    ENTITY_DIM.NAME as NAME,    ENTITY_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(ENTITY_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    ENTITY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.NAME = ENTITY_NAME AND dsf_2.EFFECTIVE_DATE <= BUSINESS_DATE AND dsf_2.EXPIRATION_DATE >= BUSINESS_DATE
),

EXP_PASS_THROUGHOut2 as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 dsf_1.ID as BATCH_DETAILS_ID,
	 TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ) as BATCH_START_DATE,
	 BUSINESS_DATE as BUSINESS_DATE,
	 ISIN_CODE as ISIN_CODE,
	 DELTA as DELTA,
	 ENTITY_NAME as ENTITY_NAME,
	 dsf_2.DIMENSION_KEY as ENTITY_ID,
	 DATA_SET_NAME as DATA_SET_NAME,
	 '{{ var("PMWorkflowName") }}' as WORKFLOW_NAME,
	 '{{ var("PMMappingName") }}' as MAPPING_NAME,
	 '{{ var("TARGET_NAME") }}' as TARGET_NAME,
	 'E300_BLANK_FIELD_OR_LKUP_FAIL' as VALIDATION_NAME,
	 'NUMBER' as DATA_TYPE_NUM,
	 'STRING' as DATA_TYPE_STRING,
	 'DATE' as DATA_TYPE_DATE,
	 'Y' as NUM_VAL_Y,
	 'ENTITY_ID' as ATTRIBUTE_NAME_ENTITY_ID,
	 'ISIN_CODE' as ATTRIBUTE_NAME_ISIN_CODE,
	 'DELTA' as ATTRIBUTE_NAME_DELTA,
	 CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT
From dsJoiner_EXP_PASS_THROUGH0Out as dsJoiner_EXP_PASS_THROUGH0Out
LEFT JOIN (
SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME FROM (  SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    BATCH_DETAILS.ID as ID,    BATCH_DETAILS.BATCH_ID as BATCH_ID,    BATCH_DETAILS.TARGET_TABLE_NAME as TARGET_TABLE_NAME,    BATCH_DETAILS.FILE_NAME as FILE_NAME,    BATCH_DETAILS.STATUS as STATUS FROM (SELECT    id,    TARGET_TABLE_NAME,    BATCH_ID,    STATUS,    ACTIVE_FLAG,    BATCH_DETAILS_START_TIME,    FILE_NAME,    RANK() OVER(partition by batch_id,TARGET_TABLE_NAME,FILE_NAME order by BATCH_DETAILS_START_TIME DESC) as RANK FROM    BATCH_DETAILS) BATCH_DETAILS WHERE    RANK= 1 AND   STATUS= 'I' AND   ACTIVE_FLAG= 1 )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}' AND dsf_1.FILE_NAME = '{{ var("FILE_NAME_OVERRIDE") }}'
LEFT JOIN (
SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    ENTITY_DIM.DIMENSION_KEY as DIMENSION_KEY,    ENTITY_DIM.NAME as NAME,    ENTITY_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(ENTITY_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    ENTITY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.NAME = ENTITY_NAME AND dsf_2.EFFECTIVE_DATE <= BUSINESS_DATE AND dsf_2.EXPIRATION_DATE >= BUSINESS_DATE
),

EXP_PASS_THROUGHOut3 as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 dsf_1.ID as BATCH_DETAILS_ID,
	 TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ) as BATCH_START_DATE,
	 BUSINESS_DATE as BUSINESS_DATE,
	 ISIN_CODE as ISIN_CODE,
	 DELTA as DELTA,
	 ENTITY_NAME as ENTITY_NAME,
	 dsf_2.DIMENSION_KEY as ENTITY_ID,
	 DATA_SET_NAME as DATA_SET_NAME,
	 '{{ var("PMWorkflowName") }}' as WORKFLOW_NAME,
	 '{{ var("PMMappingName") }}' as MAPPING_NAME,
	 '{{ var("TARGET_NAME") }}' as TARGET_NAME,
	 'E300_BLANK_FIELD_OR_LKUP_FAIL' as VALIDATION_NAME,
	 'NUMBER' as DATA_TYPE_NUM,
	 'STRING' as DATA_TYPE_STRING,
	 'DATE' as DATA_TYPE_DATE,
	 'Y' as NUM_VAL_Y,
	 'ENTITY_ID' as ATTRIBUTE_NAME_ENTITY_ID,
	 'ISIN_CODE' as ATTRIBUTE_NAME_ISIN_CODE,
	 'DELTA' as ATTRIBUTE_NAME_DELTA,
	 CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT
From dsJoiner_EXP_PASS_THROUGH0Out as dsJoiner_EXP_PASS_THROUGH0Out
LEFT JOIN (
SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME FROM (  SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    BATCH_DETAILS.ID as ID,    BATCH_DETAILS.BATCH_ID as BATCH_ID,    BATCH_DETAILS.TARGET_TABLE_NAME as TARGET_TABLE_NAME,    BATCH_DETAILS.FILE_NAME as FILE_NAME,    BATCH_DETAILS.STATUS as STATUS FROM (SELECT    id,    TARGET_TABLE_NAME,    BATCH_ID,    STATUS,    ACTIVE_FLAG,    BATCH_DETAILS_START_TIME,    FILE_NAME,    RANK() OVER(partition by batch_id,TARGET_TABLE_NAME,FILE_NAME order by BATCH_DETAILS_START_TIME DESC) as RANK FROM    BATCH_DETAILS) BATCH_DETAILS WHERE    RANK= 1 AND   STATUS= 'I' AND   ACTIVE_FLAG= 1 )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}' AND dsf_1.FILE_NAME = '{{ var("FILE_NAME_OVERRIDE") }}'
LEFT JOIN (
SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    ENTITY_DIM.DIMENSION_KEY as DIMENSION_KEY,    ENTITY_DIM.NAME as NAME,    ENTITY_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(ENTITY_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    ENTITY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.NAME = ENTITY_NAME AND dsf_2.EFFECTIVE_DATE <= BUSINESS_DATE AND dsf_2.EXPIRATION_DATE >= BUSINESS_DATE
),

EXP_PASS_THROUGHOut4 as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 dsf_1.ID as BATCH_DETAILS_ID,
	 TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ) as BATCH_START_DATE,
	 BUSINESS_DATE as BUSINESS_DATE,
	 ISIN_CODE as ISIN_CODE,
	 DELTA as DELTA,
	 ENTITY_NAME as ENTITY_NAME,
	 dsf_2.DIMENSION_KEY as ENTITY_ID,
	 DATA_SET_NAME as DATA_SET_NAME,
	 '{{ var("PMWorkflowName") }}' as WORKFLOW_NAME,
	 '{{ var("PMMappingName") }}' as MAPPING_NAME,
	 '{{ var("TARGET_NAME") }}' as TARGET_NAME,
	 'E300_BLANK_FIELD_OR_LKUP_FAIL' as VALIDATION_NAME,
	 'NUMBER' as DATA_TYPE_NUM,
	 'STRING' as DATA_TYPE_STRING,
	 'DATE' as DATA_TYPE_DATE,
	 'Y' as NUM_VAL_Y,
	 'ENTITY_ID' as ATTRIBUTE_NAME_ENTITY_ID,
	 'ISIN_CODE' as ATTRIBUTE_NAME_ISIN_CODE,
	 'DELTA' as ATTRIBUTE_NAME_DELTA,
	 CurrentlyProcessedFileName as CurrentlyProcessedFileName,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT
From dsJoiner_EXP_PASS_THROUGH0Out as dsJoiner_EXP_PASS_THROUGH0Out
LEFT JOIN (
SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME FROM (  SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    BATCH_DETAILS.ID as ID,    BATCH_DETAILS.BATCH_ID as BATCH_ID,    BATCH_DETAILS.TARGET_TABLE_NAME as TARGET_TABLE_NAME,    BATCH_DETAILS.FILE_NAME as FILE_NAME,    BATCH_DETAILS.STATUS as STATUS FROM (SELECT    id,    TARGET_TABLE_NAME,    BATCH_ID,    STATUS,    ACTIVE_FLAG,    BATCH_DETAILS_START_TIME,    FILE_NAME,    RANK() OVER(partition by batch_id,TARGET_TABLE_NAME,FILE_NAME order by BATCH_DETAILS_START_TIME DESC) as RANK FROM    BATCH_DETAILS) BATCH_DETAILS WHERE    RANK= 1 AND   STATUS= 'I' AND   ACTIVE_FLAG= 1 )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}' AND dsf_1.FILE_NAME = '{{ var("FILE_NAME_OVERRIDE") }}'
LEFT JOIN (
SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT DIMENSION_KEY, NAME, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    ENTITY_DIM.DIMENSION_KEY as DIMENSION_KEY,    ENTITY_DIM.NAME as NAME,    ENTITY_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(ENTITY_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    ENTITY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.NAME = ENTITY_NAME AND dsf_2.EFFECTIVE_DATE <= BUSINESS_DATE AND dsf_2.EXPIRATION_DATE >= BUSINESS_DATE
),

DSR_EXP_LDSA_VALIDATION_CHECKER_DELTAOut as (
	/* transType: "Expression" */
Select 
	EXP_PASS_THROUGHOut3.VALIDATION_NAME as in_VALIDATION_NAME,
	 EXP_PASS_THROUGHOut3.ATTRIBUTE_NAME_DELTA as in_ATTRIBUTE_NAME,
	 EXP_PASS_THROUGHOut3.DATA_TYPE_NUM as in_DATA_TYPE,
	 EXP_PASS_THROUGHOut3.DELTA as in_ATTRIBUTE_TO_BE_VALIDATED_NUM
From EXP_PASS_THROUGHOut as EXP_PASS_THROUGHOut),

DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut as (
	/* transType: "Expression" */
Select 
	EXP_PASS_THROUGHOut.VALIDATION_NAME as in_VALIDATION_NAME,
	 EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_ENTITY_ID as in_ATTRIBUTE_NAME,
	 EXP_PASS_THROUGHOut.DATA_TYPE_NUM as in_DATA_TYPE,
	 EXP_PASS_THROUGHOut.ENTITY_ID as in_ATTRIBUTE_TO_BE_VALIDATED_NUM
From EXP_PASS_THROUGHOut as EXP_PASS_THROUGHOut),

DSR_EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut as (
	/* transType: "Expression" */
Select 
	EXP_PASS_THROUGHOut2.VALIDATION_NAME as in_VALIDATION_NAME,
	 EXP_PASS_THROUGHOut2.ATTRIBUTE_NAME_ISIN_CODE as in_ATTRIBUTE_NAME,
	 EXP_PASS_THROUGHOut2.DATA_TYPE_STRING as in_DATA_TYPE,
	 EXP_PASS_THROUGHOut2.ISIN_CODE as in_ATTRIBUTE_TO_BE_VALIDATED_STR
From EXP_PASS_THROUGHOut as EXP_PASS_THROUGHOut),

EXP_LDSA_VALIDATION_CHECKER_DELTAOut as (
	/* transType: "Expression" */
Select 
	'{{ var("TARGET_NAME") }}' as TARGET_TABLE_NAME,
	 dsf_1.ACTIVE_Y_N_STR_VL as v_VALIDATION_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ACTIVE END ) as v_VALIDATION_ACTIVE_NVL,
	 dsf_2.ACTIVE_Y_N as v_VALIDATION_ON_TABLE_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ON_TABLE_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ON_TABLE_ACTIVE END ) as v_VALIDATION_ON_TABLE_ACTIVE_NVL,
	 ( CASE WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_DATE,
	 ( CASE WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_STR,
	 ( CASE WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL OR ( ( CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END ) = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2 ) THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_NUM,
	 ( CASE WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P' END ) as v_VALIDATION_PASS_FAIL,
	 v_VALIDATION_PASS_FAIL as o_VALIDATION_PASS_FAIL,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE ELSE NULL END ) as v_ERROR_MESSAGE_DATE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR ELSE NULL END ) as v_ERROR_MESSAGE_STR,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM ELSE NULL END ) as v_ERROR_MESSAGE_NUM,
	 v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM as o_COMBINED_ERROR_MESSAGE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as o_ERROR_SEVERITY
From DSR_EXP_LDSA_VALIDATION_CHECKER_DELTAOut as DSR_EXP_LDSA_VALIDATION_CHECKER_DELTAOut
LEFT JOIN (
SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
LEFT JOIN (
SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut as (
	/* transType: "Expression" */
Select 
	'{{ var("TARGET_NAME") }}' as TARGET_TABLE_NAME,
	 dsf_1.ACTIVE_Y_N_STR_VL as v_VALIDATION_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ACTIVE END ) as v_VALIDATION_ACTIVE_NVL,
	 dsf_2.ACTIVE_Y_N as v_VALIDATION_ON_TABLE_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ON_TABLE_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ON_TABLE_ACTIVE END ) as v_VALIDATION_ON_TABLE_ACTIVE_NVL,
	 ( CASE WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_DATE,
	 ( CASE WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_STR,
	 ( CASE WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL OR ( ( CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END ) = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2 ) THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_NUM,
	 ( CASE WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P' END ) as v_VALIDATION_PASS_FAIL,
	 v_VALIDATION_PASS_FAIL as o_VALIDATION_PASS_FAIL,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE ELSE NULL END ) as v_ERROR_MESSAGE_DATE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR ELSE NULL END ) as v_ERROR_MESSAGE_STR,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM ELSE NULL END ) as v_ERROR_MESSAGE_NUM,
	 v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM as o_COMBINED_ERROR_MESSAGE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as o_ERROR_SEVERITY
From DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut as DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut
LEFT JOIN (
SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
LEFT JOIN (
SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut as (
	/* transType: "Expression" */
Select 
	'{{ var("TARGET_NAME") }}' as TARGET_TABLE_NAME,
	 dsf_1.ACTIVE_Y_N_STR_VL as v_VALIDATION_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ACTIVE END ) as v_VALIDATION_ACTIVE_NVL,
	 dsf_2.ACTIVE_Y_N as v_VALIDATION_ON_TABLE_ACTIVE,
	 ( CASE WHEN v_VALIDATION_ON_TABLE_ACTIVE IS NULL THEN 'N' ELSE v_VALIDATION_ON_TABLE_ACTIVE END ) as v_VALIDATION_ON_TABLE_ACTIVE_NVL,
	 ( CASE WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_DATE,
	 ( CASE WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_STR,
	 ( CASE WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN ( CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL OR ( ( CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END ) = 'Y' AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2 ) THEN 'F' ELSE 'P' END ) ELSE 'P' END ) as v_NULL_CHECK_NUM,
	 ( CASE WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P' END ) as v_VALIDATION_PASS_FAIL,
	 v_VALIDATION_PASS_FAIL as o_VALIDATION_PASS_FAIL,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE ELSE NULL END ) as v_ERROR_MESSAGE_DATE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR ELSE NULL END ) as v_ERROR_MESSAGE_STR,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER' THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM ELSE NULL END ) as v_ERROR_MESSAGE_NUM,
	 v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM as o_COMBINED_ERROR_MESSAGE,
	 ( CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as o_ERROR_SEVERITY
From DSR_EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut as DSR_EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut
LEFT JOIN (
SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N_STR_VL, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
LEFT JOIN (
SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ACTIVE_Y_N, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_DELTA_master as (
  Select
  	EXP_LDSA_VALIDATION_CHECKER_DELTAOut.o_VALIDATION_PASS_FAIL as DELTA_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_DELTAOut.o_COMBINED_ERROR_MESSAGE as DELTA_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_DELTAOut.o_ERROR_SEVERITY as DELTA_ERROR_SEVERITY
  From EXP_LDSA_VALIDATION_CHECKER_DELTAOut as EXP_LDSA_VALIDATION_CHECKER_DELTAOut
),

EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details as (
  Select
  	EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_VALIDATION_PASS_FAIL as ENTITY_ID_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_COMBINED_ERROR_MESSAGE as ENTITY_ID_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_ERROR_SEVERITY as ENTITY_ID_ERROR_SEVERITY
  From EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut as EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut
),

EXP_PASS_THROUGH_details as (
  Select
  	EXP_PASS_THROUGHOut.ID as ID,
	 EXP_PASS_THROUGHOut.BATCH_ID as BATCH_ID,
	 EXP_PASS_THROUGHOut.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_PASS_THROUGHOut.BATCH_START_DATE as BATCH_START_DATE,
	 EXP_PASS_THROUGHOut.BUSINESS_DATE as BUSINESS_DATE,
	 EXP_PASS_THROUGHOut.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_PASS_THROUGHOut.MAPPING_NAME as MAPPING_NAME,
	 EXP_PASS_THROUGHOut.TARGET_NAME as TARGET_NAME,
	 EXP_PASS_THROUGHOut.VALIDATION_NAME as VALIDATION_NAME,
	 EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_ENTITY_ID as ENTITY_ID_ATTRIBUTE_NAME,
	 EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_ISIN_CODE as ISIN_CODE_ATTRIBUTE_NAME,
	 EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_DELTA as DELTA_ATTRIBUTE_NAME
  From EXP_PASS_THROUGHOut as EXP_PASS_THROUGHOut
),

EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details as (
  Select
  	EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut.o_VALIDATION_PASS_FAIL as ISIN_CODE_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut.o_COMBINED_ERROR_MESSAGE as ISIN_CODE_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut.o_ERROR_SEVERITY as ISIN_CODE_ERROR_SEVERITY
  From EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut as EXP_LDSA_VALIDATION_CHECKER_ISIN_CODEOut
),
dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out as (
	/* transType: "Joiner" */
Select 
	EXP_PASS_THROUGH_details.ID as ID,
	 EXP_PASS_THROUGH_details.BATCH_ID as BATCH_ID,
	 EXP_PASS_THROUGH_details.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_PASS_THROUGH_details.BATCH_START_DATE as BATCH_START_DATE,
	 EXP_PASS_THROUGH_details.BUSINESS_DATE as BUSINESS_DATE,
	 EXP_PASS_THROUGH_details.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_PASS_THROUGH_details.MAPPING_NAME as MAPPING_NAME,
	 EXP_PASS_THROUGH_details.TARGET_NAME as TARGET_NAME,
	 EXP_PASS_THROUGH_details.VALIDATION_NAME as VALIDATION_NAME,
	 EXP_PASS_THROUGH_details.ENTITY_ID_ATTRIBUTE_NAME as ENTITY_ID_ATTRIBUTE_NAME,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_VALIDATION_PASS_FAIL as ENTITY_ID_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_ERROR_MESSAGE as ENTITY_ID_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_ERROR_SEVERITY as ENTITY_ID_ERROR_SEVERITY,
	 EXP_PASS_THROUGH_details.ISIN_CODE_ATTRIBUTE_NAME as ISIN_CODE_ATTRIBUTE_NAME,
	 EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details.ISIN_CODE_VALIDATION_PASS_FAIL as ISIN_CODE_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details.ISIN_CODE_ERROR_MESSAGE as ISIN_CODE_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details.ISIN_CODE_ERROR_SEVERITY as ISIN_CODE_ERROR_SEVERITY,
	 EXP_PASS_THROUGH_details.DELTA_ATTRIBUTE_NAME as DELTA_ATTRIBUTE_NAME,
	 EXP_LDSA_VALIDATION_CHECKER_DELTA_master.DELTA_VALIDATION_PASS_FAIL as DELTA_VALIDATION_PASS_FAIL,
	 EXP_LDSA_VALIDATION_CHECKER_DELTA_master.DELTA_ERROR_MESSAGE as DELTA_ERROR_MESSAGE,
	 EXP_LDSA_VALIDATION_CHECKER_DELTA_master.DELTA_ERROR_SEVERITY as DELTA_ERROR_SEVERITY,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
EXP_LDSA_VALIDATION_CHECKER_DELTA_master as EXP_LDSA_VALIDATION_CHECKER_DELTA_master INNER JOIN EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details as EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details 
ON
EXP_LDSA_VALIDATION_CHECKER_DELTA_master.jkey = EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.jkey
 INNER JOIN EXP_PASS_THROUGHOut4 as EXP_PASS_THROUGHOut4 
ON
EXP_LDSA_VALIDATION_CHECKER_DELTA_master.jkey = EXP_PASS_THROUGHOut4.jkey
 INNER JOIN EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details as EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details 
ON
EXP_LDSA_VALIDATION_CHECKER_DELTA_master.jkey = EXP_LDSA_VALIDATION_CHECKER_ISIN_CODE_details.jkey
 
),

EXP_CONSOLIDATE_VALIDATIONSOut as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 BATCH_ID as BATCH_ID,
	 BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 BATCH_START_DATE as BATCH_START_DATE,
	 BUSINESS_DATE as BUSINESS_DATE,
	 WORKFLOW_NAME as WORKFLOW_NAME,
	 MAPPING_NAME as MAPPING_NAME,
	 TARGET_NAME as TARGET_NAME,
	 VALIDATION_NAME as VALIDATION_NAME,
	 '{{ var("FILE_NAME") }}' as FILE_NAME,
	 'FILE NAME:' || FILE_NAME || '/' || 'BUSINESS_DATE:' || BUSINESS_DATE || '/' as v_ERROR_MESSAGE,
	 ENTITY_ID_ATTRIBUTE_NAME as ENTITY_ID_ATTRIBUTE_NAME,
	 ENTITY_ID_VALIDATION_PASS_FAIL as ENTITY_ID_VALIDATION_PASS_FAIL,
	 ENTITY_ID_ERROR_MESSAGE as ENTITY_ID_ERROR_MESSAGE,
	 ENTITY_ID_ERROR_SEVERITY as ENTITY_ID_ERROR_SEVERITY,
	 v_ERROR_MESSAGE || ENTITY_ID_ERROR_MESSAGE as O_ENTITY_ID_ERROR_MESSAGE,
	 ISIN_CODE_ATTRIBUTE_NAME as ISIN_CODE_ATTRIBUTE_NAME,
	 ISIN_CODE_VALIDATION_PASS_FAIL as ISIN_CODE_VALIDATION_PASS_FAIL,
	 ISIN_CODE_ERROR_MESSAGE as ISIN_CODE_ERROR_MESSAGE,
	 ISIN_CODE_ERROR_SEVERITY as ISIN_CODE_ERROR_SEVERITY,
	 v_ERROR_MESSAGE || ISIN_CODE_ERROR_MESSAGE as O_ISIN_CODE_ERROR_MESSAGE,
	 DELTA_ATTRIBUTE_NAME as DELTA_ATTRIBUTE_NAME,
	 DELTA_VALIDATION_PASS_FAIL as DELTA_VALIDATION_PASS_FAIL,
	 DELTA_ERROR_MESSAGE as DELTA_ERROR_MESSAGE,
	 DELTA_ERROR_SEVERITY as DELTA_ERROR_SEVERITY,
	 v_ERROR_MESSAGE || DELTA_ERROR_MESSAGE as O_DELTA_ERROR_MESSAGE,
	 ( CASE WHEN ENTITY_ID_VALIDATION_PASS_FAIL = 'F' OR ISIN_CODE_VALIDATION_PASS_FAIL = 'F' OR DELTA_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END ) as MD_ERROR_IND
From dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out as dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out),

dsJoiner_SC_LD_SA_INSTRUMENT_DELTA0Out as (
	/* transType: "Joiner" */
Select 
	EXP_PASS_THROUGHOut1.ID as ID,
	 EXP_PASS_THROUGHOut1.BATCH_ID as BATCH_ID,
	 EXP_PASS_THROUGHOut1.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_PASS_THROUGHOut1.BUSINESS_DATE as BUSINESS_DATE,
	 EXP_PASS_THROUGHOut1.BATCH_START_DATE as BATCH_START_DATE,
	 EXP_PASS_THROUGHOut1.ENTITY_ID as ENTITY_ID,
	 EXP_PASS_THROUGHOut1.ISIN_CODE as ISIN_CODE,
	 EXP_PASS_THROUGHOut1.DELTA as DELTA,
	 EXP_CONSOLIDATE_VALIDATIONSOut.MD_ERROR_IND as MD_ERROR_IND,
	 EXP_PASS_THROUGHOut1.DATA_SET_NAME as DATA_SET_NAME,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
EXP_PASS_THROUGHOut1 as EXP_PASS_THROUGHOut1 inner JOIN EXP_CONSOLIDATE_VALIDATIONSOut as EXP_CONSOLIDATE_VALIDATIONSOut 
ON
EXP_CONSOLIDATE_VALIDATIONSOut.jkey = EXP_PASS_THROUGHOut1.jkey 
)

Select 
	ID as ID,
	BATCH_ID as BATCH_ID,
	BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	BUSINESS_DATE as BUSINESS_DATE,
	BATCH_START_DATE as BATCH_START_DATE,
	ENTITY_ID as ENTITY_ID,
	ISIN_CODE as ISIN_CODE,
	DELTA as DELTA,
	MD_ERROR_IND as MD_ERROR_IND,
	DATA_SET_NAME as DATA_SET_NAME 
From dsJoiner_SC_LD_SA_INSTRUMENT_DELTA0Out as dsJoiner_SC_LD_SA_INSTRUMENT_DELTA0Out