{{ 
    config(
        materialized='incremental',
        alias='PROCESS_ERROR_DETAILS',
        schema='LDSA_SHARED',
        pre_hook="",
        post_hook="",
        incremental_strategy='append'
    )
}}

WITH SQ_SC_LCHSA_ETD_Paricipant_YYYYmmdd_YYYYmmddHH24missOut AS (
    SELECT
        REPORT_DATE,
        TMF_CODE,
        PARTICIPANT_ROLE,
        PARTICIPANT_LEI,
        PARTICIPANT_NAME,
        COUNTRY_CODE,
        EEA_INDICATOR,
        CORPORATE_SECTOR,
        CurrentlyProcessedFileName
    FROM {{ source('FlatFile_catalog_1', 'LCHSA_ETD_Paricipant_YYYYmmdd_YYYYmmddHH24miss') }}
),

EXP_TRIMOut AS (
    SELECT
        REPORT_DATE AS REPORT_DATE,
        CASE
            WHEN REPORT_DATE IS NOT NULL THEN TO_DATE(LTRIM(RTRIM(REPORT_DATE)), 'DD/MM/YYYY')
            ELSE NULL
        END AS O_REPORT_DATE,
        RTRIM(LTRIM(TMF_CODE)) AS O_TMF_CODE,
        RTRIM(LTRIM(PARTICIPANT_ROLE)) AS O_PARTICIPANT_ROLE,
        RTRIM(LTRIM(PARTICIPANT_LEI)) AS O_PARTICIPANT_LEI,
        RTRIM(LTRIM(PARTICIPANT_NAME)) AS O_PARTICIPANT_NAME,
        RTRIM(LTRIM(COUNTRY_CODE)) AS O_COUNTRY_CODE,
        RTRIM(LTRIM(EEA_INDICATOR)) AS O_EEA_INDICATOR,
        RTRIM(LTRIM(CORPORATE_SECTOR)) AS O_CORPORATE_SECTOR,
        CurrentlyProcessedFileName AS CurrentlyProcessedFileName,
        'LCH.SA' AS O_ENTITY_NAME,
        1 AS ENABLE_IND
    FROM SQ_SC_LCHSA_ETD_Paricipant_YYYYmmdd_YYYYmmddHH24missOut
),

Target_Table_Name_SK_Max_Value AS (
    SELECT
        MAX(GENERATED_SEQ) AS max_generated_seq
    FROM {{ this }}
),

DSR_SC_EXP_GENERATOROut AS (
    SELECT
        ( (SELECT max_generated_seq FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) ) AS GENERATED_SEQ
    FROM SC_SEQ_LD_SA_PARTICIPANTOut
),

DSR_EXP_PASS_THROUGHOut AS (
    SELECT
        EXP_TRIMOut.O_REPORT_DATE AS BUSINESS_DATE,
        EXP_TRIMOut.O_TMF_CODE AS TMF_CODE,
        EXP_TRIMOut.O_PARTICIPANT_ROLE AS PARTICIPANT_ROLE,
        EXP_TRIMOut.O_PARTICIPANT_LEI AS PARTICIPANT_LEI,
        EXP_TRIMOut.O_PARTICIPANT_NAME AS PARTICIPANT_NAME,
        EXP_TRIMOut.O_COUNTRY_CODE AS COUNTRY_CODE,
        EXP_TRIMOut.O_EEA_INDICATOR AS EEA_INDICATOR,
        EXP_TRIMOut.O_CORPORATE_SECTOR AS CORPORATE_SECTOR,
        EXP_TRIMOut.ENABLE_IND AS ENABLE_IND,
        EXP_TRIMOut.O_ENTITY_NAME AS ENTITY_NAME,
        EXP_TRIMOut.CurrentlyProcessedFileName AS CurrentlyProcessedFileName
    FROM EXP_TRIMOut
),

SC_EXP_GENERATOROut AS (
    SELECT
        LPAD(GENERATED_SEQ, 9, '0') AS v_SEQ_LPAD_TO_9,
        DATEDIFF(
            SECOND,
            TO_TIMESTAMP('01/01/1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS'),
            CURRENT_TIMESTAMP()
        ) AS v_EPOC_TIME,
        v_EPOC_TIME || v_SEQ_LPAD_TO_9 AS v_CONCATE_ID,
        v_CONCATE_ID AS ID
    FROM DSR_SC_EXP_GENERATOROut
),

EXP_PASS_THROUGHOut AS (
    SELECT
        '{{ var("BATCH_ID") }}' AS BATCH_ID,
        dsf_1.ID AS O_BATCH_DETAILS_ID,
        BUSINESS_DATE AS BUSINESS_DATE,
        TO_TIMESTAMP('{{ var("BATCH_START_DATE") }}', 'DD-MON-YYYY HH24:MI:SS') AS O_BATCH_START_DATE,
        '{{ var("PMWorkflowName", "") }}' AS WORKFLOW_NAME,
        '{{ var("PMMappingName", "") }}' AS MAPPING_NAME,
        '{{ var("TARGET_NAME") }}' AS TARGET_NAME,
        TMF_CODE AS TMF_CODE,
        PARTICIPANT_ROLE AS PARTICIPANT_ROLE,
        PARTICIPANT_LEI AS PARTICIPANT_LEI,
        PARTICIPANT_NAME AS PARTICIPANT_NAME,
        COUNTRY_CODE AS COUNTRY_CODE,
        EEA_INDICATOR AS EEA_INDICATOR,
        CORPORATE_SECTOR AS CORPORATE_SECTOR,
        ENABLE_IND AS ENABLE_IND,
        ENTITY_NAME AS ENTITY_NAME,
        CurrentlyProcessedFileName AS CurrentlyProcessedFileName,
        'Y' AS NUM_FLAG_Y,
        CASE
            WHEN ENABLE_IND IS NULL OR ENABLE_IND = 0 THEN -9999
            ELSE CASE WHEN dsf_2.DIMENSION_KEY IS NOT NULL THEN dsf_2.DIMENSION_KEY ELSE NULL END
        END AS ENTITY_ID,
        'STRING' AS DATA_TYPE_STRING,
        'DATE' AS DATA_TYPE_DATE,
        'NUMBER' AS DATA_TYPE_NUMBER,
        v_TOT_REC_COUNT + 1 AS v_TOT_REC_COUNT,
        'E300_BLANK_FIELD_OR_LKUP_FAIL' AS VALIDATION_NAME,
        'ENTITY_ID' AS ATTRIBUTE_NAME_1,
        'TMF_CODE' AS ATTRIBUTE_NAME_2,
        'PARTICIPANT_ROLE' AS ATTRIBUTE_NAME_3,
        CASE WHEN PARTICIPANT_ROLE = 'TMF' THEN NULL ELSE 'PARTICIPANT_LEI' END AS ATTRIBUTE_NAME_4,
        'PARTICIPANT_NAME' AS ATTRIBUTE_NAME_5,
        'COUNTRY_CODE' AS ATTRIBUTE_NAME_6,
        'EEA_INDICATOR' AS ATTRIBUTE_NAME_7
    FROM DSR_EXP_PASS_THROUGHOut
    LEFT JOIN (
        SELECT
            ID,
            BATCH_ID,
            TARGET_TABLE_NAME,
            FILE_NAME
        FROM (
            SELECT
                ID,
                BATCH_ID,
                TARGET_TABLE_NAME,
                FILE_NAME,
                ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ID,
                    BATCH_ID,
                    TARGET_TABLE_NAME,
                    FILE_NAME,
                    ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        BATCH_DETAILS.ID AS ID,
                        BATCH_DETAILS.BATCH_ID AS BATCH_ID,
                        BATCH_DETAILS.TARGET_TABLE_NAME AS TARGET_TABLE_NAME,
                        BATCH_DETAILS.FILE_NAME AS FILE_NAME,
                        BATCH_DETAILS.STATUS AS STATUS
                    FROM (
                        SELECT
                            id,
                            TARGET_TABLE_NAME,
                            BATCH_ID,
                            STATUS,
                            ACTIVE_FLAG,
                            BATCH_DETAILS_START_TIME,
                            FILE_NAME,
                            RANK() OVER (PARTITION BY batch_id, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_DETAILS_START_TIME DESC) AS RANK
                        FROM BATCH_DETAILS
                    ) BATCH_DETAILS
                    WHERE RANK = 1
                      AND STATUS = 'I'
                      AND ACTIVE_FLAG = 1
                )
            ) lkp_inner
        ) lkp_outer
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}'
       AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME") }}'
       AND dsf_1.FILE_NAME = '{{ var("FILE_NAME_OVERRIDE") }}'
    LEFT JOIN (
        SELECT
            DIMENSION_KEY,
            NAME,
            EFFECTIVE_DATE,
            EXPIRATION_DATE
        FROM (
            SELECT
                DIMENSION_KEY,
                NAME,
                EFFECTIVE_DATE,
                EXPIRATION_DATE,
                ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    DIMENSION_KEY,
                    NAME,
                    EFFECTIVE_DATE,
                    EXPIRATION_DATE,
                    ROW_NUMBER() OVER (PARTITION BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY NAME, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        ENTITY_DIM.DIMENSION_KEY AS DIMENSION_KEY,
                        ENTITY_DIM.NAME AS NAME,
                        ENTITY_DIM.EFFECTIVE_DATE AS EFFECTIVE_DATE,
                        NVL(ENTITY_DIM.EXPIRATION_DATE, TO_DATE('31-DEC-2099', 'DD-MON-YYYY')) AS EXPIRATION_DATE
                    FROM ENTITY_DIM
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.NAME = ENTITY_NAME
       AND dsf_2.EFFECTIVE_DATE <= BUSINESS_DATE
       AND dsf_2.EXPIRATION_DATE >= BUSINESS_DATE
),

DSR_EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1Out AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_4 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.PARTICIPANT_LEI AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOROut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_7 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.EEA_INDICATOR AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAMEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_5 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.PARTICIPANT_NAME AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_6 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.COUNTRY_CODE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_1 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_NUMBER AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.NUM_FLAG_Y AS in_DIMENSION_KEY_FLAG,
        EXP_PASS_THROUGHOut.ENTITY_ID AS in_ATTRIBUTE_TO_BE_VALIDATED_NUM
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_PART_ROLEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_3 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.PARTICIPANT_ROLE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

DSR_EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut AS (
    SELECT
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS in_VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_2 AS in_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.DATA_TYPE_STRING AS in_DATA_TYPE,
        EXP_PASS_THROUGHOut.TMF_CODE AS in_ATTRIBUTE_TO_BE_VALIDATED_STR
    FROM EXP_PASS_THROUGHOut
),

EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1Out AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        CASE WHEN dsf_1.ACTIVE_Y_N_STR_VL IS NULL THEN 'N' ELSE dsf_1.ACTIVE_Y_N_STR_VL END AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        CASE WHEN dsf_2.ACTIVE_Y_N IS NULL THEN 'N' ELSE dsf_2.ACTIVE_Y_N END AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE
                    WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                         OR (CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END) = 'Y'
                            AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2
                    THEN 'F' ELSE 'P'
                END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1Out
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N_STR_VL,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N_STR_VL,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N_STR_VL,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.ACTIVE_Y_N AS ACTIVE_Y_N_STR_VL,
                        APPLICATION_VARIABLES.STRING_VALUE AS STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER'
                      AND ACTIVE_Y_N = 'Y'
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N,
            VARIABLE_NAME,
            STRING_VALUE,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N,
                VARIABLE_NAME,
                STRING_VALUE,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N,
                    VARIABLE_NAME,
                    STRING_VALUE,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
       AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
       AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOROut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        CASE WHEN dsf_1.ACTIVE_Y_N_STR_VL IS NULL THEN 'N' ELSE dsf_1.ACTIVE_Y_N_STR_VL END AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        CASE WHEN dsf_2.ACTIVE_Y_N IS NULL THEN 'N' ELSE dsf_2.ACTIVE_Y_N END AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE
                    WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                         OR (CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END) = 'Y'
                            AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2
                    THEN 'F' ELSE 'P'
                END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOROut
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N_STR_VL,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N_STR_VL,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N_STR_VL,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.ACTIVE_Y_N AS ACTIVE_Y_N_STR_VL,
                        APPLICATION_VARIABLES.STRING_VALUE AS STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER'
                      AND ACTIVE_Y_N = 'Y'
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N,
            VARIABLE_NAME,
            STRING_VALUE,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N,
                VARIABLE_NAME,
                STRING_VALUE,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N,
                    VARIABLE_NAME,
                    STRING_VALUE,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
       AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
       AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAMEOut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        CASE WHEN dsf_1.ACTIVE_Y_N_STR_VL IS NULL THEN 'N' ELSE dsf_1.ACTIVE_Y_N_STR_VL END AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        CASE WHEN dsf_2.ACTIVE_Y_N IS NULL THEN 'N' ELSE dsf_2.ACTIVE_Y_N END AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE
                    WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                         OR (CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END) = 'Y'
                            AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2
                    THEN 'F' ELSE 'P'
                END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAMEOut
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N_STR_VL,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N_STR_VL,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N_STR_VL,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.ACTIVE_Y_N AS ACTIVE_Y_N_STR_VL,
                        APPLICATION_VARIABLES.STRING_VALUE AS STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER'
                      AND ACTIVE_Y_N = 'Y'
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N,
            VARIABLE_NAME,
            STRING_VALUE,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N,
                VARIABLE_NAME,
                STRING_VALUE,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N,
                    VARIABLE_NAME,
                    STRING_VALUE,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
       AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
       AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODEOut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        CASE WHEN dsf_1.ACTIVE_Y_N_STR_VL IS NULL THEN 'N' ELSE dsf_1.ACTIVE_Y_N_STR_VL END AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        CASE WHEN dsf_2.ACTIVE_Y_N IS NULL THEN 'N' ELSE dsf_2.ACTIVE_Y_N END AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE
                    WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                         OR (CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END) = 'Y'
                            AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2
                    THEN 'F' ELSE 'P'
                END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODEOut
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N_STR_VL,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N_STR_VL,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N_STR_VL,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.ACTIVE_Y_N AS ACTIVE_Y_N_STR_VL,
                        APPLICATION_VARIABLES.STRING_VALUE AS STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER'
                      AND ACTIVE_Y_N = 'Y'
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N,
            VARIABLE_NAME,
            STRING_VALUE,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N,
                VARIABLE_NAME,
                STRING_VALUE,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N,
                    VARIABLE_NAME,
                    STRING_VALUE,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
       AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
       AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut AS (
    SELECT
        '{{ var("TARGET_NAME") }}' AS TARGET_TABLE_NAME,
        dsf_1.ACTIVE_Y_N_STR_VL AS v_VALIDATION_ACTIVE,
        CASE WHEN dsf_1.ACTIVE_Y_N_STR_VL IS NULL THEN 'N' ELSE dsf_1.ACTIVE_Y_N_STR_VL END AS v_VALIDATION_ACTIVE_NVL,
        dsf_2.ACTIVE_Y_N AS v_VALIDATION_ON_TABLE_ACTIVE,
        CASE WHEN dsf_2.ACTIVE_Y_N IS NULL THEN 'N' ELSE dsf_2.ACTIVE_Y_N END AS v_VALIDATION_ON_TABLE_ACTIVE_NVL,
        CASE
            WHEN in_DATA_TYPE = 'DATE' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_DATE IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_DATE,
        CASE
            WHEN in_DATA_TYPE = 'STRING' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE WHEN in_ATTRIBUTE_TO_BE_VALIDATED_STR IS NULL THEN 'F' ELSE 'P' END
            ELSE 'P'
        END AS v_NULL_CHECK_STR,
        CASE
            WHEN in_DATA_TYPE = 'NUMBER' AND v_VALIDATION_ON_TABLE_ACTIVE_NVL = 'Y' AND v_VALIDATION_ACTIVE_NVL = 'Y' THEN
                CASE
                    WHEN in_ATTRIBUTE_TO_BE_VALIDATED_NUM IS NULL
                         OR (CASE WHEN in_DIMENSION_KEY_FLAG IS NULL THEN 'N' ELSE in_DIMENSION_KEY_FLAG END) = 'Y'
                            AND in_ATTRIBUTE_TO_BE_VALIDATED_NUM = -2
                    THEN 'F' ELSE 'P'
                END
            ELSE 'P'
        END AS v_NULL_CHECK_NUM,
        CASE
            WHEN v_NULL_CHECK_DATE = 'F' OR v_NULL_CHECK_STR = 'F' OR v_NULL_CHECK_NUM = 'F' THEN 'F' ELSE 'P'
        END AS v_VALIDATION_PASS_FAIL,
        v_VALIDATION_PASS_FAIL AS o_VALIDATION_PASS_FAIL,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'DATE'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_DATE
            ELSE NULL
        END AS v_ERROR_MESSAGE_DATE,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'STRING'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_STR
            ELSE NULL
        END AS v_ERROR_MESSAGE_STR,
        CASE
            WHEN v_VALIDATION_PASS_FAIL = 'F' AND in_DATA_TYPE = 'NUMBER'
            THEN in_ATTRIBUTE_NAME || ':' || in_ATTRIBUTE_TO_BE_VALIDATED_NUM
            ELSE NULL
        END AS v_ERROR_MESSAGE_NUM,
        v_ERROR_MESSAGE_DATE || v_ERROR_MESSAGE_STR || v_ERROR_MESSAGE_NUM AS o_COMBINED_ERROR_MESSAGE,
        CASE WHEN v_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS o_ERROR_SEVERITY
    FROM DSR_EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N_STR_VL,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N_STR_VL,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N_STR_VL,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM (
                    SELECT
                        APPLICATION_VARIABLES.ACTIVE_Y_N AS ACTIVE_Y_N_STR_VL,
                        APPLICATION_VARIABLES.STRING_VALUE AS STRING_VALUE2
                    FROM APPLICATION_VARIABLES
                    WHERE VARIABLE_NAME = 'GENERIC_ERROR_MASTER'
                      AND ACTIVE_Y_N = 'Y'
                )
            )
        )
        WHERE rnk_lst = 1
    ) dsf_1
        ON dsf_1.STRING_VALUE2 = in_VALIDATION_NAME
    LEFT JOIN (
        SELECT
            ACTIVE_Y_N,
            VARIABLE_NAME,
            STRING_VALUE,
            STRING_VALUE2
        FROM (
            SELECT
                ACTIVE_Y_N,
                VARIABLE_NAME,
                STRING_VALUE,
                STRING_VALUE2,
                ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst
            FROM (
                SELECT
                    ACTIVE_Y_N,
                    VARIABLE_NAME,
                    STRING_VALUE,
                    STRING_VALUE2,
                    ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst
                FROM APPLICATION_VARIABLES
            )
        )
        WHERE rnk_lst = 1
    ) dsf_2
        ON dsf_2.VARIABLE_NAME = in_VALIDATION_NAME
       AND dsf_2.STRING_VALUE = TARGET_TABLE_NAME
       AND dsf_2.STRING_VALUE2 = in_ATTRIBUTE_NAME
),

EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_VALIDATION_PASS_FAIL AS ENTITY_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_COMBINED_ERROR_MESSAGE AS ENTITY_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut.o_ERROR_SEVERITY AS ENTITY_ID_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_ENTITY_IDOut
),

EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1Out.o_VALIDATION_PASS_FAIL AS PARTICIPANT_LEI_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1Out.o_COMBINED_ERROR_MESSAGE AS PARTICIPANT_LEI_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1Out.o_ERROR_SEVERITY AS PARTICIPANT_LEI_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1Out
),

EXP_LDSA_VALIDATION_CHECKER_PART_ROLE_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_PART_ROLEOut.o_VALIDATION_PASS_FAIL AS PART_ROLE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_PART_ROLEOut.o_COMBINED_ERROR_MESSAGE AS PART_ROLE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_PART_ROLEOut.o_ERROR_SEVERITY AS PART_ROLE_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_PART_ROLEOut
),

EXP_PASS_THROUGH_details AS (
    SELECT
        EXP_PASS_THROUGHOut.BUSINESS_DATE AS BUSINESS_DATE,
        EXP_PASS_THROUGHOut.BATCH_ID AS BATCH_ID,
        EXP_PASS_THROUGHOut.O_BATCH_DETAILS_ID AS BATCH_DETAILS_ID,
        EXP_PASS_THROUGHOut.O_BATCH_START_DATE AS BATCH_START_DATE,
        EXP_PASS_THROUGHOut.WORKFLOW_NAME AS WORKFLOW_NAME,
        EXP_PASS_THROUGHOut.MAPPING_NAME AS MAPPING_NAME,
        EXP_PASS_THROUGHOut.TARGET_NAME AS TARGET_NAME,
        EXP_PASS_THROUGHOut.TMF_CODE AS TMF_CODE,
        EXP_PASS_THROUGHOut.PARTICIPANT_ROLE AS PARTICIPANT_ROLE,
        EXP_PASS_THROUGHOut.ENTITY_ID AS ENTITY_ID,
        EXP_PASS_THROUGHOut.CurrentlyProcessedFileName AS CurrentlyProcessedFileName,
        EXP_PASS_THROUGHOut.COUNTRY_CODE AS COUNTRY_CODE,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_1 AS ENTITY_ID_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_2 AS TMF_CODE_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_3 AS PART_ROLE_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.VALIDATION_NAME AS VALIDATION_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_4 AS PARTICIPANT_LEI_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.PARTICIPANT_LEI AS PARTICIPANT_LEI,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_5 AS PARTICIPANT_NAME_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.PARTICIPANT_NAME AS PARTICIPANT_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_6 AS COUNTRY_CODE_ATTRIBUTE_NAME,
        EXP_PASS_THROUGHOut.ATTRIBUTE_NAME_7 AS EEA_INDICATOR_ATTRIBUTE_NAME
    FROM EXP_PASS_THROUGHOut
),

EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut.o_VALIDATION_PASS_FAIL AS TMF_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut.o_COMBINED_ERROR_MESSAGE AS TMF_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut.o_ERROR_SEVERITY AS TMF_CODE_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_TMF_CODEOut
),

EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOR_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOROut.o_VALIDATION_PASS_FAIL AS EEA_INDICATOR_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOROut.o_COMBINED_ERROR_MESSAGE AS EEA_INDICATOR_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOROut.o_ERROR_SEVERITY AS EEA_INDICATOR_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOROut
),

EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAME_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAMEOut.o_VALIDATION_PASS_FAIL AS PARTICIPANT_NAME_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAMEOut.o_COMBINED_ERROR_MESSAGE AS PARTICIPANT_NAME_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAMEOut.o_ERROR_SEVERITY AS PARTICIPANT_NAME_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAMEOut
),

EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODE_details AS (
    SELECT
        EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODEOut.o_VALIDATION_PASS_FAIL AS COUNTRY_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODEOut.o_COMBINED_ERROR_MESSAGE AS COUNTRY_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODEOut.o_ERROR_SEVERITY AS COUNTRY_CODE_ERROR_SEVERITY
    FROM EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODEOut
),

dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out AS (
    SELECT
        EXP_PASS_THROUGH_details.BUSINESS_DATE AS BUSINESS_DATE,
        EXP_PASS_THROUGH_details.BATCH_ID AS BATCH_ID,
        EXP_PASS_THROUGH_details.BATCH_DETAILS_ID AS BATCH_DETAILS_ID,
        EXP_PASS_THROUGH_details.BATCH_START_DATE AS BATCH_START_DATE,
        EXP_PASS_THROUGH_details.WORKFLOW_NAME AS WORKFLOW_NAME,
        EXP_PASS_THROUGH_details.MAPPING_NAME AS MAPPING_NAME,
        EXP_PASS_THROUGH_details.TARGET_NAME AS TARGET_NAME,
        EXP_PASS_THROUGH_details.TMF_CODE AS TMF_CODE,
        EXP_PASS_THROUGH_details.PARTICIPANT_ROLE AS PARTICIPANT_ROLE,
        EXP_PASS_THROUGH_details.ENTITY_ID AS ENTITY_ID,
        EXP_PASS_THROUGH_details.CurrentlyProcessedFileName AS CurrentlyProcessedFileName,
        EXP_PASS_THROUGH_details.COUNTRY_CODE AS COUNTRY_CODE,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_VALIDATION_PASS_FAIL AS ENTITY_ID_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_ERROR_MESSAGE AS ENTITY_ID_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.ENTITY_ID_ERROR_SEVERITY AS ENTITY_ID_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.TMF_CODE_ATTRIBUTE_NAME AS TMF_CODE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.TMF_CODE_VALIDATION_PASS_FAIL AS TMF_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.TMF_CODE_ERROR_MESSAGE AS TMF_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.TMF_CODE_ERROR_SEVERITY AS TMF_CODE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.PART_ROLE_ATTRIBUTE_NAME AS PART_ROLE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_PART_ROLE_details.PART_ROLE_VALIDATION_PASS_FAIL AS PART_ROLE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_PART_ROLE_details.PART_ROLE_ERROR_MESSAGE AS PART_ROLE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_PART_ROLE_details.PART_ROLE_ERROR_SEVERITY AS PART_ROLE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.VALIDATION_NAME AS VALIDATION_NAME,
        EXP_PASS_THROUGH_details.PARTICIPANT_LEI_ATTRIBUTE_NAME AS PARTICIPANT_LEI_ATTRIBUTE_NAME,
        EXP_PASS_THROUGH_details.PARTICIPANT_LEI AS PARTICIPANT_LEI,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1_details.PARTICIPANT_LEI_VALIDATION_PASS_FAIL AS PARTICIPANT_LEI_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1_details.PARTICIPANT_LEI_ERROR_MESSAGE AS PARTICIPANT_LEI_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1_details.PARTICIPANT_LEI_ERROR_SEVERITY AS PARTICIPANT_LEI_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.PARTICIPANT_NAME_ATTRIBUTE_NAME AS PARTICIPANT_NAME_ATTRIBUTE_NAME,
        EXP_PASS_THROUGH_details.PARTICIPANT_NAME AS PARTICIPANT_NAME,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAME_details.PARTICIPANT_NAME_VALIDATION_PASS_FAIL AS PARTICIPANT_NAME_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAME_details.PARTICIPANT_NAME_ERROR_MESSAGE AS PARTICIPANT_NAME_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAME_details.PARTICIPANT_NAME_ERROR_SEVERITY AS PARTICIPANT_NAME_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.COUNTRY_CODE_ATTRIBUTE_NAME AS COUNTRY_CODE_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODE_details.COUNTRY_CODE_VALIDATION_PASS_FAIL AS COUNTRY_CODE_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODE_details.COUNTRY_CODE_ERROR_MESSAGE AS COUNTRY_CODE_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODE_details.COUNTRY_CODE_ERROR_SEVERITY AS COUNTRY_CODE_ERROR_SEVERITY,
        EXP_PASS_THROUGH_details.EEA_INDICATOR_ATTRIBUTE_NAME AS EEA_INDICATOR_ATTRIBUTE_NAME,
        EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOR_details.EEA_INDICATOR_VALIDATION_PASS_FAIL AS EEA_INDICATOR_VALIDATION_PASS_FAIL,
        EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOR_details.EEA_INDICATOR_ERROR_MESSAGE AS EEA_INDICATOR_ERROR_MESSAGE,
        EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOR_details.EEA_INDICATOR_ERROR_SEVERITY AS EEA_INDICATOR_ERROR_SEVERITY,
        SC_EXP_GENERATOROut.ID AS ID,
        ROW_NUMBER() OVER (ORDER BY 1) AS jkey
    FROM SC_EXP_GENERATOROut
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details
        ON SC_EXP_GENERATOROut.jkey = EXP_LDSA_VALIDATION_CHECKER_ENTITY_ID_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1_details
        ON SC_EXP_GENERATOROut.jkey = EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_LEI_1_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_PART_ROLE_details
        ON SC_EXP_GENERATOROut.jkey = EXP_LDSA_VALIDATION_CHECKER_PART_ROLE_details.jkey
    INNER JOIN EXP_PASS_THROUGH_details
        ON SC_EXP_GENERATOROut.jkey = EXP_PASS_THROUGH_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details
        ON SC_EXP_GENERATOROut.jkey = EXP_LDSA_VALIDATION_CHECKER_TMF_CODE_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOR_details
        ON SC_EXP_GENERATOROut.jkey = EXP_LDSA_VALIDATION_CHECKER_EEA_INDICATOR_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAME_details
        ON SC_EXP_GENERATOROut.jkey = EXP_LDSA_VALIDATION_CHECKER_PARTICIPANT_NAME_details.jkey
    INNER JOIN EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODE_details
        ON SC_EXP_GENERATOROut.jkey = EXP_LDSA_VALIDATION_CHECKER_COUNTRY_CODE_details.jkey
),

EXP_CONSOLIDATE_VALIDATIONSOut AS (
    SELECT
        BUSINESS_DATE,
        BATCH_ID,
        BATCH_DETAILS_ID,
        BATCH_START_DATE,
        WORKFLOW_NAME,
        MAPPING_NAME,
        TARGET_NAME,
        TMF_CODE,
        PARTICIPANT_ROLE,
        ENTITY_ID,
        CurrentlyProcessedFileName,
        '{{ var("FILE_NAME") }}' AS FILE_NAME,
        COUNTRY_CODE,
        'FILE NAME:' || FILE_NAME || '/' || 'BUSINESS_DATE:' || BUSINESS_DATE || '/' || 'TMF_CODE:' || TMF_CODE || '/' || 'COUNTRY_CODE:' || COUNTRY_CODE || '/' AS v_ERROR_MESSAGE,
        ENTITY_ID_ATTRIBUTE_NAME,
        ENTITY_ID_VALIDATION_PASS_FAIL,
        ENTITY_ID_ERROR_SEVERITY,
        v_ERROR_MESSAGE || ENTITY_ID_ERROR_MESSAGE AS o_ENTITY_ID_ERROR_MESSAGE,
        TMF_CODE_ATTRIBUTE_NAME,
        TMF_CODE_VALIDATION_PASS_FAIL,
        TMF_CODE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || TMF_CODE_ERROR_MESSAGE AS o_TMF_CODE_ERROR_MESSAGE,
        PART_ROLE_ATTRIBUTE_NAME,
        PART_ROLE_VALIDATION_PASS_FAIL,
        PART_ROLE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || PART_ROLE_ERROR_MESSAGE AS o_PART_ROLE_ERROR_MESSAGE,
        VALIDATION_NAME,
        PARTICIPANT_LEI_ATTRIBUTE_NAME,
        PARTICIPANT_LEI,
        PARTICIPANT_LEI_VALIDATION_PASS_FAIL AS V_PARTICIPANT_LEI_VALIDATION_PASS_FAIL,
        PARTICIPANT_LEI_VALIDATION_PASS_FAIL AS O_PARTICIPANT_LEI_VALIDATION_PASS_FAIL,
        PARTICIPANT_LEI_ERROR_MESSAGE,
        PARTICIPANT_LEI_ERROR_SEVERITY,
        CASE WHEN PARTICIPANT_LEI_VALIDATION_PASS_FAIL = 'F' THEN 1 ELSE 0 END AS V_PARTICIPANT_LEI_ERROR_SEVERITY,
        V_PARTICIPANT_LEI_ERROR_SEVERITY AS O_PARTICIPANT_LEI_ERROR_SEVERITY,
        v_ERROR_MESSAGE || PARTICIPANT_LEI_ERROR_MESSAGE AS O_LEI_ERROR_MESSAGE,
        PARTICIPANT_NAME_ATTRIBUTE_NAME,
        PARTICIPANT_NAME,
        PARTICIPANT_NAME_VALIDATION_PASS_FAIL,
        PARTICIPANT_NAME_ERROR_MESSAGE,
        PARTICIPANT_NAME_ERROR_SEVERITY,
        v_ERROR_MESSAGE || PARTICIPANT_NAME_ERROR_MESSAGE AS O_PARTICIPANT_NAME_ERROR_MESSAGE,
        COUNTRY_CODE_ATTRIBUTE_NAME,
        COUNTRY_CODE_VALIDATION_PASS_FAIL,
        COUNTRY_CODE_ERROR_MESSAGE,
        COUNTRY_CODE_ERROR_SEVERITY,
        v_ERROR_MESSAGE || COUNTRY_CODE_ERROR_MESSAGE AS O_COUNTRY_CODE_ERROR_MESSAGE,
        EEA_INDICATOR_ATTRIBUTE_NAME,
        EEA_INDICATOR_VALIDATION_PASS_FAIL,
        EEA_INDICATOR_ERROR_MESSAGE,
        EEA_INDICATOR_ERROR_SEVERITY,
        v_ERROR_MESSAGE || EEA_INDICATOR_ERROR_MESSAGE AS O_EEA_INDICATOR_ERROR_MESSAGE,
        CASE
            WHEN ENTITY_ID_VALIDATION_PASS_FAIL = 'F'
                 OR TMF_CODE_VALIDATION_PASS_FAIL = 'F'
                 OR PART_ROLE_VALIDATION_PASS_FAIL = 'F'
                 OR PARTICIPANT_LEI_VALIDATION_PASS_FAIL = 'F'
                 OR PARTICIPANT_NAME_VALIDATION_PASS_FAIL = 'F'
                 OR COUNTRY_CODE_VALIDATION_PASS_FAIL = 'F'
                 OR EEA_INDICATOR_VALIDATION_PASS_FAIL = 'F'
            THEN 1 ELSE 0
        END AS MD_ERROR_IND,
        ID,
        CASE
            WHEN REGEXP_INSTR(CurrentlyProcessedFileName, 'DCL') > 0 THEN 'DCLSA'
            ELSE 'MATIF_MONEP'
        END AS DATA_SET_NAME
    FROM dsJoiner_EXP_CONSOLIDATE_VALIDATIONS0Out
),

DSR_FIL_ERROR_LOGICOut AS (
    SELECT
        EXP_CONSOLIDATE_VALIDATIONSOut.VALIDATION_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.PARTICIPANT_NAME_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.PARTICIPANT_NAME_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_PARTICIPANT_NAME_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.COUNTRY_CODE_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.COUNTRY_CODE_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_COUNTRY_CODE_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.EEA_INDICATOR_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.EEA_INDICATOR_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_EEA_INDICATOR_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_LEI_ERROR_MESSAGE AS LEI_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.PART_CODE_ERROR_SEVERITY AS PART_CODE_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.o_TMF_CODE_ERROR_MESSAGE AS PART_CODE_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.PART_ROLE_ERROR_SEVERITY,
        EXP_CONSOLIDATE_VALIDATIONSOut.PARTICIPANT_LEI_ATTRIBUTE_NAME AS LEI_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.O_LEI_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.BATCH_START_DATE,
        EXP_CONSOLIDATE_VALIDATIONSOut.WORKFLOW_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.MAPPING_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.TARGET_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.CurrentlyProcessedFileName,
        EXP_CONSOLIDATE_VALIDATIONSOut.MD_ERROR_IND,
        EXP_CONSOLIDATE_VALIDATIONSOut.o_ENTITY_ID_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.ENTITY_ID_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.PART_CODE_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.PART_ROLE_ATTRIBUTE_NAME,
        EXP_CONSOLIDATE_VALIDATIONSOut.BUSINESS_DATE,
        EXP_CONSOLIDATE_VALIDATIONSOut.BATCH_ID,
        EXP_CONSOLIDATE_VALIDATIONSOut.BATCH_DETAILS_ID,
        EXP_CONSOLIDATE_VALIDATIONSOut.ID,
        EXP_CONSOLIDATE_VALIDATIONSOut.PART_ROLE_ERROR_MESSAGE,
        EXP_CONSOLIDATE_VALIDATIONSOut.ENTITY_ID_ERROR_SEVERITY
    FROM EXP_CONSOLIDATE_VALIDATIONSOut
),

DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut AS (
    SELECT
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_3,
        FIL_ERROR_LOGICOut.PART_ROLE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_3,
        FIL_ERROR_LOGICOut.BUSINESS_DATE AS INPUT_BATCH_BUSINESS_DATE,
        FIL_ERROR_LOGICOut.BATCH_ID AS INPUT_BATCH_ID,
        FIL_ERROR_LOGICOut.WORKFLOW_NAME AS INPUT_WORKFLOW_NAME,
        FIL_ERROR_LOGICOut.MAPPING_NAME AS INPUT_MAPPING_NAME,
        FIL_ERROR_LOGICOut.EEA_INDICATOR_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_7,
        FIL_ERROR_LOGICOut.O_EEA_INDICATOR_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_7,
        FIL_ERROR_LOGICOut.EEA_INDICATOR_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_7,
        FIL_ERROR_LOGICOut.COUNTRY_CODE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_6,
        FIL_ERROR_LOGICOut.LEI_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_4,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_4,
        FIL_ERROR_LOGICOut.PARTICIPANT_NAME_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_5,
        FIL_ERROR_LOGICOut.ID AS INPUT_REFERENCE_RECORD_ID,
        FIL_ERROR_LOGICOut.BATCH_DETAILS_ID AS INPUT_BATCH_DETAILS_ID,
        FIL_ERROR_LOGICOut.BATCH_START_DATE AS INPUT_BATCH_START_DATE,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_5,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_6,
        FIL_ERROR_LOGICOut.PARTICIPANT_NAME_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_5,
        FIL_ERROR_LOGICOut.O_PARTICIPANT_NAME_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_5,
        FIL_ERROR_LOGICOut.TARGET_NAME AS INPUT_TARGET_NAME,
        FIL_ERROR_LOGICOut.ENTITY_ID_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_1,
        FIL_ERROR_LOGICOut.ENTITY_ID_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_1,
        FIL_ERROR_LOGICOut.CurrentlyProcessedFileName AS INPUT_FILE_NAME,
        FIL_ERROR_LOGICOut.PART_CODE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_2,
        FIL_ERROR_LOGICOut.PART_CODE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_2,
        FIL_ERROR_LOGICOut.PART_ROLE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_3,
        FIL_ERROR_LOGICOut.PART_ROLE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_3,
        FIL_ERROR_LOGICOut.LEI_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_4,
        FIL_ERROR_LOGICOut.O_LEI_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_4,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_1,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_7,
        FIL_ERROR_LOGICOut.O_COUNTRY_CODE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_6,
        FIL_ERROR_LOGICOut.COUNTRY_CODE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_6,
        FIL_ERROR_LOGICOut.ENTITY_ID_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_1,
        FIL_ERROR_LOGICOut.PART_CODE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_2,
        FIL_ERROR_LOGICOut.VALIDATION_NAME AS INPUT_ERROR_CODE_2
    FROM DSR_FIL_ERROR_LOGICOut
    WHERE MD_ERROR_IND = 1
),

SC_mplt_DV_PROCESS_ERROR_DETAILSOut AS (
    SELECT
        ID,
        PROCESS_DATE,
        REFERENCE_BATCH_ID,
        REFERENCE_PROCESS,
        REFERENCE_SUB_PROCESS,
        REFERENCE_TARGET_NAME,
        REFERENCE_RECORD_ID,
        ERROR_CODE,
        ERROR_SEVERITY,
        ADDITIONAL_DETAILS,
        REFERENCE_BATCH_DETAILS_ID,
        BATCH_START_DATE AS CREATED_TS,
        REFERENCE_BUSINESS_KEY,
        REFERENCE_ATTRIBUTE_NAME,
        REFERENCE_ATTRIBUTE_VALUE,
        VALIDATION_NAME AS INPUT_ERROR_CODE_3,
        PART_ROLE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_3,
        BUSINESS_DATE AS INPUT_BATCH_BUSINESS_DATE,
        BATCH_ID AS INPUT_BATCH_ID,
        WORKFLOW_NAME AS INPUT_WORKFLOW_NAME,
        MAPPING_NAME AS INPUT_MAPPING_NAME,
        EEA_INDICATOR_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_7,
        O_EEA_INDICATOR_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_7,
        EEA_INDICATOR_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_7,
        COUNTRY_CODE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_6,
        LEI_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_4,
        VALIDATION_NAME AS INPUT_ERROR_CODE_4,
        PARTICIPANT_NAME_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_5,
        ID AS INPUT_REFERENCE_RECORD_ID,
        BATCH_DETAILS_ID AS INPUT_BATCH_DETAILS_ID,
        BATCH_START_DATE AS INPUT_BATCH_START_DATE,
        VALIDATION_NAME AS INPUT_ERROR_CODE_5,
        VALIDATION_NAME AS INPUT_ERROR_CODE_6,
        PARTICIPANT_NAME_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_5,
        O_PARTICIPANT_NAME_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_5,
        TARGET_NAME AS INPUT_TARGET_NAME,
        ENTITY_ID_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_1,
        ENTITY_ID_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_1,
        CurrentlyProcessedFileName AS INPUT_FILE_NAME,
        PART_CODE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_2,
        PART_CODE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_2,
        PART_ROLE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_3,
        PART_ROLE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_3,
        LEI_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_4,
        O_LEI_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_4,
        VALIDATION_NAME AS INPUT_ERROR_CODE_1,
        VALIDATION_NAME AS INPUT_ERROR_CODE_7,
        O_COUNTRY_CODE_ERROR_MESSAGE AS INPUT_ATTRIBUTE_VALUE_6,
        COUNTRY_CODE_ERROR_SEVERITY AS INPUT_ERROR_SEVERITY_6,
        ENTITY_ID_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_1,
        PART_CODE_ATTRIBUTE_NAME AS INPUT_ATTRIBUTE_NAME_2,
        VALIDATION_NAME AS INPUT_ERROR_CODE_2
    FROM DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut
),

DSR_SC_PROCESS_ERROR_DETAILSOut AS (
    SELECT
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.PROCESS_DATE,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_BATCH_ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_PROCESS,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_SUB_PROCESS,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_TARGET_NAME,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_RECORD_ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_BUSINESS_KEY,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_ATTRIBUTE_NAME,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_ATTRIBUTE_VALUE,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ERROR_CODE,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ERROR_SEVERITY,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.ADDITIONAL_DETAILS,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.REFERENCE_BATCH_DETAILS_ID,
        SC_mplt_DV_PROCESS_ERROR_DETAILSOut.CREATED_TS
    FROM SC_mplt_DV_PROCESS_ERROR_DETAILSOut
)

SELECT
    ID,
    PROCESS_DATE,
    REFERENCE_BATCH_ID,
    REFERENCE_PROCESS,
    REFERENCE_SUB_PROCESS,
    REFERENCE_TARGET_NAME,
    REFERENCE_RECORD_ID,
    REFERENCE_BUSINESS_KEY,
    REFERENCE_ATTRIBUTE_NAME,
    REFERENCE_ATTRIBUTE_VALUE,
    ERROR_CODE,
    ERROR_SEVERITY,
    ADDITIONAL_DETAILS,
    REFERENCE_BATCH_DETAILS_ID,
    CREATED_TS
FROM DSR_SC_PROCESS_ERROR_DETAILSOut