/* Transformation Name ==>FirstUnion ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='VARC_LocalFolder_tmpprocessing+/+StringHandling.DOWNCASE({{ VARC_JobName_ACBSTor_Banker_Dim }}+/TempFile1+.+{{ VARC_FileExtension }})',
		schema='',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='overwrite')
}}

With OBLIGATIONDAILY_DELTAOut as (
	Select USDH_Sequence, 
		loan_portfolio_id, 
		gl_unit, 
		gl_unit_description, 
		servicing_unit, 
		servicing_unit_description, 
		servicing_unit_section, 
		servicing_unit_section_description, 
		obligation_current_officer, 
		officer_name, 
		obligor_number, 
		owner_id, 
		ca_number, 
		ca_description_text, 
		obligation_number, 
		cu_customer_shortname, 
		city_name, 
		lender_type_code, 
		cl_servicing_user_id, 
		account_structure_code, 
		loan_status, 
		accounting_method, 
		accounting_status_code, 
		accrual_schedule_status_code, 
		accrual_method_code, 
		accrual_class_code, 
		instrument_type_code, 
		product_group, 
		product_group_description, 
		product_type_code, 
		product_type_description, 
		risk_rating_officer, 
		loan_currency_code, 
		crncy_current_exchange_rate, 
		general_purpose_code, 
		industry_classification, 
		country_of_booking, 
		callable_on_demand, 
		cl_evergreen_flag, 
		secured_code, 
		pledged_for_collateral, 
		schedule_freq_code, 
		interest_rate_type, 
		reserve_rate, 
		percentage_of_rate, 
		rate_calculation_method_code, 
		floating_rate_index_code, 
		index_rate_change_frequency_code, 
		index_rate_change_timing_code, 
		base_rate, 
		spread_rate, 
		cost_of_funds_rate, 
		current_accruing_rate, 
		year_basis_code, 
		user_defined_code_1, 
		user_code_2, 
		user_code_3, 
		user_code_4, 
		user_date_1, 
		user_date_2, 
		effective_date, 
		legal_maturity_date, 
		int_rate_maturity_date, 
		first_due_date, 
		next_due_date, 
		accrual_schedule_effective_date, 
		beg_principal_amount, 
		customer_principal_bal, 
		customer_interest_bal, 
		mtd_average_principal_balance, 
		cur_interest_balance, 
		our_share_of_principal_balance, 
		our_share_of_interest_balance, 
		customer_charge_off_amt, 
		net_charge_off_amount, 
		value_of_collateral, 
		original_general_ledger_balance, 
		principal_amount_written_down, 
		current_daily_accrual_amount_account, 
		rate_setting_date, 
		interest_until_rate_maturity, 
		last_rate_rollover_date, 
		non_performing_loan_date, 
		original_amount_discounted, 
		our_share_of_fee_balance, 
		orig_our_share_prin_bal_equal_0_flag, 
		pricing_template_id, 
		unit_pseudonym, 
		portfolio_base_currency, 
		operation_indicator, 
		external_reference_number, 
		cur_principal_balance, 
		agent_bank_customer_number, 
		customerusage_fx_rate, 
		naics_industry_id, 
		parent_customer_id, 
		administrative_user_id, 
		sequence_number, 
		ccis_code, 
		internal_reference_number, 
		current_general_ledger_balance, 
		cu_customer_type_code, 
		reporting_account_type_code, 
		ccis_account_number, 
		ccis_sub_account, 
		ccis_customer_group, 
		ccis_product_type, 
		ccis_project_code, 
		ccis_reserved_code, 
		ccis_currency_indicator_code, 
		cu_alternate_customer_number, 
		fed_call_code, 
		field_update_access_identifier, 
		usdh_as_of_date, 
		usdh_date_created, 
		usdh_created_by, 
		usdh_date_updated, 
		usdh_updated_by, 
		CompositeKeyHashValue, 
		RowHashValue, 
		Flag
 from 
{{ source ('tFileInputDelimited_2','{{ VARC_CuratedZone_ObligationDaily_delta }}') }} 
 ),

CommitmentDaily_DeltaOut as (
	Select USDH_Sequence, 
		portfolio_id, 
		ca_general_ledger_unit, 
		gl_unit_description, 
		servicing_unit_number, 
		servicing_unit_description, 
		servicing_unit_section_number, 
		servicing_unit_section_description, 
		current_officer, 
		officer_name, 
		ca_primary_obligor_number, 
		ca_number, 
		ca_account_owner_number, 
		cu_customer_shortname, 
		cu_customer_name_1_display, 
		cu_guarantor_name, 
		cu_customer_type_code, 
		cu_risk_rating_line_officer, 
		country_code, 
		state, 
		guarantor_id, 
		ca_description_text, 
		ca_servicing_user_id, 
		ca_overall_status_code, 
		ca_type_code, 
		ca_type_description, 
		ca_account_structure_code, 
		ca_origination_code, 
		ca_currency_code, 
		crncy_current_exchange_rate, 
		customer_lender_type_code, 
		our_share_lender_type_code, 
		risk_rating_line_officer, 
		capital_class_code, 
		country_of_exposurerisk, 
		collateral_type_code, 
		limit_revolving_flag, 
		ca_evergreen_flag, 
		general_purpose_code, 
		general_industry_class_sic, 
		frequency_code, 
		repayment_type_code, 
		user_defined_code_1, 
		ca_user_defined_code_1, 
		user_defined_code_2, 
		user_defined_code_3, 
		user_defined_code_4, 
		user_defined_date_1, 
		user_defined_date_2, 
		user_defined_date_3, 
		last_update_control_stamp, 
		kmv_identifier, 
		ticker_symbol, 
		kmv_relationship_code, 
		original_effective_date, 
		current_expiration_date, 
		final_availability_date, 
		next_ca_review_date, 
		next_due_date, 
		ca_overall_status_date, 
		user_defined_amount_1, 
		user_defined_amount_2, 
		original_ca_amount, 
		current_ca_amount, 
		current_used_amount, 
		current_available_amount, 
		our_total_share_amount, 
		our_total_share_used_amount, 
		our_total_share_available_amount, 
		payment_amount, 
		fee_effective_date, 
		fee_expiration_date, 
		fee_current_accrual_calc_code, 
		fee_current_accrual_rate, 
		fee_current_basis_code, 
		fee_cur_base_balance_code, 
		bill_frequency_code, 
		fee_income_class_code, 
		fee_accounting_method_code, 
		fee_currency_code, 
		fee_actual_daily_accrual_amount, 
		external_reference_number, 
		guarantee_type, 
		portfolio_base_currency, 
		operation_indicator, 
		internal_ca_reference_number, 
		customer_number_of_agent_bank, 
		credit_conversion_factor, 
		secondary_officer, 
		ca_collateral_type_code, 
		naics_code, 
		parent_customer_id, 
		non_performing_loan_flag, 
		risk_rating_credit_review, 
		ca_guarantor_id, 
		ca_guarantor_type, 
		ccis_code, 
		ca_guarantor_name, 
		ca_guaranteed_limit, 
		ca_guaranteed_percent, 
		cu_guaranteed_limit, 
		cu_guaranteed_percent, 
		cu_user_defined_code_2, 
		cu_user_defined_code_3, 
		risk_rating_regulator, 
		user_defined_3, 
		ccis_account_number, 
		ccis_sub_account, 
		ccis_customer_group, 
		ccis_product_type, 
		ccis_project_code, 
		ccis_reserved_code, 
		ccis_currency_indicator_code, 
		optex_reference, 
		ca_is_legally_binding, 
		user_defined_code_1_cmmtd1, 
		user_defined_code_2_mixed_fac, 
		our_total_share_withheld_amount, 
		cu_alternate_customer_number, 
		update_ident, 
		usdh_as_of_date, 
		usdh_date_created, 
		usdh_created_by, 
		usdh_date_updated, 
		usdh_updated_by, 
		CompositeKeyHashValue, 
		RowHashValue
 from 
{{ source ('tFileInputDelimited_1','{{ VARC_CuratedZone_CommitmentDaily_delta }}') }} 
 ),

CUSTOMERDAILY_CURRENTOut as (
	Select USDH_Sequence, 
		cu_customer_id, 
		cu_customer_name_1_display, 
		cu_customer_shortname, 
		customer_2_id, 
		related_customer_name, 
		customer_2_to_customer_1, 
		cu_primary_officer_number, 
		officer_name, 
		cu_secondary_officer_number, 
		cu_servicing_unit, 
		default_gl_unit, 
		servicing_unit_section, 
		cu_citizenship_class_code, 
		cu_internal_bank_relationship, 
		cu_primary_industry_code, 
		user_defined_code_1, 
		cu_risk_rating_line_officer, 
		cu_cbrs_ratins, 
		cu_dbrs_ratins, 
		cu_moodys_ratins, 
		cu_sp_ratins, 
		kmv_identifier, 
		ticker_symbol, 
		lpc_customer_number, 
		kmv_relationship_code, 
		street_1, 
		street_2, 
		addr_street_3, 
		addr_street_4, 
		city_name, 
		state, 
		country_code, 
		relationship_start_date, 
		business_start_date, 
		number_of_full_time_employees, 
		number_of_part_time_employees, 
		annual_sales, 
		annual_sales_currency_code, 
		cu_user_defined_code_1, 
		cu_customer_type_code, 
		cu_next_customer_review_date, 
		naics_code, 
		parent_customer_id, 
		cu_customer_sort_name, 
		cu_customer_review_freq, 
		cu_user_defined_code_3, 
		customer_country_code, 
		customer_provincestate, 
		customer_party_type, 
		customer_status, 
		cu_alternate_customer_number, 
		field_update_access_identifier, 
		usdh_as_of_date, 
		usdh_date_created, 
		usdh_created_by, 
		usdh_date_updated, 
		usdh_updated_by, 
		CompositeKeyHashValue, 
		RowHashValue, 
		Column60, 
		Column61, 
		Column62, 
		Column63, 
		Column64, 
		Column65, 
		Column66, 
		Column67, 
		Column68, 
		Column69, 
		Column70, 
		Column71, 
		Column72, 
		Column73, 
		Column74, 
		Column75, 
		Column76, 
		Column77, 
		Column78, 
		Column79, 
		Column80, 
		Column81, 
		Column82, 
		Column83, 
		Column84, 
		Column85, 
		Column86, 
		Column87, 
		Column88, 
		Column89, 
		Column90, 
		Column91, 
		Column92, 
		Column93, 
		Column94, 
		Column95, 
		Column96, 
		Column97, 
		Column98, 
		Column99, 
		Column100, 
		Column101, 
		Column102, 
		Column103, 
		Column104, 
		Column105, 
		Column106, 
		Column107, 
		Column108, 
		Column109, 
		Column110, 
		Column111, 
		Column112, 
		Column113, 
		Column114, 
		Column115, 
		Column116, 
		Column117, 
		Column118, 
		Column119, 
		Column120, 
		Column121, 
		Column122, 
		Column123, 
		Column124, 
		Column125, 
		Column126, 
		Column127, 
		Column128, 
		Column129, 
		Column130, 
		Column131, 
		Column132, 
		Column133, 
		Column134, 
		Column135, 
		Column136, 
		Column137, 
		Column138, 
		Column139, 
		Column140, 
		Column141, 
		Column142, 
		Column143, 
		Column144, 
		Column145, 
		Column146, 
		Column147, 
		Column148, 
		Column149, 
		Column150, 
		Column151, 
		Column152, 
		Column153, 
		Column154, 
		Column155, 
		Column156, 
		Column157, 
		Column158, 
		Column159, 
		Column160, 
		Column161, 
		Column162, 
		Column163, 
		Column164, 
		Column165, 
		Column166, 
		Column167, 
		Column168, 
		Column169, 
		Column170, 
		Column171, 
		Column172, 
		Column173, 
		Column174, 
		Column175, 
		Column176, 
		Column177, 
		Column178, 
		Column179, 
		Column180, 
		Column181, 
		Column182, 
		Column183, 
		Column184, 
		Column185, 
		Column186, 
		Column187, 
		Column188, 
		Column189, 
		Column190, 
		Column191, 
		Column192, 
		Column193, 
		Column194, 
		Column195, 
		Column196, 
		Column197, 
		Column198, 
		Column199, 
		Column200, 
		Column201, 
		Column202, 
		Column203, 
		Column204, 
		Column205, 
		Column206, 
		Column207, 
		Column208, 
		Column209, 
		Column210, 
		Column211, 
		Column212, 
		Column213, 
		Column214, 
		Column215, 
		Column216, 
		Column217, 
		Column218, 
		Column219, 
		Column220, 
		Column221, 
		Column222, 
		Column223, 
		Column224, 
		Column225, 
		Column226, 
		Column227, 
		Column228, 
		Column229, 
		Column230, 
		Column231, 
		Column232, 
		Column233, 
		Column234, 
		Column235, 
		Column236, 
		Column237, 
		Column238, 
		Column239, 
		Column240, 
		Column241
 from 
{{ source ('tFileInputDelimited_3','{{ VARC_CuratedZone_CustomerDaily_current }}') }} 
 ),

ObligationDaily_FilteredOut as (
	
Select 
CASE WHEN product_group IS NULL OR TRIM ( product_group ) = '' OR TRIM ( product_group ) = 'null' OR TRIM ( product_group ) length ( ) == 0 THEN "" ELSE product_group END as V_ProductGroup,
CASE WHEN current_general_ledger_balance IS NULL OR TRIM ( valueOf ( current_general_ledger_balance ) ) = '' OR TRIM ( valueOf ( current_general_ledger_balance ) ) = 'null' OR LENGTH ( TRIM ( valueOf ( current_general_ledger_balance ) ) ) == 0 THEN valueOf ( "0" ) ELSE current_general_ledger_balance END as V_GeneralLedger,
CASE WHEN mtd_average_principal_balance IS NULL OR TRIM ( valueOf ( mtd_average_principal_balance ) ) = '' OR TRIM ( valueOf ( mtd_average_principal_balance ) ) = 'null' OR LENGTH ( TRIM ( valueOf ( mtd_average_principal_balance ) ) ) == 0 THEN valueOf ( "0" ) ELSE mtd_average_principal_balance END as V_MTDAvg,
BankerCde as BankerCde_1,
BankerName as BankerName_1,
CASE WHEN ( obligation_current_officer IS NULL OR TRIM ( valueOf ( obligation_current_officer ) ) = '' OR valueOf ( obligation_current_officer ) IS NULL OR TRIM ( valueOf ( obligation_current_officer ) ) = 'null' OR LENGTH ( TRIM ( valueOf ( obligation_current_officer ) ) ) == 0 ) THEN "" ELSE obligation_current_officer END as BankerCde_2,
officer_name as BankerName_2
From OBLIGATIONDAILY_DELTAOut as OBLIGATIONDAILY_DELTAOut),

tMap_Input_Delta_FileOut as (
	
Select 
CASE WHEN CommitmentDaily_Delta.ca_overall_status_code IS NULL OR TRIM ( String.valueOf ( CommitmentDaily_Delta.ca_overall_status_code ) ) = '' OR TRIM ( String.valueOf ( CommitmentDaily_Delta.ca_overall_status_code ) ) = 'null' OR LENGTH ( TRIM ( String.valueOf ( CommitmentDaily_Delta.ca_overall_status_code ) ) ) == 0 THEN "" ELSE CommitmentDaily_Delta.ca_overall_status_code END as StatusCode,
CASE WHEN CommitmentDaily_Delta.current_ca_amount IS NULL OR TRIM ( String.valueOf ( CommitmentDaily_Delta.current_ca_amount ) ) = '' OR TRIM ( String.valueOf ( CommitmentDaily_Delta.current_ca_amount ) ) = 'null' OR LENGTH ( TRIM ( String.valueOf ( CommitmentDaily_Delta.current_ca_amount ) ) ) == 0 THEN Float.valueOf ( "0" ) ELSE CommitmentDaily_Delta.current_ca_amount END as ca_amount,
CommitmentDaily_Delta.BankerCde as BankerCde_1,
CommitmentDaily_Delta.BankerName as BankerName_1,
CASE WHEN ( CommitmentDaily_Delta.current_officer IS NULL OR TRIM ( String.valueOf ( CommitmentDaily_Delta.current_officer ) ) = '' OR String.valueOf ( CommitmentDaily_Delta.current_officer ) IS NULL OR TRIM ( String.valueOf ( CommitmentDaily_Delta.current_officer ) ) = 'null' OR LENGTH ( TRIM ( String.valueOf ( CommitmentDaily_Delta.current_officer ) ) ) == 0 ) THEN "" ELSE CommitmentDaily_Delta.current_officer END as BankerCde_2,
CommitmentDaily_Delta.officer_name as BankerName_2
From CommitmentDaily_DeltaOut as CommitmentDaily_DeltaOut),

exp_out_tMap_2Out as (
	
Select 
CASE WHEN ( ObligationDaily_Delta.obligation_current_officer IS NULL OR TRIM ( String.valueOf ( ObligationDaily_Delta.obligation_current_officer ) ) = '' OR String.valueOf ( ObligationDaily_Delta.obligation_current_officer ) IS NULL OR TRIM ( String.valueOf ( ObligationDaily_Delta.obligation_current_officer ) ) = 'null' OR LENGTH ( TRIM ( String.valueOf ( ObligationDaily_Delta.obligation_current_officer ) ) ) == 0 ) THEN "" ELSE ObligationDaily_Delta.obligation_current_officer END as BankerCde,
ObligationDaily_Delta.officer_name as BankerName
From filter_tMap_2Out as filter_tMap_2Out),

tMap_3Out as (
	
Select 
CASE WHEN ( row10.cu_primary_officer_number IS NULL OR TRIM ( String.valueOf ( row10.cu_primary_officer_number ) ) = '' OR String.valueOf ( row10.cu_primary_officer_number ) IS NULL OR TRIM ( String.valueOf ( row10.cu_primary_officer_number ) ) = 'null' OR LENGTH ( TRIM ( String.valueOf ( row10.cu_primary_officer_number ) ) ) == 0 ) THEN "" ELSE row10.cu_primary_officer_number END as BankerCde,
row10.officer_name as BankerName
From tFilterColumns_1Out as tFilterColumns_1Out),

exp_out_tMap_1Out as (
	
Select 
CASE WHEN ( CommitmentDaily_Delta.current_officer IS NULL OR TRIM ( String.valueOf ( CommitmentDaily_Delta.current_officer ) ) = '' OR String.valueOf ( CommitmentDaily_Delta.current_officer ) IS NULL OR TRIM ( String.valueOf ( CommitmentDaily_Delta.current_officer ) ) = 'null' OR LENGTH ( TRIM ( String.valueOf ( CommitmentDaily_Delta.current_officer ) ) ) == 0 ) THEN "" ELSE CommitmentDaily_Delta.current_officer END as BankerCde,
CommitmentDaily_Delta.officer_name as BankerName 
From tMap_Input_Delta_FileOut as tMap_Input_Delta_FileOut Where StatusCode = 'A' AND ca_amount > 0),

Uniting inputOut as (
	
(Select 
tMap_3Out.BankerCde,
tMap_3Out.BankerName,
 
From tMap_3Out as tMap_3Out )
 Union All 
 (Select 
exp_out_tMap_2Out.BankerCde,
exp_out_tMap_2Out.BankerName,
 
From exp_out_tMap_2Out as exp_out_tMap_2Out )
 Union All 
 (Select 
exp_out_tMap_1Out.BankerCde,
exp_out_tMap_1Out.BankerName,
 
From exp_out_tMap_1Out as exp_out_tMap_1Out )),

tAggregateRow_1_Out as (
	 
 select 
 * 
 from Uniting inputOut
)
)


Select 
	BankerCde as BankerCde,
	BankerName as BankerName 
From tAggregateRow_1Out as tAggregateRow_1Out