/* Transformation Name ==>tDBOutput_InsertOldRecords_3 ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='tDBOutput_InsertOldRecords_3',
		schema='schema',
		incremental_strategy='append'
	)
}}

With tDBInput_GetCurrentRecordsOut as (
	/* SubQuery from Source ==>tDBInput_GetCurrentRecords */
Select 
 * 
 from 
(WITH 
 FROM
    {{ VARC_Schema_Dimension }}.{{ VARC_ConformedZone_ObligAccount_Dim }})
 ),

tFileInputDelimited_1Out as (
	Select ObligDimSK, 
		CmmtDimSK, 
		ObligUSDHAcctNbr, 
		ObligSourceAcctNbr, 
		ObligSourceSystemSK, 
		ObligAccrualBasisCdeSK, 
		ObligAccrualIndSK, 
		ObligAccrualStatusCdeSK, 
		ObligAppScoreNbr, 
		ObligBankruptcyIndSK, 
		ObligBankruptcyDateSK, 
		ObligCeilingRate, 
		ObligEnteredDateSK, 
		ObligFedCallCdeSK, 
		ObligFHAIndSK, 
		ObligCurrentScoreNbr, 
		ObligFixedVariableIndSK, 
		ObligFloorRate, 
		ObligForeclosureDateSK, 
		ObligForeclosureIndSK, 
		ObligIndexCdeSK, 
		ObligIssueDateSK, 
		ObligMaturityDateSK, 
		ObligQualifiedMortgageIndSK, 
		ObligBankerSK, 
		ObligOriginalGLAmt, 
		ObligClosedDateSK, 
		ObligPaidIndSK, 
		ObligPartIndSK, 
		ObligRenewalDateSK, 
		ObligRiskRatingCdeSK, 
		ObligClientSK, 
		ObligShortNme, 
		ObligAccrualStatusDateSK, 
		ObligNonAccrualStatusDateSK, 
		ObligTypeCdeSK, 
		ObligOriginalDTIRatio, 
		ObligMortgageProductIDSK, 
		ObligIndexFloorIndSK, 
		ObligTDRCdeSK, 
		ObligSupervisoryLTVCdeSK, 
		ObligOriginationBeaconConsumerCreditScore, 
		ObligRefershedBeaconConsumerCreditScore, 
		ObligRefreshedConsumerCreditScoreDateSK, 
		ObligVarRateChangeFreqCdeSK, 
		ObligIndexRateChangeTimingCdeSK, 
		ObligBaseCurrencyCde, 
		ObligSecuredInd, 
		ObligOriginalMaturityCdeSK, 
		ObligCurrentSpreadRate, 
		ObligTaxMonitoringCde, 
		ObligChargeOffCdeSK, 
		ObligTermCount, 
		ObligCCISBranchOfAcct, 
		ObligSourceLegalEntity, 
		ObligCCISOrgUnit, 
		ObligSourceProfitCenter, 
		ObligCCISGLAcctUSGAAP, 
		ObligCCISGLAcctIFRS, 
		ObligCapitalAllocationCdeSK, 
		ObligSourceGLAcct, 
		ObligIntSourceGLAcct, 
		ObligIntCCISGLAcctUSGAAP, 
		ObligIntCCISGLAcctIFRS, 
		EffectiveStartDate, 
		EffectiveEndDate, 
		CurrentRecInd, 
		InsertDatetime, 
		UpdateDatetime, 
		CompositeKeyHashValue, 
		RowHashValue
 from 
{{ source ('tFileInputDelimited_1','StringHandling.DOWNCASE({{ VARC_LocalFolder_tmpprocessing }}+/+{{ VARC_JobName_JOB_CuratedToConformed_LOAD_USDH_ACBSTor_ObligationAccount_Dim }}+/hashcode+{{ VARC_ConformedZone_ObligAccount_Dim }}+.+{{ VARC_FileExtension }})') }} 
 ),

tMap_1Out as (
	
Select 
rowout.ObligDimSK as ObligDimSK,
rowout.CmmtDimSK as CmmtDimSK,
CASE WHEN rowout.ObligUSDHAcctNbr = 'NULL' THEN null ELSE rowout.ObligUSDHAcctNbr END as ObligUSDHAcctNbr,
CASE WHEN rowout.ObligSourceAcctNbr = 'NULL' THEN null ELSE rowout.ObligSourceAcctNbr END as ObligSourceAcctNbr,
rowout.ObligSourceSystemSK as ObligSourceSystemSK,
rowout.ObligAccrualBasisCdeSK as ObligAccrualBasisCdeSK,
rowout.ObligAccrualIndSK as ObligAccrualIndSK,
rowout.ObligAccrualStatusCdeSK as ObligAccrualStatusCdeSK,
rowout.ObligAppScoreNbr as ObligAppScoreNbr,
rowout.ObligBankruptcyIndSK as ObligBankruptcyIndSK,
rowout.ObligBankruptcyDateSK as ObligBankruptcyDateSK,
rowout.ObligCeilingRate as ObligCeilingRate,
rowout.ObligEnteredDateSK as ObligEnteredDateSK,
rowout.ObligFedCallCdeSK as ObligFedCallCdeSK,
rowout.ObligFHAIndSK as ObligFHAIndSK,
rowout.ObligCurrentScoreNbr as ObligCurrentScoreNbr,
rowout.ObligFixedVariableIndSK as ObligFixedVariableIndSK,
rowout.ObligFloorRate as ObligFloorRate,
rowout.ObligForeclosureDateSK as ObligForeclosureDateSK,
rowout.ObligForeclosureIndSK as ObligForeclosureIndSK,
rowout.ObligIndexCdeSK as ObligIndexCdeSK,
rowout.ObligIssueDateSK as ObligIssueDateSK,
rowout.ObligMaturityDateSK as ObligMaturityDateSK,
rowout.ObligQualifiedMortgageIndSK as ObligQualifiedMortgageIndSK,
rowout.ObligBankerSK as ObligBankerSK,
rowout.ObligOriginalGLAmt as ObligOriginalGLAmt,
rowout.ObligClosedDateSK as ObligClosedDateSK,
rowout.ObligPaidIndSK as ObligPaidIndSK,
rowout.ObligPartIndSK as ObligPartIndSK,
rowout.ObligRenewalDateSK as ObligRenewalDateSK,
rowout.ObligRiskRatingCdeSK as ObligRiskRatingCdeSK,
rowout.ObligClientSK as ObligClientSK,
CASE WHEN rowout.ObligShortNme = 'NULL' THEN null ELSE rowout.ObligShortNme END as ObligShortNme,
rowout.ObligAccrualStatusDateSK as ObligAccrualStatusDateSK,
rowout.ObligNonAccrualStatusDateSK as ObligNonAccrualStatusDateSK,
rowout.ObligTypeCdeSK as ObligTypeCdeSK,
null as ObligOriginalDTIRatio,
rowout.ObligMortgageProductIDSK as ObligMortgageProductIDSK,
rowout.ObligIndexFloorIndSK as ObligIndexFloorIndSK,
rowout.ObligTDRCdeSK as ObligTDRCdeSK,
rowout.ObligSupervisoryLTVCdeSK as ObligSupervisoryLTVCdeSK,
rowout.ObligOriginationBeaconConsumerCreditScore as ObligOriginationBeaconConsumerCreditScore,
rowout.ObligRefershedBeaconConsumerCreditScore as ObligRefershedBeaconConsumerCreditScore,
rowout.ObligRefreshedConsumerCreditScoreDateSK as ObligRefreshedConsumerCreditScoreDateSK,
rowout.ObligVarRateChangeFreqCdeSK as ObligVarRateChangeFreqCdeSK,
rowout.ObligIndexRateChangeTimingCdeSK as ObligIndexRateChangeTimingCdeSK,
CASE WHEN rowout.ObligBaseCurrencyCde = 'NULL' THEN "1" ELSE rowout.ObligBaseCurrencyCde END as ObligBaseCurrencyCde,
rowout.ObligSecuredInd as ObligSecuredInd,
rowout.ObligOriginalMaturityCdeSK as ObligOriginalMaturityCdeSK,
rowout.ObligCurrentSpreadRate as ObligCurrentSpreadRate,
CASE WHEN rowout.ObligTaxMonitoringCde = 'NULL' THEN null ELSE rowout.ObligTaxMonitoringCde END as ObligTaxMonitoringCde,
rowout.ObligChargeOffCdeSK as ObligChargeOffCdeSK,
rowout.ObligTermCount as ObligTermCount,
CASE WHEN rowout.ObligCCISBranchOfAcct = 'NULL' THEN null ELSE rowout.ObligCCISBranchOfAcct END as ObligCCISBranchOfAcct,
CASE WHEN rowout.ObligSourceLegalEntity = 'NULL' THEN null ELSE rowout.ObligSourceLegalEntity END as ObligSourceLegalEntity,
CASE WHEN rowout.ObligCCISOrgUnit = 'NULL' THEN null ELSE rowout.ObligCCISOrgUnit END as ObligCCISOrgUnit,
CASE WHEN rowout.ObligSourceProfitCenter = 'NULL' THEN null ELSE rowout.ObligSourceProfitCenter END as ObligSourceProfitCenter,
rowout.ObligCCISGLAcctUSGAAP as ObligCCISGLAcctUSGAAP,
rowout.ObligCCISGLAcctIFRS as ObligCCISGLAcctIFRS,
rowout.ObligCapitalAllocationCdeSK as ObligCapitalAllocationCdeSK,
CASE WHEN rowout.ObligSourceGLAcct = 'NULL' THEN null ELSE rowout.ObligSourceGLAcct END as ObligSourceGLAcct,
CASE WHEN rowout.ObligIntSourceGLAcct = 'NULL' THEN null ELSE rowout.ObligIntSourceGLAcct END as ObligIntSourceGLAcct,
rowout.ObligIntCCISGLAcctUSGAAP as ObligIntCCISGLAcctUSGAAP,
rowout.ObligIntCCISGLAcctIFRS as ObligIntCCISGLAcctIFRS,
rowout.EffectiveStartDate as EffectiveStartDate,
rowout.EffectiveEndDate as EffectiveEndDate,
rowout.CurrentRecInd as CurrentRecInd,
rowout.InsertDatetime as InsertDatetime,
rowout.UpdateDatetime as UpdateDatetime,
rowout.CompositeKeyHashValue as CompositeKeyHashValue,
rowout.RowHashValue as RowHashValue
From tFileInputDelimited_1Out as tFileInputDelimited_1Out),

tMap_OutputOut as (
Select 
	row25.ObligVarRateChangeFreqCdeSK as ObligVarRateChangeFreqCdeSK,
	 row25.ObligEnteredDateSK as ObligEnteredDateSK,
	 row25.ObligAppScoreNbr as ObligAppScoreNbr,
	 row25.ObligCCISGLAcctIFRS as ObligCCISGLAcctIFRS,
	 row25.ObligPartIndSK as ObligPartIndSK,
	 row25.ObligClosedDateSK as ObligClosedDateSK,
	 row25.RowHashValue as RowHashValue_1,
	 row25.ObligUSDHAcctNbr as ObligUSDHAcctNbr,
	 row25.ObligOriginalMaturityCdeSK as ObligOriginalMaturityCdeSK,
	 row35.RowHashValue as RowHashValue_2,
	 row25.ObligBankruptcyIndSK as ObligBankruptcyIndSK,
	 row25.ObligSupervisoryLTVCdeSK as ObligSupervisoryLTVCdeSK,
	 row25.ObligAccrualStatusDateSK as ObligAccrualStatusDateSK,
	 row35.ObligDimSK as ObligDimSK,
	 row25.ObligIndexFloorIndSK as ObligIndexFloorIndSK,
	 row25.ObligTermCount as ObligTermCount,
	 row25.ObligFedCallCdeSK as ObligFedCallCdeSK,
	 row25.ObligIssueDateSK as ObligIssueDateSK,
	 row25.ObligTDRCdeSK as ObligTDRCdeSK,
	 row25.ObligRefershedBeaconConsumerCreditScore as ObligRefershedBeaconConsumerCreditScore,
	 row25.CmmtDimSK as CmmtDimSK,
	 row25.ObligCeilingRate as ObligCeilingRate,
	 row25.ObligCurrentSpreadRate as ObligCurrentSpreadRate,
	 row25.ObligFHAIndSK as ObligFHAIndSK,
	 row25.ObligCurrentScoreNbr as ObligCurrentScoreNbr,
	 row25.ObligClientSK as ObligClientSK,
	 row25.ObligRiskRatingCdeSK as ObligRiskRatingCdeSK,
	 row25.ObligIntSourceGLAcct as ObligIntSourceGLAcct,
	 row25.ObligIndexRateChangeTimingCdeSK as ObligIndexRateChangeTimingCdeSK,
	 row25.ObligIntCCISGLAcctUSGAAP as ObligIntCCISGLAcctUSGAAP,
	 row25.ObligMortgageProductIDSK as ObligMortgageProductIDSK,
	 row25.ObligForeclosureDateSK as ObligForeclosureDateSK,
	 row25.ObligCCISBranchOfAcct as ObligCCISBranchOfAcct,
	 row25.ObligTaxMonitoringCde as ObligTaxMonitoringCde,
	 row25.ObligNonAccrualStatusDateSK as ObligNonAccrualStatusDateSK,
	 row25.ObligShortNme as ObligShortNme,
	 row25.ObligSourceLegalEntity as ObligSourceLegalEntity,
	 row25.ObligMaturityDateSK as ObligMaturityDateSK,
	 row25.ObligAccrualIndSK as ObligAccrualIndSK,
	 row25.ObligIntCCISGLAcctIFRS as ObligIntCCISGLAcctIFRS,
	 row25.ObligCCISOrgUnit as ObligCCISOrgUnit,
	 row25.ObligSecuredInd as ObligSecuredInd,
	 row25.ObligFloorRate as ObligFloorRate,
	 row25.ObligTypeCdeSK as ObligTypeCdeSK,
	 row25.ObligRenewalDateSK as ObligRenewalDateSK,
	 row25.ObligQualifiedMortgageIndSK as ObligQualifiedMortgageIndSK,
	 row25.ObligOriginationBeaconConsumerCreditScore as ObligOriginationBeaconConsumerCreditScore,
	 row25.ObligOriginalGLAmt as ObligOriginalGLAmt,
	 row25.ObligSourceGLAcct as ObligSourceGLAcct,
	 row25.ObligSourceSystemSK as ObligSourceSystemSK,
	 row25.ObligAccrualBasisCdeSK as ObligAccrualBasisCdeSK,
	 row25.ObligOriginalDTIRatio as ObligOriginalDTIRatio,
	 row25.ObligFixedVariableIndSK as ObligFixedVariableIndSK,
	 row25.ObligChargeOffCdeSK as ObligChargeOffCdeSK,
	 row25.ObligIndexCdeSK as ObligIndexCdeSK,
	 row25.ObligAccrualStatusCdeSK as ObligAccrualStatusCdeSK,
	 row25.ObligPaidIndSK as ObligPaidIndSK,
	 row25.ObligBaseCurrencyCde as ObligBaseCurrencyCde,
	 row35.CompositeKeyHashValue as CompositeKeyHashValue_2,
	 row25.CompositeKeyHashValue as CompositeKeyHashValue_1,
	 row25.ObligRefreshedConsumerCreditScoreDateSK as ObligRefreshedConsumerCreditScoreDateSK,
	 row25.ObligCCISGLAcctUSGAAP as ObligCCISGLAcctUSGAAP,
	 row25.ObligSourceProfitCenter as ObligSourceProfitCenter,
	 row25.ObligForeclosureIndSK as ObligForeclosureIndSK,
	 row25.ObligCapitalAllocationCdeSK as ObligCapitalAllocationCdeSK,
	 row25.ObligBankerSK as ObligBankerSK,
	 row25.ObligBankruptcyDateSK as ObligBankruptcyDateSK,
	 row25.ObligSourceAcctNbr as ObligSourceAcctNbr 
From
tMap_1Out as tMap_1Out INNER JOIN tDBInput_GetCurrentRecordsOut as row35 
 ON
CompositeKeyHashValue = CompositeKeyHashValue
),

Router_tMap_2Out2 as (
	Select 
	tMap_OutputOut.row25.ObligDimSK as row25.ObligDimSK,
	 tMap_OutputOut.row25.CmmtDimSK as row25.CmmtDimSK,
	 tMap_OutputOut.row25.ObligUSDHAcctNbr as row25.ObligUSDHAcctNbr,
	 tMap_OutputOut.row25.ObligSourceAcctNbr as row25.ObligSourceAcctNbr,
	 tMap_OutputOut.row25.ObligSourceSystemSK as row25.ObligSourceSystemSK,
	 tMap_OutputOut.row25.ObligAccrualBasisCdeSK as row25.ObligAccrualBasisCdeSK,
	 tMap_OutputOut.row25.ObligAccrualIndSK as row25.ObligAccrualIndSK,
	 tMap_OutputOut.row25.ObligAccrualStatusCdeSK as row25.ObligAccrualStatusCdeSK,
	 tMap_OutputOut.row25.ObligAppScoreNbr as row25.ObligAppScoreNbr,
	 tMap_OutputOut.row25.ObligBankruptcyIndSK as row25.ObligBankruptcyIndSK,
	 tMap_OutputOut.row25.ObligBankruptcyDateSK as row25.ObligBankruptcyDateSK,
	 tMap_OutputOut.row25.ObligCeilingRate as row25.ObligCeilingRate,
	 tMap_OutputOut.row25.ObligEnteredDateSK as row25.ObligEnteredDateSK,
	 tMap_OutputOut.row25.ObligFedCallCdeSK as row25.ObligFedCallCdeSK,
	 tMap_OutputOut.row25.ObligFHAIndSK as row25.ObligFHAIndSK,
	 tMap_OutputOut.row25.ObligCurrentScoreNbr as row25.ObligCurrentScoreNbr,
	 tMap_OutputOut.row25.ObligFixedVariableIndSK as row25.ObligFixedVariableIndSK,
	 tMap_OutputOut.row25.ObligFloorRate as row25.ObligFloorRate,
	 tMap_OutputOut.row25.ObligForeclosureDateSK as row25.ObligForeclosureDateSK,
	 tMap_OutputOut.row25.ObligForeclosureIndSK as row25.ObligForeclosureIndSK,
	 tMap_OutputOut.row25.ObligIndexCdeSK as row25.ObligIndexCdeSK,
	 tMap_OutputOut.row25.ObligIssueDateSK as row25.ObligIssueDateSK,
	 tMap_OutputOut.row25.ObligMaturityDateSK as row25.ObligMaturityDateSK,
	 tMap_OutputOut.row25.ObligQualifiedMortgageIndSK as row25.ObligQualifiedMortgageIndSK,
	 tMap_OutputOut.row25.ObligBankerSK as row25.ObligBankerSK,
	 tMap_OutputOut.row25.ObligOriginalGLAmt as row25.ObligOriginalGLAmt,
	 tMap_OutputOut.row25.ObligClosedDateSK as row25.ObligClosedDateSK,
	 tMap_OutputOut.row25.ObligPaidIndSK as row25.ObligPaidIndSK,
	 tMap_OutputOut.row25.ObligPartIndSK as row25.ObligPartIndSK,
	 tMap_OutputOut.row25.ObligRenewalDateSK as row25.ObligRenewalDateSK,
	 tMap_OutputOut.row25.ObligRiskRatingCdeSK as row25.ObligRiskRatingCdeSK,
	 tMap_OutputOut.row25.ObligClientSK as row25.ObligClientSK,
	 tMap_OutputOut.row25.ObligShortNme as row25.ObligShortNme,
	 tMap_OutputOut.row25.ObligAccrualStatusDateSK as row25.ObligAccrualStatusDateSK,
	 tMap_OutputOut.row25.ObligNonAccrualStatusDateSK as row25.ObligNonAccrualStatusDateSK,
	 tMap_OutputOut.row25.ObligTypeCdeSK as row25.ObligTypeCdeSK,
	 tMap_OutputOut.row25.ObligOriginalDTIRatio as row25.ObligOriginalDTIRatio,
	 tMap_OutputOut.row25.ObligMortgageProductIDSK as row25.ObligMortgageProductIDSK,
	 tMap_OutputOut.row25.ObligIndexFloorIndSK as row25.ObligIndexFloorIndSK,
	 tMap_OutputOut.row25.ObligTDRCdeSK as row25.ObligTDRCdeSK,
	 tMap_OutputOut.row25.ObligSupervisoryLTVCdeSK as row25.ObligSupervisoryLTVCdeSK,
	 tMap_OutputOut.row25.ObligOriginationBeaconConsumerCreditScore as row25.ObligOriginationBeaconConsumerCreditScore,
	 tMap_OutputOut.row25.ObligRefershedBeaconConsumerCreditScore as row25.ObligRefershedBeaconConsumerCreditScore,
	 tMap_OutputOut.row25.ObligRefreshedConsumerCreditScoreDateSK as row25.ObligRefreshedConsumerCreditScoreDateSK,
	 tMap_OutputOut.row25.ObligVarRateChangeFreqCdeSK as row25.ObligVarRateChangeFreqCdeSK,
	 tMap_OutputOut.row25.ObligIndexRateChangeTimingCdeSK as row25.ObligIndexRateChangeTimingCdeSK,
	 tMap_OutputOut.row25.ObligBaseCurrencyCde as row25.ObligBaseCurrencyCde,
	 tMap_OutputOut.row25.ObligSecuredInd as row25.ObligSecuredInd,
	 tMap_OutputOut.row25.ObligOriginalMaturityCdeSK as row25.ObligOriginalMaturityCdeSK,
	 tMap_OutputOut.row25.ObligCurrentSpreadRate as row25.ObligCurrentSpreadRate,
	 tMap_OutputOut.row25.ObligTaxMonitoringCde as row25.ObligTaxMonitoringCde,
	 tMap_OutputOut.row25.ObligChargeOffCdeSK as row25.ObligChargeOffCdeSK,
	 tMap_OutputOut.row25.ObligTermCount as row25.ObligTermCount,
	 tMap_OutputOut.row25.ObligCCISBranchOfAcct as row25.ObligCCISBranchOfAcct,
	 tMap_OutputOut.row25.ObligSourceLegalEntity as row25.ObligSourceLegalEntity,
	 tMap_OutputOut.row25.ObligCCISOrgUnit as row25.ObligCCISOrgUnit,
	 tMap_OutputOut.row25.ObligSourceProfitCenter as row25.ObligSourceProfitCenter,
	 tMap_OutputOut.row25.ObligCCISGLAcctUSGAAP as row25.ObligCCISGLAcctUSGAAP,
	 tMap_OutputOut.row25.ObligCCISGLAcctIFRS as row25.ObligCCISGLAcctIFRS,
	 tMap_OutputOut.row25.ObligCapitalAllocationCdeSK as row25.ObligCapitalAllocationCdeSK,
	 tMap_OutputOut.row25.ObligSourceGLAcct as row25.ObligSourceGLAcct,
	 tMap_OutputOut.row25.ObligIntSourceGLAcct as row25.ObligIntSourceGLAcct,
	 tMap_OutputOut.row25.ObligIntCCISGLAcctUSGAAP as row25.ObligIntCCISGLAcctUSGAAP,
	 tMap_OutputOut.row25.ObligIntCCISGLAcctIFRS as row25.ObligIntCCISGLAcctIFRS,
	 tMap_OutputOut.row25.EffectiveStartDate as row25.EffectiveStartDate,
	 tMap_OutputOut.row25.EffectiveEndDate as row25.EffectiveEndDate,
	 tMap_OutputOut.row25.CurrentRecInd as row25.CurrentRecInd,
	 tMap_OutputOut.row25.InsertDatetime as row25.InsertDatetime,
	 tMap_OutputOut.row25.UpdateDatetime as row25.UpdateDatetime,
	 tMap_OutputOut.row25.CompositeKeyHashValue as row25.CompositeKeyHashValue,
	 tMap_OutputOut.row25.RowHashValue as row25.RowHashValue,
	 tMap_OutputOut.row35.ObligDimSK as row35.ObligDimSK,
	 tMap_OutputOut.row35.CompositeKeyHashValue as row35.CompositeKeyHashValue,
	 tMap_OutputOut.row35.RowHashValue as row35.RowHashValue
 FROM tMap_OutputOut as tMap_OutputOut Where NOT RowHashValue_1 = RowHashValue_2 ),

insert_old_recordOut as (
	
Select 
CmmtDimSK as CmmtDimSK,
ObligUSDHAcctNbr as ObligUSDHAcctNbr,
ObligSourceAcctNbr as ObligSourceAcctNbr,
ObligSourceSystemSK as ObligSourceSystemSK,
ObligAccrualBasisCdeSK as ObligAccrualBasisCdeSK,
ObligAccrualIndSK as ObligAccrualIndSK,
ObligAccrualStatusCdeSK as ObligAccrualStatusCdeSK,
ObligAppScoreNbr as ObligOriginationConsumerScoreNbr,
ObligBankruptcyIndSK as ObligBankruptcyIndSK,
ObligBankruptcyDateSK as ObligBankruptcyDateSK,
ObligCeilingRate as ObligCeilingRate,
ObligEnteredDateSK as ObligEnteredDateSK,
ObligFedCallCdeSK as ObligFedCallCdeSK,
ObligFHAIndSK as ObligFHAIndSK,
ObligCurrentScoreNbr as ObligRefreshedConsumerScoreNbr,
ObligFixedVariableIndSK as ObligFixedVariableIndSK,
ObligFloorRate as ObligFloorRate,
ObligForeclosureDateSK as ObligForeclosureDateSK,
ObligForeclosureIndSK as ObligForeclosureIndSK,
ObligIndexCdeSK as ObligIndexCdeSK,
ObligIssueDateSK as ObligIssueDateSK,
ObligMaturityDateSK as ObligMaturityDateSK,
ObligQualifiedMortgageIndSK as ObligQualifiedMortgageIndSK,
ObligBankerSK as BankerSK,
ObligOriginalGLAmt as ObligOriginalGLAmt,
ObligClosedDateSK as ObligClosedDateSK,
ObligPaidIndSK as ObligPaidIndSK,
ObligPartIndSK as ObligPartIndSK,
ObligRenewalDateSK as ObligRenewalDateSK,
ObligRiskRatingCdeSK as ObligRiskRatingCdeSK,
ObligClientSK as ClientSK,
ObligShortNme as ObligShortName,
ObligAccrualStatusDateSK as ObligAccrualStatusDateSK,
ObligNonAccrualStatusDateSK as ObligNonAccrualStatusDateSK,
ObligTypeCdeSK as ObligTypeCdeSK,
ObligOriginalDTIRatio as ObligOriginalDTIRatio,
ObligMortgageProductIDSK as ObligMortgageProductIDSK,
ObligIndexFloorIndSK as ObligIndexFloorIndSK,
ObligTDRCdeSK as ObligTDRCdeSK,
ObligSupervisoryLTVCdeSK as ObligSupervisoryLTVCdeSK,
ObligOriginationBeaconConsumerCreditScore as ObligOriginationBeaconConsumerCreditScore,
ObligRefershedBeaconConsumerCreditScore as ObligRefershedBeaconConsumerCreditScore,
ObligRefreshedConsumerCreditScoreDateSK as ObligRefreshedConsumerScoreDateSK,
ObligVarRateChangeFreqCdeSK as ObligVariableRateChangeFreqCdeSK,
ObligIndexRateChangeTimingCdeSK as ObligIndexRateChangeTimingCdeSK,
ObligBaseCurrencyCde as ObligCurrencyCdeBase,
ObligSecuredInd as ObligSecuredInd,
ObligOriginalMaturityCdeSK as ObligOriginalMaturityCdeSK,
CASE WHEN ( ObligCurrentSpreadRate IS NULL OR ObligCurrentSpreadRate == "" OR ObligCurrentSpreadRate == "null" ) THEN valueOf ( 0.0 ) ELSE ObligCurrentSpreadRate END as ObligCurrentSpreadRate,
ObligTaxMonitoringCde as ObligTaxMonitoringCde,
ObligChargeOffCdeSK as ObligChargeOffCdeSK,
ObligTermCount as ObligTermCount,
ObligCCISBranchOfAcct as ObligCCISBranchOfAcct,
ObligSourceLegalEntity as ObligSourceLegalEntity,
ObligCCISOrgUnit as ObligCCISOrgUnit,
ObligSourceProfitCenter as ObligSourceProfitCenter,
ObligCCISGLAcctUSGAAP as ObligCCISGLAcctUSGAAP,
ObligCCISGLAcctIFRS as ObligCCISGLAcctIFRS,
ObligCapitalAllocationCdeSK as ObligCapitalAllocationCdeSK,
ObligSourceGLAcct as ObligSourceGLAcct,
ObligIntSourceGLAcct as ObligIntSourceGLAcct,
ObligIntCCISGLAcctUSGAAP as ObligIntCCISGLAcctUSGAAP,
ObligIntCCISGLAcctIFRS as ObligIntCCISGLAcctIFRS,
VARC_ProcessDate as EffectiveStartDate,
TO_DATE ( "yyyyMMdd",
"99991231" ) as EffectiveEndDate,
"1" as CurrentRecInd,
curr_date as InsertDatetime,
curr_date as UpdateDatetime,
CompositeKeyHashValue as CompositeKeyHashValue,
RowHashValue as RowHashValue,
VARC_JobRunID as JobRunID
From tMap_OutputOut as tMap_OutputOut
WHERE !row35.RowHashValue.equals(row25.RowHashValue))


Select 
		CmmtDimSK,
	 ObligUSDHAcctNbr,
	 ObligSourceAcctNbr,
	 ObligSourceSystemSK,
	 ObligAccrualBasisCdeSK,
	 ObligAccrualIndSK,
	 ObligAccrualStatusCdeSK,
	 ObligOriginationConsumerScoreNbr,
	 ObligBankruptcyIndSK,
	 ObligBankruptcyDateSK,
	 ObligCeilingRate,
	 ObligEnteredDateSK,
	 ObligFedCallCdeSK,
	 ObligFHAIndSK,
	 ObligRefreshedConsumerScoreNbr,
	 ObligFixedVariableIndSK,
	 ObligFloorRate,
	 ObligForeclosureDateSK,
	 ObligForeclosureIndSK,
	 ObligIndexCdeSK,
	 ObligIssueDateSK,
	 ObligMaturityDateSK,
	 ObligQualifiedMortgageIndSK,
	 BankerSK,
	 ObligOriginalGLAmt,
	 ObligClosedDateSK,
	 ObligPaidIndSK,
	 ObligPartIndSK,
	 ObligRenewalDateSK,
	 ObligRiskRatingCdeSK,
	 ClientSK,
	 ObligShortName,
	 ObligAccrualStatusDateSK,
	 ObligNonAccrualStatusDateSK,
	 ObligTypeCdeSK,
	 ObligOriginalDTIRatio,
	 ObligMortgageProductIDSK,
	 ObligIndexFloorIndSK,
	 ObligTDRCdeSK,
	 ObligSupervisoryLTVCdeSK,
	 ObligOriginationBeaconConsumerCreditScore,
	 ObligRefershedBeaconConsumerCreditScore,
	 ObligRefreshedConsumerScoreDateSK,
	 ObligVariableRateChangeFreqCdeSK,
	 ObligIndexRateChangeTimingCdeSK,
	 ObligCurrencyCdeBase,
	 ObligSecuredInd,
	 ObligOriginalMaturityCdeSK,
	 ObligCurrentSpreadRate,
	 ObligTaxMonitoringCde,
	 ObligChargeOffCdeSK,
	 ObligTermCount,
	 ObligCCISBranchOfAcct,
	 ObligSourceLegalEntity,
	 ObligCCISOrgUnit,
	 ObligSourceProfitCenter,
	 ObligCCISGLAcctUSGAAP,
	 ObligCCISGLAcctIFRS,
	 ObligCapitalAllocationCdeSK,
	 ObligSourceGLAcct,
	 ObligIntSourceGLAcct,
	 ObligIntCCISGLAcctUSGAAP,
	 ObligIntCCISGLAcctIFRS,
	 EffectiveStartDate,
	 EffectiveEndDate,
	 CurrentRecInd,
	 InsertDatetime,
	 UpdateDatetime,
	 CompositeKeyHashValue,
	 RowHashValue,
	 JobRunID 
From insert_old_recordOut as insert_old_recordOut