/* Transformation Name ==>tDBOutput_UpdateRecords_1 ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='tDBOutput_UpdateRecords_1',
		schema='schema',
		incremental_strategy='append'
	)
}}

With tDBInput_GetCurrentRecordsOut as (
	/* SubQuery from Source ==>tDBInput_GetCurrentRecords */
Select 
 * 
 from 
(WITH 
 FROM
    {{ VARC_Schema_Dimension }}.{{ VARC_ConformedZone_ObligAccount_Dim }})
 ),

tFileInputDelimited_1Out as (
	Select ObligDimSK, 
		CmmtDimSK, 
		ObligUSDHAcctNbr, 
		ObligSourceAcctNbr, 
		ObligSourceSystemSK, 
		ObligAccrualBasisCdeSK, 
		ObligAccrualIndSK, 
		ObligAccrualStatusCdeSK, 
		ObligAppScoreNbr, 
		ObligBankruptcyIndSK, 
		ObligBankruptcyDateSK, 
		ObligCeilingRate, 
		ObligEnteredDateSK, 
		ObligFedCallCdeSK, 
		ObligFHAIndSK, 
		ObligCurrentScoreNbr, 
		ObligFixedVariableIndSK, 
		ObligFloorRate, 
		ObligForeclosureDateSK, 
		ObligForeclosureIndSK, 
		ObligIndexCdeSK, 
		ObligIssueDateSK, 
		ObligMaturityDateSK, 
		ObligQualifiedMortgageIndSK, 
		ObligBankerSK, 
		ObligOriginalGLAmt, 
		ObligClosedDateSK, 
		ObligPaidIndSK, 
		ObligPartIndSK, 
		ObligRenewalDateSK, 
		ObligRiskRatingCdeSK, 
		ObligClientSK, 
		ObligShortNme, 
		ObligAccrualStatusDateSK, 
		ObligNonAccrualStatusDateSK, 
		ObligTypeCdeSK, 
		ObligOriginalDTIRatio, 
		ObligMortgageProductIDSK, 
		ObligIndexFloorIndSK, 
		ObligTDRCdeSK, 
		ObligSupervisoryLTVCdeSK, 
		ObligOriginationBeaconConsumerCreditScore, 
		ObligRefershedBeaconConsumerCreditScore, 
		ObligRefreshedConsumerCreditScoreDateSK, 
		ObligVarRateChangeFreqCdeSK, 
		ObligIndexRateChangeTimingCdeSK, 
		ObligBaseCurrencyCde, 
		ObligSecuredInd, 
		ObligOriginalMaturityCdeSK, 
		ObligCurrentSpreadRate, 
		ObligTaxMonitoringCde, 
		ObligChargeOffCdeSK, 
		ObligTermCount, 
		ObligCCISBranchOfAcct, 
		ObligSourceLegalEntity, 
		ObligCCISOrgUnit, 
		ObligSourceProfitCenter, 
		ObligCCISGLAcctUSGAAP, 
		ObligCCISGLAcctIFRS, 
		ObligCapitalAllocationCdeSK, 
		ObligSourceGLAcct, 
		ObligIntSourceGLAcct, 
		ObligIntCCISGLAcctUSGAAP, 
		ObligIntCCISGLAcctIFRS, 
		EffectiveStartDate, 
		EffectiveEndDate, 
		CurrentRecInd, 
		InsertDatetime, 
		UpdateDatetime, 
		CompositeKeyHashValue, 
		RowHashValue
 from 
{{ source ('tFileInputDelimited_1','StringHandling.DOWNCASE({{ VARC_LocalFolder_tmpprocessing }}+/+{{ VARC_JobName_JOB_CuratedToConformed_LOAD_USDH_ACBSTor_ObligationAccount_Dim }}+/hashcode+{{ VARC_ConformedZone_ObligAccount_Dim }}+.+{{ VARC_FileExtension }})') }} 
 ),

tMap_1Out as (
	
Select 
rowout.ObligDimSK as ObligDimSK,
rowout.CmmtDimSK as CmmtDimSK,
CASE WHEN rowout.ObligUSDHAcctNbr = 'NULL' THEN null ELSE rowout.ObligUSDHAcctNbr END as ObligUSDHAcctNbr,
CASE WHEN rowout.ObligSourceAcctNbr = 'NULL' THEN null ELSE rowout.ObligSourceAcctNbr END as ObligSourceAcctNbr,
rowout.ObligSourceSystemSK as ObligSourceSystemSK,
rowout.ObligAccrualBasisCdeSK as ObligAccrualBasisCdeSK,
rowout.ObligAccrualIndSK as ObligAccrualIndSK,
rowout.ObligAccrualStatusCdeSK as ObligAccrualStatusCdeSK,
rowout.ObligAppScoreNbr as ObligAppScoreNbr,
rowout.ObligBankruptcyIndSK as ObligBankruptcyIndSK,
rowout.ObligBankruptcyDateSK as ObligBankruptcyDateSK,
rowout.ObligCeilingRate as ObligCeilingRate,
rowout.ObligEnteredDateSK as ObligEnteredDateSK,
rowout.ObligFedCallCdeSK as ObligFedCallCdeSK,
rowout.ObligFHAIndSK as ObligFHAIndSK,
rowout.ObligCurrentScoreNbr as ObligCurrentScoreNbr,
rowout.ObligFixedVariableIndSK as ObligFixedVariableIndSK,
rowout.ObligFloorRate as ObligFloorRate,
rowout.ObligForeclosureDateSK as ObligForeclosureDateSK,
rowout.ObligForeclosureIndSK as ObligForeclosureIndSK,
rowout.ObligIndexCdeSK as ObligIndexCdeSK,
rowout.ObligIssueDateSK as ObligIssueDateSK,
rowout.ObligMaturityDateSK as ObligMaturityDateSK,
rowout.ObligQualifiedMortgageIndSK as ObligQualifiedMortgageIndSK,
rowout.ObligBankerSK as ObligBankerSK,
rowout.ObligOriginalGLAmt as ObligOriginalGLAmt,
rowout.ObligClosedDateSK as ObligClosedDateSK,
rowout.ObligPaidIndSK as ObligPaidIndSK,
rowout.ObligPartIndSK as ObligPartIndSK,
rowout.ObligRenewalDateSK as ObligRenewalDateSK,
rowout.ObligRiskRatingCdeSK as ObligRiskRatingCdeSK,
rowout.ObligClientSK as ObligClientSK,
CASE WHEN rowout.ObligShortNme = 'NULL' THEN null ELSE rowout.ObligShortNme END as ObligShortNme,
rowout.ObligAccrualStatusDateSK as ObligAccrualStatusDateSK,
rowout.ObligNonAccrualStatusDateSK as ObligNonAccrualStatusDateSK,
rowout.ObligTypeCdeSK as ObligTypeCdeSK,
null as ObligOriginalDTIRatio,
rowout.ObligMortgageProductIDSK as ObligMortgageProductIDSK,
rowout.ObligIndexFloorIndSK as ObligIndexFloorIndSK,
rowout.ObligTDRCdeSK as ObligTDRCdeSK,
rowout.ObligSupervisoryLTVCdeSK as ObligSupervisoryLTVCdeSK,
rowout.ObligOriginationBeaconConsumerCreditScore as ObligOriginationBeaconConsumerCreditScore,
rowout.ObligRefershedBeaconConsumerCreditScore as ObligRefershedBeaconConsumerCreditScore,
rowout.ObligRefreshedConsumerCreditScoreDateSK as ObligRefreshedConsumerCreditScoreDateSK,
rowout.ObligVarRateChangeFreqCdeSK as ObligVarRateChangeFreqCdeSK,
rowout.ObligIndexRateChangeTimingCdeSK as ObligIndexRateChangeTimingCdeSK,
CASE WHEN rowout.ObligBaseCurrencyCde = 'NULL' THEN "1" ELSE rowout.ObligBaseCurrencyCde END as ObligBaseCurrencyCde,
rowout.ObligSecuredInd as ObligSecuredInd,
rowout.ObligOriginalMaturityCdeSK as ObligOriginalMaturityCdeSK,
rowout.ObligCurrentSpreadRate as ObligCurrentSpreadRate,
CASE WHEN rowout.ObligTaxMonitoringCde = 'NULL' THEN null ELSE rowout.ObligTaxMonitoringCde END as ObligTaxMonitoringCde,
rowout.ObligChargeOffCdeSK as ObligChargeOffCdeSK,
rowout.ObligTermCount as ObligTermCount,
CASE WHEN rowout.ObligCCISBranchOfAcct = 'NULL' THEN null ELSE rowout.ObligCCISBranchOfAcct END as ObligCCISBranchOfAcct,
CASE WHEN rowout.ObligSourceLegalEntity = 'NULL' THEN null ELSE rowout.ObligSourceLegalEntity END as ObligSourceLegalEntity,
CASE WHEN rowout.ObligCCISOrgUnit = 'NULL' THEN null ELSE rowout.ObligCCISOrgUnit END as ObligCCISOrgUnit,
CASE WHEN rowout.ObligSourceProfitCenter = 'NULL' THEN null ELSE rowout.ObligSourceProfitCenter END as ObligSourceProfitCenter,
rowout.ObligCCISGLAcctUSGAAP as ObligCCISGLAcctUSGAAP,
rowout.ObligCCISGLAcctIFRS as ObligCCISGLAcctIFRS,
rowout.ObligCapitalAllocationCdeSK as ObligCapitalAllocationCdeSK,
CASE WHEN rowout.ObligSourceGLAcct = 'NULL' THEN null ELSE rowout.ObligSourceGLAcct END as ObligSourceGLAcct,
CASE WHEN rowout.ObligIntSourceGLAcct = 'NULL' THEN null ELSE rowout.ObligIntSourceGLAcct END as ObligIntSourceGLAcct,
rowout.ObligIntCCISGLAcctUSGAAP as ObligIntCCISGLAcctUSGAAP,
rowout.ObligIntCCISGLAcctIFRS as ObligIntCCISGLAcctIFRS,
rowout.EffectiveStartDate as EffectiveStartDate,
rowout.EffectiveEndDate as EffectiveEndDate,
rowout.CurrentRecInd as CurrentRecInd,
rowout.InsertDatetime as InsertDatetime,
rowout.UpdateDatetime as UpdateDatetime,
rowout.CompositeKeyHashValue as CompositeKeyHashValue,
rowout.RowHashValue as RowHashValue
From tFileInputDelimited_1Out as tFileInputDelimited_1Out),

tMap_OutputOut as (
Select 
	row25.ObligVarRateChangeFreqCdeSK as ObligVarRateChangeFreqCdeSK,
	 row25.ObligEnteredDateSK as ObligEnteredDateSK,
	 row25.ObligAppScoreNbr as ObligAppScoreNbr,
	 row25.ObligCCISGLAcctIFRS as ObligCCISGLAcctIFRS,
	 row25.ObligPartIndSK as ObligPartIndSK,
	 row25.ObligClosedDateSK as ObligClosedDateSK,
	 row25.RowHashValue as RowHashValue_1,
	 row25.ObligUSDHAcctNbr as ObligUSDHAcctNbr,
	 row25.ObligOriginalMaturityCdeSK as ObligOriginalMaturityCdeSK,
	 row35.RowHashValue as RowHashValue_2,
	 row25.ObligBankruptcyIndSK as ObligBankruptcyIndSK,
	 row25.ObligSupervisoryLTVCdeSK as ObligSupervisoryLTVCdeSK,
	 row25.ObligAccrualStatusDateSK as ObligAccrualStatusDateSK,
	 row35.ObligDimSK as ObligDimSK,
	 row25.ObligIndexFloorIndSK as ObligIndexFloorIndSK,
	 row25.ObligTermCount as ObligTermCount,
	 row25.ObligFedCallCdeSK as ObligFedCallCdeSK,
	 row25.ObligIssueDateSK as ObligIssueDateSK,
	 row25.ObligTDRCdeSK as ObligTDRCdeSK,
	 row25.ObligRefershedBeaconConsumerCreditScore as ObligRefershedBeaconConsumerCreditScore,
	 row25.CmmtDimSK as CmmtDimSK,
	 row25.ObligCeilingRate as ObligCeilingRate,
	 row25.ObligCurrentSpreadRate as ObligCurrentSpreadRate,
	 row25.ObligFHAIndSK as ObligFHAIndSK,
	 row25.ObligCurrentScoreNbr as ObligCurrentScoreNbr,
	 row25.ObligClientSK as ObligClientSK,
	 row25.ObligRiskRatingCdeSK as ObligRiskRatingCdeSK,
	 row25.ObligIntSourceGLAcct as ObligIntSourceGLAcct,
	 row25.ObligIndexRateChangeTimingCdeSK as ObligIndexRateChangeTimingCdeSK,
	 row25.ObligIntCCISGLAcctUSGAAP as ObligIntCCISGLAcctUSGAAP,
	 row25.ObligMortgageProductIDSK as ObligMortgageProductIDSK,
	 row25.ObligForeclosureDateSK as ObligForeclosureDateSK,
	 row25.ObligCCISBranchOfAcct as ObligCCISBranchOfAcct,
	 row25.ObligTaxMonitoringCde as ObligTaxMonitoringCde,
	 row25.ObligNonAccrualStatusDateSK as ObligNonAccrualStatusDateSK,
	 row25.ObligShortNme as ObligShortNme,
	 row25.ObligSourceLegalEntity as ObligSourceLegalEntity,
	 row25.ObligMaturityDateSK as ObligMaturityDateSK,
	 row25.ObligAccrualIndSK as ObligAccrualIndSK,
	 row25.ObligIntCCISGLAcctIFRS as ObligIntCCISGLAcctIFRS,
	 row25.ObligCCISOrgUnit as ObligCCISOrgUnit,
	 row25.ObligSecuredInd as ObligSecuredInd,
	 row25.ObligFloorRate as ObligFloorRate,
	 row25.ObligTypeCdeSK as ObligTypeCdeSK,
	 row25.ObligRenewalDateSK as ObligRenewalDateSK,
	 row25.ObligQualifiedMortgageIndSK as ObligQualifiedMortgageIndSK,
	 row25.ObligOriginationBeaconConsumerCreditScore as ObligOriginationBeaconConsumerCreditScore,
	 row25.ObligOriginalGLAmt as ObligOriginalGLAmt,
	 row25.ObligSourceGLAcct as ObligSourceGLAcct,
	 row25.ObligSourceSystemSK as ObligSourceSystemSK,
	 row25.ObligAccrualBasisCdeSK as ObligAccrualBasisCdeSK,
	 row25.ObligOriginalDTIRatio as ObligOriginalDTIRatio,
	 row25.ObligFixedVariableIndSK as ObligFixedVariableIndSK,
	 row25.ObligChargeOffCdeSK as ObligChargeOffCdeSK,
	 row25.ObligIndexCdeSK as ObligIndexCdeSK,
	 row25.ObligAccrualStatusCdeSK as ObligAccrualStatusCdeSK,
	 row25.ObligPaidIndSK as ObligPaidIndSK,
	 row25.ObligBaseCurrencyCde as ObligBaseCurrencyCde,
	 row35.CompositeKeyHashValue as CompositeKeyHashValue_2,
	 row25.CompositeKeyHashValue as CompositeKeyHashValue_1,
	 row25.ObligRefreshedConsumerCreditScoreDateSK as ObligRefreshedConsumerCreditScoreDateSK,
	 row25.ObligCCISGLAcctUSGAAP as ObligCCISGLAcctUSGAAP,
	 row25.ObligSourceProfitCenter as ObligSourceProfitCenter,
	 row25.ObligForeclosureIndSK as ObligForeclosureIndSK,
	 row25.ObligCapitalAllocationCdeSK as ObligCapitalAllocationCdeSK,
	 row25.ObligBankerSK as ObligBankerSK,
	 row25.ObligBankruptcyDateSK as ObligBankruptcyDateSK,
	 row25.ObligSourceAcctNbr as ObligSourceAcctNbr 
From
tMap_1Out as tMap_1Out INNER JOIN tDBInput_GetCurrentRecordsOut as row35 
 ON
CompositeKeyHashValue = CompositeKeyHashValue
),

exp_out_1_tMap_2Out as (
	
Select 
row35.ObligDimSK as ObligDimSK,
{{ VARC_ProcessDate }} as EffectiveEndDate,
"0" as CurrentRecInd,
{{ curr_date }} as UpdateDatetime,
row35.CompositeKeyHashValue as CompositeKeyHashValue,
row35.RowHashValue as RowHashValue,
{{ VARC_JobRunID }} as JobRunID
From tMap_OutputOut as tMap_OutputOut
WHERE !row35.RowHashValue.equals(row25.RowHashValue))


Select 
		ObligDimSK,
	 EffectiveEndDate,
	 CurrentRecInd,
	 UpdateDatetime,
	 CompositeKeyHashValue,
	 RowHashValue,
	 JobRunID 
From exp_out_1_tMap_2Out as exp_out_1_tMap_2Out