{{
    config(
        materialized='incremental',
        alias='VERINT_EMP',
        schema='',
        pre_hook=[],
        post_hook=[],
        incremental_strategy='append'
    )
}}

with VERINT_EMP_UPD_INSOut as (
    select
        EMP_ID,
        SOR_CD,
        EFF_DTTM,
        END_DTTM,
        UNQ_KEY_TXT,
        EMP_TYPE_ID,
        ASGN_PNT,
        EMP_NBR,
        EMP_STRT_DTTM,
        EMP_END_DTTM,
        CHG_CNTR,
        MOD_BY,
        SPVSR_FLG,
        TEAM_LEAD_FLG,
        PREF_STRT_FLG,
        FRST_NM,
        LAST_NM,
        MDL_INITL,
        SUFX,
        BRTH_DT,
        USR_NM,
        USR_STS,
        PROFILE_MOD_BY,
        PROFILE_MOD_DTTM,
        FAIL_LOGIN_CNT,
        LAST_LOGIN_DTTM,
        AUD_CRE_BY_NM,
        AUD_CRE_DTTM,
        CURR_IND,
        ETL_BATCH_ID
    from {{ source('tFileInputDelimited_2', var('TEMP_DIR') ~ 'VERINT_EMP_UPD_INS') }}
),

VERINT_EMP_INSOut as (
    select
        EMP_ID,
        SOR_CD,
        EFF_DTTM,
        END_DTTM,
        UNQ_KEY_TXT,
        EMP_TYPE_ID,
        ASGN_PNT,
        EMP_NBR,
        EMP_STRT_DTTM,
        EMP_END_DTTM,
        CHG_CNTR,
        MOD_BY,
        SPVSR_FLG,
        TEAM_LEAD_FLG,
        PREF_STRT_FLG,
        FRST_NM,
        LAST_NM,
        MDL_INITL,
        SUFX,
        BRTH_DT,
        USR_NM,
        USR_STS,
        PROFILE_MOD_BY,
        PROFILE_MOD_DTTM,
        FAIL_LOGIN_CNT,
        LAST_LOGIN_DTTM,
        AUD_CRE_BY_NM,
        AUD_CRE_DTTM,
        CURR_IND,
        ETL_BATCH_ID
    from {{ source('tFileInputDelimited_3', var('TEMP_DIR') ~ 'VERINT_EMP_INS') }}
),

tUnite_1Out as (
    select
        VERINT_EMP_UPD_INSOut.EMP_ID,
        VERINT_EMP_UPD_INSOut.SOR_CD,
        VERINT_EMP_UPD_INSOut.EFF_DTTM,
        VERINT_EMP_UPD_INSOut.END_DTTM,
        VERINT_EMP_UPD_INSOut.UNQ_KEY_TXT,
        VERINT_EMP_UPD_INSOut.EMP_TYPE_ID,
        VERINT_EMP_UPD_INSOut.ASGN_PNT,
        VERINT_EMP_UPD_INSOut.EMP_NBR,
        VERINT_EMP_UPD_INSOut.EMP_STRT_DTTM,
        VERINT_EMP_UPD_INSOut.EMP_END_DTTM,
        VERINT_EMP_UPD_INSOut.CHG_CNTR,
        VERINT_EMP_UPD_INSOut.MOD_BY,
        VERINT_EMP_UPD_INSOut.SPVSR_FLG,
        VERINT_EMP_UPD_INSOut.TEAM_LEAD_FLG,
        VERINT_EMP_UPD_INSOut.PREF_STRT_FLG,
        VERINT_EMP_UPD_INSOut.FRST_NM,
        VERINT_EMP_UPD_INSOut.LAST_NM,
        VERINT_EMP_UPD_INSOut.MDL_INITL,
        VERINT_EMP_UPD_INSOut.SUFX,
        VERINT_EMP_UPD_INSOut.BRTH_DT,
        VERINT_EMP_UPD_INSOut.USR_NM,
        VERINT_EMP_UPD_INSOut.USR_STS,
        VERINT_EMP_UPD_INSOut.PROFILE_MOD_BY,
        VERINT_EMP_UPD_INSOut.PROFILE_MOD_DTTM,
        VERINT_EMP_UPD_INSOut.FAIL_LOGIN_CNT,
        VERINT_EMP_UPD_INSOut.LAST_LOGIN_DTTM,
        VERINT_EMP_UPD_INSOut.AUD_CRE_BY_NM,
        VERINT_EMP_UPD_INSOut.AUD_CRE_DTTM,
        VERINT_EMP_UPD_INSOut.CURR_IND,
        VERINT_EMP_UPD_INSOut.ETL_BATCH_ID
    from VERINT_EMP_UPD_INSOut as VERINT_EMP_UPD_INSOut

    union all

    select
        VERINT_EMP_INSOut.EMP_ID,
        VERINT_EMP_INSOut.SOR_CD,
        VERINT_EMP_INSOut.EFF_DTTM,
        VERINT_EMP_INSOut.END_DTTM,
        VERINT_EMP_INSOut.UNQ_KEY_TXT,
        VERINT_EMP_INSOut.EMP_TYPE_ID,
        VERINT_EMP_INSOut.ASGN_PNT,
        VERINT_EMP_INSOut.EMP_NBR,
        VERINT_EMP_INSOut.EMP_STRT_DTTM,
        VERINT_EMP_INSOut.EMP_END_DTTM,
        VERINT_EMP_INSOut.CHG_CNTR,
        VERINT_EMP_INSOut.MOD_BY,
        VERINT_EMP_INSOut.SPVSR_FLG,
        VERINT_EMP_INSOut.TEAM_LEAD_FLG,
        VERINT_EMP_INSOut.PREF_STRT_FLG,
        VERINT_EMP_INSOut.FRST_NM,
        VERINT_EMP_INSOut.LAST_NM,
        VERINT_EMP_INSOut.MDL_INITL,
        VERINT_EMP_INSOut.SUFX,
        VERINT_EMP_INSOut.BRTH_DT,
        VERINT_EMP_INSOut.USR_NM,
        VERINT_EMP_INSOut.USR_STS,
        VERINT_EMP_INSOut.PROFILE_MOD_BY,
        VERINT_EMP_INSOut.PROFILE_MOD_DTTM,
        VERINT_EMP_INSOut.FAIL_LOGIN_CNT,
        VERINT_EMP_INSOut.LAST_LOGIN_DTTM,
        VERINT_EMP_INSOut.AUD_CRE_BY_NM,
        VERINT_EMP_INSOut.AUD_CRE_DTTM,
        VERINT_EMP_INSOut.CURR_IND,
        VERINT_EMP_INSOut.ETL_BATCH_ID
    from VERINT_EMP_INSOut as VERINT_EMP_INSOut
),

tMap_2Out as (
    select
        row6.EMP_ID as EMP_ID,
        row6.SOR_CD as SOR_CD,
        row6.EFF_DTTM as EFF_DTTM,
        row6.END_DTTM as END_DTTM,
        row6.UNQ_KEY_TXT as UNQ_KEY_TXT,
        row6.EMP_TYPE_ID as EMP_TYPE_ID,
        row6.ASGN_PNT as ASGN_PNT,
        nullif(row6.EMP_NBR, '') as EMP_NBR,
        row6.EMP_STRT_DTTM as EMP_STRT_DTTM,
        row6.EMP_END_DTTM as EMP_END_DTTM,
        row6.CHG_CNTR as CHG_CNTR,
        nullif(row6.MOD_BY, '') as MOD_BY,
        nullif(row6.SPVSR_FLG, '') as SPVSR_FLG,
        nullif(row6.TEAM_LEAD_FLG, '') as TEAM_LEAD_FLG,
        nullif(row6.PREF_STRT_FLG, '') as PREF_STRT_FLG,
        nullif(row6.FRST_NM, '') as FRST_NM,
        nullif(row6.LAST_NM, '') as LAST_NM,
        nullif(row6.MDL_INITL, '') as MDL_INITL,
        nullif(row6.SUFX, '') as SUFX,
        row6.BRTH_DT as BRTH_DT,
        nullif(row6.USR_NM, '') as USR_NM,
        row6.USR_STS as USR_STS,
        nullif(row6.PROFILE_MOD_BY, '') as PROFILE_MOD_BY,
        row6.PROFILE_MOD_DTTM as PROFILE_MOD_DTTM,
        row6.FAIL_LOGIN_CNT as FAIL_LOGIN_CNT,
        row6.LAST_LOGIN_DTTM as LAST_LOGIN_DTTM,
        row6.AUD_CRE_BY_NM as AUD_CRE_BY_NM,
        row6.AUD_CRE_DTTM as AUD_CRE_DTTM,
        row6.CURR_IND as CURR_IND,
        row6.ETL_BATCH_ID as ETL_BATCH_ID
    from tUnite_1Out as row6
)

select
    EMP_ID,
    SOR_CD,
    EFF_DTTM,
    END_DTTM,
    UNQ_KEY_TXT,
    EMP_TYPE_ID,
    ASGN_PNT,
    EMP_NBR,
    EMP_STRT_DTTM,
    EMP_END_DTTM,
    CHG_CNTR,
    MOD_BY,
    SPVSR_FLG,
    TEAM_LEAD_FLG,
    PREF_STRT_FLG,
    FRST_NM,
    LAST_NM,
    MDL_INITL,
    SUFX,
    BRTH_DT,
    USR_NM,
    USR_STS,
    PROFILE_MOD_BY,
    PROFILE_MOD_DTTM,
    FAIL_LOGIN_CNT,
    LAST_LOGIN_DTTM,
    AUD_CRE_BY_NM,
    AUD_CRE_DTTM,
    CURR_IND,
    ETL_BATCH_ID
from tMap_2Out as tMap_2Out