version: 2

sources:
  - name: tMSSqlInput_1
    tables:
      - name: ACTIVITYMAPPING
  - name: tMSSqlInput_2
    tables:
      - name: VERINT_ACTV_MAP
  - name: tMSSqlInput_3
    tables:
      - name: tMSSqlInput_3