version: 2

sources:
  - name: tDBInput_1
    tables:
      - name: tDBInput_1
  - name: tFileInputDelimited_1
    tables:
      - name: StringHandling.DOWNCASE({{ VARC_LocalFolder_tmpprocessing }}+/+{{ VARC_JobName_JOB_CuratedToConformed_LOAD_USDH_ACBSTor_ObligationAccount_Dim }}+/hashcode+{{ VARC_ConformedZone_ObligAccount_Dim }}+.+{{ VARC_FileExtension }})