version: 2

sources:
  - name: WDBName
    tables:
      - name: AETC2,AETC_CLAIM,AETC_PART2,AETC_CARR2

models:
  - name: UpdateDMJobInfoC41_out
    description: "Final target model"
    columns:
      - name: T_STMP_UPD
        description: "T_STMP_UPD"
      - name: IS_REJECT_ROW
        description: "IS_REJECT_ROW"
  - name: M_F_AETC2
    description: "Final target model"
    columns:
      - name: I_AETC
        description: "I_AETC"
      - name: I_AETC_KEY
        description: "I_AETC_KEY"
      - name: I_LOC_BILLD_TO_KEY
        description: "I_LOC_BILLD_TO_KEY"
      - name: I_LOC_FINAL_DEST_KEY
        description: "I_LOC_FINAL_DEST_KEY"
      - name: I_LOC_SHIP2_KEY
        description: "I_LOC_SHIP2_KEY"
      - name: I_LOC_SHPFRM_KEY
        description: "I_LOC_SHPFRM_KEY"
      - name: I_SUPLR_LOC_REL_KEY
        description: "I_SUPLR_LOC_REL_KEY"
      - name: C_CARR_SCAC_KEY
        description: "C_CARR_SCAC_KEY"
      - name: C_CARR_SCAC_RESP_KEY
        description: "C_CARR_SCAC_RESP_KEY"
      - name: D_RUN_OUT
        description: "D_RUN_OUT"
      - name: D_PART_REQD_DPTR
        description: "D_PART_REQD_DPTR"
      - name: D_CARR_PROMD_PKUP
        description: "D_CARR_PROMD_PKUP"
      - name: D_CARR_ARR_SHPFRM
        description: "D_CARR_ARR_SHPFRM"
      - name: D_CARR_DEP_SHPFRM
        description: "D_CARR_DEP_SHPFRM"
      - name: D_ETA_SHIP2
        description: "D_ETA_SHIP2"
      - name: D_SENT_TO_CAP
        description: "D_SENT_TO_CAP"
      - name: D_FRTBILL_RPT
        description: "D_FRTBILL_RPT"
      - name: D_SENT_TO_MGA
        description: "D_SENT_TO_MGA"
      - name: D_SUPLR_RESP_MGA
        description: "D_SUPLR_RESP_MGA"
      - name: D_INTER_PLT_MGA
        description: "D_INTER_PLT_MGA"
      - name: D_CO_EXP_MGA
        description: "D_CO_EXP_MGA"
      - name: D_SUPLR_CAPS_RCVD
        description: "D_SUPLR_CAPS_RCVD"
      - name: D_CARR_EXP_MGA
        description: "D_CARR_EXP_MGA"
      - name: L_AETC_ACT
        description: "L_AETC_ACT"
      - name: L_DVRTD
        description: "L_DVRTD"
      - name: L_HAS_MNUL_NMBR
        description: "L_HAS_MNUL_NMBR"
      - name: C_AUTOPRC
        description: "C_AUTOPRC"
      - name: L_AETC_REPTD
        description: "L_AETC_REPTD"
      - name: L_AETC_ON_SUPERS
        description: "L_AETC_ON_SUPERS"
      - name: L_PICK_PACK
        description: "L_PICK_PACK"
      - name: L_HAS_XCHRG
        description: "L_HAS_XCHRG"
      - name: I_AETC_SRCE
        description: "I_AETC_SRCE"
      - name: L_OVERID_REL_EDIT
        description: "L_OVERID_REL_EDIT"
      - name: C_FRTBILL_RPT
        description: "C_FRTBILL_RPT"
      - name: C_SENT_TO_MGA
        description: "C_SENT_TO_MGA"
      - name: L_UPD_AETC_REC
        description: "L_UPD_AETC_REC"
      - name: L_UPD_AETC_COMPL
        description: "L_UPD_AETC_COMPL"
      - name: L_SUPLR_RESP_CAPS
        description: "L_SUPLR_RESP_CAPS"
      - name: L_SUPLR_RESP_MGA
        description: "L_SUPLR_RESP_MGA"
      - name: L_INTER_PLT_MGA
        description: "L_INTER_PLT_MGA"
      - name: L_CO_EXP_MGA
        description: "L_CO_EXP_MGA"
      - name: L_SUPLR_CAPS_RCVD
        description: "L_SUPLR_CAPS_RCVD"
      - name: L_CARR_EXP_MGA
        description: "L_CARR_EXP_MGA"
      - name: L_TRIP_RND
        description: "L_TRIP_RND"
      - name: L_MATL_TYP
        description: "L_MATL_TYP"
      - name: I_TRNSMODE
        description: "I_TRNSMODE"
      - name: C_AETC_RESPLTY
        description: "C_AETC_RESPLTY"
      - name: C_AETC_REAS
        description: "C_AETC_REAS"
      - name: C_SPLIT_RESPLTY
        description: "C_SPLIT_RESPLTY"
      - name: C_CURNCY
        description: "C_CURNCY"
      - name: C_FRTBILL_MTCH
        description: "C_FRTBILL_MTCH"
      - name: C_AETC_STAT
        description: "C_AETC_STAT"
      - name: C_CARR_SCAC
        description: "C_CARR_SCAC"
      - name: C_CARR_SCAC_RESP
        description: "C_CARR_SCAC_RESP"
      - name: I_CORPLOC_CHRG_TO
        description: "I_CORPLOC_CHRG_TO"
      - name: I_SHPMT_CARR
        description: "I_SHPMT_CARR"
      - name: C_SHPG_DOCK
        description: "C_SHPG_DOCK"
      - name: C_RECVG_DOCK
        description: "C_RECVG_DOCK"
      - name: I_LOGON_ADD_PPKAETC
        description: "I_LOGON_ADD_PPKAETC"
      - name: C_AETC_ALERT
        description: "C_AETC_ALERT"
      - name: I_LOC_FINAL_DEST
        description: "I_LOC_FINAL_DEST"
      - name: I_SUPLR_LOC_REL
        description: "I_SUPLR_LOC_REL"
      - name: I_LOC_SHPFRM
        description: "I_LOC_SHPFRM"
      - name: I_LOC_SHIP2
        description: "I_LOC_SHIP2"
      - name: I_LOC_BILLD_TO
        description: "I_LOC_BILLD_TO"
      - name: I_LOGON_SPOC
        description: "I_LOGON_SPOC"
      - name: I_RESP_PTY
        description: "I_RESP_PTY"
      - name: I_PART_MOST_CRITCL
        description: "I_PART_MOST_CRITCL"
      - name: N_APRV_AIR_CHRTR
        description: "N_APRV_AIR_CHRTR"
      - name: I_PROJ
        description: "I_PROJ"
      - name: I_SHPMT_SUPLR
        description: "I_SHPMT_SUPLR"
      - name: I_SHPMT_LD
        description: "I_SHPMT_LD"
      - name: X_CNVCTYP_REQD
        description: "X_CNVCTYP_REQD"
      - name: I_MATL
        description: "I_MATL"
      - name: T_RUN_OUT
        description: "T_RUN_OUT"
      - name: T_PART_REQD_DPTR
        description: "T_PART_REQD_DPTR"
      - name: T_CARR_PROMD_PKUP
        description: "T_CARR_PROMD_PKUP"
      - name: T_CARR_ARR_SHPFRM
        description: "T_CARR_ARR_SHPFRM"
      - name: T_CARR_DEP_SHPFRM
        description: "T_CARR_DEP_SHPFRM"
      - name: T_ETA_SHIP2
        description: "T_ETA_SHIP2"
      - name: T_BUS_HRS_OPEN
        description: "T_BUS_HRS_OPEN"
      - name: T_BUS_HRS_CLOSE
        description: "T_BUS_HRS_CLOSE"
      - name: I_CARRSHPT
        description: "I_CARRSHPT"
      - name: I_CNTNR_KEY
        description: "I_CNTNR_KEY"
      - name: P_AETC_RESPLTY
        description: "P_AETC_RESPLTY"
      - name: Q_ESTD_TRNST_HRS
        description: "Q_ESTD_TRNST_HRS"
      - name: Q_MILG
        description: "Q_MILG"
      - name: Q_AETC_GROSS_WGT
        description: "Q_AETC_GROSS_WGT"
      - name: Q_ESTD_TRNST_MINS
        description: "Q_ESTD_TRNST_MINS"
      - name: A_NRML_COST
        description: "A_NRML_COST"
      - name: A_ADMIN_COST
        description: "A_ADMIN_COST"
      - name: A_PKNG_COST
        description: "A_PKNG_COST"
      - name: A_COST_NRML_EQUIV
        description: "A_COST_NRML_EQUIV"
      - name: A_ADMIN_COST_EQUIV
        description: "A_ADMIN_COST_EQUIV"
      - name: A_COST_PACK_EQUIV
        description: "A_COST_PACK_EQUIV"
      - name: A_AETC_CO_EXP
        description: "A_AETC_CO_EXP"
      - name: A_AETC_CARR_RESP
        description: "A_AETC_CARR_RESP"
      - name: A_AETC_PLT_INTER
        description: "A_AETC_PLT_INTER"
      - name: A_AETC_SUPLR_RESP
        description: "A_AETC_SUPLR_RESP"
      - name: A_AETC_CO_EXP_US
        description: "A_AETC_CO_EXP_US"
      - name: A_CARR_RESP_US
        description: "A_CARR_RESP_US"
      - name: A_PLT_INTER_US
        description: "A_PLT_INTER_US"
      - name: A_SUPLR_RESP_US
        description: "A_SUPLR_RESP_US"
      - name: T_STMP_ADD_PPKAETC
        description: "T_STMP_ADD_PPKAETC"
      - name: I_CAP_TRANSM
        description: "I_CAP_TRANSM"
      - name: T_STMP_UPD
        description: "T_STMP_UPD"
      - name: L_CARR_DSPT
        description: "L_CARR_DSPT"
      - name: L_QUERY_RESP
        description: "L_QUERY_RESP"
      - name: L_CARR_ACPT_CHRG
        description: "L_CARR_ACPT_CHRG"
      - name: L_CARR_UNRCV_CLM
        description: "L_CARR_UNRCV_CLM"
      - name: L_CARR_OR_SUPLR
        description: "L_CARR_OR_SUPLR"
      - name: C_PTY_RESP_AETC
        description: "C_PTY_RESP_AETC"
      - name: C_RECMD_RESPLTY
        description: "C_RECMD_RESPLTY"
      - name: I_LOGON_ADD_PPKCLMS
        description: "I_LOGON_ADD_PPKCLMS"
      - name: I_CLM
        description: "I_CLM"
      - name: I_CARR_BOL
        description: "I_CARR_BOL"
      - name: I_USER_STARS_REF
        description: "I_USER_STARS_REF"
      - name: A_DSPT_NEGOTD_XCES
        description: "A_DSPT_NEGOTD_XCES"
      - name: T_STMP_ADD_PPKCLMS
        description: "T_STMP_ADD_PPKCLMS"
      - name: T_STMP_UPD_PPKCLMS
        description: "T_STMP_UPD_PPKCLMS"
      - name: D_ETA_AIRPT_DEST
        description: "D_ETA_AIRPT_DEST"
      - name: C_CARR_ACPTNC
        description: "C_CARR_ACPTNC"
      - name: I_AIRSHPT_SERV_LVL
        description: "I_AIRSHPT_SERV_LVL"
      - name: C_CNVCTYP_SERV_LVL
        description: "C_CNVCTYP_SERV_LVL"
      - name: C_CARR_OVERID
        description: "C_CARR_OVERID"
      - name: I_AIRPT_DEST
        description: "I_AIRPT_DEST"
      - name: I_FLIGHT
        description: "I_FLIGHT"
      - name: I_LOGON_ADD_PPKCARR
        description: "I_LOGON_ADD_PPKCARR"
      - name: I_CNVYNC
        description: "I_CNVYNC"
      - name: I_BOL_SUPLR
        description: "I_BOL_SUPLR"
      - name: I_FRT_AIRBILL
        description: "I_FRT_AIRBILL"
      - name: T_ETA_AIRPT_DEST
        description: "T_ETA_AIRPT_DEST"
      - name: A_ACTL_COST
        description: "A_ACTL_COST"
      - name: A_OTHR_COST
        description: "A_OTHR_COST"
      - name: A_CNTNR_RET_SHPMT
        description: "A_CNTNR_RET_SHPMT"
      - name: A_OTHR_CARR_SHPMT
        description: "A_OTHR_CARR_SHPMT"
      - name: A_COST_ACTL_EQUIV
        description: "A_COST_ACTL_EQUIV"
      - name: A_COST_OTHR_EQUIV
        description: "A_COST_OTHR_EQUIV"
      - name: A_CNTNR_RET_EQUIV
        description: "A_CNTNR_RET_EQUIV"
      - name: A_OTHR_CARR_EQUIV
        description: "A_OTHR_CARR_EQUIV"
      - name: T_STMP_ADD_PPKCARR
        description: "T_STMP_ADD_PPKCARR"
      - name: T_STMP_UPD_PPKCARR
        description: "T_STMP_UPD_PPKCARR"
      - name: I_PART_KEY
        description: "I_PART_KEY"
      - name: I_PART_RESP_KEY
        description: "I_PART_RESP_KEY"
      - name: D_SHPMT_PROM
        description: "D_SHPMT_PROM"
      - name: D_SHPMT_ARR
        description: "D_SHPMT_ARR"
      - name: D_LAST_ASN
        description: "D_LAST_ASN"
      - name: D_CREATE_SDS
        description: "D_CREATE_SDS"
      - name: D_SHPMT_LAST
        description: "D_SHPMT_LAST"
      - name: D_SHPMT_ASN
        description: "D_SHPMT_ASN"
      - name: L_REC_DEL
        description: "L_REC_DEL"
      - name: L_PART_PILOT
        description: "L_PART_PILOT"
      - name: L_PART_HAZ
        description: "L_PART_HAZ"
      - name: L_ASN_RECVD
        description: "L_ASN_RECVD"
      - name: L_RCPT_RECVD
        description: "L_RCPT_RECVD"
      - name: L_LNK_RECVD
        description: "L_LNK_RECVD"
      - name: C_REL_DATA_SRCE
        description: "C_REL_DATA_SRCE"
      - name: I_AETC_PART_SRCE
        description: "I_AETC_PART_SRCE"
      - name: L_REPK_SHPD_CNTNR
        description: "L_REPK_SHPD_CNTNR"
      - name: C_SHPMT_FREQ
        description: "C_SHPMT_FREQ"
      - name: I_TRNSMODE_SDS
        description: "I_TRNSMODE_SDS"
      - name: I_PGM
        description: "I_PGM"
      - name: I_PLT_RESP
        description: "I_PLT_RESP"
      - name: C_PART_DOT_HAZ
        description: "C_PART_DOT_HAZ"
      - name: C_PART_ICAO_HAZ
        description: "C_PART_ICAO_HAZ"
      - name: I_LOGON_ADD_PPKPART
        description: "I_LOGON_ADD_PPKPART"
      - name: I_PART
        description: "I_PART"
      - name: I_CNTNR
        description: "I_CNTNR"
      - name: I_PCHNG_TSA_RESP
        description: "I_PCHNG_TSA_RESP"
      - name: I_PART_RESP
        description: "I_PART_RESP"
      - name: I_PKSLIP_SUPLR
        description: "I_PKSLIP_SUPLR"
      - name: T_SHPMT_PROM
        description: "T_SHPMT_PROM"
      - name: T_SHPMT_ARR
        description: "T_SHPMT_ARR"
      - name: T_SHPMT_ASN
        description: "T_SHPMT_ASN"
      - name: I_MOD_YR
        description: "I_MOD_YR"
      - name: Q_PART
        description: "Q_PART"
      - name: Q_CNTNR
        description: "Q_CNTNR"
      - name: Q_PART_GROSS_WGT
        description: "Q_PART_GROSS_WGT"
      - name: Q_PLT_YTD_RECVD
        description: "Q_PLT_YTD_RECVD"
      - name: Q_PART_SHPD_YTD
        description: "Q_PART_SHPD_YTD"
      - name: Q_LAST_ASN
        description: "Q_LAST_ASN"
      - name: Q_PART_REL_YTD
        description: "Q_PART_REL_YTD"
      - name: Q_TOT_FLT
        description: "Q_TOT_FLT"
      - name: Q_INTRST_FLT_HRS
        description: "Q_INTRST_FLT_HRS"
      - name: Q_ADJ
        description: "Q_ADJ"
      - name: Q_NET_ACCUM
        description: "Q_NET_ACCUM"
      - name: Q_PART_SDS_YTD
        description: "Q_PART_SDS_YTD"
      - name: Q_YTD_REQD
        description: "Q_YTD_REQD"
      - name: Q_RDR
        description: "Q_RDR"
      - name: Q_RMO
        description: "Q_RMO"
      - name: Q_LNGTH_DIM_PKG
        description: "Q_LNGTH_DIM_PKG"
      - name: Q_WDTH_DIM_PKG
        description: "Q_WDTH_DIM_PKG"
      - name: Q_HGT_DIM_PKG
        description: "Q_HGT_DIM_PKG"
      - name: Q_CNTNR_PART_STAC
        description: "Q_CNTNR_PART_STAC"
      - name: T_STMP_ADD_PPKPART
        description: "T_STMP_ADD_PPKPART"
      - name: I_RDR_RESP
        description: "I_RDR_RESP"
      - name: I_GRP_DECK
        description: "I_GRP_DECK"
      - name: I_PLT_DECK
        description: "I_PLT_DECK"
      - name: I_PART_MOST_CRITCL_KEY
        description: "I_PART_MOST_CRITCL_KEY"
      - name: I_TRNSMODE_KEY
        description: "I_TRNSMODE_KEY"
      - name: T_STMP_DM_ADD
        description: "T_STMP_DM_ADD"
      - name: T_STMP_DM_UPD
        description: "T_STMP_DM_UPD"
      - name: N_JOB_ETL
        description: "N_JOB_ETL"
      - name: I_DATA_SRCE_DIM
        description: "I_DATA_SRCE_DIM"
      - name: A_AETC_SHPMT_COST
        description: "A_AETC_SHPMT_COST"
      - name: A_AETC_SHPMT_COST_USD
        description: "A_AETC_SHPMT_COST_USD"
      - name: A_AETC_MISC_COST
        description: "A_AETC_MISC_COST"
      - name: A_AETC_MISC_COST_USD
        description: "A_AETC_MISC_COST_USD"
      - name: A_AETC_XCES_COST
        description: "A_AETC_XCES_COST"
      - name: A_AETC_XCES_COST_USD
        description: "A_AETC_XCES_COST_USD"
      - name: N_AETC_REAS
        description: "N_AETC_REAS"
      - name: I_BUYR
        description: "I_BUYR"
      - name: C_COMMDTY
        description: "C_COMMDTY"
      - name: A_COST_TOT_EQUIV
        description: "A_COST_TOT_EQUIV"
      - name: I_SUPLR_LOC_MFG
        description: "I_SUPLR_LOC_MFG"
      - name: I_RUL_LOC_ADJ
        description: "I_RUL_LOC_ADJ"
      - name: I_FLWP_DECK
        description: "I_FLWP_DECK"
      - name: C_DIV
        description: "C_DIV"
      - name: I_PO
        description: "I_PO"
      - name: L_DRIVE
        description: "L_DRIVE"
      - name: I_USER_GRP
        description: "I_USER_GRP"
      - name: I_AETC_ACT_STAT_DIM
        description: "I_AETC_ACT_STAT_DIM"
      - name: I_AETC_RESPLTY_DIM
        description: "I_AETC_RESPLTY_DIM"
      - name: I_AETC_REAS_DIM
        description: "I_AETC_REAS_DIM"
      - name: I_AETC_CURNCY_DIM
        description: "I_AETC_CURNCY_DIM"
      - name: I_AETC_MGA_PAYMT_STAT_DIM
        description: "I_AETC_MGA_PAYMT_STAT_DIM"
      - name: I_AUTO_PRC_IND_DIM
        description: "I_AUTO_PRC_IND_DIM"
      - name: I_FRT_BILL_MTCH_ERR_DIM
        description: "I_FRT_BILL_MTCH_ERR_DIM"
      - name: I_AETC_STAT_DIM
        description: "I_AETC_STAT_DIM"
