/* Transformation Name ==>PRESENT_PARTS ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='PRESENT_PARTS',
		schema='',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='overwrite')
}}

With SEQ_REJOut as (
	Select I_PART_KEY, 
		I_PART, 
		I_LOC_SHIP2_1, 
		I_SUPLR_LOC_REL_1, 
		I_LOC_SHPFRM_1, 
		I_SHPMT_SUPLR, 
		I_PKSLIP_SUPLR, 
		I_POOLPT_SHIP2_1, 
		D_SHPMT, 
		T_SHPMT, 
		C_INVC_SHPR, 
		C_SHPR_TYP, 
		I_PART_SUPLR, 
		D_ADD, 
		T_ADD, 
		I_CNVYNC, 
		I_TRNSMODE, 
		I_BOL_MSTR, 
		C_CARR_SCAC, 
		I_LOC_CSGNE_1, 
		I_LOC_FINAL_DEST_1, 
		I_SUPLR_LOC_MFG_1
 from 
{{ source ('SEQ_REJ','SEQ_REJ') }}
 ),

PART_MAX_LKPOut as (
	/* SubQuery from Source ==>PART_MAX_LKP */
Select 
 * 
 from 
(SELECT INTEGER(COALESCE(MAX(I_PART_KEY),0)) as MAXKEY, 1 as JOINKEY FROM N_DB_APP_EDW_DEV.SCM.#'{{ var("PARTSchema", "") }}'#_PART as WITH)
 ),

PP1PKGMOut as (
	/* SubQuery from Source ==>PP1PKGM */
Select 
 * 
 from 
(SELECT distinct LTRIM(RTRIM(I_PKG)) as I_PKG, 1 as CNTNR_KEY FROM N_DB_APP_EDW_DEV.SCM.P_PP1PKGM as WITH)
 ),

PART_KEYOut as (
	/* SubQuery from Source ==>PART_KEY */
Select 
 * 
 from 
(SELECT I_PART_KEY, LTRIM(RTRIM(I_PART)) as I_PART FROM N_DB_APP_EDW_DEV.SCM.#'{{ var("PARTSchema", "") }}'#_PART as WITH)
 ),

XFR_DATA_CONVOut as (
	
Select 
TRIM ( I_PART ) as I_PART,
I_LOC_SHIP2_1 as I_LOC_SHIP2_1,
I_SUPLR_LOC_REL_1 as I_SUPLR_LOC_REL_1,
I_LOC_SHPFRM_1 as I_LOC_SHPFRM_1,
I_SHPMT_SUPLR as I_SHPMT_SUPLR,
I_PKSLIP_SUPLR as I_PKSLIP_SUPLR,
I_POOLPT_SHIP2_1 as I_POOLPT_SHIP2_1,
D_SHPMT as D_SHPMT,
T_SHPMT as T_SHPMT,
C_INVC_SHPR as C_INVC_SHPR,
C_SHPR_TYP as C_SHPR_TYP,
I_PART_SUPLR as I_PART_SUPLR,
D_ADD as D_ADD,
T_ADD as T_ADD,
I_CNVYNC as I_CNVYNC,
I_TRNSMODE as I_TRNSMODE,
I_BOL_MSTR as I_BOL_MSTR,
C_CARR_SCAC as C_CARR_SCAC,
I_LOC_CSGNE_1 as I_LOC_CSGNE_1,
I_LOC_FINAL_DEST_1 as I_LOC_FINAL_DEST_1,
I_SUPLR_LOC_MFG_1 as I_SUPLR_LOC_MFG_1,
1 as JOINKEY
From SEQ_REJOut as SEQ_REJOut),

LKP_CNTNR_REJOut as (
	Select 
	PP1PKGMOut.CNTNR_KEY as CNTNR_KEY_1,
	 XFR_DATA_CONVOut.I_PART as I_PART_1,
	 XFR_DATA_CONVOut.I_LOC_SHIP2_1 as I_LOC_SHIP2_1_1,
	 XFR_DATA_CONVOut.I_SUPLR_LOC_REL_1 as I_SUPLR_LOC_REL_1_1,
	 XFR_DATA_CONVOut.I_LOC_SHPFRM_1 as I_LOC_SHPFRM_1_1,
	 XFR_DATA_CONVOut.I_SHPMT_SUPLR as I_SHPMT_SUPLR_1,
	 XFR_DATA_CONVOut.I_PKSLIP_SUPLR as I_PKSLIP_SUPLR_1,
	 XFR_DATA_CONVOut.I_POOLPT_SHIP2_1 as I_POOLPT_SHIP2_1_1,
	 XFR_DATA_CONVOut.D_SHPMT as D_SHPMT_1,
	 XFR_DATA_CONVOut.T_SHPMT as T_SHPMT_1,
	 XFR_DATA_CONVOut.C_INVC_SHPR as C_INVC_SHPR_1,
	 XFR_DATA_CONVOut.C_SHPR_TYP as C_SHPR_TYP_1,
	 XFR_DATA_CONVOut.I_PART_SUPLR as I_PART_SUPLR_1,
	 XFR_DATA_CONVOut.D_ADD as D_ADD_1,
	 XFR_DATA_CONVOut.T_ADD as T_ADD_1,
	 XFR_DATA_CONVOut.I_CNVYNC as I_CNVYNC_1,
	 XFR_DATA_CONVOut.I_TRNSMODE as I_TRNSMODE_1,
	 XFR_DATA_CONVOut.I_BOL_MSTR as I_BOL_MSTR_1,
	 XFR_DATA_CONVOut.C_CARR_SCAC as C_CARR_SCAC_1,
	 XFR_DATA_CONVOut.I_LOC_CSGNE_1 as I_LOC_CSGNE_1_1,
	 XFR_DATA_CONVOut.I_LOC_FINAL_DEST_1 as I_LOC_FINAL_DEST_1_1,
	 XFR_DATA_CONVOut.I_SUPLR_LOC_MFG_1 as I_SUPLR_LOC_MFG_1_1,
	 XFR_DATA_CONVOut.JOINKEY as JOINKEY_1,
	 XFR_DATA_CONV.I_CNVYNC AS I_CNVYNC_2,
	 XFR_DATA_CONV.I_LOC_CSGNE_1 AS I_LOC_CSGNE_1_2,
	 XFR_DATA_CONV.I_LOC_SHPFRM_1 AS I_LOC_SHPFRM_1_2,
	 XFR_DATA_CONV.I_SHPMT_SUPLR AS I_SHPMT_SUPLR_2,
	 XFR_DATA_CONV.C_SHPR_TYP AS C_SHPR_TYP_2,
	 XFR_DATA_CONV.I_PART_SUPLR AS I_PART_SUPLR_2,
	 XFR_DATA_CONV.D_ADD AS D_ADD_2,
	 XFR_DATA_CONV.I_TRNSMODE AS I_TRNSMODE_2,
	 PP1PKGM.CNTNR_KEY AS CNTNR_KEY_2,
	 XFR_DATA_CONV.I_PART AS I_PART_2,
	 XFR_DATA_CONV.C_CARR_SCAC AS C_CARR_SCAC_2,
	 XFR_DATA_CONV.JOINKEY AS JOINKEY_2,
	 XFR_DATA_CONV.T_ADD AS T_ADD_2,
	 XFR_DATA_CONV.D_SHPMT AS D_SHPMT_2,
	 XFR_DATA_CONV.I_LOC_FINAL_DEST_1 AS I_LOC_FINAL_DEST_1_2,
	 XFR_DATA_CONV.I_SUPLR_LOC_MFG_1 AS I_SUPLR_LOC_MFG_1_2,
	 XFR_DATA_CONV.I_SUPLR_LOC_REL_1 AS I_SUPLR_LOC_REL_1_2,
	 PP1PKGM.I_PKG AS I_PKG,
	 XFR_DATA_CONV.I_PKSLIP_SUPLR AS I_PKSLIP_SUPLR_2,
	 XFR_DATA_CONV.T_SHPMT AS T_SHPMT_2,
	 XFR_DATA_CONV.I_BOL_MSTR AS I_BOL_MSTR_2,
	 XFR_DATA_CONV.C_INVC_SHPR AS C_INVC_SHPR_2,
	 XFR_DATA_CONV.I_LOC_SHIP2_1 AS I_LOC_SHIP2_1_2,
	 XFR_DATA_CONV.I_POOLPT_SHIP2_1 AS I_POOLPT_SHIP2_1_2 
FROM
	XFR_DATA_CONVOut as XFR_DATA_CONVOut 
 LEFT JOIN PP1PKGMOut
ON
	I_PART = I_PKG
 
),

JNR_PART_KEYOut as (
Select 
	LKP_CNTNR_REJOut.C_INVC_SHPR as C_INVC_SHPR,
	 LKP_CNTNR_REJOut.I_BOL_MSTR as I_BOL_MSTR,
	 LKP_CNTNR_REJOut.I_POOLPT_SHIP2_1 as I_POOLPT_SHIP2_1,
	 LKP_CNTNR_REJOut.T_ADD as T_ADD,
	 LKP_CNTNR_REJOut.I_SUPLR_LOC_REL_1 as I_SUPLR_LOC_REL_1,
	 PART_KEYOut.I_PART as I_PART,
	 LKP_CNTNR_REJOut.C_SHPR_TYP as C_SHPR_TYP,
	 LKP_CNTNR_REJOut.CNTNR_KEY as CNTNR_KEY,
	 LKP_CNTNR_REJOut.T_SHPMT as T_SHPMT,
	 LKP_CNTNR_REJOut.I_PKSLIP_SUPLR as I_PKSLIP_SUPLR,
	 LKP_CNTNR_REJOut.I_TRNSMODE as I_TRNSMODE,
	 LKP_CNTNR_REJOut.C_CARR_SCAC as C_CARR_SCAC,
	 LKP_CNTNR_REJOut.I_SUPLR_LOC_MFG_1 as I_SUPLR_LOC_MFG_1,
	 LKP_CNTNR_REJOut.D_SHPMT as D_SHPMT,
	 LKP_CNTNR_REJOut.I_LOC_CSGNE_1 as I_LOC_CSGNE_1,
	 LKP_CNTNR_REJOut.I_SHPMT_SUPLR as I_SHPMT_SUPLR,
	 LKP_CNTNR_REJOut.I_CNVYNC as I_CNVYNC,
	 LKP_CNTNR_REJOut.I_LOC_SHIP2_1 as I_LOC_SHIP2_1,
	 PART_KEYOut.I_PART_KEY as I_PART_KEY,
	 LKP_CNTNR_REJOut.I_PART as I_PART,
	 LKP_CNTNR_REJOut.D_ADD as D_ADD,
	 LKP_CNTNR_REJOut.I_PART_SUPLR as I_PART_SUPLR,
	 LKP_CNTNR_REJOut.I_LOC_FINAL_DEST_1 as I_LOC_FINAL_DEST_1,
	 LKP_CNTNR_REJOut.I_LOC_SHPFRM_1 as I_LOC_SHPFRM_1,
	 LKP_CNTNR_REJOut.JOINKEY as JOINKEY 
From
PART_KEYOut as PART_KEYOut left JOIN PART_KEYOut as PART_KEYOut 
ON
PART_KEYOut.I_PART = LKP_CNTNR_REJOut.I_PART 
),

LKP_PART_MAXOut1 as (
	Select 
	PART_MAX_LKPOut.MAXKEY as MAXKEY_1,
	 JNR_PART_KEYOut.CNTNR_KEY as CNTNR_KEY_1,
	 JNR_PART_KEYOut.I_PART_KEY as I_PART_KEY_1,
	 JNR_PART_KEYOut.C_INVC_SHPR as C_INVC_SHPR_1,
	 JNR_PART_KEYOut.C_SHPR_TYP as C_SHPR_TYP_1,
	 JNR_PART_KEYOut.I_PART as I_PART_1,
	 JNR_PART_KEYOut.I_LOC_SHIP2_1 as I_LOC_SHIP2_1_1,
	 JNR_PART_KEYOut.I_SUPLR_LOC_REL_1 as I_SUPLR_LOC_REL_1_1,
	 JNR_PART_KEYOut.I_LOC_SHPFRM_1 as I_LOC_SHPFRM_1_1,
	 JNR_PART_KEYOut.I_SHPMT_SUPLR as I_SHPMT_SUPLR_1,
	 JNR_PART_KEYOut.I_PKSLIP_SUPLR as I_PKSLIP_SUPLR_1,
	 JNR_PART_KEYOut.I_POOLPT_SHIP2_1 as I_POOLPT_SHIP2_1_1,
	 JNR_PART_KEYOut.D_SHPMT as D_SHPMT_1,
	 JNR_PART_KEYOut.T_SHPMT as T_SHPMT_1,
	 JNR_PART_KEYOut.I_PART_SUPLR as I_PART_SUPLR_1,
	 JNR_PART_KEYOut.D_ADD as D_ADD_1,
	 JNR_PART_KEYOut.T_ADD as T_ADD_1,
	 JNR_PART_KEYOut.I_CNVYNC as I_CNVYNC_1,
	 JNR_PART_KEYOut.I_TRNSMODE as I_TRNSMODE_1,
	 JNR_PART_KEYOut.I_BOL_MSTR as I_BOL_MSTR_1,
	 JNR_PART_KEYOut.C_CARR_SCAC as C_CARR_SCAC_1,
	 JNR_PART_KEYOut.I_LOC_CSGNE_1 as I_LOC_CSGNE_1_1,
	 JNR_PART_KEYOut.I_LOC_FINAL_DEST_1 as I_LOC_FINAL_DEST_1_1,
	 JNR_PART_KEYOut.I_SUPLR_LOC_MFG_1 as I_SUPLR_LOC_MFG_1_1,
	 JNR_PART_KEY.I_SUPLR_LOC_MFG_1 AS I_SUPLR_LOC_MFG_1_2,
	 JNR_PART_KEY.I_PART_KEY AS I_PART_KEY_2,
	 JNR_PART_KEY.CNTNR_KEY AS CNTNR_KEY_2,
	 JNR_PART_KEY.T_ADD AS T_ADD_2,
	 JNR_PART_KEY.I_PART AS I_PART_2,
	 JNR_PART_KEY.T_SHPMT AS T_SHPMT_2,
	 JNR_PART_KEY.JOINKEY AS JOINKEY_1,
	 JNR_PART_KEY.I_BOL_MSTR AS I_BOL_MSTR_2,
	 PART_MAX_LKP.JOINKEY AS JOINKEY_2,
	 JNR_PART_KEY.I_PART_SUPLR AS I_PART_SUPLR_2,
	 JNR_PART_KEY.C_INVC_SHPR AS C_INVC_SHPR_2,
	 JNR_PART_KEY.I_LOC_SHIP2_1 AS I_LOC_SHIP2_1_2,
	 JNR_PART_KEY.I_TRNSMODE AS I_TRNSMODE_2,
	 JNR_PART_KEY.D_ADD AS D_ADD_2,
	 JNR_PART_KEY.I_LOC_FINAL_DEST_1 AS I_LOC_FINAL_DEST_1_2,
	 JNR_PART_KEY.D_SHPMT AS D_SHPMT_2,
	 JNR_PART_KEY.I_LOC_SHPFRM_1 AS I_LOC_SHPFRM_1_2,
	 PART_MAX_LKP.MAXKEY AS MAXKEY_2,
	 JNR_PART_KEY.I_POOLPT_SHIP2_1 AS I_POOLPT_SHIP2_1_2,
	 JNR_PART_KEY.I_LOC_CSGNE_1 AS I_LOC_CSGNE_1_2,
	 JNR_PART_KEY.I_SUPLR_LOC_REL_1 AS I_SUPLR_LOC_REL_1_2,
	 JNR_PART_KEY.I_SHPMT_SUPLR AS I_SHPMT_SUPLR_2,
	 JNR_PART_KEY.I_PKSLIP_SUPLR AS I_PKSLIP_SUPLR_2,
	 JNR_PART_KEY.C_CARR_SCAC AS C_CARR_SCAC_2,
	 JNR_PART_KEY.C_SHPR_TYP AS C_SHPR_TYP_2,
	 JNR_PART_KEY.I_CNVYNC AS I_CNVYNC_2 
FROM
	JNR_PART_KEYOut as JNR_PART_KEYOut 
 LEFT JOIN PART_MAX_LKPOut
ON
	JOINKEY = JOINKEY
 
),

lnk_present_part_2Out as (
	
Select 
MAXKEY as MAXKEY,
CNTNR_KEY as CNTNR_KEY,
I_PART_KEY as I_PART_KEY,
C_INVC_SHPR as C_INVC_SHPR,
C_SHPR_TYP as C_SHPR_TYP,
I_PART as I_PART 
From LKP_PART_MAXOut1 as LKP_PART_MAXOut1 Where ( CNTNR_KEY = 0 ) AND ( I_PART_KEY = 0 ) AND ( TRIM ( C_INVC_SHPR ) = '06' ) AND ( TRIM ( C_SHPR_TYP ) = 'B' ) AND ( 1 = 2 ))


Select 
	MAXKEY as MAXKEY,
	CNTNR_KEY as CNTNR_KEY,
	I_PART_KEY as I_PART_KEY,
	C_INVC_SHPR as C_INVC_SHPR,
	C_SHPR_TYP as C_SHPR_TYP,
	I_PART as I_PART 
From lnk_present_part_2Out as lnk_present_part_2Out